### ISSUE TITLE
Mapping table to a field

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#101]
Ok so I'm starting to get the hang of this and working quite well so far.

However, I'm stuck on if there is a native way to map a field say 'School' into a multi select list from the School View for use on the pupil view. 

I know how I can do this via a custom field type post build. But unsure the method to achieve this via JCB?

**Comment by Llewellynvdm** [comment]
Sure this can be done in JCB, but at this time the demo data to demonstrate this is not free. Send me an email!
