### ISSUE TITLE
WHMCS Integration

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#103]
I'm checking to see if there is anything special that is supposed to be done to get the WHMCS integration to work.

I've set "Add License (WHMCS)" to Yes, set Implementation to "Lock Down Use (used to verify ownership)", added my "licensing" product in WHMCS, added my WHMCS Secret Key in JCB, and added the URL to my WHMCS install.

Upon compile, the License field is in options, but it doesn't appear to have integrated WHMCS license check into the code. I did see that the compile created admin/vdm.php, which is a blank file.

Is there more that is supposed to be done in JCB for this?

**Comment by ro-ot** [comment]
This feature only needs the whmcs values as explained in the component view when you activate it. So if it does not add the values to the vdm.php file you need to check that you have added all needed values.

- WHMCS Secret Key
- URL to your WHMCS install

Here is the function that adds the WHMCS to your component: https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L433 you can go over it and make sure you have all needed php modules in place.

Then last but not least you need to set Component builders basic key in global options of JCB, then you need to save the component view to insure that the data from WHMCS in the database is locked with the basic key.

Then all should work.

**Comment by Llewellynvdm** [comment]
This is actually part of the functions that adds the WHMCS features https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L244

**Comment by mwweb** [comment]
The basic 32 character key in global was the issue. It populates the admin/vdm.php file now. I'll have to look a bit more at this. 

- If I set "Lock Down Use" it properly locks down access to the component if license key isn't supplied. This isn't necessarily ideal for a component, in my opinion.

- If "Updates" is selected, it populates vdm.php, but didn't seem to be doing a license check on update. This would be the preferred. If they have an active subscription, they can download via updater. If no valid license, then they don't get updates.

**Comment by Llewellynvdm** [comment]
The update feature is still under development, the [GSoC](https://github.com/joomla-projects/gsoc17_expand_extension_manager) is actually adding these new features to Joomla as we speak. Soon as it becomes stable I will finish that part of the implementation. So for now the update feature is not ready, but yes Lock down is LOCK DOWN :)

But soon it will have the update option which is really more the open-source way of doing things, and what I prefer.
