### ISSUE TITLE
Builder did not pas form data to server

### ISSUE THREAD

**Issue by Houtsmatisering** [vdm-io/Joomla-Component-Builder#106]
Builder did not run.
Latest joomla 
Builder default php javascript change joomla.submitform( task, cform) to make sure correct form is posted. Same done for submit button.

Regards,
Jeroen

**Comment by Llewellynvdm** [comment]
Hmmm try to refresh the page... ctrl F5 this will reload all JavaScript. I did not get this error so I can debug. IF refreshing the page does not help, please give more details since I am not 100% sure I understand the issue.

**Comment by Houtsmatisering** [comment]
[default.php.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/1202160/default.php.zip)

attached you find changes i did. when rendered the compiler html has multiple admin forms. the javascript did not specify the admin form. so it will post default. I could be wrong but it worked for me.

joomla 3.4.7 and php 7 

Jeroen

**Comment by Llewellynvdm** [comment]
Wow as far as I know JCB is not ready for php7, so you got it to work in php7?

**Comment by Llewellynvdm** [comment]
Okay I looked at your fix, but it causes conflict with other buttons on the page... so I wrote [a fix](https://github.com/vdm-io/Joomla-Component-Builder/commit/7a902d454acfa6d948c6295ce27be91e145ef908#diff-d04c4a3960ed08962125a268be562576L46), try out the [staging branch](https://github.com/vdm-io/Joomla-Component-Builder/tree/staging). Let me know if it works for you.

**Comment by Llewellynvdm** [comment]
This seems like a [better fix](https://github.com/vdm-io/Joomla-Component-Builder/commit/fb7b5027c27585324eb172edd5cb7664056027ed#diff-d04c4a3960ed08962125a268be562576R58) please test and let me know.

**Comment by Houtsmatisering** [comment]
The default.php tested ok. Building works on php 7 still checking if the created component works. Thanks.

**Comment by Llewellynvdm** [comment]
@Houtsmatisering please give me feedback on php7 at [this open issue](https://github.com/vdm-io/Joomla-Component-Builder/issues/47), will safe me some time :+1:
