### ISSUE TITLE
Language file parsing errors when joomla in debug mode

### ISSUE THREAD

**Issue by Houtsmatisering** [vdm-io/Joomla-Component-Builder#107]
Tag with html seem to be a problem. May the " within the ". in the ini file.

Regards,
Jeroen

**Comment by Llewellynvdm** [comment]
You will need to add more details to a issue if you open one... We are talking about a 100 000 lines of code that can build millions and millions of lines of code. I have no idea what you are looking at, and what is happening.

I know, maybe I would need to add some issue template to the repo to help with this.... but for a start, please explain more about the issue when you open it. I really appreciate your willingness to make these issues know, just feels silly if I have to every time ask for more details... hope you understand.

**Comment by Llewellynvdm** [comment]
Okay from what I understand this is a user error, adding " in a language text line. Please make sure to use `&quot;` instead.
