### ISSUE TITLE
Adding a Countries Database Table

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#11]
Hi there,
I want to add access to a countries DB table - with country name, iso codes, continents, etc. I do not need a view for this table, but do need the ability to create a variety of field types from this table. how do i go about doing this, so that the table can be packaged with the component AND the component be able to create field types...

Thank-you!
Paola

**Comment by Llewellynvdm** [comment]
Yes it can do it and so much more... I must say to answer this question is much to long... our tutorials will help you understand much better how Component Builder constructs it's components. 

So please think about purchasing access to these tutorials it will safe you so much time, and help you understand things much quicker then any documentation.

We have a limited number of discount offers available of 20% use the following Promotion Code `GITHUB20` at [vdm.io](https://www.vdm.io/access/cart.php?a=add&pid=53)
