### ISSUE TITLE
JCB front-end

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#112]
Please help us decide in what direction we should take this.

## Adding just a shop

- First setup an API that can return product data
- Then create a shop-front that uses the JCB API to display available components, and more
- Then setup easy banners and content for JED index listings
- And more shop related stuff

## Adding a Component-Creator system (with shop)

> The idea is to be able to setup JCB on your own website, and let users build components on your website via the front-end of JCB

> Just about give every Joomla website owner the option to host their own Component-Creator system.

- Add more permission structures across JCB fields
- Change all repeatable pop-up fields to subform fields (looks better)
- Add Uikit 3 to JCB
- Design a front-end work-flow (quick guide to build basic component) that in a few clicks you can have a fully developed component.
- And more invoicing and subscription options.

So we are adding a front-end to JCB, please share your ideas with us. If your would like to share them in private, email me (get my email in JCB backend).

Thanks!

**Comment by ro-ot** [comment]
Just a display of various component that are available for sale and free download. I also think it should rather integrate with existing shops like Virtuemart and other. Not sure if building a whole new shop is what is needed.

Just a API that returns json objects, or a basic component display, that you can add custom links to buy.

**Comment by WfedFaal** [comment]
# This is a stunning tool for developers, please keep it that way!!
My vote!
- Uikit 3 [__Yes__]
- Easy banners and content for JED [__Yes__]
- More permission structures across JCB fields [__Yes__]
- Change all repeatable pop-up fields to subform fields [__Yes__]
- Adding just a shop [__No__]
- Design a __back-end__ wizard that in a few clicks you can have a fully developed component. [__Yes__]
- Component-Creator system (with shop) [__No__]

**Comment by MachineDean** [comment]
## I agree, that this should remain a developers tool.

**Comment by mwweb** [comment]
I like what **ghost** listed.

On the "More permission structures", I had, at one point, posted a suggestion on automating the setting of views upon install. That post was closed without discussion, but I'm going to repost it. I have the code added to my component, and every time that it is installed, the view permissions get automatically set to the permissions that I chose during compile. This was extremely important for my component, as I have, currently, 21 different site views, and requiring clients to manually set the site views I would become hated very soon.

I personally don't see much of a need for a JCB frontend. I'm not running JCB on my hosting server, but I am running it on my localhost. I think, along with **MachineDean** that this should remain a developers tool. I've had thoughts about some more ways to extend JCB beyond just a component builder, but holding off while PHP 7 and new J! router implementation are focused on.

**Comment by Llewellynvdm** [comment]
> Okay this is what I have been able to do so far:

- Change all repeatable pop-up fields to subform fields (only in most relevant areas, we may still do more in the future)
- More permission structures across JCB fields (have added more permissions all across JCB)

> This is what I plan to do next:

- add Uikit 3 (ASAP)

> This may not happen soon:

- Design a back-end wizard that in a few clicks you can have a fully developed component. 

> I just made a tutorial on how to build a **hello word** component, this may be the easy temporal solution. I will redo it so to make it shorted ad more professional... then  I will push it public all over the place.
