### ISSUE TITLE
Dynamic Get -> Where Issue

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#117]
I did some testing today, as I need to have a view that will have a a where filtering by modified date.

In the dynamic get, when going to  the WHERE repeatable field, if I add a new row of a.modified less than or equal to 1, JCB correctly compiles that WHERE into the model. However, if I enter a.modified less than or equal to NOW(), JCB fails to add the WHERE to the model. Or a more accurate WHERE that I was working on: a.modified less than or equal to NOW() - INTERVAL 3 DAY. 

Physically adding to the model provides the desired results. But it looks like a compiler bug in not compiling WHERE if other than 1 or 0.

**Comment by Llewellynvdm** [comment]
Can you give me a screen shot of the values, I mean exact values I could try and fix that.

I don't really think it is a bug, more like a not fully finished feature. There is a few like those around, I started building it, and left some outcomes as an open-end to return to when it becomes needed. Like if someone brings it up, or If I encounter it my self.

**Comment by mwweb** [comment]
Please see the attached.
![jcb](https://user-images.githubusercontent.com/19194012/30202702-3935ace2-9434-11e7-821f-a5132f4d746e.png)

**Comment by mwweb** [comment]
Did that screenshot help with what I was attempting? In the end, INTERVAL 3 DAY may be changed to a param. I haven't determined that yet. I just know on this particular view there may be some that want to show records 3 days old, and some up to 7 days. I'll be playing with it more once I can compile the view, and at least have a "prototype" view in place.

**Comment by Llewellynvdm** [comment]
Just pushed the fix for this, you welcome to test it... from what I tested it worked.
