### ISSUE TITLE
Missing Language File Entries for JCB Component

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#118]
I noticed that there are missing language file entries for JCB. See attached screenshot

![missing-language-file-entries](https://user-images.githubusercontent.com/870934/30190920-dbd759da-9413-11e7-817b-0d7cfcc84995.jpg)

**Comment by Llewellynvdm** [comment]
Hi Kevin not sure I understand... 

It can be that those names changed... do you actually see strings in the JCB back-end not being translated.

**Comment by kevincam3** [comment]
I just wanted to point out that the column names are not translated, that's all

**Comment by Llewellynvdm** [comment]
Okay I understand... it must be that we need to add some language strings to the sys file for these... hmmm.

I will take a closer look, Thanks!

**Comment by Llewellynvdm** [comment]
Oops wrong button :)
