### ISSUE TITLE
error in export component

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#120]
hi,
i have JCB 2.5.4 (last version until today) and when i'm trying to export component ( joomla components-> Export component) the following error is displayed: 

An error has occurred.
1054 Unknown column 'fa' in 'where clause'

also i made multilingual component (language translations for "fa-IR" language) Could this be the reason for the error?

What is the solution?
thank you very much

**Comment by Llewellynvdm** [comment]
Hi I have been thinking about this issue for the last two days... I am not sure really.

I don't know why this is hapening... hmmm I need to have it before me... lets see Unknown column.

Let my try debug this a few more days and see if I can find something. I have never had this issue before.

Just out of interest what version of PHP do you have installed and on what operating system?

**Comment by Llewellynvdm** [comment]
Okay I found the bug :) will push a fix!

**Comment by sepehr09** [comment]
thank you very much for you answer & follow up
