### ISSUE TITLE
New Subform Field

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#122]
I'm just checking...was the new subform field type supposed to be added to the fieldstype table? Checking, because I did the upgrade, and there is no subform field available. It was available in the branch before the merge.

I see it in the install sql file though. I'll manually add it, but thought that it would have inserted to the table.

**Comment by Llewellynvdm** [comment]
Subform has been part of the public JCB for some time now.

Let me get this straight... are you asking about the "subform" as a field type, or the fact that I converted all field types "properties" to a subform?

**Comment by mwweb** [comment]
As a new field type. I know subform had been discussed, but in looking after upgrading to 2.5.5, there was no subform field type.

I ended up exporting the fields from the branch build before merge, then importing into my "live" version of JCB, and it's there now. 

If it's been available for a while, there must have been an update SQL that didn't run to add it.

**Comment by Llewellynvdm** [comment]
IF you do a black install of JCB you will see that the subform is actually there :) along all other field types... so we gave all field types to the community few months ago... I should actually update the demo component to make use of all field types so you could easy update your system...

IF you are speaking about the fact that if you open fieldtypes in JCB now... the properties are all in a subform, then yes that was done automatically since the field name did not change, nothing in the database will change. But you will see in the installer script of JCB we are doing a lot of house cleaning to insure all continues to work without conflict... even with the import and export of components we have made all known adjustments to try and move these fields to subforms and still be backward compatible. Hey this exercise was expensive... and why I only did the language view, and the fieldtypes... to see the impact. The impact was three days of debugging... little much to move from repeatable fields to subforms. But we made it... lets see if more things break, hope not :)

**Comment by mwweb** [comment]
I'm actually referring to line 1000 in install.mysql.utf8.sql. This SQL add the Subform field type to componentbuilder_fieldtype.

I search through all the update queries, and the subform field is never added during an update.

So, if there is a NEW install, then the subform will get added, since it is part of install.mysql.utf8.sql. However, if JBC has already been installed, as is the case in my situation, then I would have never received the subform field type, since it was never a part of any updates.

I worked around that by exporting and importing the field types. But I just wanted to point out that subform isn't a part of updates.

**Comment by mwweb** [comment]
I'll have to play with the subforms. I just changed one of my repeatable fields to a subform, and it broke everything on my component. It wasn't even showing my records in the list view, yet they were in the table.

I don't have the time right now to debug, so I'll just change it back to repeatable for now. I currently have 4 components in the works,and pulling 16 hour days I just can't debug right now. No errors, but a broken view/Views.

**Comment by Llewellynvdm** [comment]
Hey take my advice... don't do it when you are pushed on time... they are not interchangeable at all!!!!

**Comment by Llewellynvdm** [comment]
Yea they are nice... but they store the values differently, I mean completely differently.

Repeatable fields:
```
field1
    value1
    value2

field2
   value1
   value2
```
Subforms
```
row1
    field1 => value1
    field2 => vlaue2
row2
   field1 => value1
   field2 => value2
```
So you will need to convert the already stored values and then wherever you are using the values in custom code, you will need to change that as well. 

Very painful indeed... and when you start everything breaks and you go down this deep dark valley lol... only attempt this if you have time!

**Comment by mwweb** [comment]
I decided to take the time late last night to change all of my repeatable fields over to subforms. Since repeatable fields are depreciated, and the conversion can be tricky, I decided it best to do the change now, before I formally release it.

It works nicely. I'll just have to work on laying it out different.

**Comment by Llewellynvdm** [comment]
Depreciated? Did I hear you right? are they going to dump that field type?

**Comment by mwweb** [comment]
Yes. According to the Joomla! docs, and the API it has been depreciated, and looks like it's going to be removed in version 4.0

https://docs.joomla.org/Repeatable_form_field_type
This field is deprecated
Thank you to use Subform form field type (in multiple mode) instead.

https://api.joomla.org/cms-3/classes/JFormFieldRepeatable.html
Form Field class for the Joomla Platform.

deprecated
Display a JSON loaded window with a repeatable set of sub fields

**Comment by Llewellynvdm** [comment]
Well now I have to insure to remove this from all component.. man this is just sick!!!!

**Comment by imaziofa** [comment]
Hi, Is there a way to write javascript for the subform. I want to be able to program certain behavior for some of the fields as the rows are added dynamically.

**Comment by Llewellynvdm** [comment]
add the function call to the **onchange** property, like this:
```
myFunctionCall(this);
```
Then in your function call do this to get the row details by id:
```
// little script to check values and make changes to other fields
function myFunctionCall(field) {
	// get the ID
	var id = jQuery(field).attr('id');
	var target = id.split('__');
	//set the subID
	var subID = target[0]+'__'+target[1];
	// get value
	var value = jQuery('#'+subID+'__other_fieldname_in_same_row').val();
	// set notice and do house cleaning
	if (2 == value) {
		// do your thing...
	}
}
```
There are other ways to also do this... but this feature above works very well, the other way is [explained here](https://docs.joomla.org/Subform_form_field_type).

**Comment by ilhan-uncuoglu** [comment]
And, where should i put that function? 

> 
> 
> add the function call to the **onchange** property, like this:
> 
> ```
> myFunctionCall(this);
> ```
> 
> Then in your function call do this to get the row details by id:
> 
> ```
> // little script to check values and make changes to other fields
> function myFunctionCall(field) {
> 	// get the ID
> 	var id = jQuery(field).attr('id');
> 	var target = id.split('__');
> 	//set the subID
> 	var subID = target[0]+'__'+target[1];
> 	// get value
> 	var value = jQuery('#'+subID+'__other_fieldname_in_same_row').val();
> 	// set notice and do house cleaning
> 	if (2 == value) {
> 		// do your thing...
> 	}
> }
> ```
> 
> There are other ways to also do this... but this feature above works very well, the other way is [explained here](https://docs.joomla.org/Subform_form_field_type).
