### ISSUE TITLE
Compiling Fields

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#123]
I'm just checking whether there is something special that I need to do on fieldtypes. Here's the issue that I am coming across.

In Joomla! 3.7 Joomla! extended the calendar form type to support time, as well as date (https://docs.joomla.org/Calendar_form_field_type), which they needed to do.

When I add showtime and timeformat to the fieldtype, then I update the XML in the field, the compile changes some of the fields that I have set. As soon as I physically change the data to what I had originally, in the xml file, the field works properly.

Here's a sample of what I have for the field before compile:

<field 
	type="calendar" 
	name="ohstart" 
	label="Start date" 
	default="NOW" 
        showtime="true"
        timeformat="12"
	format="%Y-%m-%d %H:%M:%S" 
	filter="user_utc" 
	description="" 
	readonly="" 
	disabled="" 
	class="" 
	size="25" 
	required="" 
	showon="" 
/>

Here is what JCB compiles it to:

				
				<field
					type="calendar"
					name="ohstart"
					label="COM_MOSTWANTEDREALESTATE_PROPERTY_OHSTART_LABEL"
					default="NOW"
					format="12"
					filter="user_utc"
					size="25"
					showtime="true"
					timeformat="12"
					required="false"
				/>

Notice that the compile is changing format from %Y-%m-%d %H:%M:%S to 12, which is crashing the date-helper.min.js with:

Uncaught TypeError: Cannot read property '0' of null
    at Function.t.parseFieldDate (date-helper.min.js:1)
    at t.checkInputs (calendar.min.js:1)
    at new t (calendar.min.js:1)
    at Function.t.init (calendar.min.js:1)
    at HTMLDocument.<anonymous> (calendar.min.js:1)

**Comment by Llewellynvdm** [comment]
I do not get the same result... 
```
<!-- [Fields 926] Deactivate Field. Type: Calendar. (joomla) -->
<field
	type="calendar"
	name="deactivate"
	label="COM_NOTICEBOARD_NOTICE_DEACTIVATE_LABEL"
	default="NOW"
	description="COM_NOTICEBOARD_NOTICE_DEACTIVATE_DESCRIPTION"
	format="%Y-%m-%d %H:%M:%S"
	filter="user_utc"
	size="22"
	required="true"
/>
```
There is no trick here, the compiler just gets what is between `format="` and `"` and place it back into it again, look [here is the line1525](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/c_Fields.php#L1525) in the Fields.php that gets the value.

So changing it to a 12 seems very weird to say the least... I have no idea what is the reason for that.

Maybe on that line1526 in the Fields.php file add this:
```
if ($property['name'] === 'format')
{
	var_dump($xmlValue);jexit();
}
```
The compile the component again, so we can see what is the value at that time... that is where I would start debugging if I had the same issue, but I don't so I cant trace it. Your on a windows box right?

**Comment by mwweb** [comment]
In your example that you have above, if you add:

				showtime="true"
				timeformat="12"

to your XML, then compile, do you get the desired result? It compiles file without those options, but fails when they are added.

Those are new options available since the release of J!3.7 for the calendar field: https://docs.joomla.org/Calendar_form_field_type

**Comment by Llewellynvdm** [comment]
Note it says:
- translateformat (optional): If set to true, the calendar will use a language string to determine the format. **The `format` attribute is ignored**. If false, the `format` attribute is used (same behaviour as today). (starting with 3.7.0)
- showtime (optional): **If set to true and translateformat is true**, the language key DATE_FORMAT_CALENDAR_DATETIME is used, otherwise DATE_FORMAT_CALENDAR_DATE. (starting with 3.7.0)

So I updated the Calender field type to have all the new options available... then added some of them. Here is the build result.
```
<!-- [Fields 926] Deactivate Field. Type: Calendar. (joomla) -->
<field
	type="calendar"
	name="deactivate"
	label="COM_NOTICEBOARD_NOTICE_DEACTIVATE_LABEL"
	default="NOW"
	description="COM_NOTICEBOARD_NOTICE_DEACTIVATE_DESCRIPTION"
	format="%Y-%m-%d %H:%M:%S"
	filter="user_utc"
	size="22"
	required="true"
	translateformat="true"
	showtime="true"
	timeformat="12"
	singleheader="true"
	todaybutton="true"
	weeknumbers="true"
	filltable="true"
	minyear="-2"
	maxyear="4"
/>
```

**Comment by Llewellynvdm** [comment]
This is how it looks in the **XML field definition** 
```
<field 
	type="calendar" 
	name="deactivate" 
	label="Deactivate Notice" 
	default="NOW" 
	description="Select the date when the notice should be deactivated." 
	size="22"
	format="%Y-%m-%d %H:%M:%S"
	filter="user_utc"
	required="true" 
	translateformat="true"
	showtime="true" 
	timeformat="12" 
	singleheader="true" 
	todaybutton="true" 
	weeknumbers="true" 
	filltable="true" 
	minyear="-2" XML field definition 
	maxyear="4" 
/>
```

**Comment by Llewellynvdm** [comment]
Maybe on that line1526 in the Fields.php file add this:
```
if ($property['name'] === 'format')
{
	var_dump($xmlValue);jexit();
}
```
The compile the component again, so we can see what is the value at that time... that is where I would start debugging if I had the same issue, but I don't so I cant trace it. Your on a windows box right?

**Comment by mwweb** [comment]
I think it's working fine now. It was not only having every option listed, but all instances of the calendar that I added needed to be updated. If there is one that is using the date time, and another that is using the "old" calendar, it failed. Updating the "old" one then setting true to false, it worked.

And, my setup is a hybrid of sorts. My main computer is a Windows device, but my dev setup with JCB is running on Oracle VirtualBox on Ubuntu.

The hybrid part is PHP, MySQL, Apache, etc. is all being run on the VirtualBox, having shared folders in my Windows file system.
