### ISSUE TITLE
Compiling Issue on J! 3.8.0

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#124]
I've been encountering some odd behavior with JCB in Joomla! 3.8. 

When I do a compile, all seems to work fine. I don't see any errors, and compiled zip is created as it should be. However, when I install the extension, not as an update, but as a new, fresh install, some site views are throwing 404 errors, with 1146 Table '{db}.#__{component}_' doesn't exist. (I altered the table names for this post). Yes, the DB is looking for #__{component)_, not the complete actual table. In looking at the database, all the tables are present. When I look at the files compiled, everything appears to be present (models, site view, templates, layouts, controllers, etc.)

As a test, I "rolled back" my installation from Joomla! 3.8.0 back to 3.7.5 and tested the compile and fresh install. The result? It compiled and installs perfectly fine.

It is really odd behavior that is happening here, and it doesn't help out a whole lot that even with error checking and debug enabled, Joomla isn't showing any error except the 404 that I listed above.

And I was able to confirm that as long as the component is compiled in 3.7.x, it appears to work fine in 3.8.0 (still testing that).

Any thoughts?

**Comment by Llewellynvdm** [comment]
Hi, I just tested this... I did not get the same result. It all just worked.

**Comment by mwweb** [comment]
Hmm. I'll keep playing with it, and maybe I'll need to go through and compare files between the two and see if I find any differences.

**Comment by Llewellynvdm** [comment]
A git repo should show that easy.. let me know. I mean if it is a bug, I will fix it, even if it is a change in Joomla... lets insure it works for all... But if I can't see it is hard to debug and fix.
