### ISSUE TITLE
Number data losing leading zeroes

### ISSUE THREAD

**Issue by alexsykes** [vdm-io/Joomla-Component-Builder#125]
Hi Llewellyn, I'm gradually working through the videos and getting used to the basics of JCB. It is a very time-saving piece of kit.
One issue that I have noticed is that when I do a dump, compile, download, uninstall, reinstall update routine, any fields containing numbers only with a leading zero - such as telephone numbers - lose the leading zero when reinstalled. Looking at the install.sql file, these data are not 'ticked' so, I guess when read in are treated as number values.
Any thoughts?

**Comment by Llewellynvdm** [comment]
Hi, The code that builds the dump is found in the [get.php of the compiler on line 2797
](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/a_Get.php#L2797) now to actual method we need to improve is found on line [2951](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/a_Get.php#L2951)

You are welcome to make a pull request, or just dump some code in this issue that you think could resolve the issue.

**Comment by Llewellynvdm** [comment]
We could add a option that if it detects the first value to be zero that it treat it as a string... something like this..
```
if (mb_substr($value, 0, 1, 'utf-8') === '0') { // needs string treatment }
```
IF you have no better idea, we can add this to the core.

**Comment by alexsykes** [comment]
Thanks. Appreciated.
