### ISSUE TITLE
form validation problem in conditional field

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#127]
Hi 
One issue that I have noticed today is when i use conditional field ( Editing the Admin View -> Conditions) , all fields used in Conditions have problem with front-end validation. i checked that fileds required="false" att is set correctly but if those field leave empty the validation give me error (front-end).
thank you

**Comment by ro-ot** [comment]
You must always add one more hidden field to the view to insure that it can work to pass he server side validation.

So it is a hidden field and the field xml looks like this
```
<field 
	type="hidden" 
	name="not_required" 
	default="[]" 
/>
```
Just add it to any page that use the conditional feature and it should resolve the validation problem.

**Comment by sepehr09** [comment]
Thank you very much,
i put that hidden field to my form but still client-side validation give me error : 
![image](https://user-images.githubusercontent.com/11753906/30959138-22f5933e-a44c-11e7-999f-35372a01f59c.png)

(the first name & last name not required but validation give me error)

**Comment by sepehr09** [comment]
i found the solution! if i'm use (required="false" ) the validation will not work correctly in conditional form, if leave required empty (required="" )  the problem will be solve!

**Comment by ro-ot** [comment]
Yes sure, or you can just remove the line altogether.
