### ISSUE TITLE
Add code to admin.js

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#128]
I'm trying to understand how to add code to admin.js I can see where to do it for admin.css

For admin.css see attached screenshot:
![image](https://user-images.githubusercontent.com/870934/31125317-47ec341a-a81e-11e7-838a-3ceb904a6d50.png)

What about for admin.js
![image](https://user-images.githubusercontent.com/870934/31125381-883e50d4-a81e-11e7-88e0-b1b2437492ae.png)

**Comment by Llewellynvdm** [comment]
I can just smile... We wanted to use Admin JS that is why it is there... but then I added a option to ad JS to a Admin View instead... So in JCB that field has not been added.

We will be adding it within any of the next releases... it is not a top priority, but I will add it under the Admin CSS field :) soon as I can.

**Comment by kevincam3** [comment]
Ok, thanks.
