### ISSUE TITLE
Joomla! 3.6 Compliance

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#13]
Hi there,
I'm aware this has just come out, but are there compliance issues for building and/or rolling out components in 3.6?

Thanks again,
Paola

**Comment by Llewellynvdm** [comment]
No since we are staying as close as we can to the API of Joomla I have not found any issues as yet.

I have update many websites all running with components build with CB tool and none had any errors. Yet if you find any issue let me know and we will make the needed adjustments.

**Comment by paolavness** [comment]
Great to hear! Thanks Llewellyn!
