### ISSUE TITLE
Is conditions fields support multiple options?

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#132]
hi,
i have some question about conditions fields, 
1- is that support multiple options ? when i separate options with comma that's not working!
![image](https://user-images.githubusercontent.com/11753906/31272149-d2fa1ea8-aa96-11e7-8624-9cb3f42afe5c.png)

2- i have one drop-down menu & 10 text fields. how i can set conditions fields to that drop-down ? for example if drop-down option 1 selected show some text field & if option 2 selected show some other fields and **Common** fields. 
actually that's not working! if i add more than one record in conditions fields, the only 1'st conditions fields work & that because other conditions have same Target Field/s.
thank you very much

**Comment by kevincam3** [comment]
Have you tried using "showon", I've never done this before but I'm learning and would like to know how to do this too. So I looked up how the "shown" attribute works and it seems like it could solve the problem. Take a look on this page and search on the page for shown to get to the part where they explain how to us it. https://docs.joomla.org/Form_field

Report back if that works and what you did so I can keep learning. Thanks.

**Comment by sepehr09** [comment]
yes that's work! even we use some Common options or use same drop-down as source for multiple fields.

![image](https://user-images.githubusercontent.com/11753906/31275037-7ab5970c-aaa2-11e7-8a9d-51221371291b.png)

thank you very much
