### ISSUE TITLE
Do we need both the assets folder and the media/com_[component_name] folder?

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#139]
Just a newbie question and I know you're working on other high priority stuff but I did want to understand this. I've in the past used an "asset" folder in my component but lately I have been putting all component assets in the media/com_[component_name] folder.

Is there a reason you decided to go with both and have some stuff in one and other stuff in another. It just seems like having it all in one place would be simpler so that's why I was curious as to why the two locations.

Thanks for the help.

**Comment by ro-ot** [comment]
The logic here is simple. You decide.

I like using the asset folder for what is private, and the media folder for what is public. Allowing both options is clearly just to give freedom.

I know @Llewellynvdm is all about **giving freedom** to the developers to be as creative as possible.

**Comment by kevincam3** [comment]
Ok, understood,

I was just wondering if we should be following the Joomla! Best Practices: https://docs.joomla.org/Development_Best_Practices

I use the media folder for what is private and images/com_[component_name] for what is public so users can access it via the media manager. But point taken.

Thanks for the feedback.

**Comment by ro-ot** [comment]
Yes always follow good practice, but allow freedom!

**Public** are the things that helps with design **front-end** stuff _/media_.
**Private** are things that is needed for the component to work **back-end** stuff _/assets_.
**Dynamic** are things the user can change **user** stuff _/images/whatever_.

**Comment by ro-ot** [comment]
Hey @kevincam3 please fork JCB :+1: share the joy!
