### ISSUE TITLE
After adding Mysql for admin view, Error 0 when compiler

### ISSUE THREAD

**Issue by kwaninmacau** [vdm-io/Joomla-Component-Builder#140]
After adding Mysql for admin view, Error 0 when compiler.
Why and how to resolve it?
Thank you very much!

**Comment by Llewellynvdm** [comment]
I am not sure, can be a number of things. 

- Does the component compile without the SQL?
- Can you change the SQL to a smaller simpler version and try again?
- IF you just add a comment does it now work?

Please give us little more information, and feedback.

**Comment by kwaninmacau** [comment]
Thank you for your reply!
First of all, how to "compile without the SQL"?
I just follow your guide video to setup my component and I added Mysql in the admin view and then compiler, as result with error.....By the way, I didn't add Mysql in the component, but even add it, still error....
Any step you miss in the video?

**Comment by Llewellynvdm** [comment]
Please watch this tutorial https://youtu.be/1KBBtQUxMTc

**Comment by Llewellynvdm** [comment]
Trust you have had success, please let us know if you still having an issue.
