### ISSUE TITLE
Site View Creation: Default access public didn't work

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#142]
FYI,

When I created a new view and selected Yes for Public Access then when to the view. I got access denied. When I went to the access settings for the view it was not set to allow for public:

![image](https://user-images.githubusercontent.com/870934/31658241-4835d4a2-b30f-11e7-815c-e15fd3380e6a.png)

**Comment by kevincam3** [comment]
I just finished watching your Hello World component video so I now understand why it didn't work.

**Comment by Llewellynvdm** [comment]
IT will only set the view to public on first install of the component. So if you un-install, and then like a client install for the first time, then it will be set. SO it is a shipping feature, not a update feature.

Let me know if you got it to work now.

**Comment by Llewellynvdm** [comment]
ahh just read you second post... great!
