### ISSUE TITLE
JCB Layouts in dynamicGet

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#145]
I know you have been swamped with all the changes, but I wanted to make a suggestion on moving about some of the subforms on views. For example, on the dynamic gets you can see how it looks:
![jcb-layouts](https://user-images.githubusercontent.com/19194012/31919436-556b6d82-b817-11e7-9bad-11164c22e11f.png)

Everything is scrunched together, making it difficult to see what entries there are. Perhaps just moving them out of the right in tab to left in tab, under "selection". That would give full width for the subform. Or a settings tab like you did on admin views.

**Comment by ro-ot** [comment]
What screen size are you working on? that is not how it looks on my screen.

**Comment by ro-ot** [comment]
![image](https://user-images.githubusercontent.com/2594383/31919754-d5809e64-b864-11e7-8b3f-0296076b326d.png)
This is on my screen, so it actually looks good.

**Comment by mwweb** [comment]
The recommended resolution of my graphics card of 3000x2000.

**Comment by Llewellynvdm** [comment]
Sure we can look at the layout... improvements are always good.

I just what to take small steps at a time, to avoid losing those who already are using the JCB component.
