### ISSUE TITLE
Improvement: Sort order if fields in Editing the Admin View 

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#147]
It would be nice to sort the fields in the order I set them to display in the admin view in the attached view:

![image](https://user-images.githubusercontent.com/870934/31999475-1eb3cf94-b972-11e7-9baf-d2e876cd001d.png)

**Comment by Llewellynvdm** [comment]
The automated sort of the fields has been removed since you can with the subform drag and drop the fields in the correct order very easy.

To avoid us change you own selected order, we removed the feature.

**Comment by kevincam3** [comment]
So do we need the "Order in Edit" if Drag and Drop works?

**Comment by Llewellynvdm** [comment]
yes the drag and drop does work :+1: 

You still need to set the order for edit and order for list, as those orders are for the compiler. The drag and drop is just for you... :)

**Comment by kevincam3** [comment]
Ok, so what I was thinking is we just have one and not both sorts. Unless there's a reason that someone would want them to be different.

**Comment by kevincam3** [comment]
It's not a big deal it was just something that was counter intuitive to me that after I changed the sort order in "Order edit" I was expecting to see them listed in that order after I saved it.

**Comment by Llewellynvdm** [comment]
I do not have one view where those are the same. So of course we want them both, they target two different concepts. The one for the list layout and the other for the edit layout in a tab and position.

**Comment by Llewellynvdm** [comment]
Hey we can always add the sort feature back.. if you are up to the task.

[Look here is the old code](https://github.com/vdm-io/Joomla-Component-Builder/blob/v2.5.5/admin/models/admin_view.php#L2822) that sorted the fields on save. 

Convert it to now work on the new admin_fields. This is [the issue that we last addressed this](https://github.com/vdm-io/Joomla-Component-Builder/issues/43).

[This is the area (line 848 in the admin_fields model) the code must go](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/admin_fields.php#L848).

So adapt the code, test it, and once you think it works as you expected, share it in this issue. Then I will test it and add it to the core once we are sure it works.

**Comment by kevincam3** [comment]
I thought it was just a simple matter of a query that was returning the results in this image and we would just sort by "Order edit" column. But if it's more complicated than that we can leave it as is.

![image](https://user-images.githubusercontent.com/870934/31999475-1eb3cf94-b972-11e7-9baf-d2e876cd001d.png)

**Comment by Llewellynvdm** [comment]
Doing it in the returned results could cause confusion. Since we will display the data in away that is not true to how it is stored. Then once the user opens the fields it will look strange and not in the same order. SO the way is to do it in the model on save, to insure that we have consistency.

**Comment by Llewellynvdm** [comment]
This is not complex... I just don't have time now. Your help with this will be wonderful.

**Comment by kevincam3** [comment]
Ok, got it. I didn't realize that the two sorts served different purposes.

**Comment by ro-ot** [comment]
Hi guys, I have not tested this.
```
if (isset($data['addfields']) && ComponentbuilderHelper::checkJson($data['addfields']))
{
	// Sort fields by 'Tab' ASC, 'Order in Edit' ASC
	$addfields = json_decode($data['addfields'], true);
	if (ComponentbuilderHelper::checkArray($addfields))
	{
		// do the actual sort by tab and order_edit
		usort($addfields, function ($a, $b) {
			$val_a = sprintf('%02u', $a['tab']) . sprintf('%02u', $a['alignment']) . sprintf('%03u', $a['order_edit']);
			$val_b = sprintf('%02u', $b['tab']) . sprintf('%02u', $b['alignment']) . sprintf('%03u', $b['order_edit']);
			return strcmp($val_a, $val_b);
		});
		$data['addfields'] = json_encode($addfields, true);
	}
}
```
But this should work.

**Comment by Llewellynvdm** [comment]
Thanks, I will add that :+1:
