### ISSUE TITLE
Order in list views not working

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#150]
I set the values for Order in list views:
![image](https://user-images.githubusercontent.com/870934/32052684-d11bad26-ba37-11e7-9d8d-8233a04a03a7.png)

Then after compiling the component it looks like this:
![image](https://user-images.githubusercontent.com/870934/32052696-d6f3bc98-ba37-11e7-9ba7-cc142fa49665.png)

**Comment by Llewellynvdm** [comment]
Do not use ZERO :+1: for ordering as a rule. So change `0 => 1, 1 => 2, 2 => 3` compile again.

**Comment by kevincam3** [comment]
Ok, that worked. If we can't use ZERO can we just remove it for the list?

**Comment by Llewellynvdm** [comment]
No :) since if the field is not part of the list view then it is zero, and since the order field is
```
<field 
	type="integer" 
	name="order_list" 
	label="Order in list views" 
	default="0" 
	description="Ordering in relation to list view of admin and site" 
	class="fieldSmall" 
	required="" 
	first="0" 
	last="20" 
	step="1" 
/>
```
We can not have any other value in there then integers, makes only sense to have 0.

**Comment by kevincam3** [comment]
Got it.
