### ISSUE TITLE
status column not translatable in linked view

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#154]
hi, this is not so urgent but in linked view tabs the status column not translatable ( PUBLISHED etc ... ) !
also i have another question why this column is always showing in linked views ? how we can hide this ? 
![image](https://user-images.githubusercontent.com/11753906/32135794-905351a0-bc11-11e7-9d8b-efc2cd5979b9.png)
thanks

**Comment by ro-ot** [comment]
You can overwrite any of the default fields, and then exclude or include them in the list view, in the update that is being worked on at this time.

Secondly the [Status](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/language/en-GB/en-GB.com_componentbuilder.ini#L148) string is translatable, as you can see in JCB itself.

**Comment by ro-ot** [comment]
This is the code that JCB will build when the status is added:
```
<?php if ($canDo->get('admin_view.edit.state')) : ?>
	<?php if ($item->checked_out) : ?>
		<?php if ($canCheckin) : ?>
			<?php echo JHtml::_('jgrid.published', $item->published, $i, 'admin_views.', true, 'cb'); ?>
		<?php else: ?>
			<?php echo JHtml::_('jgrid.published', $item->published, $i, 'admin_views.', false, 'cb'); ?>
		<?php endif; ?>
	<?php else: ?>
		<?php echo JHtml::_('jgrid.published', $item->published, $i, 'admin_views.', true, 'cb'); ?>
	<?php endif; ?>
<?php else: ?>
	<?php echo JHtml::_('jgrid.published', $item->published, $i, 'admin_views.', false, 'cb'); ?>
<?php endif; ?>
```
As you [can see here.](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/views/admin_views/tmpl/default_body.php#L110)

**Comment by sepehr09** [comment]
yes in admin list view this is ok but in linked view it's not translatable
![image](https://user-images.githubusercontent.com/11753906/32170684-cd394ac8-bd8a-11e7-989e-6a543638b0d2.png)

![image](https://user-images.githubusercontent.com/11753906/32170697-db6cd6f0-bd8a-11e7-83e6-df8b871d1491.png)
thanks

**Comment by Llewellynvdm** [comment]
Okay we will add translation to that value, seems like my implementation there was out.

See line [7069](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L7069) in the e_Interpretation.php file of the compiler.

I will add a fix with the next release.
