### ISSUE TITLE
Where do I add views in version 2.6

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#156]
I just upgraded to 2.6 but now I'm looking for where to add an Admin View, there's no button on the Admin Views tab or in the settings. Where do I do this now?

**Comment by sepehr09** [comment]
here : 
![image](https://user-images.githubusercontent.com/11753906/32219217-b2ea735a-be42-11e7-9897-cf84d959b82a.png)
or here :
![image](https://user-images.githubusercontent.com/11753906/32219269-d70e6cb4-be42-11e7-9c50-d18a38e71f42.png)

**Comment by kevincam3** [comment]
Ok,

I don't have that after upgrading here's what it looks like for me:
![image](https://user-images.githubusercontent.com/870934/32219317-f1f9dabe-be14-11e7-8e5b-d69dfe43ed63.png)

**Comment by Llewellynvdm** [comment]
Hi here is a tutorial https://youtu.be/MQrLBYhvGyA

**Comment by Llewellynvdm** [comment]
What about the list view?

![](https://user-images.githubusercontent.com/11753906/32219269-d70e6cb4-be42-11e7-9c50-d18a38e71f42.png)

**Comment by kevincam3** [comment]
Ok,

I just watched the video you sent and clearing the browsers cache did the job, things are now displaying correctly

**Comment by Llewellynvdm** [comment]
Great :+1:
