### ISSUE TITLE
With no view assigned to the dashboard you get an empty rectangle

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#157]
After installing the component and going to the dashboard I noticed an empty rectangle where the add/list buttons appear. I thought something was broken but just realized that I didn't set any view to appear on the dashboard. Not sure if we should not show anything on the dashboard if no view is set or something else.

![image](https://user-images.githubusercontent.com/870934/32219955-0defb4b2-be17-11e7-938f-b5c3c179c91d.png)

**Comment by Llewellynvdm** [comment]
Have you watched the tutorials on setting these things up? Please revert [back to the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/wiki).

**Comment by Llewellynvdm** [comment]
You must add views to the dashboard, yes.

**Comment by kevincam3** [comment]
Ok, would it be difficult to not show the rectangle if there are no view added to the dashboard, at least it won't look like something is broken if you forget to add a view to the dashboard.

**Comment by Llewellynvdm** [comment]
What? are you serious?

Well done, you get :1st_place_medal: today... lol
