### ISSUE TITLE
Help share this tool with other!

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#16]
Hi, Fellow Developers who use Component Builder.

If you have found the Component Builder Tool very helpful and would like to recommend it to other please do so by giving a rating on [Joomla's index](http://extensions.joomla.org/extensions/extension/component-builder).

Also checkout this great [PDF library](http://extensions.joomla.org/extensions/extension/core-enhancements/libraries/tcpdf-library).

To have some more reviews on these great tools will be very helpful to these projects.

Then would you consider to fork some of these projects on github? Let me know if you would need more details on how to do this.

**Comment by mwweb** [comment]
I'm actually working on an article, based on my experience with the many options available for Joomla!, whether other components, or even services, and how I've found Advanced Component Builder to be light years beyond any of them. Once I'm done with it, I hope to submit the article to the Joomla! Community Magazine, in the hopes that they will publish it.

**Comment by Llewellynvdm** [comment]
That will be great, Thanks! Let me know if you need any help on this...

**Comment by mwweb** [comment]
I emailed you a draft of my article on 2016-09-02. I hope that you received it.

**Comment by Llewellynvdm** [comment]
I did not receive anything :)

Please use `joomla [ a t ] vdm.io` if you send it again...

**Comment by mwweb** [comment]
Just resent.

**Comment by Llewellynvdm** [comment]
Got it... wow that sounds great!

I am grateful that you made the effort to write this up and to share your experience with this tool with other ... there is a few tweaks needed (minor)... give me a day or so and I will send you the edited version.

This may surprise you but not everyone is exited about tools like this, and it mostly sounds to me like their greatest objection is that upcoming developers don't actually understand how things work. Like the compiler produces a bunch of code, but that it is hard to maintain the code without the tool. So that if the project dies (by not continually adapting the new conventions and version jumps), your code seems strenuous and almost impossible to continue with. My hope is that component builder is not like this... because I am trying to remain as close as I can to the core components implementation of concepts and tasks.

I know this goes beyond your review and the point you are trying to get across (don't change what you wrote). But take note of this, since I am very sure when you post this review... the critics will be there and this seems to be one of the most plausible objections I have heard against these type of tools. Since most of the other tools like this one breaks out of the Joomla way of doing things, specially of it has huge complexity, and start adding complex class layers on top of the project to work around some of the version changes. Component Builder does none of that... and I hope we would never need to :)

Component Builder is using the Joomla API as closely as we can, and this seems like a more coherent and knowable path, since all developers building components if they read the core components code like that of the article manager will learn to use the Joomla API. All component build does is rename the dynamic values and there relations to your concept and inheritance structure.

My idea was to almost let this tool serve as a cheat sheet to how things can be done... and with the help of other developers (more advanced then me) end up formulating the way how things not only can, but must be done to insure secure, stable, scalable and maintainable code is produced. 

That is why I made it open source, and therefore basically free. I want other to help me make it even better and that it will server as a must have in all Joomla developers toolboxes.

Here is the thing... component builder is mapped as a component in itself on my local development environment. So I am improving it like you would any other component in it. I am looking for developers with the skill and the desire to really join me... and then I will possible share that version with them so we can all help improve this simple, yet advanced tool.

Did you know that there is not really any differences between the versions? I am only adding more sql data to each version, data that if you know how things work you could add it yourself and would not need the sql data I am adding. So the code are the same on all versions... just the database changes.

The Training is what is actually on sale :) and I am working on improving that in a major way... adding much more and structuring the already available stuff so one can more easily find what you are looking for.

Well I need to run again... speak again soon

**Comment by Llewellynvdm** [comment]
Hi @mwweb would you mind to post your review of Component builder on github?

**Comment by mwweb** [comment]
Where would I post a review on here?

**Comment by Llewellynvdm** [comment]
You can post it right here, or open a new issue and post it with new title, or let me add it to the wiki as feedback... I am not sure what will work best.

Hey you can even just post a link here of where you shared it in your network...
