### ISSUE TITLE
Is it possible to use the default fields in admin list view

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#160]
I would like to add a "Created By" column to my list view. I can see that this field is created by default by JCB but is there a way for me to display it in my list view?

**Comment by Llewellynvdm** [comment]
Yes please [watch this tutorial](https://youtu.be/NFp_CtE0LZI), and read [this issue](https://github.com/vdm-io/Joomla-Component-Builder/issues/144).

**Comment by Llewellynvdm** [comment]
Also please review wiki before opening issues :+1: 

https://github.com/vdm-io/Joomla-Component-Builder/wiki#28-how-to-overwrite-the-custom-fields
