### ISSUE TITLE
Sort list by ordering doesn't display that it's "Ordering"

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#161]
Only for Sort Table By: Ordering does it not display what it's ordered by

Below are two screenshots. First one sorted by Ordering, Second one by Status
![image](https://user-images.githubusercontent.com/870934/32356134-3c212cd0-c01a-11e7-9cf0-cfe3d09b95b4.png)

![image](https://user-images.githubusercontent.com/870934/32356139-40fae7fa-c01a-11e7-8ee1-a17265adbd0c.png)

**Comment by sepehr09** [comment]
that's because you sorting by "status" while all records is "published" !
it's normal!

**Comment by kevincam3** [comment]
But when I sort by anything but Ordering it works as I expect and let's me know what things are sorted by. If I sort by Ordering it should show "Ordering" in the sort box in my opinion. Joomla! Articles is an example of how I would expect it to work.

**Comment by sepehr09** [comment]
because sorting by `Ordering`  is default sorting you didn't see `Ordering `in the sort box in your opinion.
and for `status ` ordering you can just unpublish one item & sort again by status.

**Comment by kevincam3** [comment]
I understand what you're saying. I would just expect the behavior to be consistent with the Joomla! core.
