### ISSUE TITLE
spacer field in list ? 

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#162]
hi, i need to put button for my list in admin list view like this picture : 
![image](https://user-images.githubusercontent.com/11753906/32371132-e83825ac-c0a4-11e7-9b4f-d2435b28fe9d.png)

the problem is spacer field is not showing in list view!
i test spacer field but that not show in list view. for now i used hidden field & show print button with model (`Add PHP (getItems Method - before translation fix & decryption)` ), but i don't need save anything in mysql table.

**Comment by Llewellynvdm** [comment]
Hmmm this is a problem, to add none "fields" in the list view is not really a easy task.

Why not do what we did with JCB? I added some custom scripting in the body file, [take a look here](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/views/joomla_components/tmpl/default_body.php#L89) down to [line 132](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/views/joomla_components/tmpl/default_body.php#L132) is all custom script, and is adding all those nice buttons on the page.

**Comment by Llewellynvdm** [comment]
- Another way is with some javascript in the footer of the page, but can be little cumbersome.
- Also adding custom buttons.
- Or we need to adapt JCB, and make this a feature request. (not ideal timing)

**Comment by Llewellynvdm** [comment]
Have you managed this?
