### ISSUE TITLE
Layout Code Snippets are for Sermon extension

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#164]
I created a dynamic get and the Dynamic Get (snippet) is correctly using values from my table but the Layout Code Snippets are for the Sermon extension. 

![image](https://user-images.githubusercontent.com/870934/32384960-b630ed06-c0a3-11e7-89f6-788601863bad.png)

**Comment by Llewellynvdm** [comment]
The layout can be added to any component (does not belong to any component) and so it does not at this time filter the layouts.

We may look at this again. but for now it will load all.
