### ISSUE TITLE
How do you do menu item parameters

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#166]
I've been looking high and low and can't find how to be able to modify my menu items to add custom parameters.

I can see Sermon Distributor has custom parameters a tab called "Sermon Distributor" but I can't find out how it was created in JCB.

**Comment by mwweb** [comment]
I dealt with that myself. You need to have the tab named identical to the site view. For example, if the view is My Site View, in the component settings there needs to  be a tab titled My Site View. Then on compile it should add the settings(options) to your menu item.

**Comment by kevincam3** [comment]
Are we talking about tabs in the admin view or tab in the configurations?

**Comment by mwweb** [comment]
JCB->Joomla Components->Settings->Config.

Have the name in the tab name column match whst you have in Name in your site view.  Note: name, not system name.

**Comment by kevincam3** [comment]
Thanks, this seems to be broken, are you able to save anything in there. I can't even open the Sermon component and resave it. 500 error.

**Comment by mwweb** [comment]
I guess i wasn't really clear in my previous post. First time back online in almost a week dealing with a horrible case of stomach flu.

**Comment by Llewellynvdm** [comment]
The config area was fixed with the last release, so you should be able to now save changes made in it.

**Comment by kevincam3** [comment]
I have a view named players and I have a tab in config name players so I have have a menu item parameter but I want to include on the same tab some other things but don't want them to show up as menu item parameters. Any ideas?
