### ISSUE TITLE
Problem trying to save Component Config Tabs

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#167]
Here's the page I was just trying to re-save without making any changes to the variables
![image](https://user-images.githubusercontent.com/870934/32402009-5a58ad66-c102-11e7-86c4-00be9259bdf2.png)

Debugging the problem it looks like the issue is the filter set on the subform
![image](https://user-images.githubusercontent.com/870934/32402026-741a30bc-c102-11e7-897e-0bfc6ff30077.png)

I changed the filter from SAFEHTML to RAW and I can now save it.
![image](https://user-images.githubusercontent.com/870934/32402033-8b78158a-c102-11e7-82aa-b4a703a130f6.png)

I don't know if RAW is okay but it works

**Comment by Llewellynvdm** [comment]
Thanks for that, I will push a fix urgently to fix this. Raw is not good....

This issue came up due to a change in Joomla.
