### ISSUE TITLE
Is there a way to remove the author info on the Global tab

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#170]
I would like to get rid of this information from the global tab on my component.

![image](https://user-images.githubusercontent.com/870934/32404817-8597a0f8-c13f-11e7-8dcc-d441b0be8744.png)

**Comment by Llewellynvdm** [comment]
These details __Author__ are updated with your details set in the component view. SO yes you can change that to your name and contact details. But know it can not be removed at this time.

Not sure why you would not want it in the component unless you want to build a component that does not show who build it, hey then use a fake name :+1:

**Comment by kevincam3** [comment]
Can we at least get rid of the The Author Info, it's spacer that shows text.

**Comment by kevincam3** [comment]
Or have it pull an actual value from the xml file

**Comment by Llewellynvdm** [comment]
? explain more...

**Comment by kevincam3** [comment]
The "Author Info" is in the xml as a type Spacer.

**Comment by kevincam3** [comment]
It has a label and that's why it show "Author Info" but it's not a field, it's a spacer with a label

**Comment by Llewellynvdm** [comment]
Not now... we can look at this again when we have more asking for it :+1:

**Comment by kevincam3** [comment]
Ok,
It's not a deal to remove it outside of JCB. Thanks.
