### ISSUE TITLE
Can we enhance function for multilanguage support ?

### ISSUE THREAD

**Issue by ngagestudios** [vdm-io/Joomla-Component-Builder#171]
Can we enhance function for multilanguage support ?

**Comment by Llewellynvdm** [comment]
Have you [watched the tutorial on this](https://youtu.be/zzAcVkn_cWU?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)?

What would be the extra functions you have in mind?

**Comment by ngagestudios** [comment]
I meant this function 

![image](https://user-images.githubusercontent.com/12871321/32405487-5dfc80c0-c18c-11e7-9f6b-a663d02c0e23.png)

Just so we can choose which language item would be for

**Comment by ngagestudios** [comment]
Our component  creator doesn't add this language chooser - Didn't found any documentation for that as well.

**Comment by Llewellynvdm** [comment]
Yes that is an amazing feature we still do not have, I have been putting it off since it seems like a huge complex concept that I have been avoiding. Are you up for the task?

I mean do you know exactly how that should be hand coded into a 3rd party component?

**Comment by ngagestudios** [comment]
Nope - i am just beginner with Joomla :(

**Comment by Llewellynvdm** [comment]
Okay... no worries. I know how to do it by hand, but to automate it is really complex and I am waiting for another dev to join the project that also knows how this is done well, so we can work on it together. So it may still take some time... but we will get there.

But believe me there are tones of stuff it already does, and does well....

**Comment by ngagestudios** [comment]
Yes that's really awesome plugin. also i didn't find guideline on how to open item on frontend.

I checked video to get a list on frontend and it worked but didn't found similar function of getGreetRoute() on new compiled component. Just curious to know if our component builder creates controller function to open single item?

**Comment by Llewellynvdm** [comment]
Take a look at this[ play list](https://www.youtube.com/watch?v=1KBBtQUxMTc&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE), make sure to watch the hello world tutorial first :+1:
