### ISSUE TITLE
What the different in admin view  between Add PHP (save Method - before data modeling) and Add PHP (save Method - after data modeling) *

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#175]
I added these as comments to see where they would appear in the code and the appeared one after the other. I was expecting they would appear in different parts of the code.

![image](https://user-images.githubusercontent.com/870934/32524899-0f3cf512-c409-11e7-8b10-a50e9a2a0727.png)

**Comment by Llewellynvdm** [comment]
That model does not have modeling...

So if the model had translated values, encrypted or json conversion the code will end up above and below the code.
