### ISSUE TITLE
Editing the Dynamic Get

### ISSUE THREAD

**Issue by Safweb** [vdm-io/Joomla-Component-Builder#176]
Editing the Dynamic Does not work after update to joomla 3.8.2
There is nothing in the selected field.
That's when I try to add a Join View Tables
![erroonjbc](https://user-images.githubusercontent.com/33495847/32567839-cf99d772-c4bc-11e7-9483-a22d9c210fbb.png)

**Comment by Llewellynvdm** [comment]
Please clear your browser history.

**Comment by Llewellynvdm** [comment]
Did that resolve your issue?

**Comment by Safweb** [comment]
Yes, it helped after a few times, could not understand it had tried several different browsers.
Thank you very much
