### ISSUE TITLE
Exporting a component and importing it to another computer, it's missing config information

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#178]
So I exported my component to share it with a friend and when he imported it, everything was correct except the component config information.

Here is what the config section looks like on my computer, the original
![before-component-import-config](https://user-images.githubusercontent.com/870934/32628604-969528a2-c57d-11e7-9f03-20fa51729f63.png)

Here's what it looked like on my friends computer after the import

![after-component-import-config](https://user-images.githubusercontent.com/870934/32628625-ac0bbe62-c57d-11e7-927f-828c1be5be61.png)

**Comment by Llewellynvdm** [comment]
I am not sure how this can happen, all I can think is adding a debugger to the JCB package importer. So you can look at the actual JSON object being exported and being imported.

Then also on importing did you not get any waring messages saying that some mis matches were found?

Mismatching can happen do to a thousand reasons. But not being able to actually debug the import, it is hard for me to say anything.

**Comment by kevincam3** [comment]
No warning messages or errors on the import

**Comment by Llewellynvdm** [comment]
Okay thanks for the feedback on this in issue gh-179
