### ISSUE TITLE
Log File?

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#18]
Just a question here: is there a log file some where that contains errors that take place within components that CB builds? I have a component compiling and installing fine, but one of the views appears with a blank screen.

Thanks,
Paola

**Comment by Llewellynvdm** [comment]
You need to setup your PHP developing environment to show errors, and then it should print to the screen your errors... if you don't know how to do this... google "make PHP show all errors" and you should get some tutorials on how this is done.

**Comment by paolavness** [comment]
Ah yeah I've got that. I was thinking more internal errors. I figured this out tho - in the admin view, the **_  Name (single record)_** and **_Name (list or records)_** were both the same! D'oh, I forgot the 's' to make it plural!

**Comment by Llewellynvdm** [comment]
The only way to get more breakdown of the compiler.. is with adding the line-numbering feature that adds line numbers to each comment to show more-and-less where that part of the code was build... I think I mention some of that in the tutorials... and the rest is up to you and x-debug....
