### ISSUE TITLE
JForm::getInstance(name, *string*)

### ISSUE THREAD

**Issue by madiba07** [vdm-io/Joomla-Component-Builder#180]
Hello, I'm having trouble using Compiler Builder. Whenever I try to create an Admin View, when I try to create an Admin Fields I can't use the button to add a new Field, because I always get the error JForm:: getInstance (name, * string *)

Can somebody help me?

![editing_the_admin_fields](https://user-images.githubusercontent.com/6475471/32747505-d14dbd5c-c8b0-11e7-919f-e95e26cafe32.jpg)

**Comment by Llewellynvdm** [comment]
Okay not sure what you are seeing here... I have not seen this before.

So please give some more info, like version and environment details.

Make sure that you are using the latest Joomla 3.8.x and JCB 2.6.3

**Comment by madiba07** [comment]
Now it's working. 

I installed the Joomla version 3.8.x and I don't have the error. 

Thank you.
