### ISSUE TITLE
Extend Add MySQL (to view table) 

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#182]
This option, in the JCB component view, under the MySQL tab is a great feature. I have a "companion" component for another component I created. We'll call the "companion" component B, and the main component A.

Component A works fine by itself, but to use the added functionality in Component B, there are a couple of tables that need to be added to Component A. The Add MySQL functionality is great for handling this.

What would be a good addition is to add a "Remove MySQL (from view table)". 

Where "Add Mysql" add the SQL to the admin/sql/install.mysql.urf8, it would be nice to have "Remove Mysql" which would add the custom SQL to the unistall.mysql.utf8 file. That way, on install it would install the custom SQL, then on uninstall it would remove the custom SQL.

**Comment by Llewellynvdm** [comment]
We will get back to this, great idea :+1:
