### ISSUE TITLE
multilanguage not work.

### ISSUE THREAD

**Issue by ebrahimiali9005** [vdm-io/Joomla-Component-Builder#184]
hello.
multilanguage not work.
1. i Create new Language . (example: persian (fa-IR)) and translated two words.
2. compile component.
3.open zip file and not found fa-IR language.

**Comment by mwweb** [comment]
I don't recall the number, but i do see to recall that when this feature was added that there is a minimum number of translations needed before it will compile the language strings.

**Comment by ebrahimiali9005** [comment]
warning
The admin fa-IR language has 188(total en-GB strings) only 19(strings fa-IR translated) = 10% translated, you will need to translate 50% of the language strings before it will be added.
