### ISSUE TITLE
Admin View Model losing params data

### ISSUE THREAD

**Issue by stutteringp0et** [vdm-io/Joomla-Component-Builder#185]
### Steps to reproduce the issue
I'm bringing in additional form elements into an admin view via ajax, saving the data as params.  Upon save, getItem attempts to convert $item->params from json data to an array, but parent::getItems has already done it - throwing an error in the logs and removing the array from $item->params. 

### Expected result
params data remains in tact

### Actual result
params data is removed

### System information (as much as possible)
not necessary, I have your solution

### Additional comments
I'm guessing this is for older versions of Joomla that don't automatically process params values, so to maintain that compatibility - In the compiled model output, put an extra check in the params test:
if (!empty($item->params) && !is_array($item->params))

I'm working around it in my model using the "Add PHP (getItem Method)" to re-retrieve the item and set params back to the value provided by parent::getItem

**Comment by stutteringp0et** [comment]
Created PR #186 to resolve this

**Comment by Llewellynvdm** [comment]
Next time add the words *resolve gh-185* in your _git comment_ then the RP will showup in the issue area and close the issue when the RP is merge into master :+1:

**Comment by stutteringp0et** [comment]
You approved the PR - so I guess this can be closed?
