### ISSUE TITLE
default fields added to all views are named incorrectly in the display

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#188]
I just noticed that in the screenshot there's "date_created" but in the xml it's "created", I also didn't find "date_modified" but "modified" I guess there could be others.

![image](https://user-images.githubusercontent.com/870934/33331490-e1998fda-d448-11e7-904a-be51fcb9d341.png)

**Comment by kevincam3** [comment]
Related to this, it didn't override the value. I got a warning that the value already exists:

![image](https://user-images.githubusercontent.com/870934/33333046-00f4b82e-d44d-11e7-9774-68b827fded78.png)

**Comment by Llewellynvdm** [comment]
It looks like I did not update the note, it should say created and modified and not date_created... I willl update the note.

So if you want to override those fields to just change the name to created or modified.

**Comment by kevincam3** [comment]
@Llewellynvdm,

Any idea why the override isn't working properly when I try to install?

**Comment by Llewellynvdm** [comment]
Kevin this can be many reasons, best investigate your database and then the update sql in the Joomla package. I can not say, just that it is not normal and most likely an error on your part.

The normal implementation of this feature still works as expected, so to debug this will be up to you. You are welcome to give us feedback if you find out more, and if you feel this is a bug. In which case you will need to give much more information and explanation from your side.
