### ISSUE TITLE
Error after instalation

### ISSUE THREAD

**Issue by ofeyer** [vdm-io/Joomla-Component-Builder#190]
After instalation I got this error:
Parse error: syntax error, unexpected '.', expecting ')' in /home/anunturiaf/public_html/administrator/components/com_componentbuilder/helpers/componentbuilder.php on line 1496

I try to install CB on 3 diferent Joomla sites and i got the same error

**Comment by Llewellynvdm** [comment]
Please [read previous](https://github.com/vdm-io/Joomla-Component-Builder/issues/187) issues before just opening an issue. This is an old issue....

Just upgrade your php... read [closed issue 187](https://github.com/vdm-io/Joomla-Component-Builder/issues/187)
