### ISSUE TITLE
How can I change the default name when adding categories to my component

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#193]
I would like to change "Game Category" to "Categories" like default Joomla! articles does. I know I can do a language override but was wondering if it could be done directly prior to compile time.

![image](https://user-images.githubusercontent.com/870934/33608367-75965602-d9ab-11e7-8e71-90a588489dea.png)

**Comment by Llewellynvdm** [comment]
Sorry for the slow reply here... in the xml of the category field add the following:
```
othername="Categories"
```
That should do it, if you still having issue, check out the code here on lines [1434](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L1434) in the complier where it start building that logic. Then follow the `$this->catOtherName` class variable around to see how we use it.

Hope this helps!

**Comment by kevincam3** [comment]
@Llewellynvdm thanks. That worked. I had to look at the code because you have to also set: view="view name" and views="views name". I modified the Fieldtype to include these values. Thanks for pointing me in the right direction. I would've never known about these other options.

**Comment by Llewellynvdm** [comment]
Okay great, you are welcome.

But hey you can find tones of hidden tricks in JCB if you read over the compiler and try to understand how the compiler does what it does, since once you manage that you will become empowered developer of JCB :+1:
