### ISSUE TITLE
Siteview - Javascript & CSS tab malfunction

### ISSUE THREAD

**Issue by robbounds** [vdm-io/Joomla-Component-Builder#202]
### Steps to reproduce the issue
upgraded to latest JCB version 2.6.7

### Expected result
the usual smooth upgrade :)

### Actual result
immediately upon updating the component I opened an existing site view, made a small change to the default view, clicked save and received an alert/error, "some fields are unacceptable". I found a text field, 'Add Javascript (field)' was stuck open in the Javascript & CSS tab. All radio buttons in the tab indicated "no". I tried to toggle all buttons and only one actually worked, 'Add CSS (custom document script)' and it appeared to toggle the wrong field.  

### System information (as much as possible)
JCB version 2.6.7
Joomla 3.8.3
PHP 7.1
MACBook Pro 2012
macOS High Sierra
chrome, safari, firefox

**Comment by robbounds** [comment]
In addition, I did try multiple site views with the same results. Currently I'm unable to save anything unless I put a random comment in the open text area.

**Comment by Llewellynvdm** [comment]
Please clear your browser history, I mean completely including the cache. This should resolve it.

Let me know.

**Comment by robbounds** [comment]
Clearing the cache resolved the issue. Thanks!
