### ISSUE TITLE
Transfer issue between machines - admin fields not displaying

### ISSUE THREAD

**Issue by alexsykes** [vdm-io/Joomla-Component-Builder#204]
This may be similar to #178 and #179 - I am running JCB on both a desktop and a laptop and transferring between them. When exporting and importing between machines, the Admin Views lose some of their data so that clicking on the 'Edit the admins fields' icon does not display the existing fields. 

### Steps to reproduce the issue

1. Export Component from JCB
2. Import into JCB on different machine

### Expected result

1. Full functionality

### Actual result

1. From Admin Views view, click on 'Edit the admin fields' icon - goes to correct view but fields do not display
2. in Editing the Admin View/Fields and Conditions, list of fields below displays - but clicking the 'Edit admin fields for this admin view' button fails to display them for editing.
3. Hitting 'Save' in both of these screens (with no fields displayed) deletes the existing fields.

### System information (as much as possible)
Using identical machines - macos - and latest JCB.

### Additional comments
Looking at the SQL, there is a difference in the data in the #__componentbuilder_admin_fields table.

Functioning fields have a structure such as 
`{"0":{"field":"1020","order_list":"0","tab":"1","alignment":"1","order_edit":"0","permission":"0"},"1":{"field":"1030","order_list":"0","tab":"1","alignment":"1","order_edit":"0","permission":"0"}}`

Once transferred the data becomes
`[{"field":"1020","order_list":"0","tab":"1","alignment":"1","order_edit":"0","permission":"0"},{"field":"1030","order_list":"0","tab":"1","alignment":"1","order_edit":"0","permission":"0"}]`

That is - SQL is enclosed by […] and each field entry loses ' "n": '

**Comment by Llewellynvdm** [comment]
## System information (as much as possible)
> We need to know the versions of all of the stack involved, no help saying identical machines.... is it Ubuntu, is Windows, is Joomla 3.x, is PHP x, is it JCB x 

AS MUCH AS POSSIBLE information please.

I am aware of issues, but surrounding the new library area, not the admin view area so I will take a look. Thanks for the heads-up, please give use your system information, thanks!

**Comment by alexsykes** [comment]
System - MacOS - 10.13.2 - both development machines are running identical systems at home. I do NOT do any development on a live server.

 PHP 7.1.7
 MySQLi 5.6.31
Joomla! 3.8.3 StableApache/2.4.28 (Unix) PHP/7.1.7
JCB - Current build - 2.6.7

Will add that all seems OK after correcting the database data manually. The overall picture appears to be that:

- Compiled components built on one machine and compiled are portable and will install successfully on a different machine
- Projects built on one machine, then exported can be imported onto a different machine
- If the _admin_fields table is corrected by hand, all is OK 

So, if I wish to move a component, I export to a JCB_componentName.zip, copy and Import onto alternative machine, then edit the SQL data for the admin_fields table.

Hope this helps

**Comment by Llewellynvdm** [comment]
I have just ran some test on some of the biggest component I have, with like 997 fields, and it imported all those admin-views and fields without any issues.

Hmm lets see, you say you need to correct the _admin_fields table, what are you correcting, and if you start with a blank Joomla-JCB system and then import, does it do the same?

I am surprised that JCB works in PHP 7.1, I have never tested or used it in PHP 7, only some of the other developers have (who also said it works), I am still in PHP 5.6 :+1: 

I am trying to see where we have the conflict and what causes it, to me it seems divergent issue, meaning that some where something broke and now it can not recover since it is diverged from what is expected in the code.

Your feedback on this will help immensely!

**Comment by Llewellynvdm** [comment]
I suspect you are very able in PHP, maybe you can help me look at the PHP and see it I missed something. There are two places we are doing the work.

From line [94 in the joomla_components](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/joomla_components.php#L94) model is where the export is build.
The import is done in import_joomla_components model, the main functions start from around line [633](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L633).

You will follow basic conventions of trying to insure that old packages can also still be imported, but mainly that madness is the ID remapping done in the [setNewID](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1071) method, you can also take a closer look at the [prepItem](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1234) method to see how each table/view and relationships are build.

You can find the admin_fields being build on line [1759](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1759) as it is being passed to [updateSubformsIDs](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1800) where all ids are updated. 

If there is an issue it will be happening around this area. I can not see it, maybe you can. So if you see any typos, discrepancies or PHP7 incompatibilities, let me know.

**Comment by Llewellynvdm** [comment]
It could be that using the good old json_encode on [line 1016](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1016) is not working out well. I know Joomla has its own string class to do it, can that be the issue?

**Comment by alexsykes** [comment]
OK. Thanks. Will try a clean install (when I get a moment). The difference between the data sets is as in the first post. 
(1) Data is surrounded by one pair square [ ] brackets after transfer rather than braces {}
(2) Each field loses its "0":  - what I take to be an identifier. 

Unfortunately, I’m pretty good with what I know in PHP – but, once I get beyond that, it’s all a little hazy. Which is why JCB is such a God-send to me. I’ve attached a before and after dump of the particular field/table. I will take a look at JCB’s code – but can’t promise anything.

Anyway, I've attached two SQL files - before (from the developer machine) and after (transferring to the other machine). If you look at the data in the _add_fields field- around line 52 in each file, you will see the difference. 


[After_componentbuilder_admin_fields.txt](https://github.com/vdm-io/Joomla-Component-Builder/files/1584148/After_componentbuilder_admin_fields.txt)
[Before_componentbuilder_admin_fields.txt](https://github.com/vdm-io/Joomla-Component-Builder/files/1584149/Before_componentbuilder_admin_fields.txt)

**Comment by Llewellynvdm** [comment]
Wat is weir here is the before database values, it should instead look like this:
```json
{
  "addadmin_views0": {
    "adminview": "45",
    "icomoon": "user",
    "mainmenu": "1",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "edit_create_site_view": "1",
    "order": "1"
  },
  "addadmin_views1": {
    "adminview": "46",
    "icomoon": "briefcase",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "2"
  },
  "addadmin_views2": {
    "adminview": "1",
    "icomoon": "heart",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "3"
  },
  "addadmin_views3": {
    "adminview": "5",
    "icomoon": "cube",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "4"
  }
}
```
Not like this
```json
{
  "0": {
    "adminview": "45",
    "icomoon": "user",
    "mainmenu": "1",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "edit_create_site_view": "1",
    "order": "1"
  },
  "1": {
    "adminview": "46",
    "icomoon": "briefcase",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "2"
  },
  "2": {
    "adminview": "1",
    "icomoon": "heart",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "3"
  },
  "3": {
    "adminview": "5",
    "icomoon": "cube",
    "dashboard_add": "1",
    "dashboard_list": "1",
    "submenu": "1",
    "checkin": "1",
    "history": "1",
    "metadata": "1",
    "access": "1",
    "port": "1",
    "order": "4"
  }
}
```
I wonder if that is a php7 thing? since I just opened a few of those and it still saves it with the field name as not only the number. I know json_decode will always strip the numbers since it is the same with or without.

So I think we are onto the problem here, those pointers should not be just numbers, but they are.... hmmm I can tell you that the method that saves the values are just using json_encode, so it must be how the subform is build on submission.

**Comment by Llewellynvdm** [comment]
So the fields should look like this:
```json
{
  "addfields0": {
    "field": "199",
    "list": "1",
    "order_list": "1",
    "title": "1",
    "alias": "0",
    "sort": "1",
    "search": "1",
    "filter": "0",
    "link": "1",
    "tab": "1",
    "alignment": "4",
    "order_edit": "1",
    "permission": "0"
  },
  "addfields1": {
    "field": "23",
    "list": "0",
    "order_list": "0",
    "title": "0",
    "alias": "1",
    "sort": "0",
    "search": "0",
    "filter": "0",
    "link": "0",
    "tab": "1",
    "alignment": "4",
    "order_edit": "2",
    "permission": "0"
  },
  "addfields2": {
    "field": "1",
    "list": "1",
    "order_list": "2",
    "title": "0",
    "alias": "0",
    "sort": "1",
    "search": "1",
    "filter": "0",
    "link": "0",
    "tab": "1",
    "alignment": "4",
    "order_edit": "3",
    "permission": "0"
  },
  "addfields3": {
    "field": "237",
    "list": "1",
    "order_list": "3",
    "title": "0",
    "alias": "0",
    "sort": "1",
    "search": "1",
    "filter": "1",
    "link": "0",
    "tab": "1",
    "alignment": "7",
    "order_edit": "1",
    "permission": "0"
  }
}
```

**Comment by alexsykes** [comment]
OK. The numbers in place of the _addfieldsN_ data are what I added to get it functioning. I have just now added a new Admin View and compiled and this is still giving a single number in the data. **However, the Demo component supplied with JCB is as it should be.**

Let's put it on 'Hold' until I've done a complete clean install and looked at the code again with a new component. It's always possible that, as you say, it's a cumulative thing and I'm certain that you have far more vital stuff to be giving your energy and time to. I've got some time tomorrow and will get back to you.

**Comment by Llewellynvdm** [comment]
Believe me this area is vital, and if we have a bug we must fix it.

This export and import of JCB packages is being used by teams, and partners on a large scale so please, no worries, we must fix this whatever is causing the issue.

I have it going over the code found some other bugs, so this is proving to very productive. I have looked at the JavaScript, but I can't see any issues there. Clearly the PHP is not responsible for the form, but JS is building it, so that eliminates PHP7 as being part of the issue.

What browser are you using, does it save the form with only numbers from other browsers as well? This could be a Joomla bug, or fix, they may have changed things. Yet I am also on Joomla v3.8.3 and it has worked like this since subforms were added.

Sure give me your feedback once you've been able to evaluate this some more.

**Comment by Llewellynvdm** [comment]
Just as point of interest in the database where you export the component does it save the data with just numbers?

I mean JCB could be the one dumping the name from the associative array. So what is important is to know if the values we start with is correct, you will see that in the `#__componentbuilder_admin_fields` table in the `addfields` column.

So just check that if we have the correct values there, then we know the issue happens during export, and not import as I though initially.

**Comment by Llewellynvdm** [comment]
All you would need to do to get a original set of values in the table is open one of the admin fields and save the item again, then look in the DB.

**Comment by alexsykes** [comment]
OK. Done a fresh - completely clean install. New Joomla, new JCB - notes follow - all dumps attached
--------
Clean Install
Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT 
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
JCB - 2.6.7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0 

Following JCB install - 
Dump_1.sql - One field OK; 

Add Admin View and compile - no change to DB
Add 2 fields to Admin View -> Dump_2.sql - Index number only '0' - not 'addfieldsN'

Compile - OK
Install from JCB - OK 
Try to add item from Admin Menu - gives error "Table 'joomla.#__test_item' doesn't exist Table 'joomla.#__test_item' doesn't exist"

Compile again and install from Admin Extension Install - OK - but table still does not exist

Open compiled com_test_v1_0_0__J3.zip file and upload using PHPMyAdmin included install.mysql.utf8.sql file gives error message "#1101 - BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value"

Remove " DEFAULT ''" from SQL and try again

1067 - Invalid default value for 'created' 

Remove default values for all DATETIME fields 

Success! - Table created - data entered

Add record from Admin area - all OK

Make minor changes to Admin View - add Link to fields - All OK and can edit records.

Export Component then install on second Joomla - All OK!
test_item table initialised - OK
Component functions - OK

However - in JCB/Admin Views, click on Admin Fields icon goes to Editing the Admin Fields screen but NO fields list. 
'Close' - all OK
Save & Close - empties addfields data - dump_4.sql

Adding fields again Success - but still only a number in addfields field - dump_5.sql 
----------
Hope all this makes sense. Must leave it now - I'm probably in a different timezone to you (GMT+3)

One more thing - library snippets do not appear to be reachable. That's possibly a local issue as I'm in Saudi Arabia and there can be issues with the national proxy. Will be back in UK next week and check this out.
-----------

[CleanInstall.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/1584345/CleanInstall.zip)

**Comment by stutteringp0et** [comment]
Wherever that json_encode is firing - it probably needs a JSON_FORCE_OBJECT flag to prevent conversion to an array.

**Comment by Llewellynvdm** [comment]
Yes I think the flag will ensure correct formating. 

About the date format not having default '0000-00-00 00:00:00' even [Joomla still adds](https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L136) that as default. So this may be due to strict MySql or something in your setup that, not really sure.

@alexsykes your last response is a little of target in regard to the issue, or so it seems to me. There are many things being mentioned that I do not think is all related to the import export function.

Just to give you and idea, as a test, I exported (from Site A) JCB from JCB (called package 1) and imported it into another (Site B) blank Joomla (that has JCB on it) install. Then I compiled the new JCB (on Site B) and reinstalled, and everything just worked perfectly with no issues, or hangups. I then compiled it again (on site B) and installed it into a third (site C) blank website. Then I imported (on Site C) it again (with package 1) compiled it again (on site C) and installed it on site B. Then exported (package 2) from site B and imported it to site C and so it goes on and on as I am trying to debug the issue. Yet in all that I did not see the same results that you see. So it is hard to debug and fix something I can not see. To me it seems to work very good.

What I will do is add the FORCE object where needed, and the push that to the staging branch of JCB. I will then open a pull-request that @alexsykes would need to help test. I should have this ready some time next week, taking a break the next few days.

**Comment by alexsykes** [comment]
> @alexsykes your last response is a little of target in regard to the issue, or so it seems to me. There are many things being mentioned that I do not think is all related to the import export function.

Apologies for going off track. I was trying to give a complete picture of the procedure I had followed. I think the main thing that it indicated is that the issue is not related to the portability of the component but, rather, the initial storage. 

I've just done a further test on my production (real world) server and get similar results. The _Look_ admin field as supplied in the Demo component initially shows in the database as 'addfields0'. A new admin field does not - but simply as a '0'. Further, on editing and saving the _Look_ field, the data for this changes to a '0'.

Unfortunately, as I'm on shared hosting, I can't give too much detail on the server configuration. I do know that it is running PHP 7.0.26 and MariaDB - 5.5.5-10.0.33. One slight irritation is that it doesn't have 'Tidy' installed and gives an error when I try to compile and install. I'll follow up on this with hosting provider.  In the meantime, enjoy your Christmas.

**Comment by alexsykes** [comment]
A little bit more - and I think I may have found at least part of the cause of the issue. As you surmised, it appears that the issue is not related to the portability of the data but occurs at an earlier stage. My apologies for this and the time wasted on that - however, that was when it showed up.

Using JDump, I have been tracing the point at which _addfieldsN_ becomes _N_ and have located the change at this part of the _models/admin_fields.php_ file

```
if (isset($data['addfields']) && ComponentbuilderHelper::checkArray($data['addfields']))
{

	// Sort fields by 'Tab' ASC, 'Alignment' ASC, 'Order in Edit' ASC
	usort($data['addfields'], function ($a, $b) {
		$val_a = sprintf('%02u', $a['tab']) . sprintf('%02u', $a['alignment']) . sprintf('%03u', $a['order_edit']);
		$val_b = sprintf('%02u', $b['tab']) . sprintf('%02u', $b['alignment']) . sprintf('%03u', $b['order_edit']);
		return strcmp($val_a, $val_b);
	});
	
}
```
At first glance, this PHP appears to be way beyond my knowledge but I will try and take a further look today. I have noted that:
1) whatever state of the data in the _#__componentbuilder_admin_fields addfields_ table, the data is correctly '_addfieldsN_' at this point
2) following this code, it has become '_N_' only
3) commenting out the portion within the 'if' loop retains the '_addfieldsN_' data. The database reflects this.

**Comment by alexsykes** [comment]
Could this https://bugs.php.net/bug.php?id=69158 be relevant?

**Comment by Llewellynvdm** [comment]
I have made a few changes to the core to try and fix this. Let me know if the issue remains after the next update is released.
