### ISSUE TITLE
 Call to undefined function bcadd()

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#208]
### Steps to reproduce the issue
Trying to compile one of my extensions after upgrade to 2.6.9

### System information (as much as possible)
- OS Name & Version:  Linux
- MySql Version:  5.7.14
- Apache Version: 2.4
- PHP Version: 7.1.11
- Joomla Version: 3.8.3
- JCB Version:  2.6.9
- Browser: Chrome  63.0.3239.108 (Official Build) (64-bit)

### Additional comments
Some others work, but I have one that no longer will compile after the upgrade

**Comment by stutteringp0et** [comment]
That's one of the BC Math functions.  Your PHP installation is missing the bcmath extension.

If your Linux is debian based, you can add it with apt-get install php-bcmath

RHOS/CENTOS is something like yum install php-bcmath

The install method gets more complicated with other linuxes.

**Comment by kevincam3** [comment]
@stutteringp0et,
Thanks that fixed it.
