### ISSUE TITLE
issues with multiple categories in admin view

### ISSUE THREAD

**Issue by PixedBo** [vdm-io/Joomla-Component-Builder#209]
### Steps to reproduce the issue
I've created a category for an Admin View. Field is "TEXT" and Store Method is "JSON" because i want to be able to choose more than one category. This is the XML

<field 
	type="category" 
	name="catid" 
	label="Categoria" 
	extension="com_sabgest.clienti" 
	scope="" 
	required="true" 
	show_root="false" 
	default="" 
	description="Seleziona una categoria per questo cliente" 
	class="inputbox"  
	multiple="true" 
	showon="" 
/>

I've set up the field to be view in Admin View (Admin List)

### Expected result

In admin view (backend) see the table and one colum contains the multiple categories

### Actual result

When i click on the Admin view i get this error:

1146 Table 'ui6le1hj_sabgest.#__sabgest_catid' doesn't exist 

Sabgest is the component name, the prefix is ok but it seems that the table name is added 2 times. Did try to uninstall and reinstall several times...

### System information (as much as possible)
- MySql Version: 5.5.5
- Apache Version:  n/a
- PHP Version: 7.0.11
- Joomla Version: 3.8.3
- JCB Version: 2.6.9
- Browser: Firefox

**Comment by Llewellynvdm** [comment]
Yes, at this time there can be only one category per/view. This is because the field name is dynamically changed to catid to remain in sync with some of the Joomla conventions in relation to the permission structure and history integration.

So this is a known limitation, if you know of a way to implement multiple categories and remain fully integrated with Joomla let me know. I would suggest using tags, and possibly even another admin/table in a custom field.

**Comment by mwweb** [comment]
I, too, was looking at multiple categories at one time. But, from all my reading on the Joomla Forums, multi-category is not now an ability of Joomla!, nor is it planned for any time in the near future. In all the posts, it is recommended to use Tags. JCB has tags, but as I understand it, tags aren't fully built out yet, so some custom codes need to be utilized.

Tag might be an area where we will want to build out to provide this ability.

**Comment by Llewellynvdm** [comment]
The tags work as a field, and functions perfectly. You will just have to code the linkages of the front-end use.

I am using tags all over many of my projects.
