### ISSUE TITLE
Bug in Model:  $this->vvvv = $item->;

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#21]
Hey there,
Looks like a bug...

> Parse error: syntax error, unexpected ';', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in administrator/components/com_xxxx/models/programme.php on line 105

Went to line 105, this is what i found:

> $this->vvvv = $item->;

Happened after I added a linked view.

Thank you,
Paola

**Comment by Llewellynvdm** [comment]
This seems like a setting that is not correct, I would like to take a look. Will contact you via skype :)

**Comment by paolavness** [comment]
Ahh, thank you for help with that. Coding at 3am in the morning, i mistook the hint of 'id' in the input box for the parent lookup link, as an actual input... IE, the error occurred because there was nothing in the parent look up field.
