### ISSUE TITLE
Admin add view, missing function to load form

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#210]
See screenshot

### Expected result
Model would have the getForm method

### Actual result
Wrong extended class and missing methods

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.14
- Apache Version: 2.4
- PHP Version: 5.6.32
- Joomla Version:  3.8.3
- JCB Version: 2.6.9
- Browser: Chrome 63

### Additional comments
Just wondering if the name of the component being the same name as one of the views could've caused this.

![image](https://user-images.githubusercontent.com/870934/34900085-41b6439a-f7e4-11e7-864f-d52199dab872.png)

**Comment by kevincam3** [comment]
Yes,

It seems that have the component name be the same as the view name is what caused it to break. After changing the names of the admin pages things are working.

**Comment by Llewellynvdm** [comment]
Since we use the component name for the dashboard model/controller/view it will conflict if you name a view exactly the same. What you can do to avoid this is to use underscores in the name, like so:
```
get_smartcard
get_smartcards
```
Then you will have the desired effect.
