### ISSUE TITLE
Associate Template with view

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#211]
I don't understand how to link templates to a view. Can you explain that. I looked at the video on templates and searched here in the issues but and even tried to figure it out by looking at the Sermon example but I still can't seem to figure it out. 

Thanks.

**Comment by kevincam3** [comment]
Ok,

I finally figured it out. Just by including the code to load the template is all that's needed to get the compiler to include the template file in the tmpl directory of the view.

**Comment by Llewellynvdm** [comment]
Yes, and it is the same with the layouts.
