### ISSUE TITLE
Is there a way to do a custom router?

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#213]
### System information (as much as possible)
- OS Name & Version:  Windows 10
- MySql Version:  5.7.14
- Apache Version: 2.4
- PHP Version:  5.6.32
- Joomla Version:  3.8.3
- JCB Version:  2.6.9
- Browser:  Chrome 63

**Comment by Llewellynvdm** [comment]
Not at this time.

Please do not open issues if there are already issues that address this, see [issue 74](https://github.com/vdm-io/Joomla-Component-Builder/issues/74)

I will need help with this, as am not able to yet follow the full logic of the router concept in Joomla so I think someone with more understanding should help. Things work at this time, but I can see this is an area that needs major improvement. That is why I opened the issue, and as you can see it was already last year April!!! and yet no one has responded to my request.

Please continue the discussion over at [issue 74](https://github.com/vdm-io/Joomla-Component-Builder/issues/74)
