### ISSUE TITLE
Template file not in compiled version

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#214]
### Steps to reproduce the issue
Included a sub-template within my template
After compiling the component I downloaded the zip
Installed it in my staging site but the default_usersmartcart.php file was not included in the zip

### Expected result
default_usersmartcart.php would be included in the zip file

### Actual result
default_usersmartcart.php was missing

### System information (as much as possible)
- OS Name & Version:  Windows 10
- MySql Version:  5.7.14
- Apache Version: 2.4
- PHP Version:  5.6.32
- Joomla Version:  3.8.3
- JCB Version: 2.6.9
- Browser: Chrome 63

**Comment by Llewellynvdm** [comment]
Please check your alias, example:

```
<?php echo $this->loadTemplate('programsfound'); ?>
```
Then the Template alias must be `programsfound`

Since the alias is what we use to identify the template.

**Comment by kevincam3** [comment]
Ok, got it. I'm using a dynamic variable to pick the template so I'll give it the name of the template. I guess I will have to track this outside of JCB unless you have an idea of how I can use a variable for the name in my code. Thanks.

**Comment by Llewellynvdm** [comment]
Hmm let me see... you can still have JCB get the template by adding the templates to the view in a comment:

```
<?php
	// loading the dynamic JCB templates
	// $this->loadTemplate('programsfound_none');
	// $this->loadTemplate('programsfound_out');
	// $this->loadTemplate('programsfound_in');
	// $this->loadTemplate('shopfront_user');
	// $this->loadTemplate('shopfront_public');
	// $this->loadTemplate('shopfront_admin');
?>
```
This may seem like a little painful but is the only way you can have both dynamic variable loading of templates and dynamic template linkages.
