### ISSUE TITLE
How do to add css code to site.css file that's generated on the frontend

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#216]
How do you add CSS to the site.css file. I see in the admin of the component a place to add CSS to the backend admin.css, but nothing about the site.css file

- JCB Version: 3.6.9

**Comment by Llewellynvdm** [comment]
In the site_view->Javascript & CSS->Add CSS->Yes (then you wil see a field to add the css)

**Comment by kevincam3** [comment]
When I add it there it adds it to smartcart.css, which is the name of the site view and not site.css any ideas?

**Comment by Llewellynvdm** [comment]
So you want to target a global site css file that gets loaded on every site view not just one?

**Comment by kevincam3** [comment]
Correct. My reason as I mentioned in another issue, the code that loads the CSS for the site view doesn't work in Joomla! 3.6.5 so I didn't want to hack JCB to make it work and since JCB creates a site.css file I figured I'd just use that for now. I guess if there's no way to add CSS from within JCB to the site.css file then we should get rid of it.

**Comment by Llewellynvdm** [comment]
I guess that is not your call :+1: I mean to remove stuff.

I will add a fix to the other issue regarding the CSS signature compatibility issue. So using the per/site_view css will work again soon for earlier versions of Joomla.

Adding global css to the site view was planned to become available in the same area as the back-end global css (in the Joomla component area), I have just not yet needed it.

I think it should be just a few lines in the compiler and it will be available.

No let me see why should I help my dear friend @kevincam3 .... hmmm
