### ISSUE TITLE
Import of JCB packages error.

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#219]
### Steps to reproduce the issue
Export JCB package from old version of JCB and import into v2.6.10

### Expected result
Import with no problem.

### Actual result
Has an error with add_css field

**Comment by ro-ot** [comment]
I can see the issue is easy to fix, should I push a fix or will you just update the prepItem method at case joomla_component with the following:
```
// update the add_css
if (isset($item->add_css))
{
	$item->add_css_admin = $item->add_css;
}
// remove from this dataset
unset($item->add_css);
// update the css
if (isset($item->css) && [[[Component]]]Helper::checkString($item->css))
{
	$item->css_admin = $item->css;
}
// remove from this dataset
unset($item->css);
```

**Comment by Llewellynvdm** [comment]
Thanks.... I missed that! will do a quick patch and push it out.
