### ISSUE TITLE
Only 'Root' Category Appearing

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#22]
Hi there,
This is a question - I have added a category field to one of my views called 'programs'. After adding categories, I then open the 'programs' view to add a new program, but nothing other than 'Root' appears in the category drop down.

Wondering what I am doing wrong?

I have set the 'extension' field to the both the single and plural of the component but its not appearing. I can see it in the database but when adding a new program it does not appear.	

> extension="com_###component###.program"

Thank-you!
Paola

**Comment by Llewellynvdm** [comment]
Hi Paola

Make sure you use the plural name (for the list of items also called views name)
```
<field 
	type="category" 
	name="catid" 
	label="Category" 
	extension="com_###component###.programs"
	default="" 
	description="select one of the following categories" 
	class="inputbox" 
/>
```

**Comment by paolavness** [comment]
Hmm. Haven't managed to get this going. Found a work around so not to worry.
