### ISSUE TITLE
Do I custom my own router rule or ,

### ISSUE THREAD

**Issue by kwaninmacau** [vdm-io/Joomla-Component-Builder#222]
### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by kwaninmacau** [comment]
Do I custom my own router rule or modify JCB router file? Any advice?
Thank you very much!

**Comment by ro-ot** [comment]
I also picked-up this issue, we need to add the [new router option](https://github.com/vdm-io/Joomla-Component-Builder/issues/74) like yesterday.
