### ISSUE TITLE
Connecting JCB's with each-other to sync development on agreed projects?

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#233]
### Steps to reproduce the issue
When we are many working on the same project, to setup a bridge between me and my fellow developers to sync our development on agreed project with various checks and balances.

### Expected result
Synced development environment. Like git just much more basic... and inside of JCB.

### Actual result
The feature does not exist automatically.

### Additional comments
I have developed a similar project to sync databases with each-other, so I have ready an authentication tool, and the basic outline to make this work.

# Who would be interested in this kind of feature?

**Comment by ro-ot** [comment]
I would like this, we can use it for JCB itself :+1: it will save us so much trouble if it is automated. The packages manager already does most of the work!

**Comment by Llewellynvdm** [comment]
I am thinking this is such a huge improvement to JCB and it requires so much work, that I am wondering if we should not make it a paid option.

I have spend so much time on this, it is really very powerful. I think we need to have a chat about this. I mean it only us who responded to this anyway. So why share it?

**Comment by Tony301** [comment]
Hi I know I am little late to the party, but hey I would really like this feature!

Tell me what kind of security is going to be used here?

**Comment by Llewellynvdm** [comment]
Okay at this time, I am moving this feature out of JCB into its own component. I will keep updating this issue. We are planning to make this available as an addon-component.

**Comment by Llewellynvdm** [comment]
@Tony301 I am working on using our own in-house CA system like a browser. So RSA keys will be used to encrypt the communication.

**Comment by Llewellynvdm** [comment]
I am closing this, feature request and placing it on the back burner, for latter.

**Comment by AlexEdimensionz** [comment]
I think that it's worth paying for this feature.  It's a Premium enhancement..

**Comment by ro-ot** [comment]
I agree this is a premium feature, hope it is not on the back-burner to long.
