### ISSUE TITLE
Auto save Name to System Name if blank.

### ISSUE THREAD

**Issue by Twincarb** [vdm-io/Joomla-Component-Builder#236]
### Steps to reproduce the issue
Fill in the required boxes apart from System Name

### Expected result
Error Message

### Actual result
Item can be saved although back at the main view there is no handy hyperlink

### System information (as much as possible)
- OS Name & Version:  Centos 7
- MySql Version:  10.1.31-MariaDB
- Apache Version: Apache 2.4.29
- PHP Version: 7.1
- Joomla Version: 3.8.5
- JCB Version: 2.6.16
- Browser: Chrome

**Comment by ro-ot** [comment]
Fill in the **system name**, ad if you didn't check the box next to the line and at the top click on edit and add the **system name**, and save again.

We can make that a required field, but best practice, just always add the system name.

**Comment by Twincarb** [comment]
I guess it's subjective if it should be a required field, my thoughts are because it's used as the link then it should be or if saved without default it to the "Name" field.

**Comment by ro-ot** [comment]
@Llewellynvdm that could be a nice tweak. A nice to have, I know the amount of work that has already happened here is staggering. I will make this a feature request. But no promises!
