### ISSUE TITLE
Custom Admin Menu not showing on dashboard

### ISSUE THREAD

**Issue by MiAlmeida** [vdm-io/Joomla-Component-Builder#240]
### Steps to reproduce the issue

Created a custom admin menu on a component to link to the Joomla users:
![image](https://user-images.githubusercontent.com/37026740/36938766-806af53e-1f1e-11e8-96bf-cb00ee7288cc.png)

### Expected result
Besides the submenu link (that works perfectly) there should be an icon on the component's dashboard.

### Actual result
Dashboard does not have the icon/link.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.19
- Apache Version: 2.4.27
- PHP Version: 7.1.19
- Joomla Version: 3.8.5
- JCB Version: 2.6.17
- Browser: Firefox 58

**Comment by Llewellynvdm** [comment]
@MiAlmeida please test the last pushed version to the staging branch. It should work now.
