### ISSUE TITLE
Error in helper class with count() - line 3460

### ISSUE THREAD

**Issue by bosyrih** [vdm-io/Joomla-Component-Builder#243]
### Steps to reproduce the issue
After installing Component-Builder on joomla localhost.

this problem because count() not accept null. 

### Actual result

Warning: count(): Parameter must be an array or an object that implements Countable in ~\administrator\components\com_componentbuilder\helpers\componentbuilder.php on line 3460

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.2 
- PHP Version: 7.2.2
- Joomla Version:  3.8.5
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
We have already fixed this in the staging branch, and so it will be fixed in the next release. You could fix it by updating the class method `checkObject` to:
```
/**
*	Check if have an object with a length
*
*	@input	object   The object to check
*
*	@returns bool true on success
**/
public static function checkObject($object)
{
	if (isset($object) && is_object($object))
	{
		return count((array)$object) > 0;
	}
	return false;
}
```
This should resolve the issue. This error only happens in PHP 7 +
