### ISSUE TITLE
PHP 7+ Warning

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#245]
### Steps to reproduce the issue
Load a component compiled with JCB in PHP 7+ with error reporting to either maximum or developer

### Expected result
Error and warning free output

### Actual result
Warning: count(): Parameter must be an array or an object that implements Countable in /home/avatarmwweb/public_html/components/com_****/helpers/****.php on line 746

### System information (as much as possible)
- OS Name & Version: Ubuntu 14.04
- MySql Version: 10.1.28-MariaDB-1~trusty
- Apache Version: Apache/2.4.29 (Ubuntu)
- PHP Version: PHP 7.1.11-1+ubuntu14.04.1+deb.sury.org+1
- Joomla Version: 3.8.6
- JCB Version: 2.6.16
- Browser: Firefox 58.0.2

### Additional comments
The code in question that is throwing the warning is:

`	public static function checkObject($object)
	{
		if (isset($object) && is_object($object) && count($object) > 0)
		{
			return true;
		}
		return false;
	}
`

**Comment by Llewellynvdm** [comment]
Please check [issue 243](https://github.com/vdm-io/Joomla-Component-Builder/issues/243) as this will be resolved in the next release.

Thanks for the heads-up!

**Comment by Llewellynvdm** [comment]
Can you help with testing [this pull ](https://github.com/vdm-io/Joomla-Component-Builder/pull/244)request? This is a major release that will improve JCB greatly, we also added the good old string manipulation back for building fields if tidy is not available on the server.
