### ISSUE TITLE
Support for joomla custom fields

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#247]
### Feature request
Add support for joomla custom fields, for jcb components as documented
https://docs.joomla.org/J3.x:Adding_custom_fields/Implement_into_your_component

**Comment by Llewellynvdm** [comment]
@marcodings This is a great idea, and I think we can most certainly do this. 

Would you be so kind to take the JCB demo component (just compile it) and then hand code this feature into it. That way you will save me the time of doing that, and I can really just focus on adding it to the compiler in the right places.

Thanks!

**Comment by ro-ot** [comment]
Looking forward :tada: to this, can be very useful :+1:

**Comment by marcodings** [comment]
I'll attend to it asap ;) But don;t hold you breath as i have a number of sessions to prepare for multiple upcomming joomla conferences

**Comment by ro-ot** [comment]
JCB and all its projects are leaving gitHub... this is going to take some time since JCB/VDM is so integrated with github,

The new address is [https://gitlab.com/jcb-repos/Joomla-Component-Builder](https://gitlab.com/jcb-repos/Joomla-Component-Builder).

**Comment by Llewellynvdm** [comment]
I found the easy way to get the fields to display on the front-end is via the events being triggered. So I also added not event options to dynamic gets that are **getItem** type. This can server a beginning of this new feature. Please test and let me know.
