### ISSUE TITLE
Missing tabs in edit admin view And missing defualt type field value

### ISSUE THREAD

**Issue by bosyrih** [vdm-io/Joomla-Component-Builder#249]
### Steps to reproduce the issue
n/a
### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.2
- PHP Version: 7.2.2
- Joomla Version: 3.8.5
- JCB Version: 
- Browser: 

### Additional comments

when you enter to admin view and then to New there is tow things to notice 
1- type field dosn't take the defualt value Read/Write.
2- all tabs are disappeared .

i tried to install a fresh version of component-buider but it still the same problem

thanks for the great work.
![untitled](https://user-images.githubusercontent.com/20782472/37687294-b319fe3e-2ca3-11e8-9e71-925ad2c7b2e1.png)

**Comment by Llewellynvdm** [comment]
To fix this, until the patch it out, open the _/public_html/administrator/components/com_componentbuilder/views/admin_view/tmpl/edit.php_ file and on line 707 update the code from
```
<?php $numberAddtables = range(0, count($this->item->addtables) + 3, 1);?>
```
TO
```
<?php $numberAddtables = range(0, count((array) $this->item->addtables) + 3, 1);?>
```
I will push an urgent update out to fix this. Thanks!
