### ISSUE TITLE
Compiler - Post Installation Broken

### ISSUE THREAD

**Issue by paolavness** [vdm-io/Joomla-Component-Builder#25]
Hi there,
Something weird. The compiler is compiling the component but won't install it. I've tried installing several different components by first compiling, then hitting the installation button. All break with the same message. Interestingly however, the component will install on another installation of joomla...

This is the second time it happened. Last time I rebuilt the component on a fresh installation to get around it... But as the component gets bigger, i can't keep doing this.

Below is the stack trace and error thrown:

> Error
> exception 'UnexpectedValueException' with message 'JTableMenu::_getNode(1, ) failed.' in /home/onemonke/public_html/crow/libraries/joomla/table/nested.php:1532 Stack trace: #0 /home/onemonke/public_html/crow/libraries/joomla/table/nested.php(773): JTableNested->_getNode(1) #1 /home/onemonke/public_html/crow/libraries/legacy/table/menu.php(243): JTableNested->store(false) #2 /home/onemonke/public_html/crow/libraries/cms/installer/adapter/component.php(1287): JTableMenu->store() #3 /home/onemonke/public_html/crow/libraries/cms/installer/adapter/component.php(979): JInstallerAdapterComponent->_createAdminMenuItem(Array, 1) #4 /home/onemonke/public_html/crow/libraries/cms/installer/adapter/component.php(307): JInstallerAdapterComponent->_buildAdminMenus(10147) #5 /home/onemonke/public_html/crow/libraries/cms/installer/adapter.php(756): JInstallerAdapterComponent->finaliseInstall() #6 /home/onemonke/public_html/crow/libraries/cms/installer/installer.php(469): JInstallerAdapter->install() #7 /home/onemonke/public_html/crow/administrator/components/com_componentbuilder/models/compiler.php(180): JInstaller->install('/home/onemonke/...') #8 /home/onemonke/public_html/crow/administrator/components/com_componentbuilder/controllers/compiler.php(198): ComponentbuilderModelCompiler->install('com_gaiaeducati...') #9 /home/onemonke/public_html/crow/libraries/legacy/controller/legacy.php(728): ComponentbuilderControllerCompiler->installExtention() #10 /home/onemonke/public_html/crow/administrator/components/com_componentbuilder/componentbuilder.php(57): JControllerLegacy->execute('installExtentio...') #11 /home/onemonke/public_html/crow/libraries/cms/component/helper.php(405): require_once('/home/onemonke/...') #12 /home/onemonke/public_html/crow/libraries/cms/component/helper.php(380): JComponentHelper::executeComponent('/home/onemonke/...') #13 /home/onemonke/public_html/crow/libraries/cms/application/administrator.php(98): JComponentHelper::renderComponent('com_componentbu...') #14 /home/onemonke/public_html/crow/libraries/cms/application/administrator.php(152): JApplicationAdministrator->dispatch() #15 /home/onemonke/public_html/crow/libraries/cms/application/cms.php(257): JApplicationAdministrator->doExecute() #16 /home/onemonke/public_html/crow/administrator/index.php(51): JApplicationCms->execute() #17 {main}
> Warning
> Error building Administrator Menus.

Warmly,
Paola

**Comment by paolavness** [comment]
Oh... I also cleared the system caches, logged out and in, etc. but no go.

**Comment by Llewellynvdm** [comment]
I will have to see this... so can we Skype?

**Comment by Llewellynvdm** [comment]
I am around for the next few hours... lets say two hours... let me know.

**Comment by Llewellynvdm** [comment]
Okay this seems to be a problem with the Joomla installation you are working on, not sure why... but the install file works on my test website... without any errors.

Please keep me posted.

**Comment by paolavness** [comment]
thanks for the conversation and help last night. its working well on the new install, other than a crucial piece - changes to the component are not saving - throwing a weird sql error. even when trying to create a new component, same error.

> Error
> Save failed with the following error: SQL: 00000, ,

Interestingly, i can create new admin views and save admin views fine.

The component is compiling and installing on the local build and other builds, but with these too, any attempt to save new programs, participants, anything, throws the same sql error.

Wondering if it could be something to do with the assets table. Recall i copied over the CB tables only, not the assets tables.

warmly,
Paola

**Comment by Llewellynvdm** [comment]
IF that is the case... a reinstall (simply an update, with un-install) should fix that.... hmmm this is getting very tricky. I really can't help you unless I can access the database... and the files to see if there is an issue (at your own risk). 

So let me know if a reinstall (simply an update) of component builder does not fix this, since it should fix any missing database values that could cause an error. This will also count for any other component that uses the history option that integrates with Joomla's version/history component.

**Comment by paolavness** [comment]
Mmm that didn't work. I'll drop you server details in Skype.
Warmly,
Paola
