### ISSUE TITLE
Replace in code throwing a database error

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#253]
### Steps to reproduce the issue
I was trying out the custom code option
I tried to replace the cPanel text in the main view
I edited default.php and put

```
<?php 
	/***[REPLACED<>$$$$]***///
	echo JHtml::_('bootstrap.addSlide', 'dashboard_left', 'w4c', 'main'); 
	/***[/REPLACED<>$$$$]***/
?>
```

instead of the autogenerated

`<?php echo JHtml::_('bootstrap.addSlide', 'dashboard_left', 'cPanel', 'main'); ?>`

### Expected result
I expected it to compile and the text to be changed and therefore allow me to easily change it

### Actual result
compiler throws:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5

If I take the change out it works fine.

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.0.28
Joomla Version: 3.8.5
JCB Version: 2.6.17
Browser: Chrome

### Additional comments
I have tried the insert function which seemed to work fine.  Perhaps I'm not using Replace correctly?

**Comment by ro-ot** [comment]
One liner replacement does not work that well, try replacing three lines like this, but use the HTML option:
```
<--[REPLACE<>$$$$]-->
<?php echo JHtml::_('bootstrap.addSlide', 'dashboard_left', 'w4c', 'main'); ?>
<--[/REPLACE<>$$$$]-->
```
O yes and when you add it for the first time, you must use `REPLACE` the system when it adds it back will use `REPLACED`. For the system to do this you must have `Add Custom Code Placeholders` set to yes in the compiler.
![image](https://user-images.githubusercontent.com/2594383/37865681-b6b3bb74-2f88-11e8-9366-99677d85545b.png)

The sql error is not related to this, you should know that the sql is build based on your own field settings. So if it does not work you must do some homework, to insure your selections made in the field is correct.
![image](https://user-images.githubusercontent.com/2594383/37865751-c98e512c-2f89-11e8-94d9-40c5e369551c.png)

**Comment by ro-ot** [comment]
The sql can only be an issue when you use **one line**, since then you are actually escaping the code and this will break things.

Take a look at this page https://github.com/vdm-io/Joomla-Component-Builder/wiki/TIPS:-Custom-Code for more help with custom code.

**Comment by ro-ot** [comment]
Okay I just edit you comment and found you did not use one line, but from what I have found best use the HTML option outside the php tags since the line break that you have 
```
<?php 
	/***[REPLACED<>$$$$]***///
```
Will be ignored as JCB only looks at what is between the placeholders, and I think if you use `REPLACE` it will be picked up and work.

**Comment by Llewellynvdm** [comment]
Hi @alan123489 trust your issue was resolved.
