### ISSUE TITLE
Feature Suggestion - Rule validation (for fields)

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#254]
### Suggestion
A new view to build rules and an easy way to add them to fields.

### Additional comments
I know that you can do this with some custom file, that you add in and then use in the field as a `validate="newrule"` but having a easy way to do this inside JCB seems like a great idea.

One of the options is to get the code from the `/public_html/libraries/src/Form/Rule` as a starting point. So that a selection can be made, of any of the existing rules which then loads the code for that rule and then you can adapt it to your desire.

**Comment by Llewellynvdm** [comment]
Okay I have added this feature, please test and give feedback.

You will see the fields area has a new list of validation rules, and there is a new validation rules view.

**Comment by ro-ot** [comment]
I like what you did to the layout and linking of this feature into the fields area. From my test it works very well, thank you!
