### ISSUE TITLE
Datetime format not working

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#256]
### Steps to reproduce the issue

I've set up a date time field with the following XML
```xml
<field type="calendar"
  name="magazine_pub_date"
  label="COM_WEBSITEMANAGER_MAGAZINE_MAGAZINE_PUB_DATE_LABEL"
  default="CURRENT_TIMESTAMP"
  format="%d-%m-%Y %H:%M:%S" />
```

When I save with this format (UK time format) then it doesn't save.  It just leaves the box empty.

When I use this XML

```xml
<field type="calendar"
  name="magazine_pub_date"
  label="COM_WEBSITEMANAGER_MAGAZINE_MAGAZINE_PUB_DATE_LABEL"
  default="CURRENT_TIMESTAMP"
  format="%Y-%m-%d %H:%M:%S" />
```

It works fine and saves.

### Expected result
Date saved to database

### Actual result
using xml with day month year fails to save

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.0.28
Joomla Version: 3.8.5
JCB Version: 2.6.17
Browser: Chrome

**Comment by Llewellynvdm** [comment]
Check you db settings (of the field) that they are correct.
