### ISSUE TITLE
CSV import format issues

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#257]
### Steps to reproduce the issue
Not sure if this is really an issue or more the need to clarify to people.
When I save data to import in excel as csv it imports the data but when I try the drop down box the screen goes black!

It seems to come down to which version of CSV you use.

If I use CSV(Comma delimited)(*.csv) it throws the error
If I use CSV(MS-DOS)(*.csv) it seems to work

the other formats seem to work too.

### Expected result
It'll upload the data

### Actual result
black screen

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.0.28
Joomla Version: 3.8.5
JCB Version: 2.6.17
Browser: CHrome

### Additional comments

I think this could be resolved just by clearly specifying the problem with excel csv formats

**Comment by Llewellynvdm** [comment]
Hmmm did not know you get different csv formats. Will have to look into it, should work with any format. Since we are using [PHPExcel](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/custom/PHPExcel.php).
