### ISSUE TITLE
Site View Pagination Switch

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#259]
### Steps to reproduce the issue
Currently, JCB automatically creates the pagination script/code to display the pagination on each of the site views. Although good to have, it limits the ability of developers to create custom pagination.

Example...some of my views are loading all the records on some of the views with ajax/javascript filtering. Basically, on initial open it loads all records, then each filter performs a javascript filter on the loaded records, bypassing the need of having a page reload every time a filter is utilized.

However, with the default Joomla pagination, that doesn't work, since if you go to page 2, then the ajax/js is no long in use. What was needed was my implementing a javascript pagination, which works, except that the default Joomla pagination that JCB adds only loads the number of records saved in limit_list in the Joomla config.

### Expected result
The ability to choose between adding or not adding pagination on a per site view basis.

Add a switch on site views in the Joomla Component in JCB to Add Pagination? Yes/No.

If yes, then it adds the pagination as it currently does.
If no, then the pagination code is left out of the compiled component, allowing for custom code to easily be added.

### Actual result
Currently, core pagination is added to all site views.

### System information (as much as possible)
- OS Name & Version: Ubuntu 14.04
- MySql Version: 10.1.28-MariaDB-1~trusty
- Apache Version: Apache/2.4.29 (Ubuntu)
- PHP Version: PHP 7.1.11-1+ubuntu14.04.1+deb.sury.org+1
- Joomla Version: 3.8.6
- JCB Version: 2.7.0
- Browser: Firefox 58.0.2

**Comment by Llewellynvdm** [comment]
The dynamic get has the option to load or not load the pagination, is that not enough?

If you are using the same dynamic get, then just copy it so there is two of the same dynamic get... then make the one to use pagination and the other not to use pagination.

So pagination is set per dynamic get if getType is `getListQuery`
> With pagination

![image](https://user-images.githubusercontent.com/5607939/38480283-a5d09b5c-3bbc-11e8-9eb7-04c9358a1b07.png)

> Without pagination

![image](https://user-images.githubusercontent.com/5607939/38480313-d93d831a-3bbc-11e8-8c24-63b27e565bcb.png)

**Comment by mwweb** [comment]
I was completely missing it there. And now, seeing it again, I do recall it. I haven't had to go into gets in a while now.
