### ISSUE TITLE
JCB package import not working!

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#263]
### Steps to reproduce the issue
Export a JCB package that uses a key, and then try to import it.

### Expected result
That the JCB package imports work as before.

### Actual result
None of the packages I export are able to import on v2.7.2 or the last v2.7.3

### Additional comments
@Llewellynvdm the last few updates were not done via the correct channels and now I see issues jump up everywhere, would be better if we moved a little slower and have stable releases instead. I will do my best to review the pull request as quick as I can, and ask other to also do the same.

**Comment by Llewellynvdm** [comment]
You are right I was going to fast, my apologies!
