### ISSUE TITLE
Language Translation bug in ver2.7.4

### ISSUE THREAD

**Issue by bosyrih** [vdm-io/Joomla-Component-Builder#264]
### Steps to reproduce the issue
after upgrade to ver 2.7.4, if you enter to Editing the Language Translation to edit string the language
can not display in translated string .

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
Just keep getting better...

**Comment by Llewellynvdm** [comment]
This is also due to that error we fixed in the fields area, basically the php got stripped.

**Comment by bosyrih** [comment]
we can enhanced list custom by adding a choise in adminview-fields a field for is this field list if it checked then the field created.

**Comment by Llewellynvdm** [comment]
It is already like that, it did work it is just that the update broke many things and I made the mistake of pushing the release without allowing enough time to test. I am bit under pressure to get many things done. But enough of that... the fixes for this is already done. I will push it out ASAP!

**Comment by bosyrih** [comment]
if i can help with some test, let me know.

**Comment by Llewellynvdm** [comment]
I sure will, thanks!

**Comment by bosyrih** [comment]
test ok for translate
