### ISSUE TITLE
Subform not saving

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#266]
### Steps to reproduce the issue

Create a subform and place it in the admin view underneath all tabs at position "underneath tabs".

### Expected result

You will expect the subform to save multiple entries.

### Actual result

The form wil save at most 1 entry

**Comment by ro-ot** [comment]
Check the database setup that you have it set to text instead of varchar.

**Comment by ro-ot** [comment]
Let us know if you have any more questions.

**Comment by AlexDings** [comment]
This was not the issue.
After doing nothing but moving the subform inside the tabs it worked exactly as expected.

**Comment by ro-ot** [comment]
Thanks for getting back to us. I will ask @Llewellynvdm to take a look at this.
