### ISSUE TITLE
Default chosen over an empty value in sql field

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#267]
### Steps to reproduce the issue

Create a sql field and add an empty row to it so the user can chose not to fill the field.
```
SELECT null as id, null as otherfield
UNION ALL
SELECT id, otherfield FROM #__somesite_sometable
```
Then give the sql field a default value

### Expected result

You expect the sql field to save null or "" to the database when the user doesn't select a value from the dropdown and removes the default selection.

### Actual result

The default overwrites the empty value selected

### System information (as much as possible)
- OS Name & Version: Windows 10

**Comment by ro-ot** [comment]
Check your database settings in the field area, under the Data Base Tab.

**Comment by ro-ot** [comment]
Let us know if you have any more questions.

**Comment by AlexDings** [comment]
What should I check there? That doesn't seem to have anything to do with the issue?
It seems that the field gets checked for being empty on save and that the default is used if it is.
This prevents you from ever having an empty field.

**Comment by ro-ot** [comment]
Ok my bad.

So you are adding a SQL field type, and then want to add a empty option. I know the SQL field type is very limited. This is not due to JCB by Joomla itself, better to use the custom field type for more freedom.
