### ISSUE TITLE
HTTP ERROR 500 when opening compiler view

### ISSUE THREAD

**Issue by eimmegee** [vdm-io/Joomla-Component-Builder#27]
I'm pretty new to development for Joomla and the use of Component Builder, and I don't know if this is the place to ask this question, but I have the following problem:
I installed the recent version of Component Builder (V2.1.12) on a Joomla installation (v 3.6.4). I can access all views of the Component Builder, except for the Compiler view (/administrator/index.php?option=com_componentbuilder&view=compiler): this page always results in an HTTP 500 ERROR.
I know this is not a lot of info on this issue, but any idea what could be the cause of this?

**Comment by Llewellynvdm** [comment]
Hmmm, please try the release found here https://github.com/vdm-io/Joomla-Component-Builder/releases

Uninstall the component completely and install the latest release, and let me know if the error continue.

**Comment by eimmegee** [comment]
I installed the version JCB_v2.2.3.zip, but unfortunately the error continues.
Is there action I could undertake to verify what could be the root cause of this, such as verifying certain configuration settings or log files?

**Comment by Llewellynvdm** [comment]
Sorry to hear that, well of course you can check the logs. That will depend on your setup really. If you running a off-line development server, then you would need to setup a PHP error path in the php.ini file and have error reporting turned on... you can google if you don't know how that is done. If you are on a cPanel account or some other hosting infrastructure you best ask this question to your system administrator.

Then Joomla has its own error logs, but this mainly is in relation to its own API's error implementation and debugging. Yet a 500 error is usually a server error. Like a there is a function being called that is not installed or a file permission issue or something like that. Just for the record Joomla's error logs is in the log folder.

I don't think Component Builder is the reason for this error, it must be a that something on the servers is not configured correctly. I mean you can check the code of the compiler right here on github. Here is the [model](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/compiler.php) and here is the [view](https://github.com/vdm-io/Joomla-Component-Builder/tree/master/admin/views/compiler). Then the [controller is over here](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/controllers/compiler.php), but that only gets called after you click something on the page and submit the form. As you will see that is noting strange or even complex in these initial files on the compiler. Yes once you start a compilation we get into the maze... and there its gets mad and extremely complex. But none of that code runes when you open the page.

So for now I would say check your file permissions, all files must be 644 and all folder must be 755. Here is a [forum post to help](http://stackoverflow.com/a/11512211/1429677).

If that is sorted, take a look at your apache logs, here is a [form post to help](http://unix.stackexchange.com/a/39008/130056) on that.

Let me know what you find... hope you succeed.

**Comment by Llewellynvdm** [comment]
If you need more help on this, please let me know...
