### ISSUE TITLE
Not all SQL Update Versions being run

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#271]
### Steps to reproduce the issue
Create component with several updates (i.e. added various different fields during development). This results in several entries on the SQL Update Versions page.

### Expected result

When doing a 'clean' install of the component, all of the SQL Updates should be run.

### Actual result

2 of the 18 update queries (which are all ALTER commands) do not get run against one table.

### System information (as much as possible)
- OS Name & Version: WAMP
- MySql Version: 5.7.19
- Apache Version:  2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.6
- JCB Version:  2.7.6 Beta/Staging
- Browser: Chrome

### Additional comments

Not sure if this is due to some code that is still in progress on the staging branch but wanted to report it.
Also, the fields that had the issue are all ones that were set to 'Default' in the admin view field list. Fields that were set to display in list didn't have a problem.

I've uninstalled the component and made sure tables were all gone, then re-compiled and installed and keeps happening the same.

I can manually run the ALTER SQL against the db and it works.

The elements are added to the views and 'function' - but data isn't stored. Almost acting like this is a 'display only' field.

I'm not sure if anyone else is seeing this as I can only reproduce this with this one component.
(Is there a way that I could have set those updates to not happen?)

**Comment by Llewellynvdm** [comment]
Hmm this is not correct, the updates only run when you update already installed component. Hence the name updates.

IF you do a **clean** install the normal install SQL will run and that file should have all the correct and latest data for the database setup.

**Comment by Llewellynvdm** [comment]
It could be that I am not understanding the issue... so just in case. Check that you have those fields linked to the admin view as either **Default** or **Show in List View** if you set it to be **None DB** then it will not be added to the sql, as the None DB removes that field from the database completely.

**Comment by cpaschen** [comment]
Sorry ... finally tracked it down and cleaned up a mess from the Admin view MySQL Add MySQL tab. Somehow I missed that the table was not deleted. After setting the Add MySQL to NO, Do a complete uninstal. Making SURE that the tables were all wiped and a fresh compile and reinstall it all worked properly.
Please close this.
