### ISSUE TITLE
Bug with custom alias builder

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#272]
### Steps to reproduce the issue

- Create a text field (that is NOT named 'name')
- Create a new admin view
- Add the text field to the view & set to title, display in list, etc.
- Add an Alias field to the view & set to Alias
- save the form
- set Alias Type Builder to CUSTOM
- select the created text field in the Alias Builder area
- Save, close, compile

### Expected result

Alias should build using the selected field

### Actual result

Uses the default date-based alias

### System information (as much as possible)
- OS Name & Version: WAMP
- MySql Version: 5.7.19
- Apache Version: 2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.6
- JCB Version: 2.7.6 beta release (updated on 2018-04-26)
- Browser: Chrome

### Additional comments

The code generated in the model is this:

```
		// Automatic handling of alias for empty fields
		if (in_array($input->get('task'), array('apply', 'save', 'save2new')) && (int) $input->get('id') == 0)
		{
			if ($data['alias'] == null || empty($data['alias']))
			{
				if (JFactory::getConfig()->get('unicodeslugs') == 1)
				{
					$data['alias'] = JFilterOutput::stringURLUnicodeSlug($data['category_name']);
				}
				else
				{
					$data['alias'] = JFilterOutput::stringURLSafe($data['category_name']);
				}

				$table = JTable::getInstance('sp_category', 'kr_books_systemTable');

				if ($table->load(array('alias' => $data['alias'])) && ($table->id != $data['id'] || $data['id'] == 0))
				{
					$msg = JText::_('COM_KR_BOOKS_SYSTEM_SP_CATEGORY_SAVE_WARNING');
				}

				$data['alias'] = $this->_generateNewTitle($data['alias']);

				if (isset($msg))
				{
					JFactory::getApplication()->enqueueMessage($msg, 'warning');
				}
			}
		}
```
Here's the XML for the category_name field:

```
              <!-- Category_name Field. Type: Text. (joomla)-->
                <field type="text"
                       name="category_name"
                       label="COM_KR_BOOKS_SYSTEM_SP_CATEGORY_CATEGORY_NAME_LABEL"
                       size="10"
                       maxlength="50"
                       description="JFIELD_TITLE_DESC"
                       class="text_area"
                       readonly="false"
                       disabled="false"
                       required="true"
                       filter="STRING"
                       message="COM_KR_BOOKS_SYSTEM_SP_CATEGORY_CATEGORY_NAME_MESSAGE"
                       autocomplete="off" />
```
It works fine with a different admin view set-up exactly the same (as far as I can tell). [And I've compared the controller code and it is almost identical - except for the field name, etc.]

I've also tested using the  DEFAULT Alias Builder Type with the same results.

I've confirmed that the table referenced has the category_name field and it has data in it.

Not really sure that this is a bug or just a configuration error (because it works in one instance but not the other).

Any ideas where else I should check to try to debug this?

**Comment by Llewellynvdm** [comment]
This is like very hard to debug... I am trying to follow what you've done. For the most part I think I understand, but then to know where the issue is... well that is another story. What is more strange, is from the code above, things look correct.

I mean it says:
```
$data['alias'] = JFilterOutput::stringURLUnicodeSlug($data['category_name']);
```
or
```
$data['alias'] = JFilterOutput::stringURLSafe($data['category_name']);
```
Based on your system configuration.

From what I understand you want the alias to be build from the `category_name` field right? Well it is doing that.

Can you do some var_dump search at moments on the code, and tell us what you see?

Like  just after:
```
if (JFactory::getConfig()->get('unicodeslugs') == 1)
{
	$data['alias'] = JFilterOutput::stringURLUnicodeSlug($data['category_name']);
}
else
{
	$data['alias'] = JFilterOutput::stringURLSafe($data['category_name']);
}
```
add a `var_dump($data['alias'])` and lets see what value we have, then also after:
```
$data['alias'] = $this->_generateNewTitle($data['alias']);
```
So we can see where the value gets broken. Let me know what you found.

**Comment by cpaschen** [comment]
I've tracked down the problem to this line:

`if (in_array($input->get('task'), array('apply', 'save', 'save2new')) && (int) $input->get('id') == 0)`

The data is:
- task: 'apply'
- id: 9

But that 2nd half of the if appears to be filtering out and only applying to an item that has an ID of 0.
That 'seems' to me to disable this entire block of code for any existing entry when we edit the item and change the title and wipe the alias field (which is sometimes desired).

If I create a new entry then it works fine, but trying to re-set the alias on any existing entry fails.

If I change that line to:

`if (in_array($input->get('task'), array('apply', 'save', 'save2new')))`

It all appears to work fine.

I'm pretty sure that this was working previously (allowing me to 'reset' the alias on an existing entry).

**Comment by Llewellynvdm** [comment]
That is not really the issue. Since that behaviour is correct as it should only dealt with new items. So I looked a little more.

I think I found the issue... I missed a place that generates the alias based on the name field. and of course if it does not find the name field it uses the date.

I will add a fix to this, one moment.

**Comment by Llewellynvdm** [comment]
Okay I fixed, please test and let me know :+1:

**Comment by cpaschen** [comment]
Works PERFECTLY! Thanks!!!!
