### ISSUE TITLE
Filter custom multi-select fields

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#273]
This is a feature request to add the ability to filter on a Custom field that has multiple select set to true.

**Comment by Llewellynvdm** [comment]
This will remain in the list of feature requests... but we close the issue for now.

**Comment by Llewellynvdm** [comment]
We are adding the option to select multiple items with the new filter implementation. This is not exactly what you asked for, but in reflection, if you have a field that has json, we cannot via mysql filter that field without special addons for mysql. This means it is not a good idea.

But being able to select multiple items in the filter and then show both items values in the list... this we are working on.

**Comment by cpaschen** [comment]
OK ... I'll watch for this and try to help test when ready.

**Comment by Llewellynvdm** [comment]
Okay the new feature is out... and I will push the tutorial out to explain how it works soon.

**Comment by Llewellynvdm** [comment]
The new filter option above the list items in an admin view is out :+1:
