### ISSUE TITLE
CSS inclusion in list view not working?

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#278]
### Steps to reproduce the issue
Insert CSS on list view from the admin view

### Expected result
CSS to be included

### Actual result
CSS isn't included - I have to use custom code to get it included

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.0.28
Joomla Version: 3.8.5
JCB Version: 2.6.17
Browser: CHrome

### Additional comments
Javascript works fine using the list view just the css isn't included.  

Perhaps it's included in a way I don't know but I couldn't find it using element inspector.  If it include it manually with either the custom code or directly in the code there is not problem

**Comment by Llewellynvdm** [comment]
Thanks Alan, this is an area that is not fully finished... so I will finish it ASAP.

**Comment by alan123489** [comment]
thanks - I love that you can just include the Javascript from the view.

**Comment by Llewellynvdm** [comment]
Hi @alan123489 The fix that you can use until the next update would be to [open f_infusion.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php#L481) file in the compiler and from [line 480 to 482](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php#L481) change it to look like this:
```
// ###VIEWSCSS### <<<DYNAMIC>>>
$this->fileContentDynamic[$viewName_list]['###VIEWSCSS###'] = $this->getCustomScriptBuilder('css_views', $viewName_single, '', null, true);
```
This will fix the issue, basically change `$viewName_list` to `$viewName_single`
