### ISSUE TITLE
Question or suggestion... multiple cpanel

### ISSUE THREAD

**Issue by lamatieregrise** [vdm-io/Joomla-Component-Builder#279]
### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 5.5.5-10.1.32-MariaDB
- Apache Version: 
- PHP Version: 7.0.30
- Joomla Version: 3.8.7
- JCB Version: 
- Browser: chrome / safari 

### Additional comments

Hi, first I need to let me say that I'm thinking this component is amazing and bring possibilities to a whole other level. JCB his quite complex so I'm not sure if I've missed a feature I'm searching, I ve listen to most of the videos but didn't see it either, but I think that could be interesting and probably would bonify the end user experience. I like the control panel with the icons, but was wondering if there is a way to a replicate the concept onto a custom admin view to create like a subsection cpanels.

has examples:  

On the main cpanel icon (accounting) --link to -> sub cpanel with a whole other set of icons (accounting related) not showing on the main panel.   --Link to -> other subsection or list views, etc.

Sorry my English ain't very good so not sure if my explanation was clear.

Francois

**Comment by Llewellynvdm** [comment]
Okay the closest we come to this is with what I have called dynamic dashboard in the Joomla Component Area.
![image](https://user-images.githubusercontent.com/5607939/39704278-b5fca5b4-5202-11e8-8bae-3016cc00d010.png)

There you can select any custom admin view in which you can build any kind of dashboard you like... you can go full house :)

So all you do is select `dynamic` and a list of all admin and custom admin views will show-up on the right. The one you select will become the new dashboard.

![image](https://user-images.githubusercontent.com/5607939/39704392-135a6a3e-5203-11e8-8f04-fdd5474c019b.png)

Let me know if this is what you are looking for, or if I missed the question.... do know that the default dashboard is as far as I am willing to go at this time, anything more you have to build in a custom admin view. The custom admin view has all the power of a site view... it is just in the back-end. So it can also use templates, layouts and dynamic gets... enjoy!

**Comment by lamatieregrise** [comment]
Thanks i meant more like the main panel not the view or list. i did search for the default the code has the main template but where its located

![cpanel](https://user-images.githubusercontent.com/32321039/39704835-a4beff4a-51da-11e8-91aa-4b43d909ef56.jpeg)

**Comment by Llewellynvdm** [comment]
You can build that in a **custom admin view** 
![image](https://user-images.githubusercontent.com/5607939/39705060-2ecec8e4-5205-11e8-8040-aada03fcd191.png)

Then you can link that custom admin view to your component and use it as your dashboard... watch [this tutorial](https://www.youtube.com/watch?v=tU7TeYn1Djo&index=60&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE).

**Comment by Llewellynvdm** [comment]
Remember the custom admin views that I used in the tutorial has the sub menu show because I added it in the custom admin view. Usually it does not show, it is really a blank sheet that you can add anything to as a back-end view.  You can even call it Dashboard and add it to your component as the first option in the sub menu. The sky is the limit here... true freedom :+1:

**Comment by Llewellynvdm** [comment]
Let me know if you have further question on this issue.

**Comment by lamatieregrise** [comment]
Thanks for your information (and also to your video tutorials:-),I admit,I was a bit lost at the beginning, but now with the map component it's way easier to understand , can't wait to relisten to a few of the tutorials now with sermon distributors on hand. Still not at the point to be able to properly participate in git, but you can be sure that has soon had I get more comfortable with the code I'll try to join in and give it a try to help out. 
Francois
