### ISSUE TITLE
Custom PHP in View

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#28]
Maybe I'm missing something, but I'm going to ask anyway.

I have the code for some custom PHP to use a drag/drop image uploader. This PHP code will render on a single view (property), in a particular tab (media). The script is already coded to only display if the item has an item ID, which will only happen after save.

I can hard code the PHP in the tmpl/edit.php file in the location that I want, but I would prefer this be in Component Builder so it gets compiled.

Where/how would I do this in Component Builder?

**Comment by Llewellynvdm** [comment]
Hi, Have a look at this [short tutorial](https://youtu.be/hYrvLXwhwjU)... hope it helps
