### ISSUE TITLE
Feature Suggestion - Add Admin View icons to alternate dashboard tabs

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#282]
It would be very helpful if we could have the ability to add an Admin View assigned to unique tabs on the dashboard (rather than all icons being added to just the main cpanel dashboard tab) via configuration, rather than needing manually code .

It would be ideal if there was a field in the Joomla Components | Admin Views | Linked Admin Views list that could be set, similar to the Admin Vide | Fields and Conditions | Linked Fields | "Tab" field.

Then have JCB automatically build the code for the dashboard tab and including the buttons on those tabs.

**Comment by Llewellynvdm** [comment]
As I mentioned on the google forum this seems to me like to much of a locked in feature.

What I mean by that, is the current Dashboard already is a locked in feature, where everyone who use it looks the same as everyone else... and this sort of is not ideal. So we expanded the dashboard area to be able to use any **custom admin view** or **admin view** of your choice to _foster the diversity_ that will make your components stand out from among the rest.

But having said all that, I can see the diversity this could also offer to sort of make the current locked in dashboard break out of its boundaries. This means I would add this feature requests... and see when it becomes a high priority. Ideal would be if you contribute the changes :+1:

**Comment by Llewellynvdm** [comment]
Hey listen we will close the issue, but we will not drop the request, you can see the [project where all these request are being stored](https://github.com/vdm-io/Joomla-Component-Builder/projects/5), and evaluated as we proceed. So it will be up to you to go there and start talking about it again. If any issue is closed it does not mean its over, it just means we are not looking at it in our feed any more. 

So on any issue, unless it is locked, you are welcome to pick up the thread again, and if it is time to give close attention to it, we will open the issue again, so it shows up in the feed again.

**Comment by Llewellynvdm** [comment]
So when soon as you have more time, and are willing to contribute to this issue just let me know and we will open this up again.
