### ISSUE TITLE
FEATURE SUGGESTION - add email field type

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#283]
The install package for JCB (as of 2.7.9) does not include the Email for field type (https://docs.joomla.org/Special:MyLanguage/Email_form_field_type)

Although this can be added manually, it would be good to have all the standard Joomla types included with the install.

**Comment by Llewellynvdm** [comment]
ahaaa it is because it use to be a text field:
```xml
<field
	type="text"
	name="email"
	label="Email"
	size="40"
	maxlength="150"
	description="Add your email here"
	class="text_area"
	required="true"
	filter="STRING"
	validate="email"
	message="please add an email here"
	hint="your@email.com"
/>
```
But okay... I will add the time with the next update/release but do note that this will not update your field types, it will only mean a fresh install will have it.

**Comment by cpaschen** [comment]
Yes, I've been manually adding that for a while and keep forgetting to mention it.
And I only think of it when I start a new project (i.e. install new JCB).
Thanks.
