### ISSUE TITLE
SFTP not working so can't set up update server

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#288]
### Steps to reproduce the issue
Set up server for repository with sftp credentials
Check I can log in via filezilla with credentials
Check the remote site folder is accessible
Set up in Dynamic Integration the server with the details: port destination path etc.
Run the compiler with the Add to Backup Folder & Sales Server set to yes
Compile
### Expected result
The zip file to be stored in the remote destination
### Actual result

Error
The login to daily church update server has failed, please check that your details are correct!

The only thing I can think of is a certificate that I have to accept when logging on with filezilla.  Puts up a dialog box with 

The server's host key is unknown.  You have no guarantee...

But I can click to always trust the host.

I'm happy to supply ftp details to the remote server if that will help.

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.0.28
Joomla Version: 3.8.5
JCB Version: 2.6.17
Browser: CHrome

**Comment by Llewellynvdm** [comment]
SFTP is no the same as FTP, these are not the same protocols. SFTP is the ssh file transfer protocol which means ssh access. But okay sure, let me test your settings and get back to you. Please send to joomla@vdm.io

**Comment by alan123489** [comment]
Hi sorry to give confusing info about ftp vs sftp :(

I read up some more on Filezilla and they have a TOFU (Trust on first use) security model.  So they always ask for confirmation.  I don't think this is the same for php.  So I suspect that the dialogue box isn't relevant and that something else is going on.

**Comment by Llewellynvdm** [comment]
Okay what you can do is go into the code and do your own debugging :)

The function to start at is called: [moveToServer](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L3098)

I am sure you will be able to follow it and debug as you would normally do with your own code.

Do some `var_dump()` on variables from [line3363](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L3363) to see that what is expected actually is what is in the variables.

**Comment by Llewellynvdm** [comment]
I take it the issue was resolve, please give us feedback.
