### ISSUE TITLE
Will not build/compile

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#289]
Hi Guys,

I'm trying to build a simple frontend view using JCB. It should just load a list of users from the Joomla! Users Table. it would appear JCB doesn't like this as it won't build the package. 

Demo package builds fine, I just have the Users frontend view with menu item loading the Joomla! Users table, no joins for the groups yet

does JCB have a minimum requirement of views/fields?

**Comment by Llewellynvdm** [comment]
Do you have a dynamic get set? It will not build the front-end without it. Very hard to know what is wrong... reality is must be something you have not set.

Have you watched the [hello world extended](https://www.youtube.com/watch?v=IQfsLYIeblk&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=45) tutorial. Have you tried some of the other components like Sermon Distributor, Support Groups? You can now [get free access to these](https://vdm.bz/how-to-get-free-vdm-package-keys).

**Comment by tonypartridge** [comment]
Yep I sure have. I suspect it's because there is not admin view. Have you ever tried it with a frontend only? 

Demo components build fine

**Comment by tonypartridge** [comment]
Yep that's the issue, just chucked in an empty admin view and it builds.

**Comment by Llewellynvdm** [comment]
Yes, that is at this time a limitation in JCB, it only builds when you have an admin view. Since it seemed to me at first to be the only time I would build a component. If it is only front-end I usually use a module.

Great to hear you got it to work! Let me know if you have any more questions.

**Comment by tonypartridge** [comment]
@Llewellynvdm actually there can be many cases going forward in Joomla! where you only need a frontend view for the user and not a backend component i.e. com_content or com_users, banners and so on.

It would make sense to either a. remove the restriction. Or b. add a warning on build i.e. build failed, admin view is required.

**Comment by Llewellynvdm** [comment]
Yes we can look at this, I am sure it would not be to hard... for now we can add the warning for sure :+1:
