### ISSUE TITLE
Frontend Form?

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#290]
I can't see it in the docs and can't fathom it out from the component it's self. 

How do we enable a frontend Edit form to the component?

**Comment by Llewellynvdm** [comment]
Please watch the [hello world extended tutorial](https://www.youtube.com/watch?v=IQfsLYIeblk&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=45). In it I demonstrate how to add font-end editing for an admin view.

If you want to do anything beyond that you will have to custom code it at this time.

**Comment by tonypartridge** [comment]
Yes I have seen that, but since there is no admin view really as we have the Joomla! core component.. 

Ok I'll just write a custom component. Thanks anyway!

**Comment by Llewellynvdm** [comment]
So if I understand correctly you want to target other components from the front-end? That is a great idea, if you have build a custom component that does that you are willing to share it with me, we can try and adapt JCB to also be able to do that. Let me know and I will open a feature request.

**Comment by tonypartridge** [comment]
Exactly! I’ll use Joomla Component creator to do the bulk since it allows frontend end views anyway. Then should just be a refinement method and groups mapping for this frontend user management component.

I’ll share it in the new feature request you create 👌.
