### ISSUE TITLE
 css

### ISSUE THREAD

**Issue by lamatieregrise** [vdm-io/Joomla-Component-Builder#292]
Hey guys,

just a small question, because i'm not quite sure, if i have some independant css files that need to keep their specific denomination, so pasting them in the css field cant be an option, is their something in place that I've missed to connect them with the component thru JCB?or  do we do it thru the library section or we just go old school?

Francois

**Comment by Llewellynvdm** [comment]
There is a file inclusion feature, what [this tutorial to the end](https://www.youtube.com/watch?v=_c7wzW075lA&index=56&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)!

This is a very powerful feature, that allows any kind for files to be added.

**Comment by Llewellynvdm** [comment]
Also note that adding CSS in the UI will also work, since it does get added to the file linked to that admin view.
