### ISSUE TITLE
error installing package and key warning: count(): parameter must be an array or an object that implements countable in

### ISSUE THREAD

**Issue by josephballester** [vdm-io/Joomla-Component-Builder#294]
I follow the steps explained on video "How to install JCB"

When i select Joomla Component Public i set the values
FORCE LOCAL UDATE TO YES
ALL WARNING TO YES
MERGE TO YES

KEY : "i enter the key i received by email"

PRESS THE CONTINUE BUTTON.

Second laters of pressing the button a receive a list of the same warning for differect code lines ..

warning: count(): parameter must be an array or an object that implements countable in line ####

Joomla Component BUilder versino is 2.7.10 and the package im trying to download is 2.7.9.

**Comment by josephballester** [comment]
Sorry for late response

Line number is
*Warning*: count(): Parameter must be an array or an object that implements
Countable in
*C:\xampp\htdocs\jm\administrator\components\com_componentbuilder\helpers\componentbuilder.php*
on line *4586*

OS Name
XAMPP for Windows 7.2.3 installed on windows 10

mysql 5.0.12

Apachae 2.4.29

PHp 7.2.3

Joomla 3.8.8

JCB  2.7.10

Browsher: Chrome, Internet Explorer and Firefox


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Llewellynvdm** [comment]
As a quick fix add the following to [line 4586](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/componentbuilder.php#L4586) in the helper class.

```
if (count((array)$_result))
```
This should resolve the error. I will patch it with the next release.

**Comment by josephballester** [comment]
thank.

ill try and let you know.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by josephballester** [comment]
HI.

Sorry i doesnt work. Im attaching the file with this email.

Thanks again

**Comment by Llewellynvdm** [comment]
If you don't give me the next error message I can't debug...

**Comment by Llewellynvdm** [comment]
My commit to the staging branch closed the issue, but you are still welcome to continue. IF so that the staging branch has not resolved the issue.

**Comment by josephballester** [comment]
Sorry for late response

Error is the same than the previous one:

Line number is
*Warning*: count(): Parameter must be an array or an object that implements
Countable in
*C:\xampp\htdocs\jm\administrator\components\com_componentbuilder\helpers\componentbuilder.php*
 on line *4586*

**Comment by Llewellynvdm** [comment]
On [line 4586](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/componentbuilder.php#L4586) in the helper class replace:
```
if (count($_result))
```
with:
```
if (count((array)$_result))
```
This should resolve the error. This has already been patched in the staging branch.
