### ISSUE TITLE
New Table Store Method

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#295]
### Steps to reproduce the issue
To make a field store its values in its own separate table.

### Expected result
We can store the values in a separate table simply by changing the store method.

### Actual result
New Feature!

### Additional comments
Response to the [following forum](https://groups.google.com/a/vdm.io/forum/#!topic/jcb/RPTs4yaDXco) post by @alan123489

**Comment by ro-ot** [comment]
JCB and all its projects are leaving gitHub... this is going to take some time since JCB/VDM is so integrated with github,

The new address is [https://gitlab.com/jcb-repos/Joomla-Component-Builder](https://gitlab.com/jcb-repos/Joomla-Component-Builder).

**Comment by Llewellynvdm** [comment]
https://groups.google.com/a/vdm.io/d/msg/jcb/aPAuQdtkxIE/n1_epVUyBwAJ is the ongoing project discussion.

**Comment by Llewellynvdm** [comment]
This feature is indirectly been resolved, due to to non-database field option that allows you to store the values manually in another table, and then in the getItem method to load those values back again. 

I know this require some custom coding, but that should be okay, since this is an advanced task :+1: 

So I am closing this issue, should you need more help on this let me know.
