### ISSUE TITLE
Unable to re-compile component

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#296]
### Steps to reproduce the issue
Add calendar field as DATE and do not set Default on the DB tab. Save the Admin View and compile the component. Database sends an error:

Extension Update: SQL error processing query: DB function failed with error number 1064 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(50) NOT NULL DEFAULT '', `to` DATE(50) NOT NULL DEFAULT '', `params` text NOT' at line 7

CREATE TABLE IF NOT EXISTS `#__moeto_radio_ad` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`ad_name` VARCHAR(100) NOT NULL DEFAULT '',
	`alias` VARCHAR(10) NOT NULL DEFAULT '',
	`file` VARCHAR(100) NOT NULL DEFAULT '',
	`from` DATE(50) NOT NULL DEFAULT '',
	`to` DATE(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,

### Expected result
After changing the field to DATETIME and setting the defaults to custom and '0000-00-00 00:00:00' to actually re-compile the component.

### Actual result
Each time i receive the same error as there is a cache and even after i have updated the names of the fields, recreated them, recreated the admin view with the new fields etc.  and not a single time these changes reflected on the compiler error output.

### System information (as much as possible)
- OS Name & Version: Centos 7.4
- MySql Version: MariaDB 10
- Apache Version: Nginx 1.12
- PHP Version: 7.3
- Joomla Version: 3.8.8
- JCB Version: 2.8.0
- Browser: Chrome

### Additional comments

I have observed before an issue with the caledar field that it fails to compile the component unless you change it to DATETIME and set custom Default to '0000-00-00 00:00:00'. However this time does not seem to take the change at all.

**Comment by peterpetrov** [comment]
I found that one of the SQL files in the installation package contain that data. However even after the update is done and the fields are not named it does not go away. Any thoughts about how to fix this?

**Comment by Llewellynvdm** [comment]
You need to adapt the sql defaults (in the field) to work with MariaDB.

**Comment by Llewellynvdm** [comment]
Maybe use datetime instead [look at these settings](https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L133).

**Comment by peterpetrov** [comment]
That part i figured out. The problem i am reporting is after i update the field actually it doesn't do it. I found that in the update folder there are sql files that contain the updates in versions of the sql changes of the fields. Does it for any reason every time executes all the files when trying to install the component?

**Comment by Llewellynvdm** [comment]
No, you should check the update files in the component to see if it still has old values. This could happen, and can be manually updated.
![image](https://user-images.githubusercontent.com/5607939/40907505-fb57ca00-67db-11e8-9098-196ca5f4eb98.png)
Check the green button called  **Edit component updates for this joomla component** 

Those are the only sql settings that could be executed after the first install. So to manually check you DB and see what is already installed and what should still be added is what the **Component updates** is for.

The other option is to full uninstall your component and install fresh install of you component.

**Comment by peterpetrov** [comment]
So i had to uninstall the component, remove all the updates and then it worked. Just adding that note for MariaDB for date field you need to use DATETIME and set custom default to '0000-00-00 00:00:00' for it to work.
