### ISSUE TITLE
Component that has no backend and get it's front-end data from an API

### ISSUE THREAD

**Issue by kevincam3** [vdm-io/Joomla-Component-Builder#306]
I was wondering how I could create a component that has no admin view and gets it data from an API. Meaning my site view would get getting its data from an API call

**Comment by Llewellynvdm** [comment]
This option has been suggested, but at this time JCB is still not able to do this. Soon as we have the road map in place to achieve this we will send a notice on the VDM notice board.

The best option to achieve this at this time would be to build a Joomla module.
