### ISSUE TITLE
So many changes...

### ISSUE THREAD

**Issue by lamatieregrise** [vdm-io/Joomla-Component-Builder#307]
Hi Llewellynvdm,

First let me I'm sorry cutting contact so abruptly the last time, it was unintended, I've been without computers for the last 5 weeks both motherboard suddenly died (in the same week) so had to re-equip myself with brand new babies and now I'm fully functional.

I'm not able to download the latest staging version, is there something that change or an option i need to set? BTW I'm still up for the translation feature we spoke a few weeks ago 
Francois.

**Comment by Llewellynvdm** [comment]
Not able to download the staging version? Weird, should be able to download any version of JCB. Nothing changed in that regard. Please show us a screen shot of the error you are getting.

Yes we are open to look at the option of translation improvements.

**Comment by Llewellynvdm** [comment]
@lamatieregrise I will close this issue, but you are most welcome to continue commenting on it if have any more questions.
