### ISSUE TITLE
button save does not work with type_php_1 

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#311]
### Steps to reproduce the issue
I created a new field type .
 
![9](https://user-images.githubusercontent.com/5087049/42132635-94fc88be-7d24-11e8-9381-740df4659a82.PNG)

When I add the type_php_1 option , the save and save and close button does not work in the field editor with this type. When pressed, they just hang.

When I delete  the type_php_1 option, all work well.

**Comment by Llewellynvdm** [comment]
Please do ma a favour and start [watching the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/wiki), really I can teach you on github.

Please [watch this tutorial](https://youtu.be/epA9zv4yWu0?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE).
