### ISSUE TITLE
Add ability to specify static options in Custom field

### ISSUE THREAD

**Issue by fun4uskids** [vdm-io/Joomla-Component-Builder#313]
### Steps to reproduce the issue
On Custom field type, add "options" attribute and allow user to add static options which would appear in the list.  

For example:
model/forms
```
		<field name="formid"
		   type="formid"
		   label="Entry Form"
		   description="Select the Entry Form to use with this Giveaway." 
		   required="true">
			<option value="">Please select your Entry Form</option>
			<option value="0">Do not display a form</option>
		</field\>
```

Generated code
```
class JFormFieldFormId extends JFormFieldList
{

	protected function getOptions()
	{
		$db    = JFactory::getDBO();
		$query = $db->getQuery(true);
		$query->select('formid,formtitle');
		$query->from('#__rsform_forms');
		$query->where('published = 1');
		$query->order('formtitle ASC');
		$db->setQuery((string) $query);
		$forms = $db->loadObjectList();
		$options  = array();

		if ($forms)
		{
			foreach ($forms as $form)
			{
				$options[] = JHtml::_('select.option', $form->formid, $form->formtitle);
			}
		}

		$options = array_merge(parent::getOptions(), $options);

		return $options;
	}
```

**Comment by ro-ot** [comment]
I would suggest you just code it in with PHP:
```
$db    = JFactory::getDBO();
$query = $db->getQuery(true);
$query->select('formid,formtitle');
$query->from('#__rsform_forms');
$query->where('published = 1');
$query->order('formtitle ASC');
$db->setQuery((string) $query);
$forms = $db->loadObjectList();
$options  = array();

if ($forms)
{
	$options[] = JHtml::_('select.option', '', JText::_('Please select your Entry Form'));
	foreach ($forms as $form)
	{
		$options[] = JHtml::_('select.option', $form->formid, $form->formtitle);
	}
	$options[] = JHtml::_('select.option', 0, JText::_('Do not display a form'));
}

return $options;

```
and you place it in the **The php for the getOptions method** of the custom field like this:
![image](https://user-images.githubusercontent.com/2594383/42347644-6b592b0c-809e-11e8-90ec-176c0c572a6f.png)

**Comment by fun4uskids** [comment]
I knew I could make the code change in the interface.  I just didn't see how the <option>s would get added to the <field> in the form xml.  Unless I modified the form xml after the compile.  Since you have the code in the list generation, I thought it could be added to the custom field generation.

If I go into the field types, and add an options parameter to the custom field, will it properly build the <option>s in the <field> xml?

**Comment by ro-ot** [comment]
Why do you need it there, the field will be build  with the static values in the drop down. 

Only with list field type does the options get added to the xml, with custom field all happens in the PHP code.

**Comment by fun4uskids** [comment]
Oooohhh...  I see what you are saying.  I didn't read the code thoroughly
enough.  I thought it was the same code I posted.   This will work fine.

Thanks,
J Wadsworth
352-283-0615
