### ISSUE TITLE
getting Class VDM not found error when using WHMCS licensing

### ISSUE THREAD

**Issue by yourwebsolution** [vdm-io/Joomla-Component-Builder#315]
### Steps to reproduce the issue
Add the WHMCS license module in "Lock down use" mode and put in a valid license code

### Expected result
Component should load correctly

### Actual result
I get the following error message when I try and use the component - 

Class 'VDM' not found

### System information (as much as possible)
- OS Name & Version:  MAMP Pro on Mac OS
- MySql Version: 5.6.38
- Apache Version: 
- PHP Version: 7.2.1
- Joomla Version: 3.8.10
- JCB Version: 2.8.2
- Browser: Safari 11.1.1

**Comment by Llewellynvdm** [comment]
I found the bug, it is basically a few lines in the compiler, I have made the changes to fix the issue and will push it to the staging branch.
