### ISSUE TITLE
Bug with jsonToString function for Site and Admin helper files

### ISSUE THREAD

**Issue by emilioleite** [vdm-io/Joomla-Component-Builder#317]
See screenshot
![screen](https://user-images.githubusercontent.com/41153392/42632145-a3658ae0-85b2-11e8-870b-b15ffd43d11e.png)

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.7.14
- Apache Version: 2.4
- PHP Version: 7.2.3
- Joomla Version: 3.8.10
- JCB Version: 2.8.4
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
Thanks, will add the patch :+1:
