### ISSUE TITLE
Add Custom PHP Class

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#32]
I know you are holiday, but I wanted to ask this what it is still "fresh" in my mind.

I have a couple of custom PHP classes to my frontend views (hard coded in the php files themselves). I would like to add those to component builder to compile those automatically, in the correct locations. I have tried adding the code to the dynamic get, and to the admin view Add PHP (getItem method), but they aren't quite putting the code in the correct location. In my code, the custom classes are in the footer of the code, underneath (after) everything that component builder automatically generates. That is where it would be ideal to put it, as it doesn't generate errors there.

What area would I put those custom classes to generate that code in the correct location?

**Comment by Llewellynvdm** [comment]
to find out where what location is, simply add identifiable note to each PHP fields available in any area. Then compile the component, and in an IDE search for those notes in the code, this is the best way to identify placement of custom code.
