### ISSUE TITLE
Edit/Create Site View only creates menu option on intial run

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#321]
### Steps to reproduce the issue

Create fields as needed
Create Admin view (with fields)
Add Admin view to component but DO NOT check 'Edit/Create Site View
Compile 
Go back to Joomla Components view
Open component admin views
Check 'Edit/Create Site View'
Save & Close
Compile the Component

Go to MENUS | MAIN MENU | Add a new menu item
Click the SELECT button for Menu Item Type
Click on the component that you just compiled

### Expected result

There should be a Menu Item Type (under the component) with the same name as the admin view that you created

### Actual result

This view is not there

### System information (as much as possible)
- OS Name & Version: WAMP
- MySql Version: 5.5.56
- Apache Version: 2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.8
- JCB Version: 2.8.4
- Browser: chrome

### Additional comments

If you check the 'Edit/Create Site View' box when you first compile the component, the view appears in the Menu Item Type list, just not if you check that after the first compile with the admin view.

HOWEVER, it appears that the front-end view files are all created as needed - just no menu item type

**Comment by cpaschen** [comment]
ARGH ... I KNEW that it was just something I missed (It's been a couple months since I created a front-end view on anything. Sorry, I just forgot that I actually built those links manually).

However, considering that 'usually' a front-end view is required, it would sure be helpful if the process of adding the dynamic get and site view could somehow be automated so that all that would be necessary would be to actually go in and properly populate the actual view display.

Not sure how hard that might be (to automate dynamic get and site view population) but that would be a huge help and a great new feature.

**Comment by Llewellynvdm** [comment]
I am planning to add this (as you can see it is in the TODO list), just not sure when, so I will putt it on the shelf until then.

**Comment by Llewellynvdm** [comment]
Just to confirm again, this feature request is to automate the menu link creation for edit views, so that there will be a menu item for the site view, that says (Create Viewname) automatically if the Edit/Create is checked.

**Comment by Llewellynvdm** [comment]
Okay at last, we have added the feature. You will see that when adding a admin_view to the component the same place where you trigger the admin view to be added to the front-end it now has a drop-down to select `add+menu`. There are three options now `none` and `add` <-(the original behavior) and `add+menu` which is this new feature.

![image](https://user-images.githubusercontent.com/5607939/55837826-c09c5f80-5b22-11e9-9125-1c6f0cb81f64.png)

@cpaschen please run some test and let me know if this works as expected.
