### ISSUE TITLE
default field ID is writeble during editing component

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#322]
### Steps to reproduce the issue
After build your component an goto a single admin view. Click on the tab Publish, and look the field ID. 

I expected that it is read only but actual it is an edible field.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.5.5-10.1.34-MariaDB-1~xenial
- Apache Version: 
- PHP Version: 7.1.19
- Joomla Version: 3.8.10
- JCB Version: 2.8.4 (staging)
- Browser: Firefox

### Additional comments
On the place where the id xml field is added, it needt to have an extra parameter readonly="true"

**Comment by Llewellynvdm** [comment]
There is, when you create any field, and you select the field type, and it is missing a property, then just edit the field_type and add the property. Just make sure that it is a valid property in the Joomla xml field implementation of that field_type.

So you can click on the small blue pencil icon to edit the field_type:
![image](https://user-images.githubusercontent.com/5607939/43025968-a1008c54-8c6b-11e8-9993-f05424ae818d.png)
Or you can go to field types and just edit the field_type in question. Please[ watch this tutorial again](https://youtu.be/OhLzvThDXls?t=9m39s) if you need more help with this.

**Comment by Schrijvers123** [comment]
I know you could change it, but an id fiels should be by default read only. Or am I missing something?

**Comment by Schrijvers123** [comment]
Thanks for the fast response and explanation. I will check and i make sense.

Also I will look into the code of JCB to get familiar with it so I can help when necessary. I'm realy impressed what you made.

**Comment by lnk0bel** [comment]
I did not override the id field on my side and it is not read only either so it seems it's no more read only by default even when not overridden.

Created by, modified by, modified date and revision are read only but not the id.

**Comment by Llewellynvdm** [comment]
O yes it is, [here you can check the code](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L476) in the compiler that manages the ID. O wait a moment it is the xml implementation that is not adding the read only [over here](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L744). 

So the [string manipulation option]](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L476) actually does make it readonly... but it was missed with the xml implementation of the field builder... I will push a fix for that with the new default readonly for override ID.

@Schrijvers123 I am working on JCB at the moment... so the quick response :+1:

**Comment by Llewellynvdm** [comment]
Okay the fix for this has been pushed to the staging branch, let me know if it is resolved on your side.

**Comment by Schrijvers123** [comment]
After I complided the component and installed it (as an update), the field was still the same. I deinstalled my component and after that it was working.
