### ISSUE TITLE
FieldTyep CusomUser is save wrong

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#324]
### Steps to reproduce the issue
Make a new CustomUser field. And save it.

### Expected result
After saving the new field, the php code in getExcluded methode should be normal as normal. The default php code or code that you changed by yourself.

### Actual result
The php code that is used in the getGroups methode.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.5.5-10.1.34-MariaDB-1~xenial
- Apache Version: 
- PHP Version: 7.0.30
- Joomla Version: Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
- JCB Version: 2.8.4 staging
- Browser: Firefox (latest)

**Comment by Llewellynvdm** [comment]
Okay it has been fixed in the last [push to the staging branch](https://github.com/vdm-io/Joomla-Component-Builder/commit/812857da813d5863a8043b2b73e0fdc2fd780127#diff-78b2a246848801b8f5bb5e1521037903L930).
