### ISSUE TITLE
Button 'Import JCB Packages' on control pannel gives error

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#325]
### Steps to reproduce the issue
Click on main menu on component > component builder.
CLick on the button 'Import JCB Packages' 

### Expected result
The import screen

### Actual result
Error with the message: 'The most recent request was denied because it had an invalid security token. Please refresh the page and try again.'

Via the Button Joomla Component and then i the top menu Import JCB Package it is working.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.5.5-10.1.34-MariaDB-1~xenial
- Apache Version: 
- PHP Version: 7.0.30
- Joomla Version:  3.8.10
- JCB Version: 2.8.4 staging
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by Llewellynvdm** [comment]
hmm security token, this must have been because I added a token validation to the smartImport method in the controller. Thanks I missed that.

**Comment by Schrijvers123** [comment]
Test the new version and it is working.
