### ISSUE TITLE
sermondistributor:  delete a preacher record,  sermon table is not updated.

### ISSUE THREAD

**Issue by orionstardev** [vdm-io/Joomla-Component-Builder#329]
### Steps to reproduce the issue
In admin sermondistributor:  delete a preacher record.

### Expected result
in database:
- that  preacher record is deleted
- and removed in the sermon records 

### Actual result
deleted preacher record id is still in sermon record. Unless you via the  admin sermondistributor: manually update the related sermon record.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 2.4
- PHP Version: 7
- Joomla Version: 3.8.11
- JCB Version: 3.8.5
- Browser: firefox (latest)

### Additional comments
How do Linked Views work?
How should it be used? 
Which type of connection its realised "one to one", "one to many", "many to many" ? 
And how can I create such connections?

What happens when child or parent get updated or even deleted?
Do all involved table records automatically get updated? as in Joomla? using mysql Foreign key constraints?, on-delete?, on-update?

**Comment by Llewellynvdm** [comment]
Have you looked at the [tutorials](https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)? Really a lot to answer and explain.. I am not able to explain it all here... best watch the tutorials. This one speaks about the [linked views](https://youtu.be/CdSKSCTzmRA?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&t=22m20s).

I have give away so many demo components that demonstrate all this in detail, like [JCB](https://vdm.bz/how-to-get-free-vdm-package-keys) it self.

Short answer it is one to many, many to one and many to many, depending on how you set it up. No JCB does not deal with the auto delete based on relation ships. But as in JCB it can be coded in, so import the JCB package of JCB and open the admin or component view, looking over the PHP tab fields at **PHP postSaveHook Method** and **PHP publish Method after** and **PHP delete Method after** There I deal with the dynamic update of records in relationship with the related tables.

I really think I have give the community more then enough to get going...

**Comment by Llewellynvdm** [comment]
Okay if you have any more issues, please feel free to comment here, or just open a new issue.
