### ISSUE TITLE
Jmodeladmin

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#33]
I'm trying to understand why, and what causes,  some frontend views to compile st jmodelitem, and other times j model admin? Is there something that causes that?

**Comment by Llewellynvdm** [comment]
hmmm that does not make sense... can you please explain more. When you say compile, you mean the name of the view or the code of the view... I need to know more.

Please be sure that Component Builder is not PHP7 ready.... nor is its compiled components.... so check what version of PHP your using, we recommend 5.6

I have never had any issue like this before so you need to give me some more to work with. Further I may need to look at the problem...

**Comment by mwweb** [comment]
Sorry, this is in the code. I think what happened was I "duplicated" the site view in the component. This ended up creating 2 different versions of the model, for example city and cityv. City was a jmodeladmin, where cityv ended up being a jmodelitem.

**Comment by Llewellynvdm** [comment]
Okay so is this resolved?
