### ISSUE TITLE
Feature Request - Admin Fields List Layout

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#330]
This is a VERY MINOR priority feature request, but I would think that it would help others than just me.

### Steps to reproduce the issue

Create severa;  fields with a somewhat long name (more than 20 chars or so) [Esp. if you use a 'prefix' like 'SYS-' or "ADMIN-' or something to allow easy sorting and finding later]
Add the fields to an Admin View.
Go do some other development on the component.
Come back to the admin's field edit view.
Try to figure out which field you need to change.

### Expected result

Able to view the full name of the field.

### Actual result

Field name is only visible to about 20-ish characters within the drop-down select item - making it every hard to find the correct field, esp. if you have lots of fields and you prepend them with something (as above).

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser: 

### Additional comments

It is a bit difficult to override this due to the fact that each individual field is manually set with the width at the element level.

I've added:

div.chzn-container-single {
    width: 100%!important;
}

To the admin template, but that is a 'shotgun' approach and hits a lot of other items as well.
It would be nice to just have a css tag added to this or even manually set the width at this item level to 100% (so it fills the container).

Others might have a better suggestion for a way to properly deal with this, but it would just be nice to see the entire (or at least significantly more) field title in the list.

**Comment by Llewellynvdm** [comment]
Sure no problem, we could grow that field :+1:
