### ISSUE TITLE
Use alias in SEF? 

### ISSUE THREAD

**Issue by jibon57** [vdm-io/Joomla-Component-Builder#332]
### Steps to reproduce the issue
I have added views which have alias but how I can use this alias for Joomla SEF instated of ID?

### Expected result
 joomla2/my-test-menu/meeting/test

### Actual result
joomla2/my-test-menu/meeting/1

### System information (as much as possible)
- OS Name & Version: windows 10
- MySql Version: 5.7
- Apache Version: 2.4
- PHP Version: 7.1
- Joomla Version: 3.8.11
- JCB Version: 2.8.5
- Browser: firefox

**Comment by peterpetrov** [comment]
Hey Jason, i doubt this is an issue with the component. Can you please share the code you have in your views as well as the field configuration for that particular view? I assume you are talking about front-end view?

Peter

**Comment by peterpetrov** [comment]
Just so you know functionality questions and asking for help is best to be asked here:

https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!forum/jcb

The GitHub issue requests are for bug fixing mainly or functionality suggestions.

Peter

**Comment by jibon57** [comment]
@peterpetrov, thanks for reply. I had written here long ago: https://groups.google.com/a/vdm.io/forum/#!topic/jcb/prfSU4zfsgE but no response there.

**Comment by peterpetrov** [comment]
OK, let me look there. Lets close this one. Please provide there the code snippet i am asking for in the same thread.
