### ISSUE TITLE
Unable to copy file to site view

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#336]
### Steps to reproduce the issue
Go into a component in JCB, for example DEMO.
Visit Editing the Component Files & Folders.
Select a file (I just randomly grabbed one), and set the path (I set /site/views/looks/)
Save and compile.

### Expected result
The expected result is for the file to get copied to the /site/views/looks/ folder upon compile.

### Actual result
Warning
Copy failed: /var/www/dev/administrator/components/com_componentbuilder/custom/downloadController.php to /var/www/dev/administrator/components/com_componentbuilder/compiler/com_demo_v2_0_0__J3/site/views/looks/downloadController.php

### System information (as much as possible)
- OS Name & Version: 14.04.1-Ubuntu
- MySql Version: 5.5.5-10.1.28-MariaDB-1~trusty
- Apache Version: 2.4.29
- PHP Version: PHP Version 7.1.18-1
- Joomla Version: 3.8.11
- JCB Version: 2.8.5
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
This is strange I will investigate.

**Comment by mwweb** [comment]
I was wondering if that was a bug. A lot of my views I'm having to add a custom view.json.php to a few of the views, to aid in some of the new functionality. I have this working in the interim by copying the files I need to the media folder, then using JFile::copy to copy the files to the correct places. It's wasn't the ideal, but was a work around as I reported this.

**Comment by Llewellynvdm** [comment]
Can you please give me a screenshot of the files and folders area, so I can see how you have it setup.

Then one [line 772](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php#L772) of [b_Structure.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php#L772) add this line of code:
```
echo '<pre>';var_dump($this->joomlaVersionData->move->static);jexit();
```
Then compile your component, you will get a var_dump value, that you should please also give me here. After doing that remove the line again. I would just like to make sure we are doing the same thing, and getting the same result.

**Comment by mwweb** [comment]
![jcb-files](https://user-images.githubusercontent.com/19194012/45331497-e7100300-b51f-11e8-96e9-8ea61a6cc89d.png)

  public 'chartbuilderphp_gh' => 
    object(stdClass)[449]
      public 'naam' => string 'chartbuilder.php' (length=16)
      public 'path' => string 'c0mp0n3nt/site/views/looks' (length=26)
      public 'rename' => boolean false
      public 'type' => string 'file' (length=4)
      public 'custom' => string 'custom' (length=6)

![jcb_copy_failed](https://user-images.githubusercontent.com/19194012/45331572-5ede2d80-b520-11e8-8cfa-727ef649df0b.png)

**Comment by pctechnikch** [comment]
Hello

You have seen the Videos (Screenrecords) with the steps? There you can reproduce the error very good, is very simple. My installation is in a new environment - Joomla JCB and SD. ONLY saving the site views (single item) causes the error and generate another View, a other code in the view... !!

You see :
http://pctechnik.ch/ErrorJCB-SD.avi

In the attachment the desired.

(Why are you closing the ticket?)

Thanks René
Von: <<ewe>>yn <notifications@github.com>
Gesendet: Montag, 10. September 2018 12:29
An: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [vdm-io/Joomla-Component-Builder] Unable to copy file to site view (#336)


Can you please give me a screenshot of the files and folders area, so I can see how you have it setup.

Then one line 772<https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php#L772> of b_Structure.php<https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/b_Structure.php#L772> add this line of code:

echo '<pre>';var_dump($this->joomlaVersionData->move->static);jexit();

Then compile your component, you will get a var_dump value, that you should please also give me here. After doing that remove the line again. I would just like to make sure we are doing the same thing, and getting the same result.

**Comment by Llewellynvdm** [comment]
I have found the problem, the file is try to be moved before those paths exist... I will push a fix to the staging branch soon as I can.

**Comment by Llewellynvdm** [comment]
Please test [the fix](https://github.com/vdm-io/Joomla-Component-Builder/commit/7fcc93aa5b29188c098ba72ae60ba46a22e90b21) I pushed to the staging branch.

**Comment by mwweb** [comment]
Thanks ro-ot. I got swamped on the code changes I have been working on (changing list views to utilize ajax for the display and filtering). I just got around to testing it tonight, and it appears to be working for me as well.

Thanks for the fix Llewellyn.
