### ISSUE TITLE
Feature Request - Add custom functions to site models

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#337]
### Steps to reproduce the issue
Rarely, but occasionally, there may be an instance where a custom function may need to be created, which JCB can't easily do. In Site View there is the Add PHP option to "Add PHP (custom JViewLegacy methods)". If a function is set there, it will inject that code into the view.html.php file for that view.

It would be nice if that function was available for dynamic gets as well. It could inject that code below the public function getItems method.

### System information (as much as possible)
- OS Name & Version: 14.04.1-Ubuntu
- MySql Version:  5.5.5-10.1.28-MariaDB-1~trusty
- Apache Version: 2.4.29
- PHP Version: PHP Version 7.1.18-1
- Joomla Version: 3.8.11
- JCB Version: 2.9.0
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
Have added it to the list... so we can keep track of this request. Will open it again once in progress.

**Comment by mwweb** [comment]
This can actually be closed. In putting comments every that there is a custom PHP area, I found that in Site view --> Custom Buttons --> Add Custom Buttons --> PHP (model methods) does what I was looking for.
