### ISSUE TITLE
Unable to put custom button on front end view

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#338]
### Steps to reproduce the issue
Created front view and added custom button to it that redirects to external address. The idea is to test the custom button functionality. 
Target Controller Method: redirectExternal
Target: Both
Type: Default

PHP (controller methods):
```
public function redirectExternal() {

header("Location: https://www.google.bg/search?q=how+to+get+pregnant&oq=how+to+get+preg&aqs=chrome.0.0j69i57j0l4.6736j0j8&sourceid=chrome&ie=UTF-8"); /* Redirect browser */
exit();
}
```

### Expected result
When clicking the button to redirect to the link

### Actual result
Printing error that there is no function. When i enable the debug this is on line 123 which says:

123:                 if ($this->canDo->get('buttons.test_redirection'))

If i comment it out plus the if brackets and leave this code only:

                        JToolBarHelper::custom('buttons.redirectExternal', 'joomla', '', 'COM_TEST_COMPONENT_TEST_REDIRECTION', false);

i am getting then javascript errors and the command is not executed.

System information (as much as possible)
OS Name & Version: Centos 7.4
MySql Version: MariaDB 10
Apache Version: Nginx 1.12
PHP Version: 7.3
Joomla Version: 3.8.12
JCB Version: 2.9.0
Browser: Chrome

**Comment by Llewellynvdm** [comment]
Did you try it with **only function**?

**Comment by peterpetrov** [comment]
I have just now. Result is the same.

Peter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peterpetrov** [comment]
![screen shot 2018-09-11 at 13 41 23](https://user-images.githubusercontent.com/2786810/45355210-7bce3b80-b5c8-11e8-808c-be177c743102.png)
![screen shot 2018-09-11 at 13 41 00](https://user-images.githubusercontent.com/2786810/45355211-7bce3b80-b5c8-11e8-92c6-ebab55c1b196.png)

**Comment by Llewellynvdm** [comment]
No I don't want access... best keep this simple. I will run more test on my end, and get back to you.

**Comment by peterpetrov** [comment]
OK thanks. Let me know if i can assist in the testing additionally.

**Comment by ro-ot** [comment]
Found the issue, seems Joomla change this area considerably (since the time we used it) so we will need to adapt JCB.

TODO:
- Load the Joomla framework with (`JHtml::_('behavior.framework', true);`)
- Add a custom submit script for the button, that does not attempt validation
- Add the php `$this->canDo->get(...)` values to the page
- Add a form to the page with a form token for safety
- Checks to not do any of the above if the developer already added them manually

**Comment by Llewellynvdm** [comment]
I have just pushed the fix, please test the [staging branch](https://github.com/vdm-io/Joomla-Component-Builder/commit/5962b557c8244472c6637a2713978640472e8d36), and remember the button has permissions.

**Comment by peterpetrov** [comment]
I can confirm that it works. I will start doing some more tests for what kind of functions I need to implement and let you know if anything pops up.

Thank you very much!

Peter
