### ISSUE TITLE
Automated backup fails, manual backup works

### ISSUE THREAD

**Issue by yourwebsolution** [vdm-io/Joomla-Component-Builder#339]
### Steps to reproduce the issue
I'm trying to get the cronjob working to automate my backups as per in the training video.

I have configured a remote FTP server and when I click on the backup button in the component it all works fine and I get my backups.

### Expected result
Backup to complete

### Actual result
However the cron job is failing - and if I try and run the html link in the browser diirect it also fails with the message "# Error Backup failed, please try again. If the error continue, please contact your system administrator."

If I run the cron job as recommended (curl -s "https://develop.yourwebsolution.net/index.php?option=com_componentbuilder&task=api.backup" >/dev/null 2>&1_) in a terminal then I get no output at all, if I add the -H (curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" -s "https://develop.yourwebsolution.net/index.php?option=com_componentbuilder&task=api.backup") then I get the same error message.

### System information (as much as possible)
- OS Name & Version: Cloud Linux 3.10.0-714.10.2.lve1.5.15.el7.x86_64
- MySql Version: 5.6.40
- Apache Version: 2.4.34
- PHP Version: 7.1.21
- Joomla Version: 3.8.12 
- JCB Version: 2.9.0
- Br 68.0.3440.106

**Comment by Llewellynvdm** [comment]
Did you set an USER that has access to run the API update.

Check the code here on [line 48](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/site/controllers/api.php#L48) in the controller you will see it does a permission check.

In the global options there you should select the user that will be used during the update as the validator.

Then if that is working, check the next level... on [line 59](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/site/controllers/api.php#L59) does the helper method return the IDS/pks to update.... if not go to the [componentbuilderHelper::getComponentIDs()](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/site/helpers/componentbuilder.php#L525) method and do some debugging there.

Once we have the IDs then the next level... on [line 59](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/site/controllers/api.php#L59) there is a method called [getSmartExport](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/site/controllers/api.php#L59) that is part of the joomla_components (admin) model. Does it return true, and if not why, can you debug that to see...

Well let me know what you can find out then we take it from there.

**Comment by ro-ot** [comment]
You may want to check your FTP details, try doing a back-up to a local folder.

**Comment by Llewellynvdm** [comment]
@yourwebsolution any news on this front? is the issue resolved?

**Comment by Llewellynvdm** [comment]
trust this has been resolved, just comment here if the issue needs more attention.
