### ISSUE TITLE
Limited Number of fields

### ISSUE THREAD

**Issue by halatef** [vdm-io/Joomla-Component-Builder#34]
in admin view whatever the no of fields i add it displays only 2 fields in admin form, how can i fix this

**Comment by Llewellynvdm** [comment]
To gain [access to the tutorials](https://github.com/vdm-io/Joomla-Component-Builder/issues/1), that explain how component builder work.... [please visit this page](https://github.com/vdm-io/Joomla-Component-Builder/issues/1)

We explain how you add fields to a component in great detail.

**Comment by Peeripapo** [comment]
I had the same issue and i guess I fixed it by setting the order in Edit.

Edit the Admin View -> Click Fields in "Settings" Separator -> Populate the "Order in Edit" column
