### ISSUE TITLE
Feature request: Extending custom fields to allow getinput override

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#341]
### Expected result
As custom fields are used within JCB to allow for field-type changes, I would like to be able to overwrite the getInput() function of a custom field, the same way it is currently possible to do this for the getOptions() function.

This would allow people to have more control over the field's appearance and behavior.
An example would be to easily add extra data parameters to the field.
Referencing this: [Joomla documentation: Creating a custom form field type](https://www.google.com/url?q=https%3A%2F%2Fdocs.joomla.org%2FCreating_a_custom_form_field_type&sa=D&sntz=1&usg=AFQjCNFjuhEgDxBIe95Aps-vrmz-m1DxFw)

### Actual result

New feature: getInput() overwrite ability within custom fields in JCB..

### Additional comments

Follow up from this forum post:
[Custom field types](https://groups.google.com/a/vdm.io/forum/?utm_medium=email&utm_source=footer#!topic/jcb/nS24TX0CUik)

**Comment by Llewellynvdm** [comment]
Okay I think I have it ready for testing... it came out little different then I planned originally, but I think you will like how it works.

Here is a [quick tutorial](https://youtu.be/Mu9H0zgH9Lw) on how to use this feature. @AlexDings please test this on your side and let me know if it works as expected.

**Comment by AlexDings** [comment]
Thanks for the quick work.
I am quite busy with work right now but will make sure to get you all my feedback by the end of this week

**Comment by Llewellynvdm** [comment]
Lets just say I also needed this feature :+1:

**Comment by AlexDings** [comment]
The feature is looking good, and I could work with it.
However, right now the type_phpa-z values are treated as default values and are overwritten when creating the field which uses this fieldtype.

Would it be possible to make it so that the php for this fieldtype is set, and this can't be changed on the field creation. This would work better for me since I will have 10 fields using this unique list-getinput method. Having this in the fieldtype and not the field would allow me to update it on one place and have it have effect on all the fields using this fieldtype.

**Comment by Llewellynvdm** [comment]
I am not sure I understand, but for what its worth... ones you create the new custom-custom field-type just code what you want, I mean all you want it to do in to the type_php_a and b and c and so on... then when creating the field, just don't edit it, let the default be the actual. Or am I missing something?

You don't have to edit those fields, you can with placeholders make it dynamic like the original custom field.

**Comment by Llewellynvdm** [comment]
If I still don't get your question, best give some pictures :) since to me this option should also work for what you are looking for.

**Comment by Llewellynvdm** [comment]
I think the one thing we can do to make this easy, is to allow more then one line per line, so we do not need to do line for line... that is little slow... let me see if this will be easy to change.

**Comment by Llewellynvdm** [comment]
Okay that was not that hard... now you can in one line add the whole code function. Should make it easier.

**Comment by AlexDings** [comment]
The multi-line addition is great!

I am not sure how to illustrate with images, but I think you were almost following.

> @Llewellynvdm: "ones you create the new custom-custom field-type just code what you want" ... "then when creating the field, just don't edit it, let the default be the actual."

Let's imagine I did this. My desired behaviour now is that when I update the "custom-custom field-type code" this also gets **updated** in all created fields using this "custom-custom field-type".

**Comment by Llewellynvdm** [comment]
Hmm there is an easy way to do this with custom code place holders. Not in the field type but in the field.

So lets say you have a new custom-custom field type and it has a type_php_a and a type_php_b field then in those fields, in the field (not the field type) copy the code over to a custom code and get the snipped and past it into those textarea's like so:

I am doning this with a note... but you can do it in any field:
![image](https://user-images.githubusercontent.com/5607939/46209501-4f3b5300-c32e-11e8-89d3-c8a448de77ca.png)
![image](https://user-images.githubusercontent.com/5607939/46209513-5a8e7e80-c32e-11e8-9636-47a286f098ac.png)
![image](https://user-images.githubusercontent.com/5607939/46209526-64b07d00-c32e-11e8-8406-7e668e79e954.png)
![image](https://user-images.githubusercontent.com/5607939/46209566-78f47a00-c32e-11e8-97be-680fede19baa.png)

Here I am doing it with a custom field:
![image](https://user-images.githubusercontent.com/5607939/46209671-beb14280-c32e-11e8-82c1-2a8be35be35f.png)

So you still build your custom-custom field type.. then as code in the field-type, you add a customcode placeholder like this:
![image](https://user-images.githubusercontent.com/5607939/46209820-30898c00-c32f-11e8-9f83-533af01b8fe2.png)

Then you just need to update the code in the custom code area... and it will automatically update in every field, you build with that new custom-custom fieldtype.

Crazy right... well it works :+1:

**Comment by Llewellynvdm** [comment]
I just found that I had to update the search for where customcode placeholders are used, due to the new base64 storage of the php in the fields. I made that change so we can use `'` and `"` in the code... so with the next push to staging this will also be fixed.

**Comment by AlexDings** [comment]
For some reason the value of phpa doesn't get stored in the custom field.

custom-custom fieldtype: 
![image](https://user-images.githubusercontent.com/12542207/46244991-65591a00-c3e7-11e8-8570-19fba8f720d6.png)

I can see this default in the field, but it disappears on save. The value of php_1 does get stored.
![image](https://user-images.githubusercontent.com/12542207/46245004-a18c7a80-c3e7-11e8-9e4a-bc0111253d3d.png)

The code inside "[CUSTOMCODE=basicFieldGetInput]" is just the default getinput function.

**Comment by Llewellynvdm** [comment]
Let me check... that worked the last time... wonder what happened. Will get back to you.

**Comment by AlexDings** [comment]
Thank you.
I will continue for now to program the functionality I need and will later on pour it into this field

**Comment by AlexDings** [comment]
**Access to field-parameters**
When creating multiple fields of type "custom-custom fieldtype", these all create the same file under com_component>models>fields>customfieldtypename.php. Is this expected behavior? 

If so, people need to realize they can't use component builder's ###VALUE### placeholders. 
I haven't found these variables in the field's object, where the field's "id" and "name" are found either. Is there any other way to access them?

I would suggest using the field's name to create these php files, so many custom fields of the same custom-custom fieldtype may exist, which also allows people to use the ###VALUE### placeholders

**Comment by Llewellynvdm** [comment]
Please watch this https://youtu.be/_1Xi6FlWuG0, and help me see where I am doing things different and how this has effected the expected result, so I can redo the previous tutorial.

**Comment by AlexDings** [comment]
About the tutorial, I believe the first one was clear enough. You are extremely good at explaining

**Comment by Llewellynvdm** [comment]
ahaaa I have not tested that... I will take a look, not sure why it would do that... but it is possible.

**Comment by Llewellynvdm** [comment]
Okay tryout the last update, on my side it is working as expected.  Adding the custom-custom field (subject) to a subform and as a normal field in the same view:
```xml
<!-- Options Field. Type: Subform. (joomla) -->
<field
	type="subform"
	name="options"
	label="COM_DEMO_LOOK_OPTIONS_LABEL"
	layout="joomla.form.field.subform.repeatable-table"
	multiple="true"
	buttons="add,remove,move"
	icon="list"
	max="50">
	<form hidden="true" name="list_options_modal" repeat="true">
		<!-- Subject Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject"
			label="COM_DEMO_LOOK_SUBJECT_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
	</form>
</field>
<!-- Subject Field. Type: Subjects. (custom) -->
<field
	type="subjects"
	name="subject"
	label="COM_DEMO_LOOK_SUBJECT_LABEL"
	multiple="false"
/>
```
Then adding the same field multiple times to a subform and multiple times as a normal field to the same view.

This will cause the field name to change of course (to avoid data lose in the database), lets say the field name is `subject` and you add it more then once to a view, it will become `subject_one` & `subject_two`... Then if you add the same field to a subform in the same view, it will just again be `subject` in the subform, but if you also add it multiple times in the subform it will also become incremental with in the subfrom like this:
```xml
<!-- Options_one Field. Type: Subform. (joomla) -->
<field
	type="subform"
	name="options_one"
	label="COM_DEMO_LOOK_OPTIONS_ONE_LABEL"
	layout="joomla.form.field.subform.repeatable-table"
	multiple="true"
	buttons="add,remove,move"
	icon="list"
	max="50">
	<form hidden="true" name="list_options_one_modal" repeat="true">
		<!-- Subject_one Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_one"
			label="COM_DEMO_LOOK_SUBJECT_ONE_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
		<!-- Subject_two Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_two"
			label="COM_DEMO_LOOK_SUBJECT_TWO_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
		<!-- Subject_three Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_three"
			label="COM_DEMO_LOOK_SUBJECT_THREE_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
	</form>
</field>
<!-- Subject_one Field. Type: Subjects. (custom) -->
<field
	type="subjects"
	name="subject_one"
	label="COM_DEMO_LOOK_SUBJECT_ONE_LABEL"
	multiple="false"
/>
<!-- Options_two Field. Type: Subform. (joomla) -->
<field
	type="subform"
	name="options_two"
	label="COM_DEMO_LOOK_OPTIONS_TWO_LABEL"
	layout="joomla.form.field.subform.repeatable-table"
	multiple="true"
	buttons="add,remove,move"
	icon="list"
	max="50">
	<form hidden="true" name="list_options_two_modal" repeat="true">
		<!-- Subject_one Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_one"
			label="COM_DEMO_LOOK_SUBJECT_ONE_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
		<!-- Subject_two Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_two"
			label="COM_DEMO_LOOK_SUBJECT_TWO_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
		<!-- Subject_three Field. Type: Subjects. (custom) -->
		<field
			type="subjects"
			name="subject_three"
			label="COM_DEMO_LOOK_SUBJECT_THREE_LABEL"
			multiple="false"
			required="false"
			button="false"
		/>
	</form>
</field>
<!-- Subject_two Field. Type: Subjects. (custom) -->
<field
	type="subjects"
	name="subject_two"
	label="COM_DEMO_LOOK_SUBJECT_TWO_LABEL"
	multiple="false"
/>
```
As you can see in all these ways the type remains the same as `subjects`, and in my test it created the new custom-custom field type called `subjects` and it update it correctly as expected.

So let me know how it turned out on your side :+1:

**Comment by AlexDings** [comment]
Great! This final update fixed it for me and I believe it is all working as is expected.
Amazing work!

**Comment by ro-ot** [comment]
This is a stunning new feature, I have also tested it and it works amazing. Great work @Llewellynvdm :octocat:
