### ISSUE TITLE
Feature Request: Select mysql table engine.

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#345]
This feature request is to be able to select the engine for table creation when creating new Admin View. Currently it is only MyISAM. The benefit will be to create INNODB which will be better for some tables when the website is under heavy usage. The main difference is that MyISAM locks the whole table to insert or update a record. INNODB locks just the line in question. That can significantly decrease the load time for sites with a lot of content built with JCB.

**Comment by Llewellynvdm** [comment]
Okay in the admin view under the mySql tab there are three new select options, to tweak the table, give it a try and let me know it you run into any trouble.

This was a big changes, and I have tried my best to have it work in all shapes and sizes out of the box... hope that will be the case.

**Comment by peterpetrov** [comment]
It works perfectly. Thank you very much for that.

**Comment by Llewellynvdm** [comment]
Tell me @peterpetrov why would this error occur as @mwweb described in gh-348

> 
> JInstaller: :Install: Error SQL Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
> Extension Update: SQL error processing query: DB function failed with error number 1118
> Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
> SQL =
> ALTER TABLE #__componentbuilder_joomla_component ENGINE = InnoDB;

I think it is a local limitation, could I be wrong...

**Comment by peterpetrov** [comment]
That has to be local one. I will comment on the issue itself.

**Comment by Llewellynvdm** [comment]
Yes I did move the whole of JCB to InnoDB, that is the issue...

The file that does this is [2.9.5.sql](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/sql/updates/mysql/2.9.5.sql)
