### ISSUE TITLE
Members Manager 2.0.0 - Editing the Member - Upload Profile Image

### ISSUE THREAD

**Issue by joejvggithub** [vdm-io/Joomla-Component-Builder#347]
### Steps to reproduce the issue
Edit a Member
Click selecingt the file from your computer link
Select the file and click the Open button on Windows File Manager

### Expected result
File is uploaded and thumbnail displays

### Actual result
Alert message displays - There has been an error.
Staying on same page and uploading same image again produces no error alert message but no image is uploaded. If another image is displayed it displays same error message but second time does not and so on.

### System information (as much as possible)
- Windows: 7
- MySql: 5.7.2.1 
- Apache Version: 2.4.33
- PHP Version: 7.1.16
- Joomla Version: 3.8.12
- JCB Version: 
- Browser: Chrome  69.0.3497.100 (Official Build) (64-bit)

### Additional comments
Great Component! - Thanks
![logo2](https://user-images.githubusercontent.com/602866/46080283-2c0e7900-c15f-11e8-9241-6362093a9a2c.jpg)

**Comment by joejvggithub** [comment]
Pardon me - first time. Wrong area.

**Comment by Llewellynvdm** [comment]
I have fixed some issue in the member manger surrounding the Image uploader... I will push the changes soon. No worries :)
