### ISSUE TITLE
DynamicGet | Main Source: Custom 

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#349]
### Steps to reproduce the issue
Make a new dynamiGet with main source as Custom.

In the CustomGet place the code:
```
$query
			->select($db->quoteName(
				array('singletraining.id','singletraining.trainingroom','singletraining.startdate','singletraining.enddate','singletraining.trainingname'),
				array('id','trainingroom','startdate','enddate','trainingname')))
			->from($db->quoteName('#__trainershub_singletraining', 'singletraining'))
			
			->select($db->quoteName(
				array('location.address','location.city','location.country','location.locationname','location.postalcode'),
				array('trainershub_location_address','trainershub_location_city','trainershub_location_country','trainershub_location_locationname','trainershub_location_postalcode')))
			->join('INNER', ($db->quoteName('#__trainershub_location', 'location')) . ' ON (' . $db->quoteName('singletraining.location') . ' = ' . $db->quoteName('location.id') . ')')

		
			->select($db->quoteName(
				array('customer.companyname'),
				array('trainershub_customer_companyname')))
			->join('INNER', ($db->quoteName('#__trainershub_customer', 'customer')) . ' ON (' . $db->quoteName('singletraining.customer') . ' = ' . $db->quoteName('customer.id') . ')')
		
			->where('singletraining.status != 3')
			->where('singletraining.private_training = 0')
			->where('singletraining.published = 1')
			->where('yearweek( singletraining.startdate ) = yearweek( curdate( ) )')
			->order('singletraining.startdate ASC');

		// return the query object
		return $query;
```
Compile the code and see in the modell that the code is different:

```
protected function getListQuery()
	{
		// Get the current user for authorisation checks
		$this->user = JFactory::getUser();
		$this->userId = $this->user->get('id');
		$this->guest = $this->user->get('guest');
		$this->groups = $this->user->get('groups');
		$this->authorisedGroups = $this->user->getAuthorisedGroups();
		$this->levels = $this->user->getAuthorisedViewLevels();
		$this->app = JFactory::getApplication();
		$this->input = $this->app->input;
		$this->initSet = true; 
		// Get a db connection.
		$db = JFactory::getDbo();

		// Create a new query object.
		$query = $db->getQuery(true);

		// Get data
		$query
			->select($db->quoteName(
				array('singletraining.id','singletraining.trainingroom','singletraining.startdate','singletraining.enddate','singletraining.trainingname'),
				array('id','trainingroom','startdate','enddate','trainingname')))
			->from($db->quoteName('#__trainershub_singletraining', 'singletraining'))
			
			->select($db->quoteName(
				array('location.address','location.city','location.country','location.locationname','location.postalcode'),
				array('trainershub_location_address','trainershub_location_city','trainershub_location_country','trainershub_location_locationname','trainershub_location_postalcode')))
			->join('INNER', ($db->quoteName('#__trainershub_location', 'location')) . ' ON (' . $db->quoteName('singletraining.location') . ' = ' . $db->quoteName('location.id') . ')')

		
			->select($db->quoteName(
				array('customer.companyname'),
				array('trainershub_customer_companyname')))
			->join('INNER', ($db->quoteName('#__trainershub_customer', 'customer')) . ' ON (' . $db->quoteName('singletraining.customer') . ' = ' . $db->quoteName('customer.id') . ')')
		
			->where('singletraining.status != 3')
			->where('singletraining.private_training = 0')
			->where('singletraining.published = 1')
			->where('yearweek( singletraining.startdate ) = yearweek( curdate( ) )')
			->order('singletraining.startdate ASC');

		// return the query object
		return $query;

		// Get from #__trainershub_location as b
		$query->select($db->quoteName(
			array('b.address','b.city','b.country','b.locationname','b.postalcode'),
			array('trainershub_location_address','trainershub_location_city','trainershub_location_country','trainershub_location_locationname','trainershub_location_postalcode')));
		$query->join('INNER', ($db->quoteName('#__trainershub_location', 'b')) . ' ON (' . $db->quoteName('a.location') . ' = ' . $db->quoteName('b.id') . ')');

		// Get from #__trainershub_customer as c
		$query->select($db->quoteName(
			array('c.companyname'),
			array('trainershub_customer_companyname')));
		$query->join('INNER', ($db->quoteName('#__trainershub_customer', 'c')) . ' ON (' . $db->quoteName('a.customer') . ' = ' . $db->quoteName('c.id') . ')');
		// Get where a.status is 3
		$query->where('a.status != 3');
		// Get where a.private_training is 0
		$query->where('a.private_training = 0');
		// Get where a.published is 1
		$query->where('a.published = 1');
		$query->order('a.startdate ASC');

		// return the query object
		return $query;
	}
```
After the first return $query; you see a snapshop of the joine tables. This is not nessesay. 

Why using custom?

1. I like to use instead of a. or b. or c. the tablename singletraining. or location. or custom. This makes the code in serveal month late readable.
2. I'm usinging the SQL statement YEARWEAK it where. I can't add this in the normal DynamicGet. I see it in the tweaktab, but it's not used in the code (also a bug)?

### Expected result
Normal code with one query.

### Actual result
The correct query and serveal extra join tables.

### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.5.5-10.1.36-MariaDB-1~xenial 
- Apache Version: 
- PHP Version: 7.1.22
- Joomla Version: Joomla! 3.8.12 Stable [ Amani ] 28-August-2018 14:00 GMT
- JCB Version: 2.9.1
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by Llewellynvdm** [comment]
It can be that you first tried to use the normal select and join options, and then chose to go with custom, if that is the case, then just clear the values out of the subfroms. You will need to select a view or table as main source and then you will be able to clear the other joined relationships out. 

I can see this should not happen, and I can try to fix this in the core, but for now that should be the work around.

Then the `return $query` is already added by JCB so you should not need to add it. This is what JCB adds by default:
```
// Create a new query object.
$query = $db->getQuery(true);

// Get data
(((your code will go here)))

// return the query object
return $query;
```
So in the dynamic get select `Backend-view` as main source:
![image](https://user-images.githubusercontent.com/5607939/46464200-1be14400-c7c6-11e8-867b-a5d539562055.png)

Then make sure all is empty...
> Under Tweak Tab
![image](https://user-images.githubusercontent.com/5607939/46464224-256aac00-c7c6-11e8-8727-90c2990f4f7f.png)

> Under The Join Tab
![image](https://user-images.githubusercontent.com/5607939/46464235-2c91ba00-c7c6-11e8-814f-e01a83fcec0a.png)

Then change the main source back to custom, and add your code in.
![image](https://user-images.githubusercontent.com/5607939/46464326-5d71ef00-c7c6-11e8-84a2-464016ede451.png)

This should remove the other unneeded joints.

**Comment by Llewellynvdm** [comment]
It can be that you first tried to use the normal select and join options, and then chose to go with custom, if that is the case, then just clear the values out of the subfroms. You will need to select a view or table as main source and then you will be able to clear the other joined relationships out. 

I can see this should not happen, and I can try to fix this in the core, but for now that should be the work around.

Then the `return $query` is already added by JCB so you should not need to add it. This is what JCB adds by default:
```
// Create a new query object.
$query = $db->getQuery(true);

// Get data
(((your code will go here)))

// return the query object
return $query;
```
So in the dynamic get select `Backend-view` as main source:
![image](https://user-images.githubusercontent.com/5607939/46464200-1be14400-c7c6-11e8-867b-a5d539562055.png)

Then make sure all is empty...
> Under Tweak Tab
![image](https://user-images.githubusercontent.com/5607939/46464224-256aac00-c7c6-11e8-8727-90c2990f4f7f.png)

> Under The Join Tab
![image](https://user-images.githubusercontent.com/5607939/46464235-2c91ba00-c7c6-11e8-814f-e01a83fcec0a.png)

Then change the main source back to custom, and add your code in.
![image](https://user-images.githubusercontent.com/5607939/46464326-5d71ef00-c7c6-11e8-84a2-464016ede451.png)

This should remove the other unneeded joints.

**Comment by Llewellynvdm** [comment]
I will need to make a few changes to make that work... lets see.. in the compiler the work is done to work out the query on many lines. But the once that take care on the where statement are from [line  2103](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L2103) in the interpretation file.

We could change this a little, if you like to play around with it and make a suggestion you are welcome. The values used in this method are build from [line 3160](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L3160) in the get file. I have just tweaked a fix to that to avoid the loading of those hidden values if custom code is selected, so that is done :+1: 

The dynamicGet has much room for improvements, but has worked for everything I have used it for... so when I need to have it do more, I add more behavior... this is sort of how it has grown into what it is today. So if you have features, behavior that it can't reach... play around with the code, and let me know. I will of course also test things on my side, to insure what it already builds does not break down.

**Comment by Schrijvers123** [comment]
Thanks for the explanation. I will play arrounf with it and see if $query->concanate can be added

```
// Get a db connection.
		$db = JFactory::getDbo();

		// Create a new query object.
		$query = $db->getQuery(true);
		$field1 = "DATE_FORMAT( a.startdate, '%d %b %Y %H:%i' )";
		$field2 = "DATE_FORMAT( a.enddate, ' - %H:%i | ' )";

		$query
				->select($db->quoteName(array('a.id'), array('id')))
				->select($query->concatenate(array($field1, $field2, 'a.trainingname')).'as start_end')
				->from($db->quoteName('#__trainershub_singletraining', 'a'))
				->where('a.status != 3')
				->where('a.published = 1')
				->where('yearweek( a.startdate ) = yearweek( curdate( ) )')
				->order('a.startdate ASC');

		return $query
```

Above is just an example I'm goign to use (basic version of cource). I know this could be achieve also by combining string in php, but it;s in this case more secure todo it inside mySQL. 

Do you already have a solution for this or do I need to use custom?

**Comment by Llewellynvdm** [comment]
For now custom code will be your best answer, but it should not be that hard to adjust JCB to handle it. I have just not have the time right now... so all I did for now is add the catch to prevent the the hidden values from being added when custom code is selected.

**Comment by Llewellynvdm** [comment]
If you have had time to play with it, and think you have an answer to adjust JCB, you can open a new Issue (as a feature request), or just comment here :+1:
