### ISSUE TITLE
Add Foo Table dynamic not functioning

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#354]
### Steps to reproduce the issue

Create a component.
In the component | Livs & Helpers make sure that 'Add FooTable is set to Dynamic.

### Expected result

FooTable should be added automatically if needed

### Actual result

FooTable not added
Getting js errors that footable function not available
No directory created in media area (and no files present) for footable

### System information (as much as possible)
- OS Name & Version:  WAMP 3.1.0 64-bit
- MySql Version:  5.7.19
- Apache Version: 2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.12
- JCB Version: 2.9.7
- Browser: chrome/any

### Additional comments

Setting the Add FooTable to 'Add FooTable V2' solves issue.

I've only had this happen on one component, so not sure if there is some other issue that might cause this to not be dynamically added.
Wondering if anyone else is having this issue also to confirm that this isn't just an isolated issue.

**Comment by Llewellynvdm** [comment]
When footable it set to dynamic, then that means if the footable is selected in a site view, then it will be added dynamically per/site view.

So in that site view add the footable as a selected library and let me know if it still does not load.
![image](https://user-images.githubusercontent.com/5607939/48153793-c66dea80-e2cf-11e8-9098-c7345595b4de.png)

**Comment by cpaschen** [comment]
Thanks. I didn't realize that it needed to be added there.
Adding the FooTable v2 to the site view solved the issue.
So this was a user error (documentation need) not a but.
I'm closing this now as resolved.

**Comment by Llewellynvdm** [comment]
Chris, you are right... we need better documentation. I am working on ideas to resolve that, or at least set the stage :)

**Comment by cpaschen** [comment]
I've been collecting some documentation here locally of my own for JCB; however, I'm still trying to learn and most of the docs that I have aren't really all that helpful. (Also, work has gotten so busy that iI hardly have time for anything else right now). As soon as I get through a few of these projects I'm hoping to go back through some of the videos and document what you have included there and contribute them back.
