### ISSUE TITLE
Using custom files (or folder) is not working when custom files is a view layout

### ISSUE THREAD

**Issue by fred-the-coder** [vdm-io/Joomla-Component-Builder#355]
### Steps to reproduce the issue
Copy your custom file into JCB custom folder.
In your Joomla component define this file as custom file. _It is a view layout file, thus to be copied into "views/View Name/tmpl" folder of your component._
Choose as target path a path like "admin/views/_view name_/tmpl"
Build your component.

### Expected result
The file to be included into "admin/views/_view name_/tmp" within the zip installation package

### Actual result
A warning is raised at compilation time "Error copying file ...".
And the file is not in the package.

### System information (as much as possible)
- OS Name & Version: Win10
- PHP Version: 7.1
- Joomla Version: 3.8.12
- JCB Version: 2.9.0
- Browser: Firefox

### Additional comments
I found the root cause of this issue: the custom files (and folders) are managed as static content at compilation time. 
The static files are build before the dynamic files.
Thus in my case, cutsom file is a view layout, the target directory does not exist as created by dynamic component build.
As a workaround I switched the calls to $this->setDynamique() and $this->setStatic() by calling $this->setDynamique() first.
These calls are located in file "b_Structure.php" in the constructor of the class Structure:

```
public function __construct($config = array())
{
	// first we run the perent constructor
	if (parent::__construct($config))
	{
		// run global updater
		ComponentbuilderHelper::runGlobalUpdater();

               //code removed here for readability

		/* call removed 
               // set all static folders and files
		if (!$this->setStatic())
		{
			return false;
		}*/
		// set all the dynamic folders and files
		if (!$this->setDynamique())
		{
			return false;
		}
		// set all static folders and files
		if (!$this->setStatic())
		{
		    return false;
		}
		return true;
	}
	return false;
}
```

Maybe there is another way to define a view layout...?

**Comment by Llewellynvdm** [comment]
Yea we have looked at [this before](https://github.com/vdm-io/Joomla-Component-Builder/issues/336#issuecomment-420217733), we can't move static build believe me that will cause major breakdown.... and to many bugs. I did add a fix at the time, let me just dig in a little more and I will get back to you.

**Comment by Llewellynvdm** [comment]
This was the [fix](https://github.com/vdm-io/Joomla-Component-Builder/commit/7fcc93aa5b29188c098ba72ae60ba46a22e90b21) back then... and it has [been merged](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/b_Structure.php#L846) so I will need to take a closer look.

**Comment by fred-the-coder** [comment]
OK,
The [fix ](https://github.com/vdm-io/Joomla-Component-Builder/commit/7fcc93aa5b29188c098ba72ae60ba46a22e90b21) looks good.
But integrated in 2.9.1 whereas I am running 2.9.0..
Thus I need to update or to quick fix my local install...
Thank you

**Comment by fred-the-coder** [comment]
I tested the fix. The point is that the layout files are well copied, but we are missing the index.html file.
I eared they (fake index.html) are not mandatory anymore for security. Thus this is maybe not a big deal.

I guess we are missing the index.html file because it is copied/generated at "dynamic content" generation step where one generates it if folder does not exist...which is in my case already existing...my 2 cents...!

**Comment by Llewellynvdm** [comment]
Okay I missed the fact that you where still on 2.9.0.... that was it. So I assume all is well... I will close this and if you need any more help on this just comment here and I will respond.

Yes the index.html is a depreciated action, since it is not needed anymore...
