### ISSUE TITLE
Add Blob Data Type

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#360]
### Steps to reproduce the issue
Create new field. In the Database table, have another Data Type option of BLOB. Blobs are different than Long Text, and that field type would/could be beneficial for those that need it.

### Expected result
When creating a field, be able to select the data type as a blob.

### Actual result
Blob is not an option

### System information (as much as possible)
- OS Name & Version: 14.04.1-Ubuntu
- MySql Version:  5.5.5-10.1.34-MariaDB-1~trusty 
- Apache Version:  Apache/2.4.33 (Ubuntu) 
- PHP Version:  7.1.18-1+ubuntu14.04.1+deb.sury.org+1 
- Joomla Version: 3.9.1
- JCB Version: 2.9.8
- Browser: Firefox and Chrome

**Comment by Llewellynvdm** [comment]
Please try out the new blob option, and let us know how it works out.
