### ISSUE TITLE
Custom Code self reference check is off

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#365]
### Steps to reproduce the issue
Create a custom code with the name "printSomething"
Type [CUSTOMCODE=printSomethingHelper] inside as if you wanted to include that custom code inside "printSomething".

### Expected result
It saves, as there is no loop or self-reference.

### Actual result
It removes [CUSTOMCODE=printSomethingHelper] and gives the following warning:
~~~~
Warning
Placeholder Removed!
This custom code can only be used in other custom code, not in it self! Since that will cause a infinite loop in the compiler.
~~~~

### Additional comments
In my testing, this happens when the first part of the custom code name matches. For example with printSomethingHelper being included in printSomething.

**Comment by Llewellynvdm** [comment]
Please test the staging branch to see if the fix really resolved the issue for you.
