### ISSUE TITLE
default.php front-end view weird chars breaking dreamweaver

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#368]
### Steps to reproduce the issue
compile component and then view default.php from my talent site-view in an editor.

### Expected result
View complete file without weird chars.

### Actual result
Dreamweaver: code view ends when weird chars start.
BBEdit: weird chars visible in page.

### System information (as much as possible)
- OS Name & Version: Centos 7
- MySql Version: MariaDB 10.1.26
- Apache Version: 2.4.35
- PHP Version: 7.1.23
- Joomla Version: 3.9.2
- JCB Version: 2.9.8
- Browser: N/A

### Additional comments

Weird chars: J5J5ÄÏ10≈ÚXK5K5Z!K5
default.php from installed component viewing in BBEdit showing weird chars.
![default php from installed component viewing in bbedit](https://user-images.githubusercontent.com/4402824/51629868-f92b9480-1f48-11e9-95f0-9281e3f0ce37.png)
default.php from installed component viewing in Dreamweaver CC 2018 ending file.
![default php from installed component viewing in dreamweaver cc 2019](https://user-images.githubusercontent.com/4402824/51629878-fcbf1b80-1f48-11e9-9feb-e6bde510df2b.png)
VIEW PHP CODE copied from JCB site-view tab into BBEDIT. Not showing any weird chars.
![view php copied from jcb site-view tab into bbedit](https://user-images.githubusercontent.com/4402824/51629882-ffba0c00-1f48-11e9-9954-dc19101632a2.png)

**Comment by TLWebdesign** [comment]
That was what i was thinking but copying the code back out of JCB and into BBEdit it doesn't show. Only after compile it shows this. BTW view is showing just fine. no problem in the browser on the page. I deleted all white spaces after the closing </p> and have the <?php for start immediately after it. Then it shows weird stuff like this:
`<p><strong>Werkzaamheden</strong></p><ul><?php ∞P5

**Comment by TLWebdesign** [comment]
Also copying the code from JCB into the default.php and saving it again doesn't copy the weird stuff with it.

**Comment by TLWebdesign** [comment]
i removed the code of the first for loop. Because the second one was working fine. And it still showing weird chars. Just different ones. 

Then i added this before the <?php because that was still showing fine. 
![schermafbeelding 2019-01-23 om 20 25 53](https://user-images.githubusercontent.com/4402824/51631483-211cf700-1f4d-11e9-829e-e8d70f070a05.png)

Well it now broke before the comment. see screens.
![schermafbeelding 2019-01-23 om 20 26 40](https://user-images.githubusercontent.com/4402824/51631613-76f19f00-1f4d-11e9-900b-faaa05a5459a.png)

Reversing the base64 doesn't show anything weird in the code.

**Comment by TLWebdesign** [comment]
Ok this gets weirder and weirder. Removing the entire col-xs-12 div that was wrapping where the issue was happening the problem just shifts from line 407 to 411.

When i open the default.php i get an UTF-8 file is damaged or incorrectly formed error. Let me try and open it on the server see if the stuff is in there also. Otherwhise maybe my FTP client is at fault.

**Comment by TLWebdesign** [comment]
Hmm viewing the file from directadmin file manager doesn't show the weird stuff. So i guess it is a problem downloading it with FileZilla then? Never had it happen before. Happens since yesterday. 

Also only with this specific file it happens. No other files have this issue. Well thought i just open a ticket just to make sure it's not related to JCB.

**Comment by TLWebdesign** [comment]
Another funny thing. When i download it first. It gets corrupted i guess is the right word.
I then copy the correct code back in and upload.
I then download it again and it is showing just fine. lol.

**Comment by TLWebdesign** [comment]
Well i guess just close it since seems to be some weird stuff happening on my side. Sorry for bothering!

**Comment by Llewellynvdm** [comment]
No worries,  I know we are high up in the stack and so let me know if you see any weird things.

**Comment by TLWebdesign** [comment]
just to be complete on the info. I fixed the issue by telling Filezilla to download the file in binary mode.
