### ISSUE TITLE
Row size too large (> 8126)

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#369]
### Steps to reproduce the issue
Import of the JCB package of Joomla Member Manager

### Expected result
That all data just import

### Actual result
We get the following error:
```
Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline. 
```

### System information (as much as possible)
https://hub.docker.com/r/bitnami/joomla/

### Additional comments
Issue was mentioned on the [JCB forum](https://groups.google.com/a/vdm.io/forum/#!topic/jcb/eFXqITxNFoU)

**Comment by Llewellynvdm** [comment]
Hmm I can confirm when I install JCB v2.9.8 and then check the ROW_FORMAT it is set to be Compact. This seems to be the default for the InnoDB engine (in some environments), as when I change the tables to MyISAM in JCB (and compile and install) then as MyISAM, then they are by default Dynamic (in some environments).

Okay so this does seem like the issue (**ROW_FORMAT**)

We can add this to the admin views just like we did with the engine selection. These are the options I have in mind. https://dev.mysql.com/doc/refman/5.5/en/innodb-row-format.html

I am just wondering if the **file formats**, also needs attention?

**Comment by TLWebdesign** [comment]
From what i read on the interwebs is that setting it to dynamic should fix the issue. Also on our own google group it is given as the fix for another similar issue.

**Comment by Llewellynvdm** [comment]
There is not install.sql in the members manager package. The update to JCB is enough to resolve the issue, as I have tested it a few times with the [bitnami stack deployment](https://hub.docker.com/r/bitnami/joomla) of Joomla in a docker environment.

What I did is I install JCB v2.9.8 on the Bitnami Joomla website, then I used [this link](https://github.com/vdm-io/Joomla-Component-Builder/archive/staging.zip) to update it, en then the same old JMM package on gihub, and that package of 48 component and it all just worked, where it did not before, now it does.

You will see in v2.9.9 we have added an [sql update script](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/sql/updates/mysql/2.9.8.sql) to update all the tables, you should confirm that the tables indeed were updated.

Running that script manually should also work as a fix. Reality is we must convert all the tables to a DYNAMIC row_format, and that script does just that.

There is a way to see all the data being imported from the any JCB package, and that would be to do a dump [on line 620](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L620):
```
var_dump($this->data); jexit();
```
You will see all values are moved as a huge json object. and then dynamic imported to resolve all ID conflicts and merge all existing values. This is not small install.sql trick, it is a very complex, yet stable smart and intelligent import process.

**Comment by Llewellynvdm** [comment]
O yes and all new installs of JCB will start with the tables set as [DYNAMIC row_format](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/sql/install.mysql.utf8.sql#L136).

[This page](https://dev.mysql.com/doc/refman/5.7/en/innodb-row-format.html#innodb-row-format-detrmining) gives you a few pointer on how to check that a table is indeed now using the DYNAMIC row_format.

**Comment by Llewellynvdm** [comment]
I for local development use mostly docker, it just take care of so many issue for you if you use the right packages.

I have found Bitnami to be the most trustworthy and over all stable solution, and would mostly run their deployment scripts for the various project, including Joomla. A very nice tool that I found to manage the docker images, and see all the activities with a quick overview is https://portainer.io/

Then I also have a few custom setups, but for testing stuff I prefer if we all would use the same base, and at this point that base is https://hub.docker.com/r/bitnami/joomla (docker also runs on Windows)

The deployment commands are all in a docker file, and work very well. They setup the database and connects it to the Joomla install. You can tweak the docker file to use other passwords and stuff, and with just a few changes, this is also the scripts the AWS uses to deploy real live production environment for Joomla on there more affordable [light sail packages](https://aws.amazon.com/lightsail/). This is what I mostly use for small to medium size projects. So setting up a local development environment that match your production is perfect.

**Comment by TLWebdesign** [comment]
Ok yeah it did not change the row_format to dynamic. See screen of phpmyadmin. BTW working on a live domain i use for developing. It's on my own VPS.

**Comment by TLWebdesign** [comment]
Altering them manually in phpmyadmin give this error;
 
```
[Warning: #1478 InnoDB: ROW_FORMAT=DYNAMIC requires innodb_file_format > Antelope.
Warning: #1478 InnoDB: assuming ROW_FORMAT=COMPACT. ]
```
Which is weird because the documentation says that it needs barracuda instead of antelope. On Mariadb 10.1. Seems to be an issue with my configuration so i guess no further actions needed because it didn't set my tables correctly because of this. Or the script you talk about should be able to set the innodb_file_format too. But that could corrupt things from what i read so i'm not up to that on my live server. If i want to check the members package i'll just use a offline version for now i guess. 

https://mariadb.com/kb/en/library/xtradbinnodb-file-format/

**Comment by Llewellynvdm** [comment]
That may be why the JCB update did not update them. It seems like you will have to ask your hosting provider to look into this, as this is a wrong system setting. Well anyway I can be wrong, but asking them to take a look will help I am sure.

**Comment by TLWebdesign** [comment]
I'm my own Hosting provider 😄 Installation is just standard directadmin so will ask on their forums. It's definitely related to this it not being updated. No worries. Will look into it and make the necessary adjustments to my server but not at the moment because having it break down is not something i look forward too in these busy times. hihi Thanks for the support

**Comment by fred-the-coder** [comment]
@TLWebdesign I have the same issue on my local environment when trying to import one of my JCB package.
Using InnoDB engine.
How can I solve the issue by forcing row_format to Dynamic, instead of Compact?
Do I have to update MySQL install?

Thank you.

**Comment by fred-the-coder** [comment]
I reached to solve my issue by updating row_format of JCB tables.

I run this SQL statement first: SET GLOBAL innodb_file_format=Barracuda;
Then I run the "optimize" routing on all JCB tables which updated those tables and set the row_format to the one expected at creation, i.e. "DYNAMIC".

Then I was able to import my JCB component correctly!

**Comment by TLWebdesign** [comment]
Thanks for this @fred-the-coder !
