### ISSUE TITLE
Nested subforms get duplicates

### ISSUE THREAD

**Issue by AlexDings** [vdm-io/Joomla-Component-Builder#372]
### Steps to reproduce the issue

**Case 1**
1. Have a nested subform, add/open the nested subforms
![eventbugs1](https://user-images.githubusercontent.com/12542207/52168930-c9db0b80-2730-11e9-8e93-a9e816b1661d.PNG)
2. Press save
3. Result
![eventbugs2](https://user-images.githubusercontent.com/12542207/52168929-c9db0b80-2730-11e9-8799-0c695af572b5.PNG)

**Case 2**
1. Have a nested subform, add/open the nested subforms
![eventbugs3](https://user-images.githubusercontent.com/12542207/52168928-c9db0b80-2730-11e9-9e3e-89e8a6e6ac13.PNG)

2. Press save
3. Result 1
![eventbugs4](https://user-images.githubusercontent.com/12542207/52168927-c9db0b80-2730-11e9-8d3b-11099686344d.PNG)

4. Then remove this empty row that was added
![eventbugs3](https://user-images.githubusercontent.com/12542207/52168928-c9db0b80-2730-11e9-9e3e-89e8a6e6ac13.PNG)

5. Press save, the row isn't added again.
![eventbugs3](https://user-images.githubusercontent.com/12542207/52168928-c9db0b80-2730-11e9-9e3e-89e8a6e6ac13.PNG)

### Expected result
The saved result is the same as the input

### Actual result
Empty rows get added when the subforms aren't expanded

**Comment by Llewellynvdm** [comment]
First lets try this, remove manually from your model the lines that look like this, `join_db_table` being the subform field name.
```
// Set the join_db_table items to data.
if (isset($data['join_db_table']) && is_array($data['join_db_table']))
{
	$join_db_table = new JRegistry;
	$join_db_table->loadArray($data['join_db_table']);
	$data['join_db_table'] = (string) $join_db_table;
}
elseif (!isset($data['join_db_table']))
{
	// Set the empty join_db_table to data
	$data['join_db_table'] = '';
}
```

**Comment by Llewellynvdm** [comment]
Since that is all JCB is adding as house cleaning on that field when saving it. It may be that Joomla has moved on and this is no longer needed. So remove that line and save the view and lest see what happens.

**Comment by AlexDings** [comment]
Well, I removed it and the field didn't get saved at all.
I added it back and the issue is gone... aka, it works as expected

**Comment by Llewellynvdm** [comment]
No worries, let me know if the problem comes up again, for now we assume that it is resolved :+1: 

You can close the issue once you also are sure it is resolved.
