### ISSUE TITLE
SQL Type - Multi-select?

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#374]
So I've built a lists view and a users view. I want to add an SQL field to the Users view to select the assigned Lists. But for some reason we only allow single selection from sql field type? any reason as to why?

**Comment by peterpetrov** [comment]
Hey Tony, you need to use the Custom field type. It works exactly the same as the sql type but there you can extend what exactly sql to use and to choose to extend not just list but also checkboxes or radio buttons. The option for multi-select is available as well.

**Comment by tonypartridge** [comment]
Ahh so that's basically the sql-extended type. Great thanks!
