### ISSUE TITLE
Bug / Feature: Replacing and Inserting at the top/bottom of the document

### ISSUE THREAD

**Issue by TheWhykiki** [vdm-io/Joomla-Component-Builder#377]
### Steps to reproduce the issue

Try to add a replace statement at the start and the end of your code. In my example I tried to add a replace statement in my frontend view to have the ability to change everything between these lines.

### Expected result

The possibilty to change everything between the replace statements.

### Actual result

When adding some lines and compiling then, the replace statement doesn't stay in place, it moves to the next direction where blank spaces are, because the blanks are in the hash maybe....

You can see a video about this issue here:

http://downloads.whykiki.rocks/vdm/LlewelynCode.mp4

### System information (as much as possible)

- OS Name & Version: Windows 10
- MySql Version:  5.6..34
- Apache Version: dont know, the one in MAMP Pro
- PHP Version: 7.1.7
- Joomla Version: 3.9.2
- JCB Version:  2.9.11
- Browser: Google Chrome Version 72.0.3626.96 

### Additional comments

Hint written by Llewellyn:

> okay after much more testing, I think what is happening here is easy to resolve if you keep the following in mind. The ending hash  of the replacing code is a blank space (since it is at the end of the page), so if the code being replaced has blank spaces, it will at the first blank space have a positive match, and stop the replacement (and continue printing the JCB code the remains). I am thinking to fix this would require little change to the final insertion/replacement function.

**Comment by Llewellynvdm** [comment]
The function/method that adds the code back based on the ending hash is found on [line 492](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler.php#L492) in the main compiler file. I am going to try and [enhance this to detect end of file](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler.php#L511) behavior.

Give me a few days to dig into this again.

**Comment by Llewellynvdm** [comment]
Turns out there was an easier fix that I could just add to [line 5521](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L5521). I know this fix is not air-tight but it should work as the value of an empty line when md5'ed is `d41d8cd98f00b204e9800998ecf8427e` and if the line number is only one it is almost always end of the page. SO I am using those two values to detect end of page replace ending, to avoid mismatching the ending target hash.
