### ISSUE TITLE
JCB doesn't compile "products.js"

### ISSUE THREAD

**Issue by oriolun** [vdm-io/Joomla-Component-Builder#380]
### Steps to reproduce the issue

1. Add some js code in "Add JavaScript (views-file) *" section
2. Compile.
3. Install.

### Expected result

Generated js-file

### Actual result

None

### System information (as much as possible)
- OS Name & Version: Win10
- MySql Version: 5.6
- Apache Version: 
- PHP Version: 7.2
- Joomla Version: latest
- JCB Version: latest
- Browser: FF

### Additional comments

If i'm using other sections like `Add JavaScript (views-footer) *` or `Add JavaScript (view-file) *`, it works well, but not for the list view.

**Comment by Llewellynvdm** [comment]
Sorry for the delay on this, I have just not had time to check this out yet. Hope to do so soon...

**Comment by Llewellynvdm** [comment]
Please test and let me know if the issue is resolved on your end.
