### ISSUE TITLE
Add get[[component]]EditRoute

### ISSUE THREAD

**Issue by tonypartridge** [vdm-io/Joomla-Component-Builder#381]
We have get list and get item helpers, we should add an getedititemroute helper

**Comment by Llewellynvdm** [comment]
Can you add some code for this?

**Comment by Llewellynvdm** [comment]
Hi Tony, I am not as bright as some think. I am just a code-carpenter actually... lol

So if you can help me with some code on this I will be happy to add it in and see what you are hinting towards, until then I am going to close this issue. Please feel free to comment on it even if it is closed, if I notice real movement I will bump it open and take the needed action :+1:
