### ISSUE TITLE
Category select of Field Edit Form has no '- Select Category -' option

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#384]
### Steps to reproduce the issue
Make sure there is at least one Field Category
Open an existing field which is not assigned to any category.

### Expected result
The Category select show a '- Select Category -' option, since the field was not assigned to any category yet.

### Actual result
The name of the only or first created Field Category.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.11
- Browser: FireFox

### Additional comments
It is not possible to modify and save the field, without assigning it to a category.

**Comment by Llewellynvdm** [comment]
I am thinking this is a Joomla limitation, and nothing to do with JCB... help me if I am wrong.

**Comment by pjdevries** [comment]
It is not a Joomla! limitation. You can add one or more `<option>` items to the `catid` field. Or any (or most) from `list` extended fields for that matter. In this specific case, this would do the trick 
```
<field
	type="category"
	name="catid"
	label="COM_COMPONENTBUILDER_FIELD_CATID_LABEL"
	extension="com_componentbuilder.fields"
	default=""
	description="COM_COMPONENTBUILDER_FIELD_CATID_DESCRIPTION"
	class="inputbox"
>
	<option value="0">- Select Category -</option>
</field>
```
In fact it would be quite useful to have the `option` property, which is available for type `List` fields, available  in the JCB Field editor for other `list` extending fields as well :)

**Comment by Llewellynvdm** [comment]
Yes but what you are not seeing is the JCB does not build the category behavior, it just tells Joomla it is a category field, and then Joomla builds the behavior. This means that based on the XML properties of the category field Joomla builds the actual dropdown selection, not JCB.

If you see a property that is not in JCB, that can be passed to Joomla in the XML, then the category field type can be improved directly in JCB, if this is not enough then let me know where your being blocked and then I can see if I can change that.

The code used to build the category field (type) is pure Joomla based, and not JCB generated. JCB just builds the xml really ;)

If you want to go beyond and improve the Joomla implementation, take a look at the tutorials of expanding the custom fields.

**Comment by Llewellynvdm** [comment]
Here are those tutorials:
[JCB Custom Fields Type Extended](https://www.youtube.com/watch?v=91iIAuHZj38&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=74&t=0s)
[Expand Custom Field Type beyond the default](https://www.youtube.com/watch?v=Mu9H0zgH9Lw&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=76&t=0s)

**Comment by pjdevries** [comment]
But in the end it's JCB who generate the xml file, isn't it? So JCB could add that additional `<option>`  tag, even if Joomla! doesn't.

I tried it by adding the `option` property to the Category field, but apparently JCB ignores it. If I manually add it to the Sermon Distributor category field in the sermon.xml file, it shows up nicely. 

I also spent more than half an hour to locate the code where the model forms are generated, but haven't been able to find it :(

**Comment by Llewellynvdm** [comment]
The form are multiple classes all working towards the final form->field build. There is not just one class being used, it is a network of classes coming together in a very powerful and advance way.

I don't have the time to guide you in the right direction in understanding Joomla API at this moment, but the form main [class is found here](https://github.com/joomla/joomla-cms/blob/3.9.3/libraries/src/Form/Form.php).

Yes JCB builds the xml, and yes we could add the options, but it does not at this time do so for the category field-type (since it is not the normal implementation in the [Joomla core](https://github.com/joomla/joomla-cms/blob/3.9.3/administrator/components/com_content/models/forms/filter_articles.xml#L22)). I would for now point you to building your own custom field based of the [category fieldtype](https://github.com/joomla/joomla-cms/blob/3.9.3/libraries/legacy/form/field/category.php) where you can fully dictate the behavior exactly as you would like it.

So for now I am closing this issue as I don't think we will be adding any code here, at least not for Joomla 3. There is a lot happening to prep for Joomla 4, which I hope will in fact bring more liberty to the whole approach. Thank you for your understanding!

**Comment by ro-ot** [comment]
@Llewellynvdm the options is not that hard, and categories does has that feature in the core class looking at [line 103](https://github.com/joomla/joomla-cms/blob/3.9.3/libraries/legacy/form/field/category.php#L103). I will push some changes to the compiler to allow categories to add options like the list type field, if that is okay with you.

**Comment by Llewellynvdm** [comment]
Oops my bad, I missed that line. Hey I can always use the help, thanks!

**Comment by ro-ot** [comment]
Looks like we just need to move category in to the [correct group](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L2546) in the `$fieldGroups`.

Taking it out of **plain** and adding it to **option**, then also adding the option property to the category type. I have not tested it, @pjdevries could you test this?

**Comment by pjdevries** [comment]
That appears to work. I moved category field to **option** and now my manually added option property works like a charm :)

**Comment by Llewellynvdm** [comment]
Just again proof that being to close to the code is not always helpful, thanks for that step back @ro-ot reminding me of the modular approach we took. Man the the solution could be that simple.... lol. 

I will push this change up, and then have more test it to see if we have some other unforeseen issues.

**Comment by pjdevries** [comment]
Feels good to finally having been able to contribute something :)

Essentially this option should work for all field types that inherit from the basic `list` type.
