### ISSUE TITLE
JCB compiler produces erratic PHP code in function getItem()

### ISSUE THREAD

**Issue by outsch** [vdm-io/Joomla-Component-Builder#386]
### Steps to reproduce the issue
1. Create two admin views which have a parent-child relation as described in the tutorial videos using a custom field that pulls the entries of the parent table into the list choice on the child table
2. Compile component
3. Launch parent list admin view
4. Click on one entry to edit and see child records in related view

### Expected result
Related child admin view entries are shown

### Actual result
A php error is thrown: `syntax error, unexpected ';', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'` caused in my case at line 99 of the produced php code of the single parent php model code (in my case englishlookup.php) within the function getitem() as shown in below code:
```
64	/**
65	 * Method to get a single record.
66	 *
67	 * @param   integer  $pk  The id of the primary key.
68	 *
69	 * @return  mixed  Object on success, false on failure.
70	 *
71	 * @since   1.6
72	 */
73	public function getItem($pk = null)
74	{
75		if ($item = parent::getItem($pk))
76		{
77			if (!empty($item->params) && !is_array($item->params))
78			{
79				// Convert the params field to an array.
80				$registry = new Registry;
81				$registry->loadString($item->params);
82				$item->params = $registry->toArray();
83			}
84
85			if (!empty($item->metadata))
86			{
87				// Convert the metadata field to an array.
88				$registry = new Registry;
89				$registry->loadString($item->metadata);
90				$item->metadata = $registry->toArray();
91			}
92			
93			if (!empty($item->id))
94			{
95				$item->tags = new JHelperTags;
96				$item->tags->getTagIds($item->id, 'com_boagle.englishlookup');
97			}
98		}
99		$this->vvvv = $item->;
100
101		return $item;
102	}
```
However commenting out or deleting this line makes the error message disappear, however the resulting displayed view is showing only the fields `published` and `id`, so the intended functionality does not work as well.

### System information (as much as possible)
- OS Name & Version: Linux 816f1f72c9bf 4.2.8 in docker container
- MySql Version: 5.5.57-MariaDB
- Apache Version: Apache/2.4.25 (Debian)
- PHP Version: 7.2.14
- Joomla Version: 3.9.3
- JCB Version: 2.9.11
- Browser: Chrome

### Additional comments
I have set up other custom fields that work properly, but have not yet managed to build any successful parent-child admin view setup. So the behaviour might as well be due to a misconfiguration on my side, but just the produced php code does not work.
What I conceptually don't understand yet is that when I have two linked views, I don't even want to select the parent item when adding new child entries but they should rather be automatically inherited from the parent ID, and the list which is shown after having deleted the erratic code line comprises the entire child list (>2000) and ot the four child entries (same text in four different languages) that I would expect.

**Comment by Llewellynvdm** [comment]
You have some relationship not setup correctly. This is the reality, but what it is I can't say, to do so I will need to see the component. So there are two ways to do that, one is with screen shots of the admin tabs, or the areas you understand as related to this issue.

The second option is to give me the JCB package of this component. You will have to choose what direction you would like to go, all I can say for now is this is due to a wrong relationship setting.

**Comment by Llewellynvdm** [comment]
If I don't get any feedback on this I will close the issue.
