### ISSUE TITLE
Custom field ignores escape option

### ISSUE THREAD

**Issue by oriolun** [vdm-io/Joomla-Component-Builder#387]
### Steps to reproduce the issue

Create custom field for admin view.
Change escape setting to false.
Compile component.

### Expected result

`$item->custom_field;` in "default_body" admin template file for list view.

### Actual result

`$this->escape($item->custom_field);`

### System information (as much as possible)
- OS Name & Version: Debian 9
- MySql Version: 
- Apache Version: 
- PHP Version: 7.2
- Joomla Version: latest
- JCB Version: latest
- Browser:

**Comment by Llewellynvdm** [comment]
Okay lets follow this in the compiler:

The class array to track these fields are first set in c_Fields.php on [line 68](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L64) and is called `$doNotEscape` from this we search to see all its use.

So in c_Fields.php on [line 2409](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L2409) we see the criteria for a field to be added to this `$doNotEscape` class array. We see it simple checks if there is a `escape` value in the xml of the field and if true, that it is a string, the it gets added to the class array. So at this point, you can add a `var_dump` and poke at some of the values if the view name and field name is found, to see if it is actually being added to the class array `$this->doNotEscape`.

Once it is loaded to the array the next place to look is in e_Interpretation.php on [lines 6785 ](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6785) and [line 8254](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L8254) where we check if the view has any `doNotEscape` values set.

Next we look in the loop of fields being build, and find a function that builds each field called `$this->getListItemBuilder()` and then `$this->getListItem()` and then `$this->getListItemCode()` which then bring us to [line 7063](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L7063) and on [line 7074](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L7074) the logic plays out to when the escape feature is or is not used.

I can see when there is a few reasons that the may not happen, but mostly very reasonable. So take a look and let me know where it breaks down for you and why. We take it from there :+1:

**Comment by Llewellynvdm** [comment]
If I don't get any feedback on this I will close this issue.

**Comment by oriolun** [comment]
> 
> 
> If I don't get any feedback on this I will close this issue.

Don't have much time now to check it. Solved temp. by making custom template file.

**Comment by Llewellynvdm** [comment]
Hmmm okay, well I can't debug stuff I can't see. So if you don't give me feedback based on the flow of the code explained above, then I cant help you resolve this. If you have time, and are willing to take another look just comment on this issue even if it closed.

**Comment by oriolun** [comment]
Hi!

Checked your instructions. The array $this->doNotEscape doesn't contain escaped field name, but escape option is set to false in a field settings section. Maybe because this field is custom and connected to the #__categories table. Have no idea.
