### ISSUE TITLE
Compiler - error in model code with select all fields and linked view

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#390]
### Steps to reproduce the issue

- Createa dynamic get and set 'Select All' to 'Yes' to select all fields (Selection: a.*).
- Create a parent Admin View with a child Linked View (one to many). I also have a tab for the Linked View in the 'Tab Setup', but I don't know if that's needed.
- Add parent and child views to component.
- Check 'Edit/Create Site Views' for both views.
- Compile component.

### Expected result
In the model's getItem() method (towards the end of the try block):

 ```
// set id[[[parent]]]_id[[[child]]]B to the $data object.
$data->id[[[parent]]]_id[[[child]]]B = $this->getIdMap_idHotspotCcda_B($data->id);
```

### Actual result

```
// set id[[[parent]]]_id[[[child]]]B to the $data object.
    	$data->id[[[parent]]]_id[[[child]]]B = $this->getIdMap_idHotspotCcda_B($data->id
a.asset_id);
```

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.13
- Browser: FireFox

### Additional comments
Obviously this syntax error triggers a runtime exception.

**Comment by Llewellynvdm** [comment]
Please give screenshot of each area, like dynamicGet and well, every part that builds up the code behavior. Since I think this is just a wrong setting some where. But will need to look and see if I can spot it.

**Comment by pjdevries** [comment]
Won't it be easier if I send you the JCB package?

**Comment by Llewellynvdm** [comment]
If you are willing sure.

**Comment by Llewellynvdm** [comment]
If you are willing sure.

**Comment by pjdevries** [comment]
I took the liberty of sending you the package using the VDM website contact form. Hope you don't mind.

The package contains a working version of the work in progress. To reproduce the problem, the 'Select All' of dynamic get 'Map with Hotspots' should be set to 'Yes'.

**Comment by Llewellynvdm** [comment]
Okay I have it, I will take a look and get back to you.

**Comment by Llewellynvdm** [comment]
Sorry for the delay... will get to this only next weekend, at the soonest.

**Comment by pjdevries** [comment]
Apologies appreciated but definitely not necessary :) Take your time.

**Comment by Llewellynvdm** [comment]
Wow... sorry @pjdevries this issue was dropped by me. I will try and get to this today!

**Comment by Llewellynvdm** [comment]
Okay I just imported your package and compiled
![image](https://user-images.githubusercontent.com/5607939/56847500-e88a1200-68db-11e9-8433-02484f351012.png)

Then I looked in the modal (map.php) and it all looks correct to me:
![image](https://user-images.githubusercontent.com/5607939/56847548-9e556080-68dc-11e9-81bd-f4c7cd5d1dee.png)

Please let me know in what site view you are having this trouble, and again sorry about this delay, due to personal reasons I was not able to give full attention to my work for the last 5 weeks.

**Comment by pjdevries** [comment]
Hey Llewell. Once again, apologies are not necessary :) The work you have done and still do is appreciated. If this was a critical issue, I would have reminded you myself :) But thank you for taking it up never the less,

**Comment by pjdevries** [comment]
Our comments crossed :D I have been having personal (health) problems my self lately, so my attention to this issue has not been 100% either. I will try to take a look at it next week and get back to you. 

I am also considering attending a JCB workshop by Marco Dings and René Kreijveld on the Dutch Joomla! days next month, on May 16th & 17th (you're welcome to join :). Maybe we can take at look at it there.

**Comment by Llewellynvdm** [comment]
Okay that sounds good... yet we have the issue open here and I am able to give some attention towards it. So take your time and let me know where I should look :+1: once your are able.

For sure a great idea to join Marco and René at Dutch Joomla! days next month, they have a great workshop lined up!

**Comment by Llewellynvdm** [comment]
I just imported and compiled the new package you send me, and again the linked area compiles as expected.
![image](https://user-images.githubusercontent.com/5607939/57287993-ed5b7c80-70b8-11e9-836d-72138bff4b74.png)

![image](https://user-images.githubusercontent.com/5607939/57288084-23006580-70b9-11e9-8190-ef8d6154b3f3.png)

Please direct me to the file, and line that you think is not correct.
