### ISSUE TITLE
List field type lacks property 'useglobal'

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#391]
### Steps to reproduce the issue
Create a new field type `List`

### Expected result
Property `useglobal` in the list of properties.

### Actual result
No such property.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.13
- Browser: FireFox

### Additional comments
I realize that one can add additional properties to existing field types, which is what I did. But since it's a core Joomla! field type property, it might be nice to add it to JCB :)

**Comment by Llewellynvdm** [comment]
So you basically want to add `useglobal` property to the list field type in the JCB default values?

**Comment by pjdevries** [comment]
Yes, that's in short what I propose :)
