### ISSUE TITLE
URL field type lacks property 'relative'

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#392]
### Steps to reproduce the issue
Create a new field type `URL`

### Expected result
Property `relative` in the list of properties.

### Actual result
No such property.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.13
- Browser: FireFox

### Additional comments
I realize that one can add additional properties to existing field types, which is what I did. But since it's a core Joomla! field type property, it might be nice to add it to JCB :)

**Comment by Llewellynvdm** [comment]
Same here you basically want to add the property `relative` to the JCB url field type.

**Comment by pjdevries** [comment]
Indeed :)

I hope to get my local development setup such that I can start making pull requests for small modifications like this. But to be honest, although I'm a professional software develeoper and been so for mire than 30 years, I have been working by myself on rather small projects mostly. So I don't have experience with these kind of projects, Github and pull requests. Apart from that I am not used to working with the, in my opinion somewhat weird, site/admin folder structure when developing Joomla! extensions. So I'm struggling with coming to grips with that as well.

Anyway, I hope you don't mind me reporting all those, mostly minor issues. They are not intended to be annoying but meant to improve JCB. It's up to you what you think is important enough and want to do with them. I'm grateful for being allowed to use JCB, no matter what.

**Comment by Llewellynvdm** [comment]
Hey I don't mind :+1: keep them rolling. I may just fall behind at times, but we will get there.
