### ISSUE TITLE
Categories stored with unwanted target view appended to the extension name

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#394]
I added a Category Field to an Admin view, specifying the `extension` without a target view. The Admin view displays the category menu item, so I can add categories. However, the view, in which I use the Category Field, does not show the added categories.

On closer inspection, I see that the added categories are stored in the database _with_ the target view appended to the extension name, but I did not specify that in the Field definition. This is reflected  by the `<field>` definition in the generated xml file, which does not specifiy the target view either.

I attached some screenshots illustrating what I described.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
![Screenshot Editing the Field](https://user-images.githubusercontent.com/1171835/54055221-a9e5ae80-41ec-11e9-9e9f-cf56d4e0b26b.png)
![Screenshot phpMyadmin](https://user-images.githubusercontent.com/1171835/54055230-ae11cc00-41ec-11e9-9ece-14f4dede440d.jpg)
![Screenshot template xml](https://user-images.githubusercontent.com/1171835/54055233-b0742600-41ec-11e9-883c-c6c87f29c71b.jpg)

- JCB Version: JCB 2.9.13 **Beta 2019-03-06**
- Browser: FireFox

**Comment by Llewellynvdm** [comment]
Please add the views name to the xml (field properties), that is how Joomla knows what categories you are looking for.

Far as I know your categories can only be per/view and not per/component. If this has changed please share the documentation... then I will see what should be done to fix this. But from what I remember categories are linked to views.

**Comment by pjdevries** [comment]
It does work when appending the view name. But that is not my point. My point is that I think it is not necessary. Just the component name suffices. I am still trying to find concrete evidence, but here is why I think it is the case:

- The description of JCB's `category` field type itself. It says you _must_ enter the name of the extension and that you _can_ also target a view. Apparently you, or whoever wrote that description, also thought the view name appendix is optional.
- There is the description of Joomla's [Category form field type](https://docs.joomla.org/Category_form_field_type). There is no mention of the view name being mandatory for the `extension` attribute of the field.
- The [Adding categories](https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_categories/en) chapter of Joomla's [Developing an MVC Component](https://docs.joomla.org/J3.x:Developing_an_MVC_Component) only mentions the component name and not a mandatory view name.
- Looking at the entries in table `#__categories`, none of the core Joomla components have a view name attached. 

So although not being real evidence, these bits and pieces of information strongly lead to believe that a view name appendix is not mandatory. 

Does this make sense?

Regards,
Pieter-Jan

**Comment by Llewellynvdm** [comment]
Yes I wrote that... :smile: like 4 years ago.

Okay and it does make sense, I am just wondering where is JCB involved in messing it up. I am not using the category field that much, and when I do, I always link it to a view. So let me experiment with this a little and get back to you.

**Comment by pjdevries** [comment]
Yeah, time flies when you're having fun :D

Does help if I spend some time on this so you can spend it on other important stuff? You can always pick it up again if I'm not able to find it.

**Comment by pdward** [comment]
I suspect the problem is the url parameters in the admin area linkbar/submenu 
\administrator\components\com_joomplate\helpers\joomplate.php

In function addSubmenu the category link is added with the admin view as well as the component, this is then stored in the com_categories table
JHtmlSidebar::addEntry ................ index.php?option=com_categories&view=categories&extension=com_joomplate.templates

If you remove the '.templates' you can then add categories linked to the main component only and they will show up in the category field as expected

**Comment by Llewellynvdm** [comment]
I have added a fix to the staging branch, please test and let me know if the is not resolved.
