### ISSUE TITLE
Joomla! core category field type is buggy but no clean way to remedy that in JCB

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#395]
The Joomla! core `category` field type is buggy. The `show_root` setting is not evaluated by the `FormField::setup()` method, resulting in Root always showing up in the select list. 

I realize this is not a JCB issue. Unfortunately there seems to be no way to overcome this:

- Joomla! core has an alternative: the `categoryedit` field type. Unfortunately it's a com_categories field, so it can not be used out of the box in JCB.
- It is not possible to create a JCB Custom Field because it extends FormField as well and would therefore suffers from the same omission as the `category` field type. Also, because a Custom Field only allows to implement the `getOptions()` method, it's not possible to override the `FormField::setup()` method to fix that omission.
- I tried to use Custom code replacements in the form xml file, but apparently they are not parsed there. So it's not possible to add the `categoryedit` field in that manner.
- I tried to use a copy of the `categoryedit` field using the JCB Libraries feature, but apparently those libraries only apply to Site Views.

Hopefully you have a suggestion how to solve this. But I think the real solution lies in the possibility to add real custom fields to JCB. In such a way that the the custom field's PHP file is copied to the model's fields folder and the `addpath` is added to the xml files using the field.

**Comment by Llewellynvdm** [comment]
Well you can do a custom field type and overwrite any function/method.

Watch these tutorials:
https://www.youtube.com/watch?v=n5RBmP0uNCM&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=75&t=0s
https://www.youtube.com/watch?v=Mu9H0zgH9Lw&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=76&t=0s

**Comment by TLWebdesign** [comment]
i had a problem when first setting up category field also. But leaving the show_root empty will not display the root. Setting it to false doesn't do the trick tho.

**Comment by pjdevries** [comment]
Thanks for the tip @TLWebdesign. And you are right. Leaving it empty does the trick. Looking at the `category` field code again, I now see that `show_root` is not checked for its value, but merely if it's set with `isset()`. I dont't understand that I missed that.

I apparently also missed the tutorials Llewell mentions. Possibly because I mostly check the WIki and not the Tutorials. So even though there is an acceptable solution for the issue, I'going to watch those video's no because I want to be able to create custom fields all the way :)

**Comment by pjdevries** [comment]
I found an easier way for my specific issue. Using the 'Component files folders' option of the Component settings, I can copy the `categoryedit` field to my component's models/fields folder. Now it's only a matter of configuring the field in JCB's Fieldtypes.
