### ISSUE TITLE
Import Data button run custom code

### ISSUE THREAD

**Issue by VinylVault** [vdm-io/Joomla-Component-Builder#397]
Hi Llewellyn & Team JCB

I want to use the custom import button to pull info from an external site, using their API, I've written the code to do it, in PHP (ive got the whole application done in PHP).  Can you please point me at either docs or give me some assistance with linking to the database table and fields.

Thanks
Dex :)

**Comment by peterpetrov** [comment]
Hey Viny, have you checked out the outstanding videos made by the project owner? If you haven't please visit the Wiki or check out here:

https://www.youtube.com/watch?v=1KBBtQUxMTc&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE

Peter

**Comment by Llewellynvdm** [comment]
Okay... hmmm let see. Can you open this issue on the forum and then we can try and give you some support there. We want to keep the gitHub issue are very much JCB exclusive code related. I will delete this (few moments from now).

But please open the same request on the [forum](https://groups.google.com/a/vdm.io/forum/#!forum/jcb) and I will jump in and see how I can help you there.

**Comment by Llewellynvdm** [comment]
@peterpetrov  thaks for you quick response here!

**Comment by peterpetrov** [comment]
Just trying to do my part to the project! Cheers!

**Comment by VinylVault** [comment]
(moved to forum)

@peterpetrov i have look at the YT content, very helpful, but consusing for me
