### ISSUE TITLE
Checkout field default value set to 0

### ISSUE THREAD

**Issue by Peeripapo** [vdm-io/Joomla-Component-Builder#40]
When compiler creates the tables it would be nice for the automatically created fields to have default values. That would allow easier database manipulation.

Unlike created_by and modified_by  the checked_out field doesn't have a default value. Is it possible to set this to 0 ?

**Comment by Peeripapo** [comment]
I think this would be possible by changing line 4859 in file "e_interpretation.php" from : 

	$db .= PHP_EOL."\t`checked_out` INT(11) NOT NULL,";
to
	$db .= PHP_EOL."\t`checked_out` INT(11) NOT NULL DEFAULT '0',";

Also, for consistency we could change the params field too (line 4829)  from:

	$db .= PHP_EOL."\t`params` TEXT NOT NULL,";
to
	$db .= PHP_EOL."\t`params` TEXT NOT NULL DEFAULT '',";

**Comment by Llewellynvdm** [comment]
Hi, I am not sure I understand... component builder does have the correct default values for the DB on those fields mentioned. 

But yes there is a way to update those default fields (in [this tutorial](https://youtu.be/FHQfIhWHYyQ) I called **How to overwrite the custom fields** explain how this is done). I can also add those changes to the core... I will use the [Joomla banner table as a guideline ](https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L199)

**Comment by Peeripapo** [comment]
Yes, I'm suggesting changing the core and the defaults I suggested are the same as the #__categories table instead of the #__banners table. 

In your comment you said you'd use banner table as guide but you linked to the categories table.

Please use the categories table as guideline as it sets default values to all fields.

Hope I helped :)

**Comment by Llewellynvdm** [comment]
Sure... that is great.
