### ISSUE TITLE
Add PHP (getListQuery - JModelList) diff pos in dynamic get

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#407]
Hi,

Add PHP (getListQuery - JModelList) in _**dynamic get**_ inserts the custom script in a different position respect to the same option in _**admin view / PHP**_.
While in admin view, with my custom script, I can access the whole query already set by JCB, in dynamic view I can't.

Sometimes we need to customize the query and, for example, in admin view I was able to refine the select('a.*') method adding a 'DISTINCT' mysql command, while in dynamic get I can't access the query as it is not jet populated by JCB. It's already set, but empty at this stage.

It should be possible to move the dynamic get injection to the same place of admin view?

**Comment by Llewellynvdm** [comment]
Okay, I hear you. Let me say the dynamicGet was my first try at building a query builder, and wow it is still not fully there. So there are two things I need to achieve here, one I need to continue to expand the features of the dynamicGet area to be able to eventually do everything that is possible, or needed. The second I need to allow devs the freedom to rule the code.

That all said, I can add those areas you are asking for... but why not also add the needed, or lacking feature you want to custom code.

**Comment by jcodewalker** [comment]
Well, I'm not able to say anything about other features to add as I'm still learning hot to use JCB but I think you already did an amazing work. Only, the dynamic get works a little bit different from the back end view. I suppose moving the injection from before the query building to after doesn't require a big effort and you can do it really quickly.
With this, you already achieve at least the freedom to rule the code and, I still suppose, the freedom to do everything (let's say manually). Great result, minimum effort.
Then, for the other features to add, there is Joomla v4 in the near feature... I would think about that in Jv4 mode, but really, you already did an amazing component. I have another hint but I'm going to open another thread.
