### ISSUE TITLE
Feature request: languages dropdown field included in publishing tab

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#412]
Hi Llewellyn,

What do you think to have an option to include (or not) the languages drop down list field in publishing tab?

With this option users can decide if include it or not in that tab.
I believe that 90% of components are multi-language nowadays.

**Comment by Llewellynvdm** [comment]
Please revert to already existing issues [Can we enhance function for multilanguage support ?](https://github.com/vdm-io/Joomla-Component-Builder/issues/171)
