### ISSUE TITLE
error listing items with a category field

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#413]
Using a category type field in an admin view, I get this error message:
error: 1146 Table '[DBNAME].#__ktchpro_catid' doesn't exist

ktchpro is the component name

the error is generated in the view's model, getItems method, by this loop:
		// set values to display correctly.
		if (KtchproHelper::checkArray($items))
		{
			foreach ($items as $nr => &$item)
			{
				// convert catid
				$item->catid = KtchproHelper::jsonToString($item->catid, ', ', 'catid');
			}
		}

I don't know where that 'catid' table comes from (and it is strange that a table contains the 'id' in the name), as the component has just this view (just 1 admin view, no site views). The categories work fine, I can add category, list them and all seems to work fine. Even the edit form works fine, the field loads the correct categories list and is saves the data, as I see the json string saved in the db into 'catid' field.

The error comes up when I try to list the view's items (not the category items, which works fine).

I've checked the category field definition and there is no trace of this 'catid'.

Need more info?
Thanks in advance.

**Comment by jcodewalker** [comment]
Just after received (let me say finally) the key to unlock the sample components, I went deep to investigate.
The error comes up when multiple selection category field is included in items list. As long as the multiple selection category field is not included in the list layout it works fine.
All the rest, category field itself, work fine both in component category and component view edit form.

**Comment by Llewellynvdm** [comment]
Yes this is indeed the case, you can only have one category field per/item. This is due to Joomla's own convention and limitations towards many of its classes. you can not pass two category ids, just one. Further more the category field must always be catid, and you can only have that name once per/item in the database.

So this is not a JCB limitation but a logic one based on Joomla's own conventions.
