### ISSUE TITLE
Crowdin error stopping save of updated component

### ISSUE THREAD

**Issue by alan123489** [vdm-io/Joomla-Component-Builder#416]
### Steps to reproduce the issue
Add an admin view to component
Click save

### Expected result
component saves with no errors

### Actual result
throws:
Invalid field:  Crowdin Project Identifier 
Invalid field:  Crowdin Project API (Key)(encrypted field) 
Invalid field:  Crowdin Username(encrypted field) 

I can't save the updated component.  Can't find how to turn off the error checking.

### System information (as much as possible)
OS Name & Version: Windows 10
MySql Version: 5.7
Apache Version:
PHP Version: 7.2
Joomla Version: 3.9.4
JCB Version: 2.9.18
Browser: CHrome

### Additional comments
I noticed that the latest release has links to Crowdin so I'm guessing that some field in my existing component is causing a problem.  This only happens with the latest version

I've reverted to 2.9.14 which works fine.

**Comment by Llewellynvdm** [comment]
Can you please try in another browser, or just clearing the current browser cache?

I am not able to duplicate the issue, so I suspect it is related to your browser memory.

**Comment by alan123489** [comment]
Hi 

I reinstalled and it seems to work.  I did try ctrl f5 yesterday when I got the error and it didn't work then?  I also wonder how those errors could come up at all since I don't use Crowdin or have any reference to it on my development machine.

Anyway it works now thanks.  If I can find a way of replicating it I'll let you know

**Comment by Llewellynvdm** [comment]
Crowdin is a new feature we are working on, as an integration with their translation platform. The fields that will work as the bases for this integration are found under the `Dynamic Integration` tab in your Joomla Component edit view. Changing the Translation tool field to Crowdin will give you the needed details. We should have this ready hopefully in the next release, I am working with Crowdin directly to insure we take the best possible approach to this, to insure JCB can easy scale any of its projects language reach.
