### ISSUE TITLE
Front end form view renders side modules outside of the component area

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#417]
### Steps to reproduce the issue

Create Admin form and add Front end view and Menu item to it when adding to the component. 
Add right side module - a menu module for example.
Apply proper permissions so you can open it and open the view.
I am using Helix Ultimate but exactly the same is tested on the Protostar template with the same result.

### Expected result

The view to be rendered properly as the screenshot:

![Screen Shot 2019-05-30 at 21 57 41](https://user-images.githubusercontent.com/2786810/58657302-a282fc80-8326-11e9-9184-f682985ed77e.png)

### Actual result

The right side module is outside the main container and it is "pushed out" to bottom.

 
![Screen Shot 2019-05-30 at 21 57 54](https://user-images.githubusercontent.com/2786810/58657321-af9feb80-8326-11e9-8571-b9a3724b5f11.png)
![Screen Shot 2019-05-30 at 21 57 30](https://user-images.githubusercontent.com/2786810/58657322-b0388200-8326-11e9-91e5-976e5f984f91.png)

### System information (as much as possible)
- OS Name & Version: CentOS
- MySql Version: MariaDB 10
- Apache Version: nginx 1.12
- PHP Version: 7.2
- Joomla Version: 3.9.6
- JCB Version: 2.9.18
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
This is due to the isis styles being added to the edit view. If you open the view.html.php file you will find a note how to fix this.

![image](https://user-images.githubusercontent.com/5607939/58660178-1d4b1800-8325-11e9-8b81-a881f670daf3.png)

If you know of a better way to set the styles for the edit view... let me know :+1:

**Comment by peterpetrov** [comment]
What about to reverse that idea? Set the ISIS to be false by default and add the radio button only if you need the template to load on front end? Also to add declaration to check if that is site view:

$app = JFactory::getApplication();
if ($app->isSite()) {
 if ($this->params->get('add_isis_template', 0)){
//Load ISIS css and js only if there is a button and is set to yes.
}
}

**Comment by peterpetrov** [comment]
Also i don't think it works. Tested that now with both Helix Ultimate and Protostar templates.

Screenshot of button in config:

![Screen Shot 2019-05-30 at 23 27 13](https://user-images.githubusercontent.com/2786810/58662293-871dee80-8332-11e9-8ce7-e54eb9e3366e.png)
![Screen Shot 2019-05-30 at 23 25 05](https://user-images.githubusercontent.com/2786810/58662294-87b68500-8332-11e9-90a4-cd2bfe7e45fa.png)

Screenshot of right side module:

![Screen Shot 2019-05-30 at 23 26 29](https://user-images.githubusercontent.com/2786810/58662308-8edd9300-8332-11e9-95cb-7e955038a121.png)

**Comment by marcodings** [comment]
administrator/components/com_componentbuilder/compiler/joomla_3/edit_site.php

There is a closing </div> to many in EDITBODY,
this breaks the protostar frontend layout when adding a record based on the admin edit view
dunno yet where/how this is, adding an opening div before is a quick fix

![image](https://user-images.githubusercontent.com/3484222/59105078-67d72080-8933-11e9-993c-505220e605f2.png)

**Comment by Llewellynvdm** [comment]
Okay I am trying to see where this is happening, you can help me look... in the compiler from [line 7665 in the interpretation](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L7665) class the div's are being added based on the layout of the view there is a number of outcomes. At this time all the layouts are already build and we are just building the `###EDITBODY###` text, it is being placed in the `$body` variable. :blush: I know the method is way over sized... and needs refactoring. But alas the same variables are being used over and over... so hmmm I just kept going.

I will refactor this area... and see what we get, it does seem like we have two div's to many being added around line [8019](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L8019)

**Comment by Llewellynvdm** [comment]
I think I found the issue, I have pushed an update (refactored the method) to the staging branch, please test and let me know.

**Comment by peterpetrov** [comment]
I have tested it on two different instances and can confirm it works as expected now. After installing the update the components in question have to be rebuild - that is just for these people that will try it. And the side modules in both Protostar and Helix Ultimate are showing properly.

**Comment by marcodings** [comment]
I'll be able to try this evening..
