### ISSUE TITLE
Feature request - On Before Cancel

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#418]
Can we add within the cancel controller a section to set some values? This is just before "return $cancel;".

**Comment by peterpetrov** [comment]
It seems to work but could we have that compiled over the front end controllers as well?

**Comment by peterpetrov** [comment]
Just to remind that the front end doesn't receive the new "cancel" sections. Could you please add that as well?

P.

**Comment by Llewellynvdm** [comment]
This has been done in [commit: 8acbb3b3a414f356e4dcb95958fdf75c0cedac16](https://github.com/vdm-io/Joomla-Component-Builder/commit/8acbb3b3a414f356e4dcb95958fdf75c0cedac16#diff-6c228d6e65603da9ffd3bdce679814acR180)

**Comment by peterpetrov** [comment]
Thanks. Let me test it.

**Comment by peterpetrov** [comment]
It works perfectly. Thank you very much!
