### ISSUE TITLE
Category filter in sidebar broken in staging (190607) since last stable release

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#419]
### Steps to reproduce the issue
Have a category for fields on JCB itself,
assign one or more fields to that/a category
Now attempt to filter the fieds list-view

### Expected result
Dropdown list for the category filter has the category

### Actual result
It does not.
( it worked in the last stable release)

### System information (as much as possible)
- JCB Version: staging as per june 7, 2019

### Additional comments
![image](https://user-images.githubusercontent.com/3484222/59105534-6a864580-8934-11e9-94ca-398e6fa4b1bf.png)

**Comment by Llewellynvdm** [comment]
Please also give me a screen shot of the category field attributes in JCB and the resulting xml produced by the compiler.

We mad some changes to the category filter recently and this could be part of the side effects.

**Comment by marcodings** [comment]
this is the component builder component itself ( NOT a bespoke component). As such you should easilly be able to see all you require?

**Comment by Llewellynvdm** [comment]
Okay here is the issue. We changed the convention from list view name to single view or edit view name and yet the JCB field category still use the list view so it has a mismatch. Should I fix it in the field properties then all your categories set will be lost and Joomla will act like you never build them, so the solution is to improve our filter builder for the category, as to detect the value set in the field properties and use that instead... so to insure that the convention is stable.

**Comment by Llewellynvdm** [comment]
Okay I think I fixed this issue... let me know. But I can see the need to refactor the whole category integration. There is the feature to link the category of one view to another view in JCB, and there is no documentation about this, and so I see a feature that is not used, and is part of why the category integration is so complex. Reality is all things considered it should work now, but needs more attention in the near future.
