### ISSUE TITLE
Save Component Site views error

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#420]
### Steps to reproduce the issue
Open a component in JCB -> click on Site Views -> Edit -> try to edit the site view and save.

### Expected result
Save normally.

### Actual result
Getting an error as the screenshot. Problem is it doesn't say what exactly is incorrect and no changes were made at all to the site views.

![Screen Shot 2019-06-10 at 23 36 01](https://user-images.githubusercontent.com/2786810/59225129-9d506800-8bd8-11e9-9d28-a194059ff3aa.png)

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: latest staging
- Browser:

**Comment by Llewellynvdm** [comment]
Okay I found the issue, we fixed the validation on the subforms and now there are a number of fields that are required that should not be... so I made the needed changes, it should now work as before.

**Comment by peterpetrov** [comment]
It works properly now. Thank you.
