### ISSUE TITLE
loss of admin editview formcontent

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#422]
### Steps to reproduce the issue
unknown...

### Actual result
This morning an admin edit view "stopped" showing content. Comparing the generated content (right) with the locally stored development copy. Shows that there is no content to the form.

![image](https://user-images.githubusercontent.com/3484222/59417384-75732700-8dc7-11e9-91a9-06c59d64ac90.png)

Other admin views and list views seem to work just fine. This "phenomenan" occurred after deleting a field from the admin view.

**Comment by peterpetrov** [comment]
Hey Marco, which version of JCB you are running?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marcodings** [comment]
i have switching between stable and staging (and they all show the same version
last try was on june 12th staging ( which has a bug in jcb configuration)

**Comment by Llewellynvdm** [comment]
We are no on v2.9.20 in the staging, but I must warn you not to use your main development environment to test out the staging branch. Two reasons, first you can not go back, as most beta versions on install removes fields from the database, and add new once, even removes files at times, and going back does not restore them. Second reason if you run into an issue with the beta/staging branch, you can't go back to stable/master since it will make things worse.

I do always run on the latest/beta version and so even JCB gets build with the latest/beta this is how I validate the staging branch is ready for release and so on my side it makes sense... but not on your side, as you can't do a quick fix in the compiler like I am able to. I have a far clear picture of what was changed and why, so if something does not build right... I can easy fix it. JCB in this way has it own build in build check :+1: like unit test... lol

I am as surprised as you at how good this is working out... I can so easy find out when things do not work.. due to this design.

**Comment by Llewellynvdm** [comment]
About your issue, I need more info as it does not fully add up.

**Comment by marcodings** [comment]
Additional information, the xml for the form is generated
`administrator/components/com_jcpqm/models/forms/question.xml`
the edit view
`administrator/components/com_jcpqm/views/question/tmpl/edit.php`

looks like
```html
<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
JHtml::_('formbehavior.chosen', 'select');
JHtml::_('behavior.keepalive');
$componentParams = $this->params; // will be removed just use $this->params instead
?>
<script type="text/javascript">
	// waiting spinner
	var outerDiv = jQuery('body');
	jQuery('<div id="loading"></div>')
		.css("background", "rgba(255, 255, 255, .8) url('components/com_jcpqm/assets/images/import.gif') 50% 15% no-repeat")
		.css("top", outerDiv.position().top - jQuery(window).scrollTop())
		.css("left", outerDiv.position().left - jQuery(window).scrollLeft())
		.css("width", outerDiv.width())
		.css("height", outerDiv.height())
		.css("position", "fixed")
		.css("opacity", "0.80")
		.css("-ms-filter", "progid:DXImageTransform.Microsoft.Alpha(Opacity = 80)")
		.css("filter", "alpha(opacity = 80)")
		.css("display", "none")
		.appendTo(outerDiv);
	jQuery('#loading').show();
	// when page is ready remove and show
	jQuery(window).load(function() {
		jQuery('#jcpqm_loader').fadeIn('fast');
		jQuery('#loading').hide();
	});
</script>
<div id="jcpqm_loader" style="display: none;">
<form action="<?php echo JRoute::_('index.php?option=com_jcpqm&layout=edit&id='. (int) $this->item->id . $this->referral); ?>" method="post" name="adminForm" id="adminForm" class="form-validate" enctype="multipart/form-data">

</form>
</div>
```
NOTHING in the form

**Comment by marcodings** [comment]
Additional information, the xml for the form is generated
`administrator/components/com_jcpqm/models/forms/question.xml`
the edit view
`administrator/components/com_jcpqm/views/question/tmpl/edit.php`

looks like
```html
<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
JHtml::_('formbehavior.chosen', 'select');
JHtml::_('behavior.keepalive');
$componentParams = $this->params; // will be removed just use $this->params instead
?>
<script type="text/javascript">
	// waiting spinner
	var outerDiv = jQuery('body');
	jQuery('<div id="loading"></div>')
		.css("background", "rgba(255, 255, 255, .8) url('components/com_jcpqm/assets/images/import.gif') 50% 15% no-repeat")
		.css("top", outerDiv.position().top - jQuery(window).scrollTop())
		.css("left", outerDiv.position().left - jQuery(window).scrollLeft())
		.css("width", outerDiv.width())
		.css("height", outerDiv.height())
		.css("position", "fixed")
		.css("opacity", "0.80")
		.css("-ms-filter", "progid:DXImageTransform.Microsoft.Alpha(Opacity = 80)")
		.css("filter", "alpha(opacity = 80)")
		.css("display", "none")
		.appendTo(outerDiv);
	jQuery('#loading').show();
	// when page is ready remove and show
	jQuery(window).load(function() {
		jQuery('#jcpqm_loader').fadeIn('fast');
		jQuery('#loading').hide();
	});
</script>
<div id="jcpqm_loader" style="display: none;">
<form action="<?php echo JRoute::_('index.php?option=com_jcpqm&layout=edit&id='. (int) $this->item->id . $this->referral); ?>" method="post" name="adminForm" id="adminForm" class="form-validate" enctype="multipart/form-data">

</form>
</div>
```
NOTHING in the form

**Comment by peterpetrov** [comment]
I want to add that i get that same thing happened to me as well. What i did is i have updated field type of a filed from Custom (sql query) to Radio and was updating values within few fields in the showon section. Trying to find additional information.

**Comment by marcodings** [comment]
Was my initial problem with the "question" adminview,
after `adding a field` to my "exam" adminview this too is now empty :(

Adding that field was the only structural change apart from adding code to "buttons" and such

This seems to be a more than a fluke, it has stop my component development for now :((

**Comment by Llewellynvdm** [comment]
I found the issue, Marco all the fields are in the publishing tab, instead of details, Just move them to the details tab and it should be resolved. Let me know.

**Comment by peterpetrov** [comment]
![Screen Shot 2019-06-17 at 21 31 02](https://user-images.githubusercontent.com/2786810/59627590-3fc39a80-9147-11e9-8dba-d4fd6a40dd2d.png)


I don't see Details tab.

**Comment by marcodings** [comment]
For both admin views the details tab was gone. There was only one, the publishing tab. Where alle the fields now defaulted to.

Adding the details tab, and reassinging the fields made the views reappear, Hurray!

the question that arrises would be `why` the details tab got deleted ( and no.. it was not me ;) )

**Comment by marcodings** [comment]
> 
> 
> ![Screen Shot 2019-06-17 at 21 31 02](https://user-images.githubusercontent.com/2786810/59627590-3fc39a80-9147-11e9-8dba-d4fd6a40dd2d.png)
> 
> I don't see Details tab.

Thats the "problem" it seems to be "magically" deleted (see above)

**Comment by Llewellynvdm** [comment]
Well at least we are on to it... I will try to find out why it gets dumped.

**Comment by peterpetrov** [comment]
Yep, that worked for me as well. Thanks @marcodings .

**Comment by Llewellynvdm** [comment]
Okay so the code that renders the tab names in the `subform` is found in the [custom field called `viewtabs` ](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/fields/viewtabs.php#L77) from line 77 it loads the tabs, and if none is found it loads only the Details as default, so since it loads only the Publish and not Details... is weird.

**Comment by Llewellynvdm** [comment]
Okay, I think this would fix it. if the issue come up again just comment on this issue :+1:

**Comment by marcodings** [comment]
FYI the not showing also caused the added field not to be added to the database, resulting in not saving its data. Just added it manually
