### ISSUE TITLE
Codemirror does not save css

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#423]
### Steps to reproduce the issue
Switch editor in JCB settings to "codemirror"

### Expected result
Have editing working with nice syntax highlighting

### Actual result
Editing and save works on PHP/JS fields in the admin view.
Editing works on CSS field, however save fails. ( when i switch back to "none editor" i can save and css file is created during compile

![image](https://user-images.githubusercontent.com/3484222/59417937-6e98e400-8dc8-11e9-9d4c-0f68670df475.png)

**Comment by Llewellynvdm** [comment]
This is an old issue, please revert [communication here](https://github.com/vdm-io/Joomla-Component-Builder/issues/353) :+1:
