### ISSUE TITLE
Use of "nowdoc' for readbility

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#425]
throughout the compiler we see code being "build" in the following way
```php
// reset script
$script = array();
$script[] = $this->_t(1) . "/**";
$script[] = $this->_t(1) . " * Method to set/copy dynamic folders into place (use with caution)";
$script[] = $this->_t(1) . " *";
$script[] = $this->_t(1) . " * @return void";
$script[] = $this->_t(1) . " */";
$script[] = $this->_t(1) . "protected function setDynamicF0ld3rs(\$app, \$parent)";
$script[] = $this->_t(1) . "{";
$script[] = $this->_t(2) . "//" . $this->setLine(__LINE__) . " get the instalation path";
$script[] = $this->_t(2) . "\$installer = \$parent->getParent();";
$script[] = $this->_t(2) . "\$installPath = \$installer->getPath('source');";
$script[] = $this->_t(2) . "//" . $this->setLine(__LINE__) . " get all the folders";
$script[] = $this->_t(2) . "\$folders = JFolder::folders(\$installPath);";
$script[] = $this->_t(2) . "//" . $this->setLine(__LINE__) . " check if we have folders we may want to copy";
$script[] = $this->_t(2) . "\$doNotCopy = array('media','admin','site'); // Joomla already deals with these";
$script[] = $this->_t(2) . "if (count(\$folders) > 1)";
$script[] = $this->_t(2) . "{";
$script[] = $this->_t(3) . "foreach (\$folders as \$folder)";
$script[] = $this->_t(3) . "{";
$script[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Only copy if not a standard folders";
$script[] = $this->_t(4) . "if (!in_array(\$folder, \$doNotCopy))";
$script[] = $this->_t(4) . "{";
$script[] = $this->_t(5) . "//" . $this->setLine(__LINE__) . " set the source path";
$script[] = $this->_t(5) . "\$src = \$installPath.'/'.\$folder;";
$script[] = $this->_t(5) . "//" . $this->setLine(__LINE__) . " set the destination path";
$script[] = $this->_t(5) . "\$dest = JPATH_ROOT.'/'.\$folder;";
$script[] = $this->_t(5) . "//" . $this->setLine(__LINE__) . " now try to copy the folder";
$script[] = $this->_t(5) . "if (!JFolder::copy(\$src, \$dest, '', true))";
$script[] = $this->_t(5) . "{";
$script[] = $this->_t(6) . "\$app->enqueueMessage('Could not copy '.\$folder.' folder into place, please make sure destination is writable!', 'error');";
$script[] = $this->_t(5) . "}";
$script[] = $this->_t(4) . "}";
$script[] = $this->_t(3) . "}";
$script[] = $this->_t(2) . "}";
$script[] = $this->_t(1) . "}";
// done

return PHP_EOL . PHP_EOL . implode(PHP_EOL, $script);

```

I propose to refactore and to make use of 
https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc
which would make the code much more readable, less error prone and less cpu expensive;

The above snipit would translate to the following equivalent `nowdoc` 
```php
$script=<<<'EOD'


	/**
	 * Method to set/copy dynamic folders into place (use with caution)
	 *
	 * @return void
	 */
	protected function setDynamicF0ld3rs($app, $parent)
	{
		// get the instalation path
		$installer   = $parent->getParent();
		$installPath = $installer->getPath('source');
		// get all the folders
		$folders = JFolder::folders($installPath);
		// check if we have folders we may want to copy
		$doNotCopy = array('media', 'admin', 'site'); // Joomla already deals with these
		if (count($folders) > 1)
		{
			foreach ($folders as $folder)
			{
				// Only copy if not a standard folders
				if (!in_array($folder, $doNotCopy))
				{
					// set the source path
					$src = $installPath . '/' . $folder;
					// set the destination path
					$dest = JPATH_ROOT . '/' . $folder;
					// now try to copy the folder
					if (!JFolder::copy($src, $dest, '', true))
					{
						$app->enqueueMessage('Could not copy ' . $folder . ' folder into place, please make sure destination is writable!', 'error');
					}
				}
			}
		}
	}
EOD;
return $script;
```

**Comment by Llewellynvdm** [comment]
This was a conscious choice, so we can control the tab space (this is a big deal which we are working towards), and be able to add in any kind of code snippets in between the code/string. See there is a mad house inside the tab space, and I moved that all to one function, which means soon we will be able to add the option to JCB to build the spaces/tabs based on your company speck, and not just based on the JCB default.

Reality is we are taking about thousands of lines of code here.... literally, I am not going to redo those :)

I actually have a little script to which I give the code (when I add them) and it builds that which you see. So believe me to change those is no small task.

But let me say this, soon all code will move out of the compiler into a component of its own. This will enable you to adapt even those code strings... little peak at what is coming with JCB v4

So I don't think we need to give attention to this at this time.

**Comment by marcodings** [comment]
I get it's a herculeum task and I just wanted to bring attention to an
alternative.

At least the tabbing is not an issue. Indentation is preserved. That is of
course if your ide is not messing things up.

We have bigger fish to fry,  so let's see for J4.

**Comment by Llewellynvdm** [comment]
Thanks... I do know about nowdoc, and the indentation is not easy as it looks. At this time you will see if you look at [$this->tabSpacer](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L718) we are using the default `\t` to get our tabs and not '	' this is by design. Since there are real differences between IDE's and operating systems when it comes to how the tab is build. Some use spaces, some use tabs and other break it up in... well weird stuff.

So I added the `_t` [method](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L840) to serve as a central point of control. This was in the early years of JCB and today it works with no issues.... so I really think it is best the way it is now, the alternative will bring with it a new set of hurdles that I have already crossed to arrive at what we have today. Since like I said it was a conscious choice, not to use `nowdoc` :+1: 

Yet I am grateful for you sharing, please keep them coming... I firmly believe the best of JCB is still to come.
