### ISSUE TITLE
Custom Field button behavior to add/edit

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#426]
When we add a field of type custom to an admin view, we have the option `botton` that allows creation of the refernced `view` in the specified `component` ( shown as `[1]`)

![image](https://user-images.githubusercontent.com/3484222/59502960-79727800-8e9f-11e9-930f-072cdb400db8.png)

Inspection of the code shows there is an option to edit a previously selected field ( shown as `[2]`,`[3]`.

However currently this only works if the `name` of the button equals the name of the view or views. This could be acceptable if you only have 1 custom field, it clashes if you have more.

going to the relevant `admin/models/fields/yourcustomname.php` we find 
```php
if (($buttonName === 'question' || $buttonName === 'questions') && $user->authorise('question.edit', 'com_jcpqm') && $app->isAdmin()) // TODO for now only in admin area.
```
question and questions are the view names

Removing the tests for the ButtonName
```
/***[REPLACED$$$$]***//*2*/
            // why would we test against question(s) here ??? ($buttonName === 'question' || $buttonName === 'questions')
 			if ( $user->authorise('question.edit', 'com_tmt') && $app->isAdmin())
            {
/***[/REPLACED$$$$]***/
```
seems to make the edit field behave as expected `[2]` and `[3]`
- `[2]` refences a table in our own component
- `[3]` refences a table in a different ( not our own component)

**Comment by Llewellynvdm** [comment]
The [last commit added this change](https://github.com/vdm-io/Joomla-Component-Builder/commit/2fb4a1ae4330333483e57d43a1c81a53fc78d2c0#diff-323c961a30280c4e8e3b6386453d3decR3167) so I trust this is resolved.
