### ISSUE TITLE
Field relations not working with custom field as target list field

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#428]
### Steps to reproduce the issue
Create custom field in admin view. try to make a field relation to add another field or just plain text to it. 

### Expected result
Field relation to view correctly.

### Actual result
Still displaying default field value. Only title of column gets changed.

### System information (as much as possible)
- PHP Version: 7.x
- Joomla Version: 3.9.8
- JCB Version: 2.9.18
- Browser: Latest Firefox

### Additional comments

Why i run into this problem and maybe i'm going at this all wrong.
I have a custom field dropdown list. in my php i added a user('name') in between quotes to the options text. This works fine in single edit view. But in list view this get's ignored. So i wanted to find a way to add this back again. I figured i just make a relation and ignore the 2nd field as it's not displayed anyway and add the query there. Or should i not be doing that at all and instead use custom code?

**Comment by Llewellynvdm** [comment]
Can you give some screen shots?

**Comment by TLWebdesign** [comment]
Yes here are some screenshots :) Let me know if you need more.

Relations Screen:
![relations-screen](https://user-images.githubusercontent.com/4402824/59675120-eb5f0000-91c4-11e9-8eff-bdb5b87f019d.png)

PHP Query Custom Field:
![php query custom field](https://user-images.githubusercontent.com/4402824/59675146-f6b22b80-91c4-11e9-9d73-7c596063e6fd.png)

Custom Field settings:
![customfield-settings](https://user-images.githubusercontent.com/4402824/59675177-09c4fb80-91c5-11e9-8078-76b3de792b9c.png)

Custom field dropdown from edit view:
![customfield-editview](https://user-images.githubusercontent.com/4402824/59675264-3842d680-91c5-11e9-8ad4-abaa0a3b77e9.png)

Here a small screencap from the column showing the changed name but field values are just plain DB field values. No edits.
![listview-customfield column](https://user-images.githubusercontent.com/4402824/59675339-5dcfe000-91c5-11e9-8ae6-8c55748629c6.png)

Model getItems:
![model-getitems](https://user-images.githubusercontent.com/4402824/59675412-822bbc80-91c5-11e9-8f0c-52fec874b52e.png)

Model getListQuery:
![model-getlistquery](https://user-images.githubusercontent.com/4402824/59675436-8ce65180-91c5-11e9-85d8-a37ffb599291.png)

HTML List View default_body.php
![listview-html](https://user-images.githubusercontent.com/4402824/59675446-91126f00-91c5-11e9-8499-2bfb90ddd922.png)

**Comment by Llewellynvdm** [comment]
Change the custom code to:
```php
$item->werkgeverid_bedrijfsnaam = $item->werkgeverid_bedrijfsnaam . 'Test, ' . $item->{1470};
```
And see if it works.

**Comment by TLWebdesign** [comment]
That worked great. Ok i now know where to find the correct code if it doesn't work out of the box (example code) :D Thanks a bunch!
