### ISSUE TITLE
Bug in Dynamic gets -> Where

### ISSUE THREAD

**Issue by oxido21** [vdm-io/Joomla-Component-Builder#433]
### Steps to reproduce the issue
Go to "Dynamic Gets", "Tweak" tab.
In the "Where" section, if you add a row and complete the row like this:
Table Key: a.id equal $this->id

### Expected result
The var $this-> to remain like so

### Actual result
The simbols $ and > it will be removed, so after saving, the var will look like "this-id".

### System information (as much as possible)
- OS Name & Version: Linux cloud
- MySql Version: 5.5.5-10.1.40-MariaDB
- Apache Version: 
- PHP Version: 7.1.30
- Joomla Version: 3.9.8
- JCB Version: 2.9.18
- Browser: All

### Additional comments
Screensot: https://i.imgur.com/ZpjVoKv.jpg

**Comment by Llewellynvdm** [comment]
You can test the staging branch and confirm that this is resolved, thanks for the heads-up. We fixed the validation and filter implementation on subforms... and now the fix is help us with some bugs :+1:

**Comment by oxido21** [comment]
Fixed!
Thank you for the quick response.
