### ISSUE TITLE
missing addTablePath in getModel helper

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#434]
the helpermethod `JcpqmHelper::getModel()` is missing the 
`JModelLegacy::addTablePath($path.'/tables');`
With this missing, the model of another component is instantiated but a call to ->getitem will cause a crash

**Comment by Llewellynvdm** [comment]
Problem here is that the $path can be site or admin path, yet the tables are always in the admin area of the JCB components.

So we will for the table path need a better solution.

The table path is via the config passed to `JModelLegacy::getInstance` in the `$config['table_path']` so you could ideally do this already with the` $config` function variable.

Look here at the [BaseDatabaseModel line 262](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Model/BaseDatabaseModel.php#L262)4 which is the JModelLegacy class.

**Comment by Llewellynvdm** [comment]
I made a easy work around... [check it out](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L5549) and let me know
