### ISSUE TITLE
Add Module Builder to JCB

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#437]
### Steps to reproduce the issue
I want to add the option to build modules related or linked to components in JCB

### Expected result
That you in JCB can map a fully functional module

### Actual result
Feature Request.

### Additional comments
It will be able to use dynamic gets and other JCB tools to model your module, and when compiling the component it will also compile the model and auto generate a combined package.

Should you have some ideas, please share them here!

**Comment by marcodings** [comment]
reuse opportunity https://github.com/joomla-extensions/boilerplate

**Comment by Llewellynvdm** [comment]
@mwweb We are looking at a subscription/donation concept for new cutting-edge add-ons to JCB in form of plugins.

The new Joomla privacy suite iteration, better action log iteration, and packaging will all be part of this.

I am thinking after a year these cutting edge plugins  will be made available for free to the community, but those who want early access will have to make a donation to JCB.

I am thinking we need some way to start funding the development, and this has been the best idea so far.

With regards to the packager idea... it will allow for external stuff to be added. But we are planning to improve the current library area in JCB to make difference between JS-HTML-CSS libs and PHP libs. So that you can in them map a library and have JCB package it for you like it does with the plugins, and soon to be added modules.

**Comment by Llewellynvdm** [comment]
> What i meant by library is a Joomla library that is installed as a library, and installed to the [root]/libraries folder.

Yes me too.
