### ISSUE TITLE
syntax error in dashboard view

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#438]
### Steps to reproduce the issue
I added the suggestion from the "dashboard methods" as comments to the field

![image](https://user-images.githubusercontent.com/3484222/60880779-9dc63800-a244-11e9-97a1-3c7224647332.png)

### Expected result

Nothing special, just a placeholder in the code to lookup the code

### Actual result

Syntax error

The comment caused 2 $this->get statements to be added, which is unexpected as they are comments

![image](https://user-images.githubusercontent.com/3484222/60880891-dcf48900-a244-11e9-9c4f-167677c05bf0.png)

The second of the 2 causes the syntax error

**Comment by Llewellynvdm** [comment]
This is how JCB know it should add the method to the view, so if you want to add it in a comment then You must use another convention, like lets say:
```
// use the [public function getMethodname(  )] to insure the data is set to the view
```
> note the two spaces in the method argument area, that breaks convention, and still reads correctly.

JCB does not work with live code... but just simple strings... which means we can't use the normal PHP way to pull code across, so for time and speed we just use [ComponentbuilderHelper::getAllBetween()](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L13302) to just get all methods that are public and starts with get and takes no arguments.

I dont think we will change that, we can maybe add some documentation... what do you think?

**Comment by marcodings** [comment]
Documenting it is fine. I just wanted to "flag" the issue as it took me by
surprise.

**Comment by Llewellynvdm** [comment]
![image](https://user-images.githubusercontent.com/5607939/61500678-9df4cf00-a9cc-11e9-9395-93ef14e54015.png)

![image](https://user-images.githubusercontent.com/5607939/61500692-ac42eb00-a9cc-11e9-913e-e5d022a84fbf.png)

This issue was resolved in the last release, let me know if you think more needs to be done.
