### ISSUE TITLE
folder create error at component compilation

### ISSUE THREAD

**Issue by waltraudharror** [vdm-io/Joomla-Component-Builder#439]
New JCB installation under windows 10 with Xamp keeps bringing warnings after compilation of the demo project without changes made.

I have checked the tmp and log settings at Joomla

These are the error messages:

Warning
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\site\views\look\tmpl
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\site\views\looks
Joomla\CMS\Filesystem\Folder::create: Could not create folder.Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\site\layouts\look
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Calculation\Token
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale\en\uk
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale\no
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale\pl
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\Escher\DgContainer\SpgrContainer
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\Escher\DgContainer
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\Escher\DggContainer\BstoreContainer\BSE
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\Escher\DggContainer
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\trend
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Worksheet\AutoFilter\Column
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Worksheet\Drawing
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\models
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\sql\updates\mysql
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\sql
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\look\tmpl
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\look
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\looks\tmpl
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\looks
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\media
JFolder: :delete: Path is not a folder. Path: C:\xampp\htdocs\joomie\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\site\assets\js

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
Please join the [chat on the forum](https://groups.google.com/a/vdm.io/forum/#!topic/jcb/1BYIhVE6B1k), and in the future read over the closed issues [[1]](https://github.com/vdm-io/Joomla-Component-Builder/issues/421) [[2]](https://github.com/vdm-io/Joomla-Component-Builder/issues/432) before opening a new one. 

I am closing this issue since there are other issue opened where you can continue to share your findings. Please we want to hear from you, just not a good idea to have many issue about the same problem.

Thanks.
