### ISSUE TITLE
Automatically increase field order in Admin View

### ISSUE THREAD

**Issue by Peeripapo** [vdm-io/Joomla-Component-Builder#44]
When editing the fields of an Admin View It would be great that if we want to add a field other than as the last item of a tab, that if we typed a number that already existed it would automatically add 1 to the order of the other fields after that one.

This would make managing edit Admin Views SO MUCH easier :)

**Comment by Llewellynvdm** [comment]
Same here :) if you write this up I will add it... seems little buggy but give it a go..

**Comment by ro-ot** [comment]
Why not just remove the whole ordering field and just use the order the fields are in the window. IT seems to be saved in order as see in the modal view.

**Comment by Llewellynvdm** [comment]
Well the idea was that you can change the order without having to remove and add the fields again... so if we could ad some JavaScript to help with the numbering it should be okay.

**Comment by Peeripapo** [comment]
We can do this, but I'll need some free time to work on it. Trying fix some stuff on dynamic import first.
