### ISSUE TITLE
Link a form module to a dynamic site

### ISSUE THREAD

**Issue by waltraudharror** [vdm-io/Joomla-Component-Builder#449]
In Joomla it is possible to choose on which page you want a module to be shown.,

In a JCB component I can choose a module to be shown on the main page. But is it possible to show a module only on the dynamic generated page which are generated through the getroute function?

Thank You!

### Expected result
Place code in componet to load the module 

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
You can still load modules according to the template positions around the main area (which is the display of the component)

Then JCB also have an option to load modules dynamically into the component area. There are a few demo components that does this, like [CBP](https://github.com/namibia/CBP-Joomla-3-Component), and [Member Manager](https://github.com/vdm-io/Joomla-Members-Manager) the way to get this behavior ([get access to these demo components](https://vdm.bz/how-to-get-free-vdm-package-keys)) is not very obvious and there is no tutorials of this at this time... but it is really easy to understand.

In your [site-view, template or layout](https://github.com/vdm-io/Joomla-Members-Manager/blob/master/site/views/cpanel/tmpl/default_loginmodule.php) where you want to load the module, you simply need to add the [following code](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/site/views/cpanel/tmpl/default.php#L30)... then JCB will automatically [load this method](https://github.com/namibia/CBP-Joomla-3-Component/blob/master/site/views/cpanel/view.html.php#L205) to the view.html.php.
```php
$this->getModules('your-location-top' /** module position **/,'div' /** seperator **/,'uk-panel' /** class **/);
```

The Method JCB will load to your [view.html.php](https://github.com/vdm-io/Joomla-Members-Manager/blob/master/site/views/cpanel/view.html.php)
```php
/**
 * Get the modules published in a position
 */
public function getModules($position, $seperator = '', $class = '')
{
	// set default
	$found = false;
	// check if we aleady have these modules loaded
	if (isset($this->setModules[$position]))
	{
		$found = true;
	}
	else
	{
		// this is where you want to load your module position
		$modules = JModuleHelper::getModules($position);
		if ($modules)
		{
			// set the place holder
			$this->setModules[$position] = array();
			foreach($modules as $module)
			{
				$this->setModules[$position][] = JModuleHelper::renderModule($module);
			}
			$found = true;
		}
	}
	// check if modules were found
	if ($found && isset($this->setModules[$position]) && MembersmanagerHelper::checkArray($this->setModules[$position]))
	{
		// set class
		if (MembersmanagerHelper::checkString($class))
		{
			$class = ' class="'.$class.'" ';
		}
		// set seperating return values
		switch($seperator)
		{
			case 'none':
				return implode('', $this->setModules[$position]);
				break;
			case 'div':
				return '<div'.$class.'>'.implode('</div><div'.$class.'>', $this->setModules[$position]).'</div>';
				break;
			case 'list':
				return '<ul'.$class.'><li>'.implode('</li><li>', $this->setModules[$position]).'</li></ul>';
				break;
			case 'array':
			case 'Array':
				return $this->setModules[$position];
				break;
			default:
				return implode('<br />', $this->setModules[$position]);
				break;
			
		}
	}
	return false;
}
```
Hope this helps :+1:

**Comment by waltraudharror** [comment]
Thank you very much for Your reply.

 

So far I understand adding this line

 

$this->getModules('your-location-top' /** module position **/,'div' /** seperator **/,'uk-panel' /** class **/);

 

doesn’t work. 

 

It only checks if the the module has to be loaded and loads the module if it is set at the module settings page.

 

The command 

 

$modules = JModuleHelper::getModules($position);

 

only returns a empty arry, because the module is not set (I want it to load it manually in the dynamic page generated with getroute::)

 

Am I right?

 

Kind regards

 

Nils

 

 

 

 

 

To my template will only do a module check. 

 

Von: {{ewe}}yn <notifications@github.com> 
Gesendet: Dienstag, 23. Juli 2019 13:27
An: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
Cc: waltraudharror <nhei@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [vdm-io/Joomla-Component-Builder] Link a form module to a dynamic site (#449)

 

You can still load modules according to the template positions around the main area (which is the display of the component)

Then JCB also have an option to load modules dynamically into the component area. There are a few demo components that does this, like CBP <https://github.com/namibia/CBP-Joomla-3-Component> , and Member Manager <https://github.com/vdm-io/Joomla-Members-Manager>  the way to get this behavior (get access to these demo components <https://vdm.bz/how-to-get-free-vdm-package-keys> ) is not very obvious and there is no tutorials of this at this time... but it is really easy to understand.

In your site-view, template or layout <https://github.com/vdm-io/Joomla-Members-Manager/blob/master/site/views/cpanel/tmpl/default_loginmodule.php>  where you want to load the module, you simply need to add the following code <https://github.com/namibia/CBP-Joomla-3-Component/blob/master/site/views/cpanel/tmpl/default.php#L30> ... then JCB will automatically load this method <https://github.com/namibia/CBP-Joomla-3-Component/blob/master/site/views/cpanel/view.html.php#L205>  to the view.html.php.

$this->getModules('your-location-top' /** module position **/,'div' /** seperator **/,'uk-panel' /** class **/);

The Method JCB will load to your view.html.php <https://github.com/vdm-io/Joomla-Members-Manager/blob/master/site/views/cpanel/view.html.php> 

/**
 
 * Get the modules published in a position
 
 */
 
public function getModules($position, $seperator = '', $class = '')
 
{
 
        // set default
 
        $found = false;
 
        // check if we aleady have these modules loaded
 
        if (isset($this->setModules[$position]))
 
        {
 
               $found = true;
 
        }
 
        else
 
        {
 
               // this is where you want to load your module position
 
               $modules = JModuleHelper::getModules($position);
 
               if ($modules)
 
               {
 
                       // set the place holder
 
                       $this->setModules[$position] = array();
 
                       foreach($modules as $module)
 
                       {
 
                               $this->setModules[$position][] = JModuleHelper::renderModule($module);
 
                       }
 
                       $found = true;
 
               }
 
        }
 
        // check if modules were found
 
        if ($found && isset($this->setModules[$position]) && MembersmanagerHelper::checkArray($this->setModules[$position]))
 
        {
 
               // set class
 
               if (MembersmanagerHelper::checkString($class))
 
               {
 
                       $class = ' class="'.$class.'" ';
 
               }
 
               // set seperating return values
 
               switch($seperator)
 
               {
 
                       case 'none':
 
                               return implode('', $this->setModules[$position]);
 
                               break;
 
                       case 'div':
 
                               return '<div'.$class.'>'.implode('</div><div'.$class.'>', $this->setModules[$position]).'</div>';
 
                               break;
 
                       case 'list':
 
                               return '<ul'.$class.'><li>'.implode('</li><li>', $this->setModules[$position]).'</li></ul>';
 
                               break;
 
                       case 'array':
 
                       case 'Array':
 
                               return $this->setModules[$position];
 
                               break;
 
                       default:
 
                               return implode('<br />', $this->setModules[$position]);
 
                               break;
 
                       
 
               }
 
        }
 
        return false;
 
}

Hope this helps 👍

**Comment by marcodings** [comment]
> 
> In Joomla it is possible to choose on which page you want a module to be shown.,
> 
I'd suggest this is a joomla thing ( as log as you are not talking about module positions insed the component area), with at least two solutions
1) add (hidden) menu items for your dynamically generated views and position your modules based on those
2) use an extension like regular labs, "modules anywhere" that allows for much more options to display the module, including based on url

**Comment by waltraudharror** [comment]
Thank you, I will check that tool later. 




Holen Sie sich Outlook für Android







On Wed, Jul 24, 2019 at 12:30 PM +0200, "Marco Dings" <notifications@github.com> wrote:













In Joomla it is possible to choose on which page you want a module to be shown.,



I'd suggest this is a joomla thing ( as log as you are not talking about module positions insed the component area), with at least two solutions

add (hidden) menu items for your dynamically generated views and position your modules based on those
use an extension like regular labs, "modules anywhere" that allows for much more options to display the module, including based on url

**Comment by waltraudharror** [comment]
With modules anywhere I could place the module load command in the site view and everything works fine. 




Thank You




Holen Sie sich Outlook für Android







On Wed, Jul 24, 2019 at 12:30 PM +0200, "Marco Dings" <notifications@github.com> wrote:













In Joomla it is possible to choose on which page you want a module to be shown.,



I'd suggest this is a joomla thing ( as log as you are not talking about module positions insed the component area), with at least two solutions

add (hidden) menu items for your dynamically generated views and position your modules based on those
use an extension like regular labs, "modules anywhere" that allows for much more options to display the module, including based on url
