### ISSUE TITLE
[little (supposed) bug] 

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#453]
I have a db table with a user_id field which not always contain an id value <>0. Some records are added from logged in users (in this case user_id contains the user ID value) others are adde by guests (in this case user_id contains 0).

In the admin view I've set user_id as custom field, which retrieve the user's data from #__users dbfield.

Compiled and installed.
In the installed component admin list view, I get a PHP error message:
Warning: count(): Parameter must be an array or an object that implements Countable in /Library/WebServer/Documents/web/Joomla395/administrator/components/com_test/views/comments/view.html.php on line 288

Line 288 is: 		if (count($groups) > 0)
of the method:
	protected function getTheUser_idNameSelections()
	{
		// Get a db connection.
		$db = JFactory::getDbo();

		// Create a new query object.
		$query = $db->getQuery(true);

		// Select the text.
		$query->select($db->quoteName(array('a.id','a.name')));
		$query->from($db->quoteName('#__users', 'a'));
		// get the targeted groups
		$groups= JComponentHelper::getParams('com_test')->get('commentsuserid');
		if (count($groups) > 0)
		{
			$query->join('LEFT', $db->quoteName('#__user_usergroup_map', 'group') . ' ON (' . $db->quoteName('group.user_id') . ' = ' . $db->quoteName('a.id') . ')');
			$query->where('group.group_id IN (' . implode(',', $groups) . ')');
		}
		$query->order('a.name ASC');

		// Reset the query using our newly populated query object.
		$db->setQuery($query);

		$results = $db->loadObjectList();
		if ($results)
		{
			$filter = array();
			$batch = array();
			foreach ($results as $result)
			{
				$filter[] = JHtml::_('select.option', $result->id, $result->name);
			}
			return  $filter;
		}
		return false;
	}

If I didn't wrong something, just a check like:
if( ![[[Component]]]Helper::checkArray($groups): // $groups is null when I get the error
    $groups = array();
endif;
fix the error.

Please, let me know.
Thanks in advance.

**Comment by nibra** [comment]
Replacing
`	if (count($groups) > 0)`
with
`	if (!empty($groups))`
would solve the issue...

**Comment by jcodewalker** [comment]
Yes but the file is automatically compiled by JCB... so it should be made by Llewellyn in the compiler I suppose.

**Comment by Llewellynvdm** [comment]
Can you please compile the component with line to show **debug line numbers** in the comments and let me know where in the compiler this are is being build.

![image](https://user-images.githubusercontent.com/5607939/62636686-477b1080-b93a-11e9-95fb-b1cb55e5700c.png)

Then I will tweak that area no problem.

**Comment by jcodewalker** [comment]
Hi Llewellyn,
just below this:
		// [Interpretation 10808] get the targeted groups
Thanks a lot!

**Comment by Llewellynvdm** [comment]
ahh got it on [line 10810](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L10810) you can add the patch as @nibra suggested.

**Comment by Llewellynvdm** [comment]
woops.. seconds to late :+1: 

But yes those line numbers help looking into JCB's compiler and know where what is done... wvery handy indeed.

**Comment by jcodewalker** [comment]
Thank you!
