### ISSUE TITLE
[bug] CSS  data not accepted in both site/admin view with codemirror editor

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#456]
Hello Llewellyn,
Using CodeMirror editor, if the CSS is empty I'm not able to input css data (error: some values are unacceptable).
If I set text editor to none, I'm able to input css data. Once saved, I can set again CodeMirror and now it accepts the css code.
So, if the css field is empty CodeMirror doesn't allow me to insert css data. If the field already contains data it works.
I'm referring to:
JCB/admin view/myview/CSS tab/both CSS fields
JCB/site view/myview/Javascript & CSS tab/both CSS fields
Joomla v3.9.10, JCB 2.9.21 stable (both brand new installation).
Best regards.

**Comment by Llewellynvdm** [comment]
This is an old issue, please revert [communication here](https://github.com/vdm-io/Joomla-Component-Builder/issues/353) :+1:

**Comment by jcodewalker** [comment]
I’m sorry, I thought it was a different issue.

**Comment by Llewellynvdm** [comment]
Hmmm let me see are you speaking about fields in JCB or in your own component?

**Comment by Llewellynvdm** [comment]
Well whatever the case, this issue with CodeMirror is sort of a pain, we did in this [patch changed](https://github.com/vdm-io/Joomla-Component-Builder/commit/2af4b8cf50234c20a8d5fd4fc0a7572dca342b17) all of the fields we could to not being required. So you should not get `error: some values are unacceptable` in JCB anymore. Yet if you added the editor to your own component... follow the issue I pointed you to and you will see this is a CodeMirror issue really... not a JCB issue.

Joomla was not made to be an IDE.... that is the short answer I suppose. But okay CSS should work... if you have any ideas on what we are doing wrong... or how we can fix this [communication it all here](https://github.com/vdm-io/Joomla-Component-Builder/issues/353) :+1:

**Comment by Llewellynvdm** [comment]
But just that you know... this fix has not yet been pushed to the master branch, and is only in the staging. I just pushed a stable staging branch up... and it will go in for testing so we can push the new features out to all.

**Comment by jcodewalker** [comment]
I’m speaking about fields in JCB, both admin and site view.

**Comment by Llewellynvdm** [comment]
Okay so the latest release is now out... and it should fix this issue, let me know.

**Comment by jcodewalker** [comment]
Perfect!
Thank you!
