### ISSUE TITLE
[feature request] installation sql with "unique" fields

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#460]
### Steps to reproduce the issue
Add a "default" Joomla field (it means same dbname field) to the admin view (es: published, access and so on) that it is added by JCB by default (I don't need/want to disable this option in JCB).
Compile -> Install

### Actual result
The sql shows the field added two times, one by the admin view I set and one by JCB per default option.

### Why I need this
There are complex projects where data entry are divided in several tabs.
I need to keep some fields, like "published" and "access level" in the first tab, for an ease access.

### Note
The model/form/xml form hasn't twice the field, so once installed I can set the field in the first tab and it is automatically removed from "publishing" tab.
So, all in all, it "only" requires a check over the sql compile. It add flexibility to the graphic layout too.

Thanks in advance!

**Comment by jcodewalker** [comment]
It seems only access field is added twice...
I'm going to check all fields.

**Comment by jcodewalker** [comment]
So, it seems only the following fields are added twice:
access
metadesc
metadata
metakey

all the rest is cleaned up and compiled once.

**Comment by Llewellynvdm** [comment]
Hmm this is hard to communicate in a few words. Have you [watched this tutorial](https://www.youtube.com/watch?v=FHQfIhWHYyQ&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=30&t=0s)?

**Comment by jcodewalker** [comment]
Hello Llewellyn,

It’s exactly what I did. It works for fields named ‘published', ‘created', ‘created_by' and so on.
It doesn’t work only with fields named:
‘access'
‘metadesc’
‘metadata’
‘metakey’

Attached you can find the test (sql installa file) I did with your ‘demo’ component.

Thanks in advance!
claudio

**Comment by Llewellynvdm** [comment]
Okay, yes those are not fields considered as part of the default fields since they are added and removed by the way you add the admin view to a component. But I can have a look and see what we can do to combine them with the normal default fields.... will be tricky.

Sorry for not noticing that in you original request...

**Comment by jcodewalker** [comment]
No problem!
