### ISSUE TITLE
[feature-request] Add filter to Admin Fields list 

### ISSUE THREAD

**Issue by MastersOfMedia** [vdm-io/Joomla-Component-Builder#461]
### Steps to reproduce the issue
A feature request to implement a filter on 'Field Category' for the Admin Fields list.

### Expected result
I am adding fields for a specific application and assign them to a Field Category. The field Category shows up alright in the Admin Field list, but one can not filter on a Field Category (one can not filter at all). This would be helpful when the list gets very long and the number of Field Categories grows. 

### Actual result
No filter options in the Admin Fields list

### System information (as much as possible)
- OS Name & Version: CentOS 7
- MySql Version: 5.7
- Apache Version: 2.4.41
- PHP Version: 7.3.8
- Joomla Version: 3.9.11
- JCB Version: 2.10.0
- Browser: FF 68.0.1

### Additional comments
A minor feature request.

Erik

**Comment by Llewellynvdm** [comment]
I am not sure I follow, where is the Admin Field list? what area are you hinting at? I know of the Fields, Admin Views, but I don't know of admin field list...

**Comment by MastersOfMedia** [comment]
I am sorry, I was unclear. I mean the Admin Fields view. 

![Schermafbeelding 2019-08-16 om 23 54 40](https://user-images.githubusercontent.com/26111381/63200353-3f7d4800-c081-11e9-93a4-847ac90d3c59.png)

**Comment by Llewellynvdm** [comment]
Okay we call that the fields view, since fields are not only used in admin views... but also in component config and now even in the plugin area. But okay, have you tired adding some of those fields to categories? and see i the category filter then shows-up. Far as I know it is there...

**Comment by MastersOfMedia** [comment]
Thansk for the clarification Llewellyn. I'm new to JCB so I need to learn a lot :)

I actually created a new category and a couple of new fields i created are assigned to this category. The category shows up in the list, but no filter for category appears. Here's how it looks:

![Schermafbeelding 2019-08-17 om 00 27 36](https://user-images.githubusercontent.com/26111381/63201510-d946f400-c085-11e9-9d43-e521d9cc0b02.png)

**Comment by Llewellynvdm** [comment]
Hmmm... here I just ran a test on a demo site and it works as expected.

The list with some categories added to the fields:
![image](https://user-images.githubusercontent.com/5607939/63201787-01832280-c087-11e9-822a-094d759e858a.png)

The category filter on the left under Select Access:
![image](https://user-images.githubusercontent.com/5607939/63201809-1cee2d80-c087-11e9-811d-b964de2b5d8a.png)

Then I selected on category:
![image](https://user-images.githubusercontent.com/5607939/63201845-46a75480-c087-11e9-9b3e-18624acd00a5.png)

Then the list filter by that selection:
![image](https://user-images.githubusercontent.com/5607939/63201860-53c44380-c087-11e9-99f6-61af8b401d41.png)

So it seems to work on my end... not sure why not on yours. Did you add more then one category?

**Comment by MastersOfMedia** [comment]
Thanks for the explanation. It actually does work at my end, already with one category added. The filter is simply in the place where I was not looking. I must be completely deformed by how things are presented in Joomla! itself, hadn't noticed there is a filter in the left column as I expected it to show up above the list. My bad and please forget I asked... :/

**Comment by Llewellynvdm** [comment]
Ahh I think I know... you did not see the filters under the sub-menu... there is an[ issue open to change](https://github.com/vdm-io/Joomla-Component-Builder/issues/378) that. Hey no worries... you are most welcome, please ask... I need it! I am the one not getting to everything fast enough... but soon :+1:

**Comment by MastersOfMedia** [comment]
Thanks Llewellyn. And please don't worry about not getting things done fast enough. You're doing a great job :)
