### ISSUE TITLE
[feature request] field position in tab: full width in tab ABOVE

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#462]
Hello,
it would be great to have a "full width in tab above" position, in JCB Editing the Admin Fields.
Right now (if I'm not wrong) there is "full width in tab" and it is shown below "left in tab" and "right in tab".
Unfortunately the best place to set a dynamic advice is above the fields.
If there is already a method to get it, please let me know.

Thanks in advance.

**Comment by Llewellynvdm** [comment]
Have you tried to add something to the `above tab` position and with css style it to full width? Try the class `span12` this should do the trick.

**Comment by jcodewalker** [comment]
Hi,

hummm, do you say to add the position in the compiler template (compiler/joomla_3/edit_body.php)?
I can’t find the edit body for the admin side… ant hint?
Thanks in advance,
claudio

**Comment by Llewellynvdm** [comment]
No I said to add whatever you want placed, field or note in the `above tab` position.
![image](https://user-images.githubusercontent.com/5607939/63311388-2fbe6780-c2fe-11e9-80b1-18d1876a5cce.png)

So for example if you want to show dynamic notices, add a [`note`](https://docs.joomla.org/Note_form_field_type) to the `above tab` position with no text like this:
```
<div class='notice-area'></div>
```
Then target the div with whatever message you like.

Then again you can always use this [uikit lib](https://getuikit.com/docs/notification)... as it is part of JCB core, and can be included to any component via the component area tab->Libs & Helpers->Add Uikit 

Then you can also use [Joomla default message options](https://docs.joomla.org/Display_error_messages_and_notices), as most templates have there own implementation or massage placeholders/positions front and back-end.

**Comment by jcodewalker** [comment]
Oh, yes, I did it in the “absolute above” position and didn’t like it too much, to be honest, yet it is a solution. Instead the uikit could fit the bill because even if the tab is scrolled down and the "absolute above” position is off the screen the message can be seen anyway.
Didn’t know uikit is loaded in the admin area as well… it’s a beautiful news!
Thank you!
Best regards,
claudio

**Comment by jcodewalker** [comment]
Sorry Llewellyn,

But it seems the UIkit is not loaded in the head of the (admin side) component.
I’ve included it in the JCB component area tab->Libs & Helpers->Add Uikit.
In the Joomla/admin/components/com_mycomponent/options I even set “force” as loading option but I can’t find the uikit inclusion in the head of the document and, obviously, I get the error… "Uncaught TypeError: Cannot read property 'notification' of undefined”.

Inside JQuery, I trigger the notification with:
$.UIkit.notification({message: 'Success message...', status: 'success'});

Is there something I’m missing?

Thanks in advance,
claudio

**Comment by Llewellynvdm** [comment]
Yes you need to be added, those switches just add the lib to the project, you must still pull it in to admin views. The site and custom admin views are automated... but not admin views.

Here is a script I use all the time when adding both v2 and v3 to a component:
```
		// get Uikit Version
		$this->uikitVersion = $this->params->get('uikit_version', 2);
		// Load uikit options.
		$uikit = $this->params->get('uikit_load');
		$isAdmin = JFactory::getApplication()->isClient('administrator');
		// Set script size.
		$size = $this->params->get('uikit_min');
		// Use Uikit Version 2
		if (2 == $this->uikitVersion && ($isAdmin || $uikit != 2))
		{
			// Set css style.
			$style = $this->params->get('uikit_style');
			// only load if needed
			if ($isAdmin || $uikit != 3)
			{
				// add the style sheets
				$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/uikit' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			}
			// add the style sheets
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/accordion' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/tooltip' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/notify' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/form-file' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/progress' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/css/components/placeholder' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2//css/components/upload' . $style . $size . '.css' , (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			// only load if needed
			if ($isAdmin || $uikit != 3)
			{
				// add JavaScripts
				$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/uikit' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			}
			// add JavaScripts
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/components/accordion' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/components/tooltip' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/components/lightbox' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/components/notify' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v2/js/components/upload' . $size . '.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
		}
		// Use Uikit Version 3
		elseif (3 == $this->uikitVersion && ($isAdmin || $uikit != 2))
		{
			// add the style sheets
			$this->document->addStyleSheet( JURI::root(true) .'/media/com_[[[component]]]/uikit-v3/css/uikit'.$size.'.css', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/css');
			// add JavaScripts
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v3/js/uikit'.$size.'.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
			// add icons
			$this->document->addScript( JURI::root(true) .'/media/com_[[[component]]]/uikit-v3/js/uikit-icons'.$size.'.js', (###Component###Helper::jVersion()->isCompatible('3.8.0')) ? array('version' => 'auto') : 'text/javascript');
		}
```
> The list item of the custom code placeholder:

![image](https://user-images.githubusercontent.com/5607939/63871187-b688d980-c9bb-11e9-8a3f-ac0f05befebe.png)
___
> The custom code view:

![image](https://user-images.githubusercontent.com/5607939/63871199-c43e5f00-c9bb-11e9-88b4-61dd62bb8ddb.png)
___
> See I have used it in a few admin views

![image](https://user-images.githubusercontent.com/5607939/63871333-02d41980-c9bc-11e9-860c-3e666fde2864.png)


Then on the admin view -> PHP tab -> php_document I just add to the placeholder

> So I added it to custom code and use only the placeholder where needed like this:

![image](https://user-images.githubusercontent.com/5607939/63871429-272ff600-c9bc-11e9-876c-41d51c918413.png)

So yes mostly admin edit views... I have not yet have to load it to a List view, but to do so is not that hard, just adapt the custom code I gave and then add it to the JavaScript Tab -> Add JavaScript (views-footer) *

Some thing like this:
```
<?php 
// do you PHP here
// the $this->document object/class is still available.
?>
// add your javascript here
```

**Comment by jcodewalker** [comment]
AAhaaa, ok.
Thank you!
