### ISSUE TITLE
[bug?] New Custom Code in FF doesn't trigger js properly

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#466]
### Steps to reproduce the issue
Open New Custom Code

### Expected result
the template with all its buttons and editor

### Actual result
template without buttons ( shown as links but not working)
textarea instead of editor

### System information (as much as possible)
- OS Name & Version: OS 10.10.5 (yosemite)
- Joomla Version: 3.9.11
- JCB Version: 2.10.0 (master)
- Browser: Firefox version: 68.0.2

### Additional comments
opening (edit) 
![Schermata 2019-08-23 alle 10 34 52](https://user-images.githubusercontent.com/49115855/63579531-2c8fd980-c593-11e9-816e-106051ddc4cf.png)
an existing custom code works fine
in Chrome works fine both new and edit

**Comment by Llewellynvdm** [comment]
I have tried to duplicate this in Firefox but not getting the same result, all seems to work just fine.

> CodeMirror as editor

![image](https://user-images.githubusercontent.com/5607939/63870501-5f363980-c9ba-11e9-9fb1-df4a78aea1d5.png)

> None as editor

![image](https://user-images.githubusercontent.com/5607939/63870649-a8868900-c9ba-11e9-9dc6-2a64be359923.png)

What editor have you selected?

**Comment by Llewellynvdm** [comment]
I assume this to be resolved (week of silence)... let me know.

**Comment by jcodewalker** [comment]
I’m sorry, I didn’t see your reply.

No, it’s random. Between 50% to 80% of the times, opening a new window (empty content) it doesn’t render the editor.
No problem opening an existing code.
Not something I can’t survive to…
