### ISSUE TITLE
Front-end form have only the cancel button

### ISSUE THREAD

**Issue by oxido21** [vdm-io/Joomla-Component-Builder#469]
### Steps to reproduce the issue
Hi Guys,
I have created an Admin view with this settings: https://i.imgur.com/aeDCAuP.jpg
and this permisions: https://i.imgur.com/TpIAuhf.jpg

And in the Component Admin View i added the "Add+Menu" for Edit/Create Site View (add site edit & create view for this admin view)
I can save a new antry only i'm loged in as super admin, but as regular registred user the "save button" does't exist, i have only the option to cancel, as you can see in this picture
https://i.imgur.com/fdu1uEa.jpg

In front end result : https://i.imgur.com/i0IgD5G.jpg

What should i do to have the save button in front end for registred users?

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.11
- JCB Version: 2.10.0
- Browser:

**Comment by Llewellynvdm** [comment]
This must be a permissions issue, please try again at giving more permissions.

**Comment by oxido21** [comment]
Sorry sorry, this was  not a problem, i forget that i have to set te permision after i instal the component ;)). 
So everything is okay
