### ISSUE TITLE
JCB on PHP 7

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#47]
We need to make sure that JCB and all the components build with it works on PHP 5.6 and PHP 7

At this time it only works on PHP 5.6 any one who is willing to help comment on this issue!

**Comment by Llewellynvdm** [comment]
This is of course where we should start http://php.net/manual/en/migration70.php

**Comment by Houtsmatisering** [comment]
If been working with MAMP php 7.1.0. So far I cannot report any issues related to php 7.
Regards,
Jeroen

**Comment by Llewellynvdm** [comment]
That is great news. I will close this issue for now, if you run across any issues, even with the components that are build with JCB in php 7 please let us know.
