### ISSUE TITLE
 Cannot create destination folder when compiling

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#470]
### Steps to reproduce the issue
Clean install of Joomla. Compile the demo.

### Expected result
compiling without errors

### Actual result
Error:  Cannot create destination folder

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 5.5.5-10.3.11-MariaDB-1:10.3.11+maria~bionic
- Apache Version: 
- PHP Version: 7.2.22
- Joomla Version: 3.9.11
- JCB Version: 2.10.0
- Browser: Chrome

### Additional comments
All folder and file permissions is 755

**Comment by jonasborneland** [comment]
I should mention that I´m running it on a shared host. Would that cause these kind of errors?

**Comment by jonasborneland** [comment]
On a local MAMP server i get this error:
`Warning
JFolder: :delete: Could not delete folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\assets
JFolder: :delete: Could not delete folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin
JFolder: :delete: Could not delete folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel
Failed deleting PlotArea.php
Failed deleting config
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale\en
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale\es
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\locale
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Reader\Excel5
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\RichText
Failed deleting Error.php
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\JAMA
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Shared\PCLZip
Failed deleting Style.php
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel\Writer\OpenDocument
Failed deleting index.html
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers\PHPExcel
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\helpers
Failed deleting import.php
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\models
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\sql\updates
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\tables
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\demo\tmpl
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\import\tmpl
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\import
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin\views\look\tmpl
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\admin
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\media\uikit-v2\fonts
Failed deleting datepicker.js
Failed deleting form-select.js
Failed deleting sortable.js
Failed deleting modal.js
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\media
Failed deleting en-GB.com_demo.ini
JFolder: :delete: Path is not a folder. Path: C:\MAMP\htdocs\administrator\components\com_componentbuilder\compiler\com_demo_v2_0_0__J3\site\layouts`

**Comment by Llewellynvdm** [comment]
Check out this form post on [file and folder](https://stackoverflow.com/a/11512211/1429677) permissions. Also this recent [issue 421](https://github.com/vdm-io/Joomla-Component-Builder/issues/421) where there was also a permissions issue.

**Comment by peterpetrov** [comment]
Also you are using Chrome which is known to display errors and warnings when compiling. Try to compile with a browser that is not build over Chromium engine and let us know.

**Comment by jonasborneland** [comment]
Thanks! @peterpetrov and @Llewellynvdm ... I'm trying with bitnami now

**Comment by jonasborneland** [comment]
Seems to be working after installing with bitnami using your video tutorial.
The only error I´m getting (Also in FireFox browser) is:
```
Language Warning
The admin af-ZA language has 181(total en-GB strings) only 19(strings af-ZA translated) = 10% translated, you will need to translate 50% of the language strings before it will be added.
```

**Comment by jonasborneland** [comment]
@peterpetrov @Llewellynvdm It is diffently working now, though i still have the `Language Warning
` appering. Thanks for the really huge work you out into JCB! I'm really looking forward to use it.... Do you know ehat causes the language warning?

**Comment by peterpetrov** [comment]
@jonasborneland you are getting that message because you have installed some of the components by Llewllyn which are default to Africas English language. If you want to get rid of the message you need to update a setting in JCB options. 

/administrator/index.php?option=com_config&view=component&component=com_componentbuilder

Search for:

Add Language if %? ready. *

Which is set to 50% by default. Setting it to 0 will make the error disappear.

P

**Comment by jonasborneland** [comment]
@peterpetrov Fantastic! Now every thing works flawless!
