### ISSUE TITLE
[feature request] toolbar custom button function customizable in custom admin view

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#471]
### Steps to reproduce the issue
submit a form in a custom admin view, "views" view (getListQuery)

### Actual result
I need to send a form (data coming from a file and going to a file) from a custom admin view, items list views. Why items list view and not item edit view? Because I need also to retrive a list of data from a db table, so I need to set a getListQuery.
This results in a form tags open and closed by JCB BEFORE custom data content.
So I have to set a new form.
This doesn't allow me to set custom buttons to submit my form and I can't set a jquery to grab the button either, because the javascript function JCB set before grabs all the functions and submit the first form ('getElementById('adminForm')'

To submit the form I need to set a button inside the content. Not a drama, but graphically totally different from the other views.

And there is not any option to disable the tollbar neither, so I can set a custom toolbar and avoid two tollbars in the view.

This coul be fixed by allowing to set the form ID to submit with the custom buttons (default 'adminForm')
![custom_admin_view](https://user-images.githubusercontent.com/49115855/64065720-5ab78e00-cc11-11e9-81ba-0fb7dcd315d8.jpg)
.

Thanks in advance.

**Comment by Llewellynvdm** [comment]
You can do this easy with some custom JavaScript:
```js
<script type="text/javascript">
Joomla.submitbutton = function(task, key)
{
	if (task == ''){
		return false;
	} else {
		var component = jQuery('#component').val();
		var isValid = true;
		
		if(component == '' && task == 'compiler.compiler'){
			isValid = false;
		}
		if (isValid){
			jQuery('#form').hide();
			// get correct form based on task
			if (task == 'compiler.compiler' || task == 'compiler.installCompiledPlugin') {
				var form = document.getElementById('compilerForm');
			} else {
				var form = document.getElementById('adminForm');
			}
			// set the plugin id
			if (task == 'compiler.installCompiledPlugin') {
				form.install_item_id.value = key;
			}
			// set the task value
			form.task.value = task;
			form.submit();
			// some ui movements
			if (task == 'compiler.compiler'){
				jQuery('#compiler').show();
			} else if (task == 'compiler.clearTmp'){
				jQuery('#loading').css('display', 'block');
				jQuery('#clear').show();
			} else {
				jQuery('#loading').css('display', 'block');
			}
			return true;
		} else {
			jQuery('.notice').show();
			return false;
		}
	}
}
</script>
```
Do you have the JCB imported as a JCB package? you will see a custom admin view called **complier** the [code above is from that view](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/compiler/tmpl/default.php), and is what I use to get the needed form and details per/task. Take a closer look at how we did all that, and see it in action every time you compile a component :+1: 

Adding a form id to the buttons will cause a serious complexity at times that is best resolved with your own custom code, for you know best what you want to do.

See the normal toolbar is build with Joomla API, and targets the `Joomla.submitbutton` method which is what gets the task and submits the form. So to basically override that method is the easy solution.

No if you are triggering the submission from the toolbar, then investigate the button to get the submit button task name:
![image](https://user-images.githubusercontent.com/5607939/64161181-8323d000-ce3d-11e9-8151-5422b1f64cbe.png)

Really it is that simple, look at the [JCB package importer](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/import_joomla_components/tmpl/default.php#L21) and see how I also do the same.

So with `var form = document.getElementById('yourOtherFormID');` you can load your form in your custom code and do your stuff :+1: inside the `Joomla.submitbutton` function, just make sure to add the default behavior that JCB wrote in the method as well or the other buttons will fail.

**Comment by jcodewalker** [comment]
The JQuery is the first thing I tried, but it seemed that the jQuery script, that JCB include by default, grabs it before than mine and send the adminForm, which come first than mine, obviously.

I’ll try again knowing that this is the right way to get it working and will investigate deeper.

No, I’ve the JCB package at the moment. I have to invest some time to make a new installation with all the JCB imported package to see it in action in different solutions.
