### ISSUE TITLE
Dynamic get with arrays

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#474]
I tried following your youtube video about the dynamic get, but It´s not really walked trough how to use it with the multiple rows type?

I have a table containing the id´s of another table like: '{"0":"2","1":"3","2":"1"}'

I´ve then done a dynamic get with Join View Tables like this:
![image](https://user-images.githubusercontent.com/6105278/64515601-29178480-d2ed-11e9-8755-fc6737226395.png)

but in my model for the site view inside this generated function:
`public function getJjdelIdJj_delDddb_B($jjdel)`

I had to convert the array string into an actual array insted of the json string.
I did it like this:
`$array = json_decode($array, true);`
before it worked. 
Every time i recompile, I have to open the file and insert the above json decoder.

What did I miss for the jcb to do this? :)

And, thank you for such an amazing tool for creating components.

**Comment by Llewellynvdm** [comment]
Hmmm, I am not sure I follow. Sounds like you are trying to do something that JCB does not yet support, but with a little bit of custom coding can be done.

I need to see the code to understand more, and then screen shots of all the dynamic view tabs so I can see what you did in JCB an how JCB compiled it.

**Comment by peterpetrov** [comment]
Hey Jonas, have you considered custom dynamic get? You should have to write the query on your own but the it will also be very flexible in adding more "outside of the box" functionalities.

Peter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jonasborneland** [comment]
Thanks!

I got these two admin views
![image](https://user-images.githubusercontent.com/6105278/64523421-8ebf3d00-d2fc-11e9-8591-88b790ae2fd7.png)

In the "jjpakker" admin view, I got a field to select rows form the jjdele view.
The custom field in "jjpakker" looks like:
![image](https://user-images.githubusercontent.com/6105278/64523615-faa1a580-d2fc-11e9-99e2-1a1b9d87c98e.png)
In the database the selected rows is stored as the json string mentioned above "'{"0":"2","1":"3","2":"1"}'".

I then have a dynamic get like:
![image](https://user-images.githubusercontent.com/6105278/64523803-6a179500-d2fd-11e9-969d-7b7699832dd7.png)

And the site view contains this:
![image](https://user-images.githubusercontent.com/6105278/64524319-8bc54c00-d2fe-11e9-8b7c-b180f966c324.png)


That dosen´t work without the decode json I added in the model code.
But with the decode json added, i gives me this on the frontend:

![image](https://user-images.githubusercontent.com/6105278/64524185-4dc82800-d2fe-11e9-9874-6695d7bff63d.png)

**Comment by jonasborneland** [comment]
> Hmmm, I am not sure I follow. Sounds like you are trying to do something that JCB does not yet support, but with a little bit of custom coding can be done.
> 
> I need to see the code to understand more, and then screen shots of all the dynamic view tabs so I can see what you did in JCB an how JCB compiled it.

I´m basicly trying to do the same as you do here https://youtu.be/OPuCoxPW35s?t=753 but just with multiple items insted of a single item

**Comment by jonasborneland** [comment]
After looking a lot at this. This seems to me to be an error.
Has anyone used the IN statement of the dynamic get?

Inside the model for my site view, this function gets generated `public function getJjdelIdJj_delCebc_B($jjdel)`
In that function you will find this line:
```
// Check if $jjdel is an array with values.
		$array = $jjdel;
		if (isset($array) && JjviewpakkerHelper::checkArray($array, true))
		{
			$query->where('b.id IN (' . implode(',', $array) . ')');
		}
		else
		{
			return false;
		}
```
Which (I guess) works as expected with single row. But with multiple rows:
![image](https://user-images.githubusercontent.com/6105278/64613339-32c8e700-d3d6-11e9-9d1a-ef56df35b955.png)
You got an array that you need to convert to json like:
$array = json_decode($array, true);
instead of the "$array" above in: `// Check if $jjdel is an array with values.
		$array = $jjdel;`

**Comment by jonasborneland** [comment]
@Llewellynvdm What data type do you use for the json arrays?

**Comment by Llewellynvdm** [comment]
I use `text` most of the time unless I know it will be very small then I use `varchar(265)`.

About what I asked for... :

> maybe share a screen shot of the whole getItem method

That is the code of a method in the model called `getItem` or `getItems` not the GUI stuff but the code of the actual site-view model. So what you shared does not help me see the code I actually asked for.

**Comment by jonasborneland** [comment]
Thanks @Llewellynvdm!

I made it all work out trying the suggestions here and on the Google forum.
Thank you all for helping med out!

I made it work using a custom get where I did the json_decode inside:
```
$filterDele = "";
foreach ($this->_item as $del) {
    $rawSubform = json_decode($del->subform, true);
    foreach ($rawSubform as $subformpart){
        $filterDele .= $subformpart['jjdel'].",";
    }
    
}
$filterDele = substr($filterDele, 0, -1);

// Get from #__pakker_jj_del as a
$query->select('a.*');
$query->from($db->quoteName('#__pakker_jj_del', 'a'));
$query->where('a.id IN ('.$filterDele.')');
```

I´m so glad it is working now, I really felt stuck. But with the help from you and Peter, and Jcodewalker and Peter on the google forum, it is now working perfectly.

I really admire your work on JCB, it´s truly a powerful and useful tool. Thanks!
