### ISSUE TITLE
Javascript (edit view footer) not added anywhere

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#478]
### Steps to reproduce the issue
I added this code. But even if I search my whole FTP server for "skiftTekst" its not found. It seems like its not getting added.
![image](https://user-images.githubusercontent.com/6105278/65154495-e875e480-da2b-11e9-88dc-596139ba7e94.png)

**Comment by peterpetrov** [comment]
Hey Jonas,

I just tested and it adds the code at the bottom of the edit view.

[root@dev coder.taktix.eu]# grep -r . -e "consoleLogTest"
./administrator/components/com_profiles/views/profile/tmpl/edit.php:funtion consoleLogTest(){
./components/com_profiles/views/profile/tmpl/edit.php:funtion consoleLogTest(){

Are you sure you have compiled the component before searching for it?

Regards,
Peter

**Comment by jonasborneland** [comment]
Yes. I will try to do a test in another component

**Comment by jonasborneland** [comment]
@peterpetrov Thanks for replying. After a couple of recompiles and completely removing the component and installing again it is working now :)
