### ISSUE TITLE
"Depreciated" Code in compiler?

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#48]
Not to add more work to you, but it looks like there is some "depreciated" code in the compiler. See below on examples (note: this was using Sermon Distributor, running the check through JED Checker component -- https://extensions.joomla.org/extension/jedchecker/)

- JError::raiseError(500, implode('', $errors)); 
JError is deprecated, you should use JFactory::getApplication()->enqueueMessage();:

- return JError::raiseWaring(404, JText::_('JERROR_ALERTNOAUTHOR'));
JError is deprecated, you should use JFactory::getApplication()->enqueueMessage();:

- $checkValue = JRequest::getInt('id');
JRequest is deprecated, you should use JFactory::getApplication()->input;:

I know I've seen some areas that are using the enqueueMessage above, but others that are using the raiseError or raiseWaring

**Comment by Llewellynvdm** [comment]
I know about this issue, it is depreciated, and we will change it soon...

**Comment by mwweb** [comment]
Great I figured you probably did, but I've learned not to assume.

**Comment by Llewellynvdm** [comment]
Hey it is great that you pointed it out... thanks! and please continue to do that :+1:

**Comment by Llewellynvdm** [comment]
Here is why I have not changed it... [part of core](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/article/view.html.php#L72)

So I though if they left it there... why not wait until they remove it :)

You will see that is the only place in the compiler it is still used... in the JViewLegacy files.
