### ISSUE TITLE
[bug] Color type field is not listed in fields list

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#481]
### Steps to reproduce the issue
Set up a color type field

### Expected result
To be listed in fields list

### Actual result
missing

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.1
- Browser: firefox

### Additional comments
The field is correctly saved into the database but it's not shown in fields list

**Comment by Llewellynvdm** [comment]
It is listed, and is called color :+1: 

![image](https://user-images.githubusercontent.com/5607939/66572614-90855600-eb71-11e9-96df-d4f147e9f71f.png)

![image](https://user-images.githubusercontent.com/5607939/66572637-9e3adb80-eb71-11e9-952a-29a185700a03.png)

**Comment by Llewellynvdm** [comment]
If it is missing then please go over your field types and see if you by accident changed its name or removed it.
![image](https://user-images.githubusercontent.com/5607939/66572757-d04c3d80-eb71-11e9-8197-46ccd0ef92b4.png)

**Comment by jcodewalker** [comment]
I'm sorry!
Yes, I did set a filter..
You has been faster than me..
Thank you!
