### ISSUE TITLE
Ftp Srtting Error

### ISSUE THREAD

**Issue by gartes** [vdm-io/Joomla-Component-Builder#485]
### Steps to reproduce the issue
In method - getFtp($serverID, $permission)
php 7.2 - 
parse_str($server->signature); 
### Expected result
return Array

### Actual result
error need two param  parse_str($server->signature , $options);

extract($options);
### System information (as much as possible)
- OS Name & Version: Linux
- MySql Version: 
- Apache Version: 
- PHP Version: 7.2
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
This is not enough information, please explain more. Is this in JCB or in your own component. What version of JCB and Joomla are you using... 

If I can't see the issue, I can't help resolve it... :walking_man:
