### ISSUE TITLE
Use input field values in custom php save method in admin view.

### ISSUE THREAD

**Issue by hennysmafter** [vdm-io/Joomla-Component-Builder#486]
Hey I have an admin view with a lot of fields setup. These are all stored to the db table created automatically and all of that works fine. But now I need a few of these fields to store in a different Joomla table.

So I created a piece of php code that does just that and here below I post the part that I am struggling with:

```php
function generateDetails() {
  $details = "Lorem ipsum dolar sit met";
  $owner = "henk";
  addDetails($details,$owner);
}
```

The above works fine both details are beeing saved to the db table that I want but now I don't want it hardcoded it needs to grab the values from the input fields. So I tried numerous things and all of them have not been succesful.

```php
// As done in modules
function generateDetails() {
  $details = $params->get('details');
  $owner = $params->get('owner');
  addDetails($details,$owner);
}

// Depreciated but hey I am willing to try anything.
$details = JRequest::getVar('details');

// I also tried the old and outside Joomla variants of $_GET & $_POST but nothing seems to work

Furthermore tried with:
1...
$params = JComponentHelper::getParams('com_componentname');
$details = $params->get('jform[details]');
2...
$params = JComponentHelper::getParams('com_componentname');
$details = $params->get('details');
3...
 jimport('joomla.application.component.helper');
$app = JFactory::getApplication();
$params = $app->getParams();
$param = $params->get('details');
4...
 jimport('joomla.application.component.helper');
$relation_params = & JComponentHelper::getParams( 'com_componentname' );
$name = $relation_params->get( 'details' );
5...
 jimport('joomla.application.component.helper');
$name = JComponentHelper::getParams('com_componentname')->get('details');
```

So how to get those input values and use it in the Custom PHP Code area of an Admin View.

All the code I have written for these functions are all located within (Add PHP (save Method - after data modeling) *) is this the wrong area? PS: I watched the videos that are related to this subject but sadly haven't found the information I require.

PS: I am waiting patiently for the keys to the more advanced packages as I am sure that I can find a whole lot of information in those packages. Any idea when the new round of keys sending starts?

PS2: I know that a lot of the things I tried are variations from one of the other but I think I put it in here anyway.

**Comment by Llewellynvdm** [comment]
Hi, here is a [new feature we just pushed out a few days ago](https://youtu.be/JjAdCDQ8ht8), that will resolve this for you no problem. Let me know what you think!

**Comment by marcodings** [comment]
Nice one !
