### ISSUE TITLE
syntax error in generated getItem method

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#488]
Generated getItem in the models flags a syntax error for flags as protected
![image](https://user-images.githubusercontent.com/3484222/67944388-ab7d4000-fbdc-11e9-825a-a4b6e0a65666.png)

**Comment by Llewellynvdm** [comment]
So I have been able to validate that this is indeed a PHPStorm issue, linked to the [Update classes](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Updater/Update.php#L26) used by the Updater::update() to install an update.
