### ISSUE TITLE
Feature Request - Add field names to Linked Fields section

### ISSUE THREAD

**Issue by oriolun** [vdm-io/Joomla-Component-Builder#489]
Hi!
It will be very helpful to add this feature in new releases. Now we have only title and type of field in the linked fields section of fields tab on the "Editinig view" page. So it will looks like "Title [type] [name] edit button".
Thanks.

**Comment by Llewellynvdm** [comment]
Please explain a little more, maybe with some screen shots. I have the idea this can already be done, but let me just get a clearer understanding of what you are saying before I say more.

**Comment by oriolun** [comment]
Like this: 
![screenshot-quantum-magic ru-2019 11 04-20_11_16](https://user-images.githubusercontent.com/47156894/68142047-c551b680-ff3f-11e9-9b3f-108c69ec5f51.png)

**Comment by Llewellynvdm** [comment]
Okay, I have added this feature. I am not sure how it will impact the GUI speed, so we will try it out, and if it slows it down we will need to look at this again. So take it for a test drive and let me know.
