### ISSUE TITLE
[BUG] label of field named version is always replaced with Release

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#490]
### Steps to reproduce the issue
add a text field to look view of demo component as follows:
name: version
label: Version
description: whatever
compile and install

### Expected result
label: Version

### Actual result
label: Revision

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.1
- Browser: 

### Additional comments
No matter what I set as label in field definition, it is always replaced with "Release"

**Comment by Llewellynvdm** [comment]
Ahaa found it, was a typo! I just pushed up the fix.
