### ISSUE TITLE
[BUG] "data length" not saved in new field

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#491]
### Steps to reproduce the issue
Set new field (i.e. radio), set tinyint, data length: 1, default: 0

### Expected result
Open the field and find data length: 1

### Actual result
data length: none set

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.5
- Browser: 

### Additional comments
It is saved properly when edit the field once created

**Comment by Llewellynvdm** [comment]
Bug has been fixed in [issue 487](https://github.com/vdm-io/Joomla-Component-Builder/issues/487), if not please communicate your findings there.

Make sure your JavaScript on the page is loading the changes we made.

**Comment by Llewellynvdm** [comment]
@jcodewalker mentioned that this issue is still not resolved.
