### ISSUE TITLE
Plugin language strings not added to Language translation

### ISSUE THREAD

**Issue by vistamedia** [vdm-io/Joomla-Component-Builder#493]
### Steps to reproduce the issue
Create a plugin with JText strings (in script file with a custom code placeholder)
Attach the plugin to a component
Compile it.

### Expected result
Language strings should be added to Language Translations in order to be able to translate via Excel in another language.

### Actual result
Language strings are compiled inside the plugin and added to the en-GB folder but aren't available inside component builder for translation.

### System information (as much as possible)
- OS Name & Version: MacOS 10.15.1
- MySql Version:  5.7.26
- Apache Version: 2
- PHP Version:  7.1.30
- Joomla Version: 3.9.13
- JCB Version: 2.10.5
- Browser: Firefox 70.0.1 (64 bits)

**Comment by Llewellynvdm** [comment]
Yes indeed, we are still working on this area of the plugins. Will try to push a update soon.

**Comment by Llewellynvdm** [comment]
Please test [staging branch](https://github.com/vdm-io/Joomla-Component-Builder/commit/230834057ab5fef3410312fec9029e7e5df59ddb) and let me know how it works.
