### ISSUE TITLE
[Enhancement] Dynamic get - get Item: redirect always in xhtml fails

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#495]
### Steps to reproduce the issue
Set a dynamic get, getItem
Set a site view (let's call it view-a) using this dynamic get
Set another site view (let's call it view-b) with a link to view-a?id=5
id=5 doesn't exists

### Expected result
Redirected to the main view

### Actual result
Redirected to the main view but the page is not loaded because the urls contains &amp; instead of &

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser: 

### Additional comments
Both in local environment and live site

**Comment by Llewellynvdm** [comment]
This does not make sense, can you please explain more.

**Comment by jcodewalker** [comment]
Hello,

Sorry, I’ve been out of city for a long time.

So, setting a get item dynamic get, JCB automatically sets a check for empty result:
                if (empty($data))
                {
                    $app = JFactory::getApplication();
                    // If no data is found redirect to default page and show warning.
                    $app->enqueueMessage(JText::_('COM_COMPONENTNAME_NOT_FOUND_OR_ACCESS_DENIED'), 'warning');
                    $app->redirect(JRoute::_('index.php?option=com_componentname&view=itemslist'));
                    return false;
                }

Now, being Jrouted in xhtml, & becomes &amp; and both in local environment and live sites it fails to find the targeted redirect. If I hard correct the redirect url, changing the &amp; with & it works as expected.

I’ve just noticed that on GitHub bot & and &amp; are displayed as & and my message doesn’t make sense.

I hope now it’s clear.

To let it works, I have to set a custom code to redirect like:
 $app->redirect(JRoute::_('index.php?option=com_componentname&view=itemslist’) false,);

What to set an option in JCB to allow user decide if a check is required or not, and in case it is required, if it must be in xhtml or not?

Thanks in advance.

**Comment by jcodewalker** [comment]
Hello,

Sorry, I’ve been out of city for a long time.

So, setting a get item dynamic get, JCB automatically sets a check for empty result:
                if (empty($data))
                {
                    $app = JFactory::getApplication();
                    // If no data is found redirect to default page and show warning.
                    $app->enqueueMessage(JText::_('COM_COMPONENTNAME_NOT_FOUND_OR_ACCESS_DENIED'), 'warning');
                    $app->redirect(JRoute::_('index.php?option=com_componentname&view=itemslist'));
                    return false;
                }

Now, being Jrouted in xhtml, & becomes &amp; and both in local environment and live sites it fails to find the targeted redirect. If I hard correct the redirect url, changing the &amp; with & it works as expected.

I’ve just noticed that on GitHub bot & and &amp; are displayed as & and my message doesn’t make sense.

I hope now it’s clear.

To let it works, I have to set a custom code to redirect like:
$app->redirect(JRoute::_('index.php?option=com_componentname&view=itemslist’) false,);

What to set an option in JCB to allow user decide if a check is required or not, and in case it is required, if it must be in xhtml or not?

Thanks in advance.

**Comment by Llewellynvdm** [comment]
Okay, I can have a look at this.
