### ISSUE TITLE
Small issue on the actionlog compiler plugin

### ISSUE THREAD

**Issue by vistamedia** [vdm-io/Joomla-Component-Builder#497]
### Steps to reproduce the issue
Just compile any component with the actionlog compiler plugin enabled

### Expected result
Be able to install, update or uninstall the component.

### Actual result
The component cannot be updated or uninstalled anymore.

### Additional comments
As it is a Pro subscription plugin I cannot submit a pull request

Here is the fix:
Open plugins/extension/componentbuilderactionlogcompiler/componentbuilderactionlogcompiler.php

Replace:
```
	protected function getMainPOSTUPDATESCRIPT(&$placeholders)
	{
		$script = PHP_EOL . PHP_EOL . $this->_t(3) . "//" . $this->setLine(__LINE__) . " Create the " . $this->bbb . "component" . $this->ddd . " action logs extensions object.";
```
By:
```
	protected function getMainPOSTUPDATESCRIPT(&$placeholders)
	{
		$script  = PHP_EOL . $this->_t(3) . "\$db = JFactory::getDbo();";
		$script .= PHP_EOL . $this->_t(3) . "\$app = JFactory::getApplication();";
		$script .= PHP_EOL . PHP_EOL . $this->_t(3) . "//" . $this->setLine(__LINE__) . " Create the " . $this->bbb . "component" . $this->ddd . " action logs extensions object.";
```
AND Replace:
```
	protected function getMainUNINSTALLSCRIPT(&$placeholders)
	{
		$script  = PHP_EOL . PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Remove " . $this->bbb . "Component" . $this->ddd . " from the action_logs_extensions table";
```
By:
```
	protected function getMainUNINSTALLSCRIPT(&$placeholders)
	{
		$script  = PHP_EOL . $this->_t(2) . "\$db = JFactory::getDbo();";
		$script .= PHP_EOL . $this->_t(2) . "\$app = JFactory::getApplication();";
		$script .= PHP_EOL . PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Remove " . $this->bbb . "Component" . $this->ddd . " from the action_logs_extensions table";
```

Otherwise the rest works perfectly!!! Thanks for this amazing component builder!!!

**Comment by Llewellynvdm** [comment]
Thank you, I will push a fix out. I did not get that issue since my components have the history integration activated, and so it seems like that is what added those values in the script for me, or so it  seems at a quick glance.
