### ISSUE TITLE
File fieldtype not saving files

### ISSUE THREAD

**Issue by jonasborneland** [vdm-io/Joomla-Component-Builder#498]
### Steps to reproduce the issue
Create new field using the Type: File
Add the field to an admin view
compile the component
Got to the admin view and upload a file with the new file field.
Save

### Expected result
The file path should be presented in the database of the component

### Actual result
doesn´t save

### Additional comments
The fieldtype file seems to be missing "multiple" option too

**Comment by Llewellynvdm** [comment]
Hmm the file field needs some extra help, it is one of those fields that we had to make tutorials to explain its implementation. [Watch this and let me know if you still could not manage](https://www.youtube.com/watch?v=o482sK4DxkM&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=57&t=0s).
