### ISSUE TITLE
PHP (display) * on Admin Views

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#5]
I just upgraded to 2.1.9, and there's an issue with PHP (display) * when creating or editing an Admin View. That field is constantly showing (the toggle doesn't work to disable it), so since it's a required field I am unable to save.
![screenshot_fri_may_20_12 01 59](https://cloud.githubusercontent.com/assets/19194012/15438793/b770e4d8-1e82-11e6-9478-0a5dea71acba.png)
![screenshot_fri_may_20_12 02 13](https://cloud.githubusercontent.com/assets/19194012/15438794/b771e004-1e82-11e6-99eb-7ec155b8f0a1.png)

**Comment by Llewellynvdm** [comment]
Hi please try F5 refresh on the page since it seems like the javascript needes to reload. It is still loading the old javascript. Let me know it this does not solve it.

**Comment by mwweb** [comment]
It looks like that resolved it. I will have to remember to do a refresh whenever I run an update.
