### ISSUE TITLE
Module translateion string not in Language Translations

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#503]
### Steps to reproduce the issue
The language string form a module can't find in the translation table.

### Expected result
Translation strings in Language Translation

### Actual result
None

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
linked to [issue 493](https://github.com/vdm-io/Joomla-Component-Builder/issues/493) as an enhancement request.

**Comment by Llewellynvdm** [comment]
Please test [staging branch](https://github.com/vdm-io/Joomla-Component-Builder/commit/230834057ab5fef3410312fec9029e7e5df59ddb) and let me know how it works.
