### ISSUE TITLE
Not html code in translation string

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#505]
### Steps to reproduce the issue
goto a string that needs to be translated (e.g. a dashboard menuitem).
Add behinf it <br /><br /> as the original is given.

### Expected result
<br /><br /> behind it.

### Actual result
The html tags are removed.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
There are reasons why some areas does not allow html tags, most commonly because the same string is used in multiple locations and will break the code if html remains in the string.

If the dashboard is not working well, you can build your own dashboard with custom admin view.
