### ISSUE TITLE
Use dynamic get data in custom admin view -> custom button

### ISSUE THREAD

**Issue by dyvel** [vdm-io/Joomla-Component-Builder#508]
This is not a component builder issue as such, more a "help wanted" request.

I have created a dynamic get and in my custom view, I have this get as my main get.
In my template I'm using the data from my dynamic get, and all is working as expected here. 

Now, my issue is, I have added a custom button in my custom (single) view, called Export CSV. What I would like to do is, getting the data I see in my custom admin view, into the function that is called when the button is pressed. 

But I can't figure out how to access the data from the query inside my button function. 
Any pointers / help is greatly appreciated.

Thanks

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
You should add a controller method that calls the model method that returns the data in the first place. No need to take the date via the browser, you can server side get the same data.

There are ways to get values from the custom admin view into the controller, with a basic post (with your own button) like we are doing in the compiler area of JCB. So take a look at the JCB package at how we build the compiler area, which is a custom admin view.

Let me know if you have any more questions.

**Comment by dyvel** [comment]
Thank you so much! :-) Figured it out now after looking at the compiler controller...

**Comment by dyvel** [comment]
One question though (just let me know if you don't have time or do not wish to spend time on this). 

Let me try to explain. From my admin list view, I'm selecting an item, and when I press my custom button it leads me to my custom view, where I have a URL like: DOMAIN/administrator/index.php?option=com_bladfil&view=postliste&cid=1

In my custom view I have another custom button, and when pressing that button, I'm getting the data from my custom view inside a my button controller function (public function getCSV()). The URL now changes to DOMAIN/administrator/index.php?option=com_bladfil&view=postliste 

I would like to also pass the data from the item that was selected.

The way I have done it now, I feel is not the best. It does work though. 
I'm getting the cid from the HTTP referer inside my controller function for my button like this:
`parse_str($_SERVER['HTTP_REFERER'], $url);`

Then passing that to the model, to get the item data
`$item = $this->getModel('bladudsendelse')->getItem($url['cid']);`

My button controller function looks like this:

```
public function getCSV() {
	JSession::checkToken() or jexit(JText::_('JINVALID_TOKEN'));
    
	parse_str($_SERVER['HTTP_REFERER'], $url);
	$item = $this->getModel('bladudsendelse')->getItem($url['cid']);
	
	// Get model
	$model = $this->getModel();
	
	// Get items
	$data = $model->getItems();

	// Pass data to the model
	$model->exportMemberships($item, $data);
}
```

I'm thinking there must be a better way to do this?

**Comment by Llewellynvdm** [comment]
Never directly work with `$_SERVER` as this is a huge security risk, always work with the [Joomla API](https://docs.joomla.org/Retrieving_request_data_using_JInput) to access those values like this:
```
$first_url = $input->server->get('HTTP_REFERER', null, 'STRING');
```
Then I would dynamically update the second **url** to have the `cid` as well, so that could look like this:
```
$cid = $input->get->get('cid', 0, 'INT');
$url = JRoute::_('/index.php?option=com_bladfil&view=postliste&cid=' . (int) $cid);
```
The rest of you code looks okay.

**Comment by dyvel** [comment]
Thank you so much for taking the time to answer my question. I understand what I should do, but I don't know how to "dynamically update the second url to have the cid". I know you are busy, so don't spend time on this. I'll try and figure it out :-)
