### ISSUE TITLE
Snippets do not update

### ISSUE THREAD

**Issue by ManfredHuebner** [vdm-io/Joomla-Component-Builder#510]
### Steps to reproduce the issue
Go to GetSnippets and try to load updates for Bootstrap 4 snippets. I see under "New" lots of new snippets. Try to update them by "Bulk" or standalone.

### Expected result
Snippets should get updated into the DB and marked as "equal"

### Actual result
Snippets do not get updated, neither "bulk" or manually.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 5.7
- Apache Version: 2 (running on localhost)
- PHP Version: 7.2
- Joomla Version: 3.9.14
- JCB Version: 2.10.9
- Browser: Firefox

### Additional comments
On my test website on V-Server (Linux) there are no snippets visible at all and JCB do not get Snippets from Git repo. Loading spinner runs and runs ...

**Comment by Llewellynvdm** [comment]
I am actually working in this area, since the Assistant will have what we call plans and it will be json maps that the Assistant can use to build a component. So I have started consolidating the two areas to share code. Yet this is only in the staging branch, but I will run some test, since I did not work on that area for months until now. When last did it work?

**Comment by Llewellynvdm** [comment]
Okay I see there is indeed an error (bug), still debugging it, but it should not be major.

**Comment by Llewellynvdm** [comment]
Okay found it, to patch your JCB [update this line 3392](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/ajax.php#L3392) in the Ajax class as follow:
```
if (($snippet = [[[Component]]]Helper::getGithubRepoData('lib_snippet_' . $base_path, $url, null, 'array')) !== false)
```
The next release should have the fix, since I just pushed the fix to the staging branch.

**Comment by ManfredHuebner** [comment]
Thanks, patch works :-)
