### ISSUE TITLE
Custom admin tabs not showing

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#513]
### Steps to reproduce the issue
Create admin view to a component and add custom tabs (more than one). Add fields to the custom tabs 

### Expected result
When you switch between the tabs all tab related data to show.

### Actual result
Tabs are changing but when you click on the first one it doesn't work. It works if the tab is clicked and after refreshing the page. The inconvenience there is that the user might loss data this way. 

### System information (as much as possible)
- OS Name & Version: Centos 7
- MySql Version: 
- Apache Version: 
- PHP Version: 7
- Joomla Version: 3.9.14  
- JCB Version: 2.10.9
- Browser: Chrome and Mozilla.

**Comment by Llewellynvdm** [comment]
Hi Peter, what type of debugging have you been able to do on this? I mean in the component view, on the PHP side of things. Since JCB is just using Joomla to build those tabs, it does noting on its own really.

Please give me any feedback that you have :+1:
