### ISSUE TITLE
Adminlist tableordering/-sort not working

### ISSUE THREAD

**Issue by tostern** [vdm-io/Joomla-Component-Builder#514]
### Steps to reproduce the issue
Just recognized that the tablesorting selection in the Adminview of a component did not survive, e.g. when using the pagination.

### Expected result
Selected ordering should survive pagination.

### Actual result
Ordering did not work with pagination.

### System information (as much as possible)
- OS Name & Version: Ubuntu 18.04
- MySql Version: 5.7
- Apache Version: 2.4
- PHP Version: 7.2
- Joomla Version: 3.9.14
- JCB Version: 2.10.9
- Browser: Chrome

**Comment by Llewellynvdm** [comment]
Yes I have also noticed this area is broken, we need to change the whole filtering and ordering actually.

**Comment by mabdelaziz77** [comment]
I found a quick workaround until it is fixed.
Edit the file administrator/components/com_componentbuilder/compiler/joomla_3/default.php
replace these 2 lines:
```
<input type="hidden" name="filter_order" value="" />
<input type="hidden" name="filter_order_Dir" value="" />
```
With this:
```
<input type="hidden" name="filter_order" value="<?php echo $this->listOrder; ?>" />
<input type="hidden" name="filter_order_Dir" value="<?php echo $this->listDirn; ?>" />
```
