### ISSUE TITLE
not include folder on site install

### ISSUE THREAD

**Issue by prismadigitale** [vdm-io/Joomla-Component-Builder#515]
### Steps to reproduce the issue
include folder on site view 
see screenshot
![Screenshot42](https://user-images.githubusercontent.com/16606928/73009282-8af60800-3e10-11ea-9ead-77ae6edbee8f.png)

### Actual result
see screenshot
![Screenshot43](https://user-images.githubusercontent.com/16606928/73009293-90ebe900-3e10-11ea-944e-e41f53fd79df.png)

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.14
- JCB Version: 2.10.9

- Browser: 

### Additional comments
In the previous version of component builder this thing worked perfectly now I don't understand why it doesn't work anymore.

**Comment by prismadigitale** [comment]
No I realized that the problem that does not accept empty folders or with hidden files like an .htaccess and I need to put a folder with an .htaccess how can I do?

**Comment by Llewellynvdm** [comment]
This is by design, moving hidden files are not ideal. You could probably use some custom script in the install script (of the component) that moves a regular file and renames it to being hidden. But JCB does not do this out of the box.
