### ISSUE TITLE
Display Custom Field Items in Modal

### ISSUE THREAD

**Issue by philecom** [vdm-io/Joomla-Component-Builder#516]
First of all, I will like to thank you for this great component.

I don't know if what I'm about to request is already there but, can we have a feature where a custom field can display its items in a modal just like Joomla user field for selecting users.

I have a custom field in edit view linked to a table with over 1000 items and I think it will be easy for me to filter and select the particular item if they're displayed in modal with pagination. Thank you.

**Comment by Llewellynvdm** [comment]
JCB does not do this out of the box, but as with all these kind of advance behavior you can in combination of many features in JCB custom code this to work.

I do not have this written out at this time so I could just copy past it over for you. But it can bedone buy building your own custom-custom field.

Watch these tutorials >>

- https://www.youtube.com/watch?v=91iIAuHZj38&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73
- https://www.youtube.com/watch?v=n5RBmP0uNCM&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=74
- https://www.youtube.com/watch?v=Mu9H0zgH9Lw&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=75

IF you need help to code this out we offer [JCB support](https://www.vdm.io/jcb-support) over here.

**Comment by philecom** [comment]
@Llewellynvdm Thank you.
