### ISSUE TITLE
Custom Admin Views problem with pagination

### ISSUE THREAD

**Issue by jibon57** [vdm-io/Joomla-Component-Builder#519]
Hello,

I am trying to create a custom admin view but pagination isn't working because the codes are inseting outside of the `<form>` tag. Possible problem here:

https://github.com/vdm-io/Joomla-Component-Builder/blob/630bfcb1771c1fbcbe62496e2c9e93398a0d7b98/admin/compiler/joomla_3/default_list_custom_admin.php#L30

I think it's better to remove that form & let developer to add their own `form` code or

```
<form action="<?php echo JRoute::_('index.php?option=com_###component###&view=###sviews###'); ?>" method="post" name="adminForm" id="adminForm" class="form-validate" enctype="multipart/form-data">
        ###CUSTOM_ADMIN_BODY###
        <input type="hidden" name="task" value="" />###HIDDEN_INPUT_VALUES###
        <?php echo JHtml::_('form.token'); ?>
</form>
```

**Comment by Llewellynvdm** [comment]
The changes made to this area will break some implementations, but the fix will allow for more correct implementation.
