### ISSUE TITLE
Issue #504 (Custom Code Changes) still not resolved

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#521]
### Steps to reproduce the issue

Upgrade to JCB 2.10.9

### Expected result

Fix in issue #504 should be applied in the compiler class.

### Actual result

No changes made. Issue as noted in #504 still present. Looses any changes made to code on compile.

### System information (as much as possible)
- OS Name & Version: Bitnami LAMP stack on Windows 10
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.9
- Browser: 

### Additional comments

Looks like somehow this change didn't get applied to the latest release of JCB.
Tested/checked on several installs/updates and same thing happens.

**Comment by Llewellynvdm** [comment]
Please make comments on the original post, and check if the actual branch has been merged with the master. I will communicate with you on the original issue, and if needed open it up again.
