### ISSUE TITLE
[BUG?] Add JavaScript (views-file) doesn't add anything to the file

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#522]
### Steps to reproduce the issue
Use demo component
Add JavaScript (views-file) to Looks admin view and add some javascript code (even a comment)

### Expected result
looks.js file in assets/js/ containing the added code

### Actual result
looks.js contains only JCB headers ending with /* JS Document */

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.15
- JCB Version: 2.10.11
- Browser: 

### Additional comments
The file is correctly loaded by the browser and can be inspected with browser inspector

**Comment by Llewellynvdm** [comment]
Thank you! found the issue, not sure when it was changed, since it did work before. But the fix will be to change [line 10205](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L10205) to:
```php
$this->viewScriptBuilder[$viewName_list]['list_fileScript'] = $list_fileScript;
```
I will push out the fix in the next release.
