### ISSUE TITLE
[BUG] Again: lenght lost in field setting

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#523]
### Steps to reproduce the issue
Create new field, save, close, edit the field

### Expected result
Database lenght settled as saved

### Actual result
data lost

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.15
- JCB Version: 2.10.11
- Browser: 

### Additional comments
This bug was already found (#491) and fixed [issue 487](https://github.com/vdm-io/Joomla-Component-Builder/issues/487)

**Comment by Llewellynvdm** [comment]
@jcodewalker please lets communicate further on the original issue, so we can keep things together.

**Comment by Llewellynvdm** [comment]
The note in the readme of JCB says:

> Then if you run into any issues, related to the JCB code, like bugs, start by searching the (**open & closed**) issues over on Github, and **if the issue has not been mentioned before, then only open a new issue**, following the community guidelines.

So old issues, must be addressed where they exist in the issue stream instead of having duplicate issues all over the place about the same issue.

Thank you for your understanding.
