### ISSUE TITLE
hidemainmenu set to true on custom view as dashboard - bug?

### ISSUE THREAD

**Issue by dyvel** [vdm-io/Joomla-Component-Builder#529]
Hi
I've created a custom view and set it as a dynamic dashboard. Doing so, adds hidemainmenu = true to the view.html.php in the addToolBar function. 

Normally hidemainmenu = true is only when editing something, but this is not the case in the dashboard, so I'm thinking I'm missing something, or perhaps this is a bug?

### Steps to reproduce the issue
Create a custom view
Add it as a dynamic dashboard

### Expected result
Joomla menu still accessible fra the dashboard

### Actual result
Joomla menu is not accessible

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 7.2.28
- Joomla Version: 3.9.15
- JCB Version: 2.10.11
- Browser:

**Comment by Llewellynvdm** [comment]
Please give me some screen shots.

**Comment by dyvel** [comment]
I've created a short video instead, as it was easier to explain this way :-)
https://drive.google.com/file/d/1PPSE2fzykd_DRtOKTZnSMxJxCx3gzovv/view?usp=sharing

**Comment by Llewellynvdm** [comment]
I see, yes let me look.In JCB the `compiler` view, which is also a custom admin view does not hide the main menu, but the `get snippets` view does. Lets look at this...

Okay this seems to be a lazy me... we do in fact have the default of the tow hard coded files of both [list](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/compiler/joomla_3/JViewLegacy_list_custom_admin.php#L53) and [single](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/compiler/joomla_3/JViewLegacy_custom_admin.php#L53) custom admin views.

So we see in the [compiler view the same](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/compiler/view.html.php#L308), but here in the view [I override it](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/views/compiler/tmpl/default.php#L15). So in JCB this is the area I added the override:
![image](https://user-images.githubusercontent.com/5607939/76671421-df12a280-659e-11ea-927f-d7766f12630f.png)

We can therefore say by default it is false, and you can make it true with this little line:
```php
$this->app->input->set('hidemainmenu', false);
```
That you can add in the _PHP (custom view script) *_ area, under the _PHP_ tab of the custom admin view.

We could make this a switch I suppose.... that would have been more easy to understand.

**Comment by dyvel** [comment]
Thank you! I got it working now.
I would think that a dashboard should always set hidemainmenu to false, but at least now I know how to change it. :-)

**Comment by Llewellynvdm** [comment]
I think you are right, when an custom admin view gets used as a dashboard we should fix the hidemainmenu to be false. I will see how I can fix this.

**Comment by Llewellynvdm** [comment]
@dyvel I have made some changes to fix the behavior, let me know if this works better for you.
