### ISSUE TITLE
Export & Import of JCB mapped component.

### ISSUE THREAD

**Issue by ro-ot** [vdm-io/Joomla-Component-Builder#53]
The feature request has been made to export JCB mapped components, and the ability to import that exported package.

**Comment by Llewellynvdm** [comment]
This will be amazing :) are you up for the challenge?

I think it should be a Json or SQL dump file (with a possible key for encryption and decryption), and that the import should make use of the default import of each view.

I will add a new custom admin view to import and export components. @ro-ot you will need to build the import and export logic. I will bump the private repo with the changes, or lets use a branch.

Let me know.

**Comment by ro-ot** [comment]
Yes I think this is a very needed feature. I will start with the logic.

Lets do a public branch called dev or staging

**Comment by ro-ot** [comment]
The zipped json file seems best. What do you mean with 

> a possible key for encryption and decryption

**Comment by Llewellynvdm** [comment]
okay so json it is... how will we deal with the images, files and folders linked to the component? that would need to be part of the zip file.

The ability to lock the data so no one can use it unless they have the key used to export it. There should be the option for a global key per component. Basically to insure if you use this feature as a backup of your components, it is secure where ever you store it.

That brings up another feature, the option to setup this concept to constantly run and with this feature run backups to an FTP location or local folder, like that used during compilation.

I can add the above feature once we have the basic functionality in place.

**Comment by ro-ot** [comment]
Yes that is why I said zipped. So we can add other files,folders and images to this package. 

The locking option is great, but could be to much for the initial development. I will see what is the time frame I have to do this.

**Comment by ro-ot** [comment]
You said to use the default import option per view, does that not work with CSV's instead of json?

**Comment by Llewellynvdm** [comment]
Wow you are right... so let me take a look at this, csv could work.... but then we will have one per view, which is not a problem.

I will get back to you on that one.

**Comment by Llewellynvdm** [comment]
I think the csv could work, we will just have to insure that the code data remains in base64 as it is stored in the DB, so we will need some tweaking there.

**Comment by ro-ot** [comment]
I think we should still use JSON as the data storage, it seems like the easiest way, and it is much more stable.

I main the data linking is in json objects in the DB and all those ids in those objects will all change in most cases during importing of a component. I think we can better manage the relationships in json.

**Comment by Llewellynvdm** [comment]
I have used serialized on the db data and stored it in our own db.vdm file since in the long run this data should only work in JCB right.

I will still add the images, that has not been done as yet.

Next the import part, this will be tricky :1st_place_medal:

**Comment by ro-ot** [comment]
Great work @Llewellynvdm I agree with the direction you took. I think we have an amazing feature here. This can become a key aspect!

I can't help with the import at this time, so if you want to do it go right head. But it seems might complicated!

**Comment by ro-ot** [comment]
Wow this is amazing stuff. Thanks @Llewellynvdm for making this happen!

**Comment by Llewellynvdm** [comment]
https://youtu.be/lkE0ZiSWufg see it in action...

**Comment by mwweb** [comment]
I just decided to give this a test, and getting an error. I downloaded a fresh copy of Joomla and did a compare between my installed version, and the fresh download, and the files match.

Warning: Header may not contain more than a single header, new line detected in C:\xampp\htdocs\dev\libraries\joomla\application\web.php on line 947

Error
An error has occurred.
1054 Unknown column 'a.*' in 'field list' SQL=SELECT `a`.`*` FROM `gax8s_componentbuilder_joomla_component` AS `a` WHERE a.id IN (25) ORDER BY a.ordering ASC
Call stack
#	Function	Location
1	JApplicationCms->execute()	C:\xampp\htdocs\dev\administrator\index.php:51
2	JApplicationAdministrator->doExecute()	C:\xampp\htdocs\dev\libraries\cms\application\cms.php:261
3	JApplicationAdministrator->dispatch()	C:\xampp\htdocs\dev\libraries\cms\application\administrator.php:152
4	JComponentHelper::renderComponent()	C:\xampp\htdocs\dev\libraries\cms\application\administrator.php:98
5	JComponentHelper::executeComponent()	C:\xampp\htdocs\dev\libraries\cms\component\helper.php:380
6	require_once()	C:\xampp\htdocs\dev\libraries\cms\component\helper.php:405
7	JControllerLegacy->execute()	C:\xampp\htdocs\dev\administrator\components\com_componentbuilder\componentbuilder.php:56
8	ComponentbuilderControllerJoomla_components->smartExport()	C:\xampp\htdocs\dev\libraries\legacy\controller\legacy.php:702
9	ComponentbuilderModelJoomla_components->getSmartExport()	C:\xampp\htdocs\dev\administrator\components\com_componentbuilder\controllers\joomla_components.php:160
10	JDatabaseDriverMysqli->execute()	C:\xampp\htdocs\dev\administrator\components\com_componentbuilder\models\joomla_components.php:122

**Comment by Llewellynvdm** [comment]
Did you do a fresh install of JCB? on a Joomla website that is also fresh?

**Comment by ro-ot** [comment]
@mwweb to test pull request is little more tricky then what you did. @Llewellynvdm can you not make a quick video on how this should be done... please :+1:

**Comment by mwweb** [comment]
@ro-ot... this was testing the export component feature in jcb 2.4.0. That's where the error is occurring.

**Comment by Llewellynvdm** [comment]
Please make the comments on the pull request that is being tested. Here is a quick tutorial.. [hope it helps](https://youtu.be/cxryVA5Cni8)

@mwweb the bug that you found does not exist that is why I asked if it is a fresh install :)

If you open the code of [\com_componentbuilder\models\joomla_components.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/joomla_components.php#L104) on line 104 you will see that the `Unknown column 'a.*'` that it is giving as a warning is not an error, but normal JDatabase syntax that is used in all over the place. 

Check your local file if it is the same on that line ;)

**Comment by mwweb** [comment]
Fresh Joomla install on CentOs (account on my web server).
Fresh install of JCB 2.4.1
Went to Components -> Component Builder -> Joomla Components
Selected Demo Component
Click Export Components button

Result:

An error has occurred.
1054 Unknown column 'a.*' in 'field list' SQL=SELECT `a`.`*` FROM `#__componentbuilder_joomla_component` AS `a` WHERE a.id IN (25) ORDER BY a.ordering ASC

**Comment by Llewellynvdm** [comment]
I am sorry, I will look at this again, not sure how we missed this. Will get back to you soon. Thanks!

**Comment by Llewellynvdm** [comment]
@mwweb, hi Download [this version](https://github.com/vdm-io/Joomla-Component-Builder/archive/master.zip) and let me know if your error is resolved.

**Comment by mwweb** [comment]
That works. No error, and it created the zip file in the tmp folder.

**Comment by mwweb** [comment]
I know is a closed issue, but I just tested it and noticed some "odd" behavior. When attempting to export, all of the images (component image and dashboard images) are throwing errors. See a sample below:

JFile: :copy(/var/www/mwredev/images/component_images/MWR_3D_Box-right.png, /var/www/mwredev/tmp//JCB_mostWantedRealEstate/images/component_images/MWR_3D_Box-right.png): copy(/var/www/mwredev//tmp//JCB_mostWantedRealEstate/images/component_images/MWR_3D_Box-right.png): failed to open stream: No such file or directory

Notice that when it's attempting to "create" the tmp path that it is adding double // rather than a single( mwredev//tmp// )

**Comment by Llewellynvdm** [comment]
Okay, I have added some new code to try and fix this. But we need to look little closer at this, the fix is not ideal. It will work but ugly :-1: 

But if this happens again, I mean you find a bug that was already reported and then closed few days ago (if closed like few minutes ago, no problem :+1:) but if a few days ago, then please open a new issue and just refer to the closed issue. That way all issues are active that needs attention :) So all can see the issue is back. Now only those who were linked in this conversation will see it.

> _Like this:_
> Hi in issue #54 there was a typo in the compiler. It is back...

I will add the fix to the active pull request, then you can test it there and comment on it there :+1:
