### ISSUE TITLE
Broken HTML

### ISSUE THREAD

**Issue by jibon57** [vdm-io/Joomla-Component-Builder#530]
Hello,

https://github.com/vdm-io/Joomla-Component-Builder/blob/86f671c87cd99172230e7bb71a988414a4fb9ce8/admin/compiler/joomla_3/default_main.php#L27

Here I think we should strip html tags otherwise it will break html list because of extra `<br>`. So like this:

`<span class="dashboard-title"><?php echo strip_tags(JText::_($icon->name)); ?></span>`

**Without strip tag:**

![image](https://user-images.githubusercontent.com/6080277/76695985-2fc5f080-66b0-11ea-9b5d-ff1012d8495d.png)

**Comment by Llewellynvdm** [comment]
[Here we want](https://github.com/vdm-io/Joomla-Component-Builder/blob/86f671c87cd99172230e7bb71a988414a4fb9ce8/admin/compiler/joomla_3/DASHJModelList.php#L107) the `<br /><br />` to be added to the icon name, so the strip will break the layout in that instance.

What we really needed, is this whole dashboard area must be refactored. We need to add better control over this area for the developers, also more options beyond what is now possible.
