### ISSUE TITLE
Encryption on a component config field (textfield) doesn't seem to be working

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#532]
### Steps to reproduce the issue
Create a textfield with encryption set to medium or basic.
Add this field to the component config in it's own tab.
Install component
Fill in the component config fields
Set 32char key for encryption
Set path to folder outside public_html (/home/user/domains/domain.nl/jcbsafe)

### Expected result

See data in DB encrypted.
See a encryption file in the specified folder

### Actual result

Data is there as plain text
No encryption file created in specified folder.

### System information (as much as possible)
- MySql Version: 10.4.11-MariaDB
- Apache Version: 2.4.41
- PHP Version: 7.3.13
- Joomla Version: 3.9.16
- JCB Version: 2.10.11
- Browser: Firefox 74.0

**Comment by Llewellynvdm** [comment]
Can you give a screenshot of the save method where the field is modeled, and so of the getItem method where the field is retrieved. I need  to see it it did add the php. Then if it did, then your next option is to check that your database field type is large enough to store the encrypted value. Usually text is the bet choice.

**Comment by TLWebdesign** [comment]
Yeah i don't think those exist. I only use these fields as component configuration params (not inside any views). So they live only in the config.xml if i'm correct (my search of the fieldname inside the component didn't find anything about this field anywhere) The fields hold credentials of an api i'm using (TextKernel) to parse resumes.

**Comment by Llewellynvdm** [comment]
I mean the code in the model, I need to see those. Those methods exist :)

**Comment by Llewellynvdm** [comment]
Ahaa that is way, JCB only manages the model of your admin views, it does not manage the config component. So if you want to use encryption you will need to add the fields to an admin view.

**Comment by TLWebdesign** [comment]
Thanks for the explanation! :) Figured it was just something that JCB didn't do in that area. No problem.
