### ISSUE TITLE
greek characters issue on list field

### ISSUE THREAD

**Issue by nikkolaos** [vdm-io/Joomla-Component-Builder#533]
### Steps to reproduce the issue
1. Create a new field of type list.
2. In the option field, insert some key|value combinations with greek characters, for example:
0|Είδος
![jcb-list](https://user-images.githubusercontent.com/61727664/77088260-de4d9680-6a0c-11ea-8261-24b94704318c.jpg)
,1|Τύπος,2|Δοκιμή,3|Τεστ

### Expected result
Have a list dropdown field that shows four options to select from.

### Actual result
You get the list dropdown field, all the keys 0-3 are in place but the actual text is the same in all four items.  Please see the attached screenshot.

### System information (as much as possible)
- OS Name & Version: Debian 9
- MySql Version: MariaDB version 10.1.44
- Apache Version: 2.4.25
- PHP Version: 7.3.15
- Joomla Version: 3.9.16
- JCB Version: 2.10.11
- Browser: Chrome

### Additional comments
- In Database, I used Data Type (VARCHAR)(255)(Collation: None) and Field Modeling Method (JSON).
- When I do exactly the same with latin characters, everything is working fine.
- Are the options translatable? If yes, one could maybe enter the translation token and then translate.

**Comment by Llewellynvdm** [comment]
Please build your component with the Latin alphabet (English GB), and then via the translation area add the Greek translation. 

There is another alternative of the correct transliteration option in JCB, please read over [issue 789](https://github.com/vdm-io/Joomla-Component-Builder/pull/483#issuecomment-541100660), you will see that you will need to change the main language of your system to greek.

**Comment by nikkolaos** [comment]
This will do the work.

Thank you for revealind issue 483 and the fast reply.
