### ISSUE TITLE
Module Marking comments

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#534]
### Steps to reproduce the issue

Create and install module.

### Expected result
Module content to appear without the comment part

### Actual result
/***[JCBGUI.joomla_module.default.1.$$$$]***/
/***[/JCBGUI$$$$]***/

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.11
- Browser: 

### Additional comments
When you export the module you can see that the comments are out of the php tags.

**Comment by Llewellynvdm** [comment]
I am not sure I understand, the modules will add the placeholder tags if you have it set for the component it is linked to, and if you remove it from the component it will also remove the placeholders from module.

I have a number of modules and it works as expected, please explain more.

**Comment by peterpetrov** [comment]
[Image]

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by peterpetrov** [comment]
this is what i get

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peterpetrov** [comment]
![Screen Shot 2020-03-20 at 10 16 51](https://user-images.githubusercontent.com/2786810/77146562-ff0cff00-6a93-11ea-8d56-afc50a10c331.png)


Sorry about the previous messages. This is what i get. The comments are out of the php tags and coming out as plain text. Here is a screenshot form the code part:



![Screen Shot 2020-03-20 at 10 18 55](https://user-images.githubusercontent.com/2786810/77146663-3da2b980-6a94-11ea-8b13-f3138a489c23.png)

**Comment by Llewellynvdm** [comment]
Yes now I understood, here is a small issue, should be able to fix easy.

[On line 6592](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L6592) in the get class of the compiler **add** the following new line:
```php
$guiMapper['type'] = 'html';
```
Let me know if this resolves it, then I will add it to the next release.

Make sure to close your PHP which you are adding to the **default html** area.

**Comment by peterpetrov** [comment]
Is this the stage branch? I am using the stable release at the moment.

**Comment by Llewellynvdm** [comment]
Okay in the master branch on [line 6523](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/a_Get.php#L6523) is where you must add the new line, note don't remove anything, just add.

**Comment by peterpetrov** [comment]
I guess si have to re-compile JCB maybe? I will check and let you know.

**Comment by Llewellynvdm** [comment]
No, just adding that line and recompile the module should be enough. (must be added to the code of the JCB you are working in)

**Comment by peterpetrov** [comment]
Thanks. I confirm it worked.

Thanks.
