### ISSUE TITLE
Confusing message in 'Notice Board' for JCB Pro

### ISSUE THREAD

**Issue by shoulders** [vdm-io/Joomla-Component-Builder#535]
### Steps to reproduce the issue
Login to the joomla admin and go to the **notice board** section of JCB and read the messages on the feed. 

### Expected result
- The **get the pro links** should go to a single page on https://www.joomlacomponentbuilder.com/ outlining there what you get for the subscription.
- Maybe explain more on what the individual plugins you will get in some more depth on this page.
- The price of the subscription should be easiy to find on this page. As of now I have not found this and I am not going to sign up to the **open collective** on the off chance it might tell me.
- explain what **open collective** is and why you are using them.

### Actual result
The link https://vdm.bz/get-jcb-pro-membership takes me to a confusing page **open collective** asking me for details which at this point I do not want to give. I do not know what the **open collective** is and I am not sure what I am signing up to or why.

### System information (as much as possible)
- OS Name & Version: Windows 10 1903
- MySql Version: 5.5.5-10.4.10-MariaDB 
- Apache Version: Apache/2.4.41 (Win64) OpenSSL/1.1.1c 
- PHP Version:  PHP/7.3.12 
- Joomla Version: Joola 3.9.16
- JCB Version: 2.10.11
- Browser: Firefox 74.0

### Additional comments

For me as an amateur Joomla programmer things like this are confusing and considering you are aiming this software at amateurs Joomla programmers it would be a good thing if you can clear all of this this up so more people can consider buying the subscription either for the additional software or just to support JCB.

The **open collective** page is very messy and confusing.

Keep up the good work.

thanks

**Comment by Llewellynvdm** [comment]
JCB does not make free coffee just yet... but we will get there :+1: 

Thanks for your input I will see what I can do... hope to see you become a pro-member **soon**, as its main objective is to support the **future of JCB**.

As an amateur Joomla! programmer you **_must remember_** projects like **JCB** can only continue to exist if **you**, the community financially support the developers and other key players that work on the project full time.

Pro-members are doing that and getting a bonus for doing so.

But yes can't hurt to make all that easier for other to understand. If you have the time [setup a meeting with me](https://vdm.bz/get-meeting-llewellyn) and we can look at our options.

**Comment by shoulders** [comment]
@Llewellynvdm I will be in touch in the near future. I have had an accident in my garden so I am not firing on all cylinders at the minute. What meeting software do you use?
