### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by Polm90** [vdm-io/Joomla-Component-Builder#539]
I'm using the last version of Joomla (3.9.16) and the last version of the component builder (2.10.3).

Since a couple of days ago, the component builder stopped to save anything. Everytime I press "save" or "close" or "save & close", the site redirects to administrator/index.php?option=com_componentbuilder&layout=edit&id=111 but displaying the component builder dashboard (and data is not saved on db).

The generated component has the same issue. But if I try not with a SuperUser account, it works properly.
I've noticed that with the SuperUser account, the http request done to save, returns a 200 code (and have many more fields, such as the component permissions fields) while with the not SuperUser account returns a 303 code.

The strange thing is that the same site (with the same code) runs correctly locally; I've already tried to reinstall the site, replacing the code with the local copy but the issue persists. The issue started suddenly, without I've changed anything.

What can I do to fix it?

**Comment by Llewellynvdm** [comment]
This sounds like a environment issue not a JCB issue. I am using JCB and component build with JCB on various servers and environments, yet none is showing this behavior.

Check your logs of Apache, Mod_sec, and PHP

Let me know if you find out any more details.

**Comment by Llewellynvdm** [comment]
O yes and JCB is on v2.10.13, make sure you are on this version.

**Comment by Polm90** [comment]
Thank you for your suggestion. I've found that I needed to increase (in the php.ini file) the number of input variables that can be send in a form request to the server.
Now it works again!
Thank you!

(the JCB version was already 2.10.13...I forgot a "1" in my first post)
