### ISSUE TITLE
Typo in compiler

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#54]
It was pointed out to me by a partner that there is a typo in the compiler, which is compiling "catagory" rather than "category". This then shows the typo on the dashboard, and in the language files.

It looks like the use of "catagory" is in 2 files in the compiler, and possibly 3 locations within e_Interpretation.php

administrators/components/com_componentbuilder/helpers/compiler/e_Interpretation.php (3 hits)
administrators/components/com_componentbuilder/script.php (52 hits)

e_Interpretation.php

Line 3694:
					$dbStuff[$view.' catagory'] = $this->getCategoryContentType($view, $views, $component);

Line 9634:
			$allow[] = "\t\t\t\t//".$this->setLine(__LINE__)." set catagory id";

Proper spelling would be "set category id"

Line 11151:
						$langName = 'Catagory &nbsp;For<br />'.ComponentbuilderHelper::safeString($otherViews, 'W');

**Comment by Llewellynvdm** [comment]
Thanks, I am terrible with spelling...  strange as that is.
