### ISSUE TITLE
Issue compiling an administrator module

### ISSUE THREAD

**Issue by vistamedia** [vdm-io/Joomla-Component-Builder#541]
### Steps to reproduce the issue
Create a simple admin module with nothing inside
![2020-04-23_22-54-25](https://user-images.githubusercontent.com/9335926/80148489-69462180-85b5-11ea-8173-6d3a00e309c5.jpeg)

### Expected result
An installable module

### Actual result
![2020-04-23_22-40-10](https://user-images.githubusercontent.com/9335926/80148571-8aa70d80-85b5-11ea-93ff-3ca3f1e628fa.jpeg)

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser: 

### Additional comments
In the xml file client="admin" instead of client="administrator". This is the reason of the bug. If I edit the XML file and replace admin by administrator it functions properly.

**Comment by Llewellynvdm** [comment]
Can you test this fix?

On line [8168](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L8168) in the get class of the compiler
```
$module->target_client = 'administrator';
```
This should resolve the issue, please confirm.

**Comment by vistamedia** [comment]
Yes Llewellyn it works like charm! Merci :)
