### ISSUE TITLE
Feature request: add custom header to admin classes

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#548]
### Steps to reproduce the issue
like we can do in site side, it would be nice to be able to add custom header in admin side as well, so we can use some core utilities like:
use Joomla\Utilities\ArrayHelper; // just an example...

Perhaps it could be added in "Custom Buttons" area..?

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
There is three three areas, Model, View, and Controller. Where exactly would you like this added?

**Comment by jcodewalker** [comment]
Well, the most the better...
Said that, so far I needed to add something only in Controller (single, meant "edit" Controller to better process posted data).
Thank you.

**Comment by marcorensch** [comment]
+1 for intergration in Model

**Comment by Llewellynvdm** [comment]
https://www.youtube.com/watch?v=TjoH5rj4UgM
