### ISSUE TITLE
Almost every Admin list screen needs a Component filter dropdown

### ISSUE THREAD

**Issue by Sophist-UK** [vdm-io/Joomla-Component-Builder#549]
### Steps to reproduce the issue
Install e.g. Component Builder as a Component then go and try to find your own Fields amongst those of CB.

### Expected result
Ability to filter by component so that you can see the wood from the trees / wheat from the chaff.

### Actual result
A lot of scrolling.

### System information (as much as possible)
- JCB Version: 2.10.13

**Comment by Sophist-UK** [comment]
P.S. Filter should be persistent i.e. if you are working with a filter for a specific component and you switch screens you should still only see stuff from the selected component.

**Comment by Sophist-UK** [comment]
Fields do not appear to be associated with a component - yet they are the object most frequent and in need of filtering.

**Comment by Llewellynvdm** [comment]
This is a great idea, but in terms of time I am not able to commit time to this, you are welcome to give code suggestions if you have time. Until then I will close the issue, but soon as you want to take it further, please do not open a new issue, just bump this issue and I will reopen it at that time.
