### ISSUE TITLE
Field filter only works partially

### ISSUE THREAD

**Issue by Sophist-UK** [vdm-io/Joomla-Component-Builder#550]
### Steps to reproduce the issue
1. Import CB WOW.
2. Create several fields starting rp_
3. Filter by rp_

### Expected result
Only the fields starting rp_ are shown

### Actual result
Many of the CB fields are also shown

### System information (as much as possible)
JCB Version: 2.10.13

**Comment by Llewellynvdm** [comment]
I am not sure I understand the issue, but I would point you to watch the tutorials to fully understand how the components get connected to fields, and how to be able to see on fields that are linked to a admin-view is in fact possible in the admin-views themselves.

If you already understand the above, and I have not understood the issue let me know and I will take another look. Until then I am closing this issue. No need to create a new issue if you want to continue the conversation... just reply on this one, and if your request is ready for action I will reopen this issue no problem :+1:

**Comment by Sophist-UK** [comment]
My request is a simple one. If you have multiple components defined in JCB - which in many/most cases will be independent of one another, you will tend to be working on one component at any point in time and it therefore seems to me to be helpful if you can limit what is displayed in lists to the one component that you are working on.

So in the filter list in the side bar, I would like to see a filter for Component, and for this to be persistent as you switch between admin lists.

**Comment by Llewellynvdm** [comment]
Okay then sounds like the same request as you made in issue #549 and the same can therefore be said.

Meaning: This is a great idea, but in terms of time **I am not able to commit time to this,** you are welcome to **give code suggestions** if you have time. Until then I will keep this closed, but soon as you want to take it further, please do not open a new issue, just bump this issue and I will reopen it at that time.

I appreciate your willingness to contribute ideas, this particular idea has been a long standing one, so its not new. Hopefully you can help make it happen.

**Comment by Llewellynvdm** [comment]
Yet please take note, that you can indeed see only the fields related to an admin_view when you open the admin_view and look under the fields tab.
