### ISSUE TITLE
Feature request: extend <> JTable

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#551]
### Steps to reproduce the issue
I can't find a way (othen than **_Custom Coding_** the table file) to extends the JTable_**Something**_ instead of JTable, not in admin view setting nor in dynamicGet (to use in a custom view).
If there is already a way, please let me know.
Thanks

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
Yes this is indeed not doable as yet... but we are working towards that specially with Joomla4 in view. Until then custom code to the rescue... :+1:
