### ISSUE TITLE
Component Updates - 500 Internal Serever Error - Error decoding JSON data

### ISSUE THREAD

**Issue by sshlord** [vdm-io/Joomla-Component-Builder#552]
### Steps to reproduce the issue
I have a component with 100 versions and a lot of mysql changes, and in the component updates pannel gives error on open.

### Expected result
See Component Updates versions

### Actual result
In Console - 500 Internal Serever Error
In Browser Page - Error decoding JSON data: Control character error, possibly incorrectly encoded

### System information (as much as possible)
- OS Name & Version: Ubuntu 18.04 server
- MySql Version: Ver 15.1 Distrib 10.1.38-MariaDB
- Apache Version: 2.4
- PHP Version: 7.2
- Joomla Version: 3.9.18
- JCB Version: 2.11.0
- Browser: Chrome

### Additional comments
I think this isssue is caused by type of version_update column in DB, that now is TEXT and i think it needs to be LONGTEXT.
I've checked the in the table and for the last update the JSON is cutted and incomplete... so, it gives error on decoding.

**Comment by Llewellynvdm** [comment]
Can you manually update the mysql table and test to see it it resolves the issue, then you may need to cut down the number of updates by adding version step-up. Meaning that lets say the first 30 changes until version 2.3.0 and then the next 50 up to version 2.4.0 and so on...

Basically consolidating the changes.

But okay as a start manually change the database table, and then let me know, not a huge problem for us to enlarge it. But any component with that many updates will become a challenge.

**Comment by sshlord** [comment]
I already updated the mysql column to LONGTEXT and repaired the JSON string. Now things are back to normal, i can see all component updates.

And yes you are right you can enlarge it but in future can be a performance issue when needs to read and write that huge JSON string.

Thanks for the idea with version step-up.
