### ISSUE TITLE
Calendar field in Repeatable does not show calendar

### ISSUE THREAD

**Issue by sshlord** [vdm-io/Joomla-Component-Builder#553]
### Steps to reproduce the issue
A repeatable field with 4 fields in it. First 3 are Custom and last one is Calendar. I can't add more than 5 groups of fields and calendar doesen't open when clicked.

### Expected result
Add more than 5 repeated group of fields and Calendar show the calendar when clicked.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser: 

### Additional comments
Sometimes i receive in console messages that says that calendar field have duplicated id.

**Comment by Polm90** [comment]
I have the same issue...
And one more...
If I save the form, the repeatable field is received by the server with 10 values for each field in the subform, even if I've added less than 10 rows in the repeatable. The extra values are all null.
If in the repeatable field there are 2 calendar fields, the values sent to the server are always 20.
If I remove the calendar fields from the repeatable field, the values sent to the server are correct (no extra null)

**Comment by Llewellynvdm** [comment]
Okay this is a Joomla issue, not JCB. Since JCB just setup the XML for the repeatable fields, Joomla generates the fields and saves it. So when I last had a look at this Joomla did not even allow calendar fields in the repeatable fields. So if it does allow it now... then this is already a step-up for them.

Then another point, do not use repeatable fields, rater use the subform field. Repeatable fields are discontinued in Joomla 4.

**Comment by Polm90** [comment]
Ok, but using a subform, data are saved on the db but when I try to edit an entity, the subform is always empty...can you help me?

**Comment by sshlord** [comment]
Tried the subform and worked on second try :) First time didn't created the column in DB, changed the name of field and returned error on build when tried to change the name. I've created the column mannualy in DB with old name and build it again... and this time worked.

Didn't tried yet the callendar in Subform but i will try it and let you know if is working.

**Comment by Polm90** [comment]
Ok, i got what I was doing wrong... I set the field modelling method on the database tab to JSON instead of Default. Setting Default it works properly. Thank you.
