### ISSUE TITLE
Feature request: site single view model redirect using return variable if set

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#556]
### Steps to reproduce the issue
Site side, single view (dynamic get: getItem), model file:
it'd be great if it could check for a return variable set in the url and if so use it instead to redirect the user to Juri::root() or should be editable to avoid a custom code

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
Can you not just code this in? Using the **Add PHP (before getting the Item)** area, you can get the value from the url, and then act upon it accordingly.

**Comment by jcodewalker** [comment]
Yes, sorry, forget to add "in access level checking routine", which is automatically added by JCB:
`		$this->user = JFactory::getUser();
		// check if this user has permission to access item
		if (!$this->user->authorise('site.view.access', 'com_component'))
		{
			$app = JFactory::getApplication();
			$app->enqueueMessage(JText::_('COM_COMPONENT_NOT_AUTHORISED_TO_VIEW_ISSUEADD'), 'error');
			**_// redirect away to the home page if no access allowed.
			$app->redirect(JURI::root());_**
			return false;
		}
`

**Comment by Llewellynvdm** [comment]
This feature can be removed, by when you add the site view, to uncheck the access option:
![image](https://user-images.githubusercontent.com/5607939/82091662-0c431480-96f8-11ea-9238-ec97ce3931b8.png)
or to have it checked and then to make it public. Then after you can add your own code as I explained before.

**Comment by jcodewalker** [comment]
With JCB v2.10.13 it still doesn'r work.
Please, try it out. Add access and public access by default.
