### ISSUE TITLE
Custom field using concat as values

### ISSUE THREAD

**Issue by Polm90** [vdm-io/Joomla-Component-Builder#558]
I'd like to create a custom field using a concatenate value.

For example:
I have a table with id, name and surname columns.
I would like to have a custom field that use the 'id' as key_field and 'CONCAT("name", " ", "surname")' as the value_field (so that the user will be able to see the fullname in the select).

Is it possible to do?

Thank you

**Comment by Llewellynvdm** [comment]
Yes, with custom coding, also depend where you want this effected. To store the value concatenate during save, or to display the value concatenate on retrieval. With each have options there is very easy path to code it actually.

Let me know where you want it done, and I can give better direction. This is actually a forum post.

**Comment by Polm90** [comment]
I want to display the value concatenate on retrieval!
Thank you

**Comment by Llewellynvdm** [comment]
Currently the dynamicGet when using the GUI does not make provision to add `CONCAT("name", " ", "surname")` to the query code. You can when adding your own custom SQL achieve this.

The other option would be to combine them after getting the values from the DB in the `Add PHP (after getting the Items)` or `Add PHP (after getting the Item)` area with PHP.

**Comment by Llewellynvdm** [comment]
I have not hear back from you so I assume this is resolved. Should this not be the case, just comment on this issue again and we will reopen it if needed.
