### ISSUE TITLE
Use Global Option is shown in admin view even if set to false or 0

### ISSUE THREAD

**Issue by marcorensch** [vdm-io/Joomla-Component-Builder#562]
### Steps to reproduce the issue
Create a new field of type list
Set useglobal to false or 0
attach it to an admin view

### Expected result
if useglobal is set to false or 0 it should not show the "Use Global" option in the select list

### Actual result
It shows the "Use Global" option always if something is set as value for useglobal, even if its set to false or 0. 

### System information (as much as possible)
- OS Name & Version: MacOS 10.15.4
- MySql Version: 5.7.26 
- Apache Version: 
- PHP Version: 7.4.2 
- Joomla Version: 3.9.18
- JCB Version: 2.11.2
- Browser: Firefox

### Additional comments

*Workaround*
Empty the useglobal option in the field settings to not show the "Use Global" option in the select list.

**Comment by Llewellynvdm** [comment]
The Category field behavior is really fully managed by Joomla. This is the documentation, but to see it work, or to see the best practice you should import the [SermonDistributor](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/admin/models/forms/sermon.xml#L158) [JCB](https://vdm.bz/how-to-install-jcb-packages) package. The SD use the category field in a very strait forward way.

You can also see it in [action in JCB itself outsource](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/forms/field.xml#L225), and there [is this turorial](https://youtu.be/9NO2rKnC6Ug?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&t=29m24s).

**Comment by marcorensch** [comment]
i am not talking about the category fieldtype - its the list fieldtype that works unexpected

**Comment by Llewellynvdm** [comment]
Woops completely wrong post... lol

Sorry not sure how that happened, let me see the list option... hmmm let me see, jsut remove the property completely and it will not show :+1:

**Comment by Llewellynvdm** [comment]
That field is also completely managed by Joomla, in fact all fields are.

So looking at the [code where that happens in Joomla](https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/joomla/form/fields/list.php#L181), you see that only if the field is missing does in not load, so adding it makes it load. You can jump into the code and see why its  behavior is wrong, yet to fix it you must make a pull request to Joomla.

**Comment by Llewellynvdm** [comment]
Seems like the false is converted to a string, instead of a boolean. So in the GUI I have removed the **false**, and left the field empty as you suggested. Thanks!

**Comment by Llewellynvdm** [comment]
Just note that this change will not reflect in any existing installed, to effect that change once I pushed it out [watch this tutorial](https://www.youtube.com/watch?v=dv31jFBSlwc) to understand the path to update fieldtypes.
