### ISSUE TITLE
Issue with the import feature

### ISSUE THREAD

**Issue by ohrionmartin** [vdm-io/Joomla-Component-Builder#563]
### Steps to reproduce the issue
1. Import any JCB component
2. Finish the import process
3. Try importing another component

### Expected result
Get a new window to select the new component you would like to import 

### Actual result
Shows the **Confirmation Step Before Importing!** of the previously imported component and when you click **Continue** it gives you an import error. When you click on the **Import JCB Packages** button again, you will be able to import another component successfully.

### System information (as much as possible)
- OS Name & Version: Ubuntu 20.04
- MySql Version: 5.5.5-10.4.11-MariaDB
- Apache Version: Apache/2.4.43 (Unix) OpenSSL/1.1.1g PHP/7.4.5 mod_perl/2.0.8-dev Perl/v5.16.3
- PHP Version: 7.4.5
- Joomla Version: Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
- JCB Version: 2.11.2
- Browser: Firefox/Chrome

**Comment by Llewellynvdm** [comment]
Please give screenshots of each step, thanks!

**Comment by ohrionmartin** [comment]
@Llewellynvdm I think this video might help: https://youtu.be/gjJnEHWGD5Y 
Issue reproduced with the **helloworld** component

**Comment by ohrionmartin** [comment]
The issue seems to be with XAMPP, because everything works perfect on Bitnami
