### ISSUE TITLE
Submenu all xx Fields / xx Field Groups get selected when selecting one

### ISSUE THREAD

**Issue by marcorensch** [vdm-io/Joomla-Component-Builder#564]
### Steps to reproduce the issue
Create at least two admin views and active Joomla! Fields for those views.
Compile your component
click on one of the xx Fields or xx Field Groups link in the submenu to the left

### Expected result
It open the desired view's Fields or Field Groups and Highlight the selected Link on the left in the submenu.

### Actual result
It open the desired view's Fields or Field Groups and Highlights all the xx Fields or xx Field Groups in the submenu on the left.

### System information (as much as possible)

    OS Name & Version: MacOS 10.15.4
    MySql Version: 5.7.26
    Apache Version:
    PHP Version: 7.4.2
    Joomla Version: 3.9.18
    JCB Version: 2.11.2
    Browser: Firefox

### Additional comments
The view itself is working you can manage the fields / field groups for the desired admin view its just a display issue. See screenshot here: 
![jcb_fields_all_selected](https://user-images.githubusercontent.com/11912135/83130016-f103dc00-a0dd-11ea-96dd-5730d8499592.jpg)

It might be a joomla thing but is there probably a way to add a custom js somewhere in the code to just highlight the "right one"

Another possible soultion might be to not display all "viewname" fields & "viewname" field groups links directly in the submenu?

**Comment by Llewellynvdm** [comment]
I will close this issue, and ask that you continue communication about this issue at the [earlier thread](https://github.com/vdm-io/Joomla-Component-Builder/issues/561).

With that please watch this [quick tutorial](https://youtu.be/MMrHDUNBhsk). The I will push a fix to address the problem of the sub-menu, but you must understand the implementation. Please continue to follow the progress [here](https://github.com/vdm-io/Joomla-Component-Builder/issues/561).
