### ISSUE TITLE
'Class PHPExcel_IOFactory not found' error in Language Translations Import

### ISSUE THREAD

**Issue by maciejczub** [vdm-io/Joomla-Component-Builder#565]
### Steps to reproduce the issue
Language Translations > Import Data

### Expected result
Import file with translated strings.

### Actual result
Error: Class 'PHPExcel_IOFactory' not found 

### System information (as much as possible)
- PHP Version: 7.3.14
- Joomla Version: 3.9.16
- JCB Version: 2.11.2
- Browser: Firefox 76.0.1

### Additional comments
Library dependency problem?

**Comment by Llewellynvdm** [comment]
This is indeed a bug, to fix add the [following lines of code in the import_language_translations.php file](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_language_translations.php#L418), replace the whole method.
```php
	/**
	* Set the data from the spreadsheet to the database
	*
	* @param string  $package Paths to the uploaded package file
	*
	* @return  boolean false on failure
	*
	**/
	protected function setData($package,$table,$target_headers)
	{
		if (ComponentbuilderHelper::checkArray($target_headers))
		{
			// make sure the file is loaded
			ComponentbuilderHelper::composerAutoload('phpspreadsheet');
			$jinput = JFactory::getApplication()->input;
			foreach($target_headers as $header)
			{
				$data['target_headers'][$header] = $jinput->getString($header, null);
			}
			// set the data
			if(isset($package['dir']))
			{
				$inputFileType = IOFactory::identify($package['dir']);
				$excelReader = IOFactory::createReader($inputFileType);
				$excelReader->setReadDataOnly(true);
				$excelObj = $excelReader->load($package['dir']);
				$data['array'] = $excelObj->getActiveSheet()->toArray(null, true,true,true);
				$excelObj->disconnectWorksheets();
				unset($excelObj);
				return $this->save($data, $table);
			}
		}
		return false;
	}
```
Let me know if this resolves the issue.

**Comment by maciejczub** [comment]
In the meantime I installed the PHPExcel library manually and added `jimport('phpexcel.library.PHPExcel');` in the code. This solved the problem but this patch above also works great. Thank you very much.

**Comment by Llewellynvdm** [comment]
Yes we remove the old library just a few days ago, and this is still some of the growth pains. I would advice you to remove the old lib, as it is completely [abandoned by its developers](uhttps://github.com/PHPOffice/PHPExcelrl), and instead use the snipped I gave you :+1:
