### ISSUE TITLE
[enhancement] field for postSaveHook method (site side)

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#568]
### Steps to reproduce the issue
add a postSaveHook method in site side controller

### Expected result
a field to enter the method content (like in backend) and not added (empty) automatically.
Right now a custom code is the only way I see to add any content to the method (if I'm not wrong).

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
I am not sure I follow. To little details!

Simple answer, all admin edit views ported to the site area (with that little selection option when adding the admin view to the component) has the postSaveHook method in the controller as well, therefore you can use the `if (JFactory::getApplication()->isClient('site'))` to trigger code that you want to only work only on the site side of things.

The normal site view does not extent the admin form, and therefore does not have the save method. This means any form submission must be manually modeled. You can use the Add Button area to  write you own controller method to catch the data, and your own model method to store it.

We are not planning to extend the site view area to become a form submission view. I would instead encourage you to build an admin view (you can hid it from all menus in the admin area if you like) and port it to the site area. The **admin view** is your best path to building forms... unless you know enough then using the custom code path (add you own controller, and model methods) should be easy enough.

Porting an ADMIN VIEW to the site area [watch this tutorial](https://www.youtube.com/watch?v=tmB22d9dQ4M&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=39&t=0s).

Let me know if you have any more questions.

**Comment by jcodewalker** [comment]
Hello,

sometimes I have to create the site edit view from scratch. So, we are talking of manually created site view, and therefore forget the view created automatically by JCB from admin view when we check the “edit/create site view” checkbox, this is not the case.

Go to JCB main menu -> site view -> create new. add some code and compile.
Problem is, we can’t add postSaveHook method in the controller (in custom button section) as it is already included automatically by JCB. As I have to edit the view from scratch, I would expect to be able to add even the postSaveHook method in the controller or, at least, its content.
So, the solution should be for JCB either to not add the postSaveHook method (which is empty and can be edited only with a custom code) [and this is the natural solution from my point of view, as already there is a field to add methods to the controller] or to add a field to JCB to let us to add content in the automatically added postSaveHook method.

The solution is up to you, but if I can say I would prefer to avoid to include the postSaveHook method automatically (in the manually created view, not in the site view created automatically by JCB from admin view).

Hope this make things more clear.

Let me know if you have more questions.

Best regards
Il giorno 11/giu/2020, alle ore 23:05, Llewellynvdm <notifications@github.com> ha scritto:

**Comment by jcodewalker** [comment]
Ok, thinking to back-compatibility, adding a field for the postSaveHook method content could be the best solution…
