### ISSUE TITLE
Module Builder Issues: wrong field path for target admin

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#569]
### Steps to reproduce the issue
Add custom fields to the module (module target: administrator area)

### Expected result
Fields and rules path
/administrator/components/com_mycomponent/models/fields
and
/administrator/components/com_mycomponent/models/rules
if "Fields and Rules path" is targeted to component
OR
/administrator/modules/mod_mymodule/fields
and
/administrator/modules/mod_mymodule/rules
if "Fields and Rules path" is targeted to module 

### Actual result
/administrator/components/com_mycomponent/modules/fields
and
/administrator/components/com_mycomponent/modules/rules
if "Fields and Rules path" is targeted to component
NOTE: modules instead of models

and
/modules/mod_mymodule/fields
and
/modules/mod_mymodule/rules
if "Fields and Rules path" is targeted to module 
NOTE: missing /administrator/

Result: the fields are not fired.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: on both 3.9.11 and 3.9.19
- JCB Version: on both 2.10.13 and 2.11.2
- Browser: 

### Additional comments
I was not able to find out where the path are set in compiler.
I need an hint on how to fix it  hardcoding the file(s) as I have to release a component to customer. Thanks.

**Comment by jcodewalker** [comment]
Ok, I found where the bug is:
class getModuleMainXML
so, I fixed the file and now it works if I set the target path to component.
Didn't find where the module path is added though, it is still a bug to fix.

**Comment by Llewellynvdm** [comment]
Can you give me a few screenshots about this. Meaning how you set it up on JCB, and then what JCB build, and then what you changed, and where you think the compiler should change. 

Thanks!

**Comment by jcodewalker** [comment]
Hello,
for JCB, just add a module for administrator side to demo component. In module config, add custom fields to the form and point the fields path either to module or component, see attached image 8point-path-to-module) .

Compile.
The xml has a wrong absolute path, pointing to module in site side (xml-pointing-to-module-wrong)


The result is (result-with-xml-wrong):

the first 4 fields are custom fields and you can see they are not fired.


Now, to fix the bug, 
file: administrator/components/com_componentbuilder/helpers/compiler/e_interpretation.php
function: getModuleMainXML
line: 26400 (more or less, as I was testing other things when I shoot the screen…)

where the function set rule and field path to component:
you see that the path points to module folder instead to model folder, 
you don’t need the pic to fix this but as you asked for it, here you are (code-point-to-model-fixed):


where the function set rule and field path to module:
the original code points to site module (code-point-to-module-original):


and fix as this (code-point-to-module-fixed):


The result with this fixed is (result-with-module-path-fixed):

The custom fields are fired.
Hope it helps.

Best regards,
claudio

**Comment by Llewellynvdm** [comment]
Still no images here, there are other threads that also speak about this issue, or so it seems, have you read over [issue 511](https://github.com/vdm-io/Joomla-Component-Builder/issues/511)?

If these are the same issues, then we should continue the discussion on the earlier thread.

**Comment by jcodewalker** [comment]
Hello,
yes, it’s the same issue indeed, but didn’t find it in my research.

Please, what do you mean with “Still no images here”?
Read the text (mine and those of others who already posted in the other thread) carefully.
It doesn’t exists any Joomla “modules" folder inside administrator/components/com_component/ folder (see here <https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L26371>). Have you ever seen a Joomla xml installer file which creates such hierarchy? No. ;-)

Solution:

file: administrator/components/com_componentbuilder/helpers/compiler/e_interpretation.php
row 26368 <https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L26368>: . $this->componentCodeName . '/modules/rules"';
change to: . $this->componentCodeName . '/models/rules”';

row 26371 <https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L26371>: . $this->componentCodeName . '/modules/fields"';
change to: . $this->componentCodeName . '/models/fields”';

row 26405 <https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L26405>: the if statement says that it is referring to administrator client modules, so the path must point to administrator area.
current: . 'addrulepath="/modules/' . $module->file_name
change to: . 'addrulepath=“/administrator/modules/' . $module->file_name

row 26408 <https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L26408>: . 'addfieldpath="/modules/' . $module->file_name
change to: . 'addfieldpath=“/administrator/modules/' . $module->file_name

Hope now you can fix this issue.

**Comment by Llewellynvdm** [comment]
Sorry that I took so long, **I see the typo**, and have fixed the path when targeting the **admin area**.
