### ISSUE TITLE
Module builder: form field creates two groups of fields on first saving

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#572]
### Steps to reproduce the issue
Create new module, go to forms & fields tab, click on "Related forms +" button, add a field to the first tab shown. Save.

### Expected result
The tab shown as before saving.

### Actual result
Two group of fields. The firs group has the correct info (field name, fieldset name label and so on) but no field attached, the second group has the correct field attached but the default info (field name, fieldset name label) , those that are shown when you click on "Related forms +" button.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.11.2
- Browser:

**Comment by Llewellynvdm** [comment]
I need screenshot of the screen be fore and after, to understand the issue. Simple because I do not get the same behavior on my end. So giving me more information is critical. I have found that pictures are the best way to explain things when it comes to code.

**Comment by jcodewalker** [comment]
module-form-1.jpg: module just saved with basic required info. now I want to add some configuration field (as far as I know it doesn’t matter the type of field you try to add…)
I don’t want to show the fields in the module main tab, but in “Configuration” tab. The module-form-1.jpg shows haw I set the data.

Now the result I get: module-form-2.jpg

**Comment by Llewellynvdm** [comment]
There is now images showing in your post, here is my screenshot of your post:

![image](https://user-images.githubusercontent.com/5607939/86574998-e3f8c900-bf76-11ea-9e4d-6ba03685d427.png)

**Comment by jcodewalker** [comment]
That’s a problem of Github…

**Comment by jcodewalker** [comment]
![module-form-2](https://user-images.githubusercontent.com/49115855/86593864-4f05c800-bf96-11ea-9827-72403b9cb110.jpg)
![module-form1](https://user-images.githubusercontent.com/49115855/86593871-50cf8b80-bf96-11ea-9d32-1ecb92fbf3ff.png)

**Comment by Llewellynvdm** [comment]
One tab takes many fields, and you just need one to add all you config fields. If you add a tab, with no fields it will be ignored. This is how my fields look like:
![image](https://user-images.githubusercontent.com/5607939/86988603-e6d30400-c198-11ea-90f0-ad5af3760681.png)
![image](https://user-images.githubusercontent.com/5607939/86988619-f2bec600-c198-11ea-8d76-02463c6c7c19.png)

Then in module the outcome looks like this:
![image](https://user-images.githubusercontent.com/5607939/86988708-2bf73600-c199-11ea-8553-8484afc8bb5c.png)
![image](https://user-images.githubusercontent.com/5607939/86988729-36193480-c199-11ea-9157-05e553dda4ef.png)

So to target only a tab with fields change the Fieldset Name and Label:
![image](https://user-images.githubusercontent.com/5607939/86988839-74aeef00-c199-11ea-8b0b-79f15a22d88d.png)

**Comment by jcodewalker** [comment]
_So to target only a tab with fields change the Fieldset Name and Label:_

And what is the difference with what I did?
![Schermata 2020-07-06 alle 08 52 15](https://user-images.githubusercontent.com/49115855/87003776-8fdf2600-c1bc-11ea-9a80-cf1d422d1be6.png)
Can you see the different Fieldset Name and Label in my test? Did you test your installation following exactly this sequence?
