### ISSUE TITLE
During textarea field completion - 0 Error decoding JSON data: Syntax error

### ISSUE THREAD

**Issue by nikkolaos** [vdm-io/Joomla-Component-Builder#574]
### Steps to reproduce the issue
Create a textarea (TEXT) field, then use it to create a Subform.
Create a textarea (TEXT) field.
Then use this subform and this textarea to create another subform.

### Expected result
Use the subform to add pieces of text.

### Actual result
After adding some text, you get the error: "0 Error decoding JSON data: Syntax error"
Even if you copy-paste exactly the same text to all textareas.

### System information (as much as possible)
- OS Name & Version: Debian 9
- MySql Version: MariaDB version 10.1.44
- Apache Version: Apache version 2.4.25
- PHP Version: 7.3.16
- Joomla Version: 3.9.15
- JCB Version: 2.11.2
- Browser: Chrome

**Comment by peterpetrov** [comment]
Hey Nik, can you check your database for that field and confirm that the json data is in tact? My point is that usually i get the error if i haven't calculated how big the subform field should be and if you put a text area there it might get truncated due to the limit of the sql field.

**Comment by nikkolaos** [comment]
Hi @peterpetrov , thank you for your reply.

I checked the database, the json data seems truncated.

All my textarea fields are of type text in the database. Do you think changing the type to longtext would do the job?

**Comment by peterpetrov** [comment]
Hey Nik, sorry for the late reply. 

The text field has a limit of 65535 characters. In this case that include each bracket, comma etc. I do blob column type (up to 4 GB chars) and try to limit the usage to IDs only. Adding free text can be unpredictable from user point of view. 

What i am trying to say is that in your case for you to be sure all data will be storred you should either use bigger sql column type or limit the usage of the field. And yes - you should prepare and consider as much as possible details. But you got it right. Just keep in mind what sql engin you are using and read about their properties. I am using MariaDB and there is a differences in some areas compared to MySQL.

So well done.

Cheers.
