### ISSUE TITLE
Getting 404 going with tutorial

### ISSUE THREAD

**Issue by PowerAmbroz** [vdm-io/Joomla-Component-Builder#575]
### Steps to reproduce the issue
Hi. I've tryed your Hello World tutorial, the long version, and doing everything as there is shown, when I create the links for the greeted. I get a 404 after clicking the name. For example John has a link on him (localhost/joomla/greeted/john.html) and that is when the error is.

### Expected result
Expect to show the greeting

### Actual result
Shows 404 error

### System information (as much as possible)
- OS Name & Version: Win 10
- MySql Version: MariaDB 10.4.10
- Apache Version: 2.4.41
- PHP Version: 7.2.31
- Joomla Version: 3.9.19
- JCB Version: 2.11.2
- Browser: Newest Firefox

### Additional comments
![t1](https://user-images.githubusercontent.com/9193428/86437918-d1c42400-bd05-11ea-9cfc-deabef23e839.jpg)
![t2](https://user-images.githubusercontent.com/9193428/86437923-d2f55100-bd05-11ea-98da-8f113c1226d0.jpg)

**Comment by Llewellynvdm** [comment]
Please check that you have the .htaccess file setup in your Joomla install, or turn the SEO off in the global config of Joomla. That should resolve this. Let me know if it doesn't :+1:

**Comment by PowerAmbroz** [comment]
> Please check that you have the .htaccess file setup in your Joomla install, or turn the SEO off in the global config of Joomla. That should resolve this. Let me know if it doesn't 👍

Forgot about the htaccess. Now it is set and working. 
Thanks a lot.
