### ISSUE TITLE
Admin Custom ViewS - pagination doesn't work

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#578]
### Steps to reproduce the issue
Create a custom list view, dynamic get with pagination, add it to the component, compile and install

### Expected result
working pagination links

### Actual result
links work like anchor: page scroll up to the top and the form is not submitted

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.11.2
- Browser: 

### Additional comments
I've got it working with the following changes:
1. The pagination display links method invoked in a standart admin view is: $this->pagination->getListFooter();
The pagination display links method invoked in Custom admin view is: $this->pagination->getPagesLinks();
Both render almost identical html but the firs works, the second doesn't.

2. The pagination display links in a standard admin view are within the `<form>` tags
The pagination display links in a custom admin view are (obviously) out of `<form>` tags, as the `<form>` tags are added manually and the pagination links are added automatically by JCB.
If I move the links outside the `<form>` tags both don't work.

### Solution:
Use the same display links method of standard admin view.

### Question: 
how to fix the issue related to the `<form>` tags? Pagination links must be within these tags, but is not possible as long as both are not placed in place in the same way, either by the user or automatically by JCB.

### Proposal: 
talking of a **custom** view, paginations should be added by the user, it's not that difficult to copy and paste what the user can find in a standard admin list view. Alternatively we could use placeholder like [[[paginationlinks]]], [[[paginationlimitbox]]] and [[[paginationcounter]]] so can have both full customization power and automation.

**Comment by Llewellynvdm** [comment]
Please look at [Sermon Distributor](https://github.com/SermonDistributor/Joomla-3-Component/blob/master/site/views/preachers/view.html.php#L44) which has a working example.

There is a [[[[LIMITBOX]]]](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6838) placeholder option, and the pagination is added at the bottom, as seen here [on line 6868](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6868).

This function [setCustomViewBody](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L6826) is where it all is happening.

**Comment by Llewellynvdm** [comment]
You see this same function [setCustomViewBody](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php#L1301) used for the custom admin area. Here to form is added to the [top](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php#L1312) and the [bottom](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/f_Infusion.php#L1318) but only if you did not add your own form.

I can see room to improve on this, once you have looked at the code. Let me know what you think, we could still add a placeholder for the pagination like we did for the LIMITBOX. Let me know.

**Comment by jcodewalker** [comment]
Yes, I think [[[PAGINATIONLINKS]]] and [[[PAGINATIONCOUNTER]]] could be added to display respectively the pagination links and the pagination results counter. It would be perfect.

**Comment by Llewellynvdm** [comment]
Okay I updated the method to use the following placeholder:
```html
[[[LIMITBOX]]]
[[[PAGESCOUNTER]]]
[[[PAGESLINKS]]]
[[[PAGINATIONSTART]]]
[[[PAGINATIONEND]]]
```
Here is the code of the method:
```php
public function setCustomViewBody(&$view)
{
	if (ComponentbuilderHelper::checkString($view['settings']->default))
	{
		if ($view['settings']->main_get->gettype == 2
			&& $view['settings']->main_get->pagination == 1)
		{
			// does this view have a custom limitbox position
			$has_limitbox = (strpos(
					$view['settings']->default,
					$this->bbb . 'LIMITBOX' . $this->ddd
				) !== false);
			// does this view have a custom pages counter position
			$has_pagescounter = (strpos(
					$view['settings']->default,
					$this->bbb . 'PAGESCOUNTER' . $this->ddd
				) !== false);
			// does this view have a custom pages links position
			$has_pageslinks = (strpos(
					$view['settings']->default,
					$this->bbb . 'PAGESLINKS' . $this->ddd
				) !== false);
			// does this view have a custom pagination start position
			$has_pagination_start = (strpos(
					$view['settings']->default,
					$this->bbb . 'PAGINATIONSTART' . $this->ddd
				) !== false);
			// does this view have a custom pagination end position
			$has_pagination_end = (strpos(
					$view['settings']->default,
					$this->bbb . 'PAGINATIONEND' . $this->ddd
				) !== false);

			// add pagination start
			$this->placeholders[$this->bbb . 'PAGINATIONSTART' . $this->ddd]
				= PHP_EOL
				. '<?php if (isset($this->items) && isset($this->pagination) && isset($this->pagination->pagesTotal) && $this->pagination->pagesTotal > 1): ?>';
			$this->placeholders[$this->bbb . 'PAGINATIONSTART' . $this->ddd]
				.= PHP_EOL . $this->_t(1) . '<div class="pagination">';
			$this->placeholders[$this->bbb . 'PAGINATIONSTART' . $this->ddd]
				.= PHP_EOL . $this->_t(2)
				. '<?php if ($this->params->def(\'show_pagination_results\', 1)) : ?>';

			// add pagination end
			$this->placeholders[$this->bbb . 'PAGINATIONEND' . $this->ddd]
				= $this->_t(2) . '<?php endif; ?>';
			// only add if no custom page link is found
			if (!$has_pageslinks)
			{
				$this->placeholders[$this->bbb . 'PAGINATIONEND'
				. $this->ddd]
					.= PHP_EOL . $this->_t(2)
					. '<?php echo $this->pagination->getPagesLinks(); ?>';
			}
			$this->placeholders[$this->bbb . 'PAGINATIONEND' . $this->ddd]
				.= PHP_EOL . $this->_t(1) . '</div>';
			$this->placeholders[$this->bbb . 'PAGINATIONEND' . $this->ddd]
				.= PHP_EOL . '<?php endif; ?>';

			// add limit box
			$this->placeholders[$this->bbb . 'LIMITBOX' . $this->ddd]
				= '<?php echo $this->pagination->getLimitBox(); ?>';

			// add pages counter
			$this->placeholders[$this->bbb . 'PAGESCOUNTER' . $this->ddd]
				= '<?php echo $this->pagination->getPagesCounter(); ?>';

			// add pages links
			$this->placeholders[$this->bbb . 'PAGESLINKS' . $this->ddd]
				= '<?php echo $this->pagination->getPagesLinks(); ?>';

			// build body
			$body = array();
			// Load the default values to the body
			$body[] = $this->setPlaceholders(
				$view['settings']->default, $this->placeholders
			);
			// only load these if at-least one is not set via a custom placeholder
			if (!$has_limitbox || !$has_pagescounter || !$has_pageslinks ||
				!$has_pagination_start || !$has_pagination_end)
			{
				// add pagination start
				if (!$has_pagination_start)
				{
					$body[] = $this->placeholders[$this->bbb . 'PAGINATIONSTART' . $this->ddd];
				}

				if (!$has_limitbox && !$has_pagescounter)
				{
					$body[] = $this->_t(3)
						. '<p class="counter pull-right"> <?php echo $this->pagination->getPagesCounter(); ?> <?php echo $this->pagination->getLimitBox(); ?></p>';
				}
				elseif (!$has_limitbox)
				{
					$body[] = $this->_t(3)
						. '<p class="counter pull-right"> <?php echo $this->pagination->getLimitBox(); ?></p>';
				}
				elseif (!$has_pagescounter)
				{
					$body[] = $this->_t(3)
						. '<p class="counter pull-right"> <?php echo $this->pagination->getPagesCounter(); ?> </p>';
				}
				// add pagination end
				if (!$has_pagination_end)
				{
					$body[] = $this->placeholders[$this->bbb . 'PAGINATIONEND' . $this->ddd];
				}
			}
			// lets clear the placeholders just in case
			unset($this->placeholders[$this->bbb . 'LIMITBOX' . $this->ddd]);
			unset($this->placeholders[$this->bbb . 'PAGESCOUNTER' . $this->ddd]);
			unset($this->placeholders[$this->bbb . 'PAGESLINKS' . $this->ddd]);
			unset($this->placeholders[$this->bbb . 'PAGINATIONSTART' . $this->ddd]);
			unset($this->placeholders[$this->bbb . 'PAGINATIONEND' . $this->ddd]);
			// insure the form is added (only if no form exist)
			if (strpos($view['settings']->default, '<form') === false)
			{
				$this->addCustomForm[$this->target][$view['settings']->code]
					= true;
			}

			// return the body
			return implode(PHP_EOL, $body);
		}
		else
		{
			// insure the form is added (only if no form exist)
			if ('site' !== $this->target
				&& strpos(
					$view['settings']->default, '<form'
				) === false)
			{
				$this->addCustomForm[$this->target][$view['settings']->code]
					= true;
			}

			return PHP_EOL . $this->setPlaceholders(
					$view['settings']->default, $this->placeholders
				);
		}
	}

	return '';
}
```
I have pushed this change to the staging branch please test and let me know it it works as expected.

**Comment by Llewellynvdm** [comment]
I assume this works...
