### ISSUE TITLE
Feature Request: FTP Uploaded extension filename with versioning in it like with compiler download button.

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#580]
The Sales server is setup on my system but when it uploads the package it does not contain the version in the filename.
Is it possible to change the filename to keep the same format as when you use the "download" button in the compiler view after compiling? 

That way i don't have to go on FTP and rename the file for my clients to be able to actually use the joomla update feature. 

Or maybe there is a good reason why this is not implemented this way?

Kind regards,

Tom

**Comment by Llewellynvdm** [comment]
The reason I did not add the version to this file was due to the unwillingness to update the linking of the file in an external system. So I would like the file once, and thereafter with all updates just update the existing file that is linked to this external system.

But I can see that you have another idea here, and valid. Where my client just download the same file, yet now changed, how want your client to see the version.... the place where [this happens in the compiler on line 971](https://github.com/vdm-io/Joomla-Component-Builder/blob/98f18219148d9c744350b425db7951c16194c633/admin/helpers/compiler.php#L971) in the main compiler file:
```php
private function zipComponent()
{
	// Component Folder Name
	$this->filepath['component-folder'] = $this->componentFolderName;
	// the name of the zip file to create
	$this->filepath['component'] = $this->tempPath . '/'
		. $this->filepath['component-folder'] . '.zip';
	// Trigger Event: jcb_ce_onBeforeZipComponent
	$this->triggerEvent(
		'jcb_ce_onBeforeZipComponent',
		array(&$this->componentContext, &$this->componentPath,
		      &$this->filepath['component'], &$this->tempPath,
		      &$this->componentFolderName, &$this->componentData)
	);
	//create the zip file
	if (ComponentbuilderHelper::zip(
		$this->componentPath, $this->filepath['component']
	))
	{
		// now move to backup if zip was made and backup is required
		if ($this->backupPath && $this->dynamicIntegration)
		{
			// Trigger Event: jcb_ce_onBeforeBackupZip
			$this->triggerEvent(
				'jcb_ce_onBeforeBackupZip', array(&$this->componentContext,
				                                  &$this->filepath['component'],
				                                  &$this->tempPath,
				                                  &$this->backupPath,
				                                  &$this->componentData)
			);
			// copy the zip to backup path
			JFile::copy(
				$this->filepath['component'],
				$this->backupPath . '/' . $this->componentBackupName
				. '.zip'
			);
		}

		// move to sales server host
		if ($this->componentData->add_sales_server == 1
			&& $this->dynamicIntegration)
		{
			// make sure we have the correct file
			if (isset($this->componentData->sales_server))
			{
				// Trigger Event: jcb_ce_onBeforeMoveToServer
				$this->triggerEvent(
					'jcb_ce_onBeforeMoveToServer',
					array(&$this->componentContext,
					      &$this->filepath['component'], &$this->tempPath,
					      &$this->componentSalesName, &$this->componentData)
				);
				// move to server
				ComponentbuilderHelper::moveToServer(
					$this->filepath['component'],
					$this->componentSalesName . '.zip',
					(int) $this->componentData->sales_server,
					$this->componentData->sales_server_protocol
				);
			}
		}
		// Trigger Event: jcb_ce_onAfterZipComponent
		$this->triggerEvent(
			'jcb_ce_onAfterZipComponent',
			array(&$this->componentContext, &$this->filepath['component'],
			      &$this->tempPath, &$this->componentFolderName,
			      &$this->componentData)
		);
		// remove the component folder since we are done
		if ($this->removeFolder($this->componentPath))
		{
			return true;
		}
	}

	return false;
}
```
You will see there are a number of plugin events in the function where you can come in and change the file name the way you like. Every-time you see a `$this->triggerEvent(...)` in the compiler this is a plugin event, and you can with a plugin target that event :+1:

**Comment by Llewellynvdm** [comment]
You should look at this value `$this->componentSalesName` and change only that since it holds the sales server file name.

**Comment by TLWebdesign** [comment]
Yeah i was just worried with updates there could become a conflict but i don't think this is a valid concern tho. There are other benefits to having a seperate file for every update tho. Will look into the plugin Thanks for the info! :)

**Comment by TLWebdesign** [comment]
I'm quite the noob when it comes to plugins. Just haven't had to deal with them in the past. So i created a plugin and it actually works. I tested it by having it send an e-mail to me. 

So i know it is being triggered. But the file that is uploaded is not edited.

This is the code but it does not work:

`use Joomla\CMS\Application\CMSApplication;
use Joomla\CMS\Plugin\CMSPlugin;

/**
 * Extension - Componentbuilder plugin.
 *
 * @package   Componentbuilder
 * @since     1.0.0
 */
class PlgExtensionComponentbuilder extends CMSPlugin
{
/**
	 * Event Triggered in the compiler [on Before Move To Server]
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */

public function jcb_ce_onBeforeMoveToServer(&$context, &$filepath, &$tempPath, &$componentSalesName, &$componentData)
	{
		// do something on the jcb_ce_onBeforeMoveToServer event
		
		$this->componentSalesName = $this->componentBackupName."TEST";
		
					// BERICHT
					$message = '
					<html>
					<head>
					  <title>Test plugin</title>
					</head>
					<body>
					  <p>Component Sale Name = '.$componentSalesName.'</p>
					  <p>Component Backup Name = '.$this->componentBackupName.'</p>
					  <p>New Sale Name = '.$this->componentSalesName.'</p>
					</body>
					</html>
					';

					// HEADERS
					$headers  = 'MIME-Version: 1.0' . "\r\n";
					$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

					// Additional headers
					$headers .= 'From: TLTEST <test@tltest.nl>' . "\r\n";
					$headers .= 'Reply-to: mymail@idk.nl' . "\r\n";

					// VERSTUUR E-MAIL
					mail('mymail@idk.nl', 'Test plugin', $message, $headers);
		
		
	}
}`

Both $this->componentBackupName and $this->componentSalesName are empty. It seems the plugin can't directly target them. I created the plugin with JCB itself.

**Comment by Llewellynvdm** [comment]
You will need to give me more code, I mean the whole plugin code, so I can see where you are doing wrong... the function where the above code run.

**Comment by TLWebdesign** [comment]
This is the whole code: it was above too but not commented correctly as code. 

```
<?php
/*----------------------------------------------------------------------------------|  www.vdm.io  |----/
				Vast Development Method 
/-------------------------------------------------------------------------------------------------------/

	@version		2.0.1
	@build			29th juli, 2020
	@created		18th oktober, 2016
	@package		Demo
	@subpackage		componentbuilder.php
	@author			Llewellyn van der Merwe <https://www.vdm.io/>	
	@copyright		Copyright (C) 2015. All Rights Reserved
	@license		GNU/GPL Version 2 or later - http://www.gnu.org/licenses/gpl-2.0.html
  ____  _____  _____  __  __  __      __       ___  _____  __  __  ____  _____  _  _  ____  _  _  ____ 
 (_  _)(  _  )(  _  )(  \/  )(  )    /__\     / __)(  _  )(  \/  )(  _ \(  _  )( \( )( ___)( \( )(_  _)
.-_)(   )(_)(  )(_)(  )    (  )(__  /(__)\   ( (__  )(_)(  )    (  )___/ )(_)(  )  (  )__)  )  (   )(  
\____) (_____)(_____)(_/\/\_)(____)(__)(__)   \___)(_____)(_/\/\_)(__)  (_____)(_)\_)(____)(_)\_) (__) 

/------------------------------------------------------------------------------------------------------*/

// No direct access to this file
defined('_JEXEC') or die('Restricted access');


use Joomla\CMS\Application\CMSApplication;
use Joomla\CMS\Plugin\CMSPlugin;

/**
 * Extension - Componentbuilder plugin.
 *
 * @package   Componentbuilder
 * @since     1.0.0
 */
class PlgExtensionComponentbuilder extends CMSPlugin
{
/**
	 * Event Triggered in the compiler [on Before Move To Server]
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	public function jcb_ce_onBeforeMoveToServer(&$context, &$filepath, &$tempPath, &$componentSalesName, &$componentData)
	{
		// do something on the jcb_ce_onBeforeMoveToServer event
		
		$this->componentSalesName = $this->componentBackupName."TEST";
	}
}
```

The function is boilerplate code.

It get's triggered because when testing it with  a simple mail script it sends it correctly. It is not possible to access $this->componentSaleName from the compiler file the plugin is triggered.

**Comment by Llewellynvdm** [comment]
Try this:
```php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');


use Joomla\CMS\Application\CMSApplication;
use Joomla\CMS\Plugin\CMSPlugin;

/**
 * Extension - Componentbuilder plugin.
 *
 * @package   Componentbuilder
 * @since     1.0.0
 */
class PlgExtensionComponentbuilder extends CMSPlugin
{
/**
	 * Event Triggered in the compiler [on Before Update Files]
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	public function jcb_ce_onBeforeUpdateFiles(&$context, &$compiler)
	{
		// do something on the jcb_ce_onBeforeUpdateFiles event
		$compiler->componentSalesName = $compiler->componentBackupName . "TEST";
	}
}
```

**Comment by TLWebdesign** [comment]
@Llewellynvdm Thanks! That works of course. And after digging in again in the compiler code and comparing the two different trigger events i now understand it much better. Thanks as always!
