### ISSUE TITLE
Dynamic build trips over timestamp fieldtype

### ISSUE THREAD

**Issue by jchlagrand** [vdm-io/Joomla-Component-Builder#582]
### Steps to reproduce the issue
  `datum` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
in a create table statement

### Expected result
datum field of type timestamp

### Actual result
datum field of type time and a illegal default for my system of '0000-00-00 00:00:00';

### System information (as much as possible)
- OS Name & Version: debian 10
- MySql Version: Ver 14.14 Distrib 5.7.30, for Linux (x86_64)
- Apache Version: 2.4
- PHP Version: 7.4
- Joomla Version: 3.20
- JCB Version: 2.11.2
- Browser: Chrome

### Additional comments
No compile errors, fails the 'intall on this website'.

**Comment by Llewellynvdm** [comment]
Can you please give me some more details with regard to the errors, and the expected outcome.

What should the SQL values be, and what exactly does the GUI in JCB look like (screenshots) of the field database setup tab, and the field properties.

**Comment by jchlagrand** [comment]
LS,

To start a new component in JCB, I found, the dynamic build is essential to progress any further. Even though it is marked a ‘beta’ function!
Meantime I manually modified the component (for it does not report a compilation error) to the correct timestamp field properties (the install mysql.utf8.sql).
Joomla installed ok. A look at the table using mysql also shows correct timestamp fields. In other words Joomla supports it.
So, please fix or at least report timestamp as not supported instead of simply turn it into a time field with false defaults.

Regards,

Jacco Lagrand.

**Comment by Llewellynvdm** [comment]
Okay so the import from the database schema did not work well. So lets look at this, the [defaults we have are listed here](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/extrusion/a_mapping.php#L72), in fact you can look over all the defaults here and give suggestion on improvements.

Then [here we start stripping](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/extrusion/a_mapping.php#L181) the table values. There is a function to [getTableName](https://github.com/vdm-io/Joomla-Component-Builder/blob/98f18219148d9c744350b425db7951c16194c633/admin/helpers/extrusion/a_mapping.php#L222) and to [getFields](https://github.com/vdm-io/Joomla-Component-Builder/blob/98f18219148d9c744350b425db7951c16194c633/admin/helpers/extrusion/a_mapping.php#L257), then in the getFields there is a [getType](https://github.com/vdm-io/Joomla-Component-Builder/blob/98f18219148d9c744350b425db7951c16194c633/admin/helpers/extrusion/a_mapping.php#L332).

This was a very basic first attempt from my side to get an option available, an help to improve this will be excellent.

**Comment by Llewellynvdm** [comment]
Should you have any feedback on this issue, just bump this issue again and I will reopen if needed.
