### ISSUE TITLE
bug in custom import in admin view

### ISSUE THREAD

**Issue by sabersaberi2** [vdm-io/Joomla-Component-Builder#584]
### Steps to reproduce the issue
go to admin view and add one simple Space in each of scope that you want. i add to save scope

### Expected result
work normally such as default import

### Actual result
return this error : 
Call to undefined method Lmskaran_skyroomHelper::composerAutoload()

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 7.2
- Joomla Version:  last
- JCB Version:  2.11.2
- Browser: 
chrome
### Additional comments
it is occur because the predefined ready template code in setData Method generate wrong code and we change below code 

[[[Component]]]Helper::composerAutoload('phpspreadsheet');
$jinput = JFactory::getApplication()->input;
foreach($target_headers as $header)
{
  $data['target_headers'][$header] = $jinput->getString($header, null);
}
// set the data
if(isset($package['dir']))
{
  $inputFileType = IOFactory::identify($package['dir']);
  $excelReader = IOFactory::createReader($inputFileType);
  $excelReader->setReadDataOnly(true);
  $excelObj = $excelReader->load($package['dir']);
  $data['array'] = $excelObj->getActiveSheet()->toArray(null, true,true,true);
  $excelObj->disconnectWorksheets();
  unset($excelObj);
  return $this->save($data, $table);
}

TO

JLoader::import('PHPExcel', JPATH_COMPONENT_ADMINISTRATOR . '/helpers');
$jinput = JFactory::getApplication()->input;
foreach($target_headers as $header)
{
  $data['target_headers'][$header] = $jinput->getString($header, null);
}
// set the data
if(isset($package['dir']))
{
  $inputFileType = PHPExcel_IOFactory::identify($package['dir']);
  $excelReader = PHPExcel_IOFactory::createReader($inputFileType);
  $excelReader->setReadDataOnly(true);
  $excelObj = $excelReader->load($package['dir']);
  $data['array'] = $excelObj->getActiveSheet()->toArray(null, true,true,true);
  $excelObj->disconnectWorksheets(); 
  unset($excelObj);
  return $this->save($data,$table);
}

**Comment by Llewellynvdm** [comment]
Please upgrade to JCB v 2.12.3 and do take note of this issue #444 with regards to the change to the PHP excel library.

**Comment by Llewellynvdm** [comment]
Then to make sure that the custom code is now also using the new PHP excel library, it will be best to close the custom code, and save the view, and then open the custom code again so that it loads the new code that is now being shipped with JCB.

**Comment by Llewellynvdm** [comment]
If you have any more feedback, just bump this issue and I will reopen if needed.
