### ISSUE TITLE
DATETIME field type compiles install/update sql incorrectly with default set

### ISSUE THREAD

**Issue by stutteringp0et** [vdm-io/Joomla-Component-Builder#585]
### Steps to reproduce the issue
Create a datetime field with DATETIME or CURRENT_TIMESTAMP as the default value

### Expected result
`received_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

### Actual result
`received_timestamp` DATETIME CURRENT_TIMESTAMP NOT NULL,

### Additional comments

Opening issue just so I can attach it to a PR, BRB :)

**Comment by Llewellynvdm** [comment]
Thank you! [Merged](https://github.com/vdm-io/Joomla-Component-Builder/commit/c32baff933a084ac08dda77f26385847f84b8216)
