### ISSUE TITLE
Incorrect link to Members Manager Tutorial Video

### ISSUE THREAD

**Issue by duetnet** [vdm-io/Joomla-Component-Builder#590]
Firstly, apologies for placing this issue on JCB git hub, but I did not get a response to this issue on JCB Google groups page ....

**Problem** 

The "JCB Members manager" page link (https://github.com/vdm-io/Joomla-Members-Manager)
shows a link to a youtbe video tutorial (https://www.youtube.com/watch?v=lkE0ZiSWufg&feature=youtu.be)
**but the linked tutorial** is for "Export & Import of fully mapped components" and **NOT** "JCB Members manager".

I know I did watch the 'Members Manager' tutorial some time last year, but it seems to have disappeared from the Joomla Mount list of videos and I cannot seem to find it anywhere.

**Reason**

I am trying to get to grips with the exact purpose of and usage of the Members Manager component but struggling to understand how would/could integrate with a/my component.

I am creating a component where I have require multiple 'manager' user groupings, each with one or more 'member' sub-groupings. I then want to set up an administrator per 'manager' grouping, who is then only able to add/administer only joomla users linked to 'member' sub-groupings in his own group.

Alternatively, can someone point me to a similar solution so that I can see how I can solve my requirement.

Many thanks.

**Comment by Llewellynvdm** [comment]
Sorry @duetnet if I could in five minutes answer you here I would. But the question requires much more details, and collaboration that is really focused on building your component. The only video tutorial of member manger is this one: https://youtu.be/TOiRoPERSTs and I never got to do more.

VDM has a paid service available here: https://www.vdm.io/jcb-support if you would like us to help you build, or extend any project.

**Comment by duetnet** [comment]
Hi Llewellyn

 

Thanks for your response…

 

I do remember this tutorial and will restudy it…

 

My requirement as you may remember during our discussions, is to have multiple organisations using my component, each organisation has its own administrator who can only create and maintain users belonging to his organisation and only have user groups specific to his organisation to which he can allocate users….

 

I did study members manager to try and see what it was trying to do. Did not quite get to grips with the ‘account’ and ‘types’ concept as I am not sure how this works/integrates with other components…not sure what must be set up and how it will work…

 

In the meantime, I have now developed my own solution where the required activity/controls/management can occur, using JCB to create the admin view and interfacing with the joomla user management system.  

 

So my mechanism allows the administrator only to view/create/edit a user from an existing employee in the same company as the administrator and happily seems to be working fine…but will need to test thoroughly 😉

 

I now just need to be able to deactivate/change the JCB export /import / batch functionality and create my own mechanisms wich hopefully can piggyback onto the joomla user manager admin list activate/block/batch functionality.

 

Thanks for everything.
