### ISSUE TITLE
Params in edit.php

### ISSUE THREAD

**Issue by PowerAmbroz** [vdm-io/Joomla-Component-Builder#591]
### Steps to reproduce the issue
Build a new komponent using JCB, installed, tryed to add record

### Expected result
Normal form for adding data

### Actual result
![image](https://user-images.githubusercontent.com/9193428/91047846-01fbb500-e61b-11ea-8c44-5e40f8c35cb4.png)

### System information (as much as possible)
- OS Name & Version: Win10 Home
- MySql Version: MaraiDB 10.4.10
- Apache Version: 2.4.41
- PHP Version: 7.3.12
- Joomla Version: 3.9.20
- JCB Version: 2.11.4
- Browser: Firefox

### Additional comments
Almost always whet I try to create a component using JCB i get this Error. The only solution is to reinstall joomla and JCB. The it is a chance that this error won't show up.
Component:
[com_mylink_v0_1_1__J3.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/5117970/com_mylink_v0_1_1__J3.zip)

**Comment by Llewellynvdm** [comment]
You are probably using existing custom code from other demo components I build, and it require a helper field called $params. So add this field to the components helper area, and this should resolve the issue.
```php
	/**
	* the params
	**/
	protected static $params;
```
![image](https://user-images.githubusercontent.com/5607939/91365593-ce2eb400-e801-11ea-9513-089a7df223d9.png)

So you go to the component and open the **Libs & Helpers** tab and then add the above code snipped to the **Add PHP (helper Classes - Both admin & site)** => **PHP (for both admin & site)**

**Comment by Llewellynvdm** [comment]
I assume this is resolved, if you still have any issues, just reply to this issue again.
