### ISSUE TITLE
Menu Prefix cannot be removed

### ISSUE THREAD

**Issue by stutteringp0et** [vdm-io/Joomla-Component-Builder#598]
### Steps to reproduce the issue
delete prefix field contents in component config, or edit database entry for component and store an empty string for menu_prefix

### Expected result
no menu prefix

### Actual result
default menu prefix

### System information (as much as possible)
irrelevant

### Additional comments

I'd love a way to remove the prefix.  If it's empty, why not leave it out instead of forcing the default?

**Comment by Llewellynvdm** [comment]
Okay so there are two places to set the menu prefix, one is in a component, and the other is default (global)

Should you like the default to be no prefix, you can just... ahaa I see that when left empty, it uses the default. Sorry I missed that, so you basically want me to remove the default, and make the default empty. I agree that this makes more sense. Done :+1:
