### ISSUE TITLE
Feature request: empty views

### ISSUE THREAD

**Issue by studio16** [vdm-io/Joomla-Component-Builder#599]
The site view "Main get"selection box should have a "none" option to create views which are not related to anything. 
Now u get a "Not found or access denied!" because of nothing returning from the model.
I'm bypassing that now by clearing the getitem function to:
public function getItem($pk = null)
	{}

Would be nice however, especially considering upgrades/updates, if it can be done via the JCB.
Perhaps it would be possible during compiling if the Main get is set to "none" to leave the getItem function empty.

Just a thought

**Comment by Llewellynvdm** [comment]
Currently this is not that easy to achieve, this was looked at before, and the compiler would need to much attention to achieve this. Better to just create one "blank" type of dynamic get and use it wherever you need an "empty site view".
