### ISSUE TITLE
Missplaced Generated Comment when using Custom Import

### ISSUE THREAD

**Issue by marcorensch** [vdm-io/Joomla-Component-Builder#603]
### Steps to reproduce the issue
Activate Custom Import for a table
affected file: administrator/components/com_component/views/import_VIEW/tmpl/default.php

### Expected result
You got custom import

### Actual result
You have custom import BUT
it places a Comment into the code:
`/***[JCBGUI.admin_view.html_import_view.116.$$$$]***/`
As a result this comment will be displayed in the import dialog.
The Comment is missplaced and should be before line 29 where the PHP Tag is closed.

Code Snipped (Line 26 -> 31):
```
// No direct access to this file
defined('_JEXEC') or die('Restricted access');

JHtml::_('jquery.framework');
JHtml::_('bootstrap.tooltip');
JHtml::_('script', 'system/core.js', false, true);
JHtml::_('behavior.keepalive');
?>

/***[JCBGUI.admin_view.html_import_view.116.$$$$]***/
<script type="text/javascript">
```

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 
- Browser:

**Comment by Llewellynvdm** [comment]
Okay it seems like the placeholder is in the right place, but with the wrong commenting style. This `html_import_view` is an HTML area , and should have an HTML commenting style.

![image](https://user-images.githubusercontent.com/5607939/95267286-2b704900-0835-11eb-9e2d-08e78fb04ee5.png)

So I need to change [this code](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/a_Get.php#L3028) to make sure the placeholder is HTML instead.

So change this code from:
```php
$guiMapper['field'] = $importScripter;
```
to the following:
```php
// update GUI mapper field
$guiMapper['field'] = $importScripter;
$guiMapper['type'] = 'php';
// Make sure html gets HTML comment for placeholder
if ('html_import_view' === $importScripter)
{
	$guiMapper['type'] = 'html';
}
else
{
	$guiMapper['type'] = 'php';
}
```
Thanks for the heads up, I missed this one!
