### ISSUE TITLE
Issue with user type of field

### ISSUE THREAD

**Issue by abhagatmavenview** [vdm-io/Joomla-Component-Builder#608]
### Steps to reproduce the issue
Use a user-type-field in backend

### Expected result
The user-type-field is meant only for backend. This field shouldn't show on the frontend

### Actual result
The user-type-field shows on the frontend form as well. And, of course, this field doesn't work on the frontend. And hence, if the field is mandatory, then, the user can't submit the form at all.

**Comment by Llewellynvdm** [comment]
The user field works in both back-end and front-end, access is controlled with the Joomla access system, and implemented view the linking process of the fields to an admin view.
![image](https://user-images.githubusercontent.com/5607939/96355850-f7bfd980-10e6-11eb-9e2f-66f761ba14b5.png)

So with the limited information you provided I am not able to say anything more. So I will close this issue and ask that you that if you have not already, please carefully go over the [JCB tutorials found on Youtube](https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE).

Should this issue continue, please do not hesitate to post to this tread again, and we will reconsider your request.
