### ISSUE TITLE
The toolbar does not exist at this path since Joomla version 3.9

### ISSUE THREAD

**Issue by pctechnikch** [vdm-io/Joomla-Component-Builder#612]
### Steps to reproduce the issue
protected function addToolBar(){
   JLoader::register('JToolbarHelper', JPATH_ADMINISTRATOR.'/includes/toolbar.php');

There is no longer a toolbar at this path since J 3.9. But should be corrected.

### Expected result
No errors found yet

### Actual result
No errors found yet

### System information (as much as possible)
- OS Name & Version:  Win 10
- MySql Version: 8.0.18
- Apache Version: 2.4.41
- PHP Version: 7.4
- Joomla Version: 3.9.22
- JCB Version: 2.11.7
- Browser: 

### Additional comments
JCB geneted The line of code in frontend JViewLegacy. Since the toolbar.php no longer exists at this path, I recommend making a change.
I work with the toolbar in the frontend, but I have no errors (lol).
The problem was discussed in the Joomla community:
https://github.com/joomla/joomla-cms/issues/21960

Many thanks
Rene

**Comment by Llewellynvdm** [comment]
I will take a look at this, and come back to you.
