### ISSUE TITLE
Filtering in admin view problem with radio field

### ISSUE THREAD

**Issue by WebAtelier47** [vdm-io/Joomla-Component-Builder#613]
### Steps to reproduce the issue
Create a radio field with 2 options 1|Yes,0|No
Apply filter for this field in admin view settings

### Expected result
Correct filtering when select Yes or No

### Actual result
It work for Yes but the No option return all items (Yes and No)

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 7.4
- Joomla Version: 2.98.22
- JCB Version: 2.11.7
- Browser:

**Comment by Llewellynvdm** [comment]
Not sure why this happens, I have a few ideas... but hard to say if I can't see the code, or GUI. Can you give more information, with some screenshots and code snippets of this area.

We are working of fixing the filter area to use the new Joomla above search tools. This will still take a week or so... but it will be out soon.

**Comment by imorkovin** [comment]
Imho, the filtering field in MySql table has two value - "1" and NULL? But NULL is not equal "0".

**Comment by WebAtelier47** [comment]
Hi,

See my screenr here https://app.usebubbles.com/riDzVcJ6qbHW7CDjSBqd6m/comments-on-localhost/ and here https://fromsmash.com/jcb the JCB package and the component.

Thanks a lot.

**Comment by vistamedia** [comment]
It's a bug indeed. The filtering of numerical values should be done this way : 
`$iata = $this->getState('filter.iata');
if (is_numeric($iata))
{
	$query->where('a.iata = ' . (int) $iata);
}
`
instead of this
`if ($iata = $this->getState('filter.iata'))
{
	$query->where('a.iata = ' . $db->quote($db->escape($iata)));
}
`
Not sure it's very easy to update in the compiler...

**Comment by vistamedia** [comment]
I have a good news for you, the new filter implementation will fix this issue. I just tested it :)

**Comment by WebAtelier47** [comment]
Cool, thanks.

**Comment by Llewellynvdm** [comment]
Okay so this issue was also resolved [here](https://github.com/vdm-io/Joomla-Component-Builder/commit/06c97afa05c5f75438d7778236aff820a686a7d5). Let me know if you have any further questions.
