### ISSUE TITLE
Feature Request - Created item date in admin list view

### ISSUE THREAD

**Issue by WebAtelier47** [vdm-io/Joomla-Component-Builder#617]
It would be interesting to be able to have the creation date in the items list in admin view.

**Comment by Llewellynvdm** [comment]
This is already doable with the [custom field override option](https://www.youtube.com/watch?v=FHQfIhWHYyQ&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=29).

**Comment by WebAtelier47** [comment]
Oups, thanks and sorry.
