### ISSUE TITLE
Feature request: add custom code after parent::save()

### ISSUE THREAD

**Issue by patatagit** [vdm-io/Joomla-Component-Builder#619]
### Steps to reproduce the issue
Actually is not possible to add custom code after parent::save() check is verified.
Please see administrator/components/com_componentbuilder/compiler/joomla_3/JModelAdmin.php line 419
```
if (parent::save($data))
{
          **I need to add some code here**
          return true;
}
```
I hope this enhancement will be added early

### System information
- JCB Version: 2.11.7

**Comment by Llewellynvdm** [comment]
The best place to add code after the parent save method is in in the postSaveHook method:
![image](https://user-images.githubusercontent.com/5607939/101549353-30c54d80-39b6-11eb-9f17-e86c485401b5.png)

Else your next option would be to target the event with a plugin... this is also already possible.

For now I will close this issue, but if you still unable to succeed let me know, and we can try again :+1:

**Comment by Llewellynvdm** [comment]
The postSaveHook method can be found under the PHP tab in the admin view.

**Comment by Llewellynvdm** [comment]
Should you like to use the plugin instead, then the following options should be selected when you create your plugin:
![image](https://user-images.githubusercontent.com/5607939/101549829-02943d80-39b7-11eb-8bac-f9b39d2c8f31.png)

That will give you the following code:
```php
/**
 * This is an event that is called after the content is saved
 * into the database.
 *
 * @param   string  $context  The context of the content passed to the plugin (added in 1.6)
 * @param   object  $article  A JTableContent object
 * @param   bool    $isNew    If the content has just been created
 *
 * @return  void
 *
 * @since   1.0
 */
public function onContentAfterSave($context, $article, $isNew)
{
	// then with this code target the component and view
	if ($context === 'com_[[[component]]].target_view')
	{
		// your code here ;)
	}
}
```

**Comment by Llewellynvdm** [comment]
Should you like to use the plugin instead, then the following options should be selected when you create your plugin:
![image](https://user-images.githubusercontent.com/5607939/101550380-e5ac3a00-39b7-11eb-9dd7-2a3986b8311e.png)

That will give you the following code:
```php
/**
 * This is an event that is called after the content is saved
 * into the database.
 *
 * @param   string  $context  The context of the content passed to the plugin (added in 1.6)
 * @param   object  $article  A JTableContent object
 * @param   bool    $isNew    If the content has just been created
 *
 * @return  void
 *
 * @since   1.0
 */
public function onContentAfterSave($context, $article, $isNew)
{
	// then with this code target the component and view
	if ($context === 'com_[[[component]]].target_view')
	{
		// your code here ;)
	}
}
```

**Comment by patatagit** [comment]
Basically, I need to run another function (in order to save some data in another db table) only after the parent::save() function is successful completed. 
Ok, I will use postSaveHook. The way of building a plugin is too much for what I need to do.
Many thanks for your suggestions
