### ISSUE TITLE
Plugin does not install when there are MySQL install/uninstall statements added

### ISSUE THREAD

**Issue by bM8qwa** [vdm-io/Joomla-Component-Builder#620]
### Steps to reproduce the issue

- Enter "Joomla Plugins"
- Create or edit plugin, open tab "MySQL"
- Add install and/or uninstall SQL strings in corresponding text areas
- Save and close plugin
- Compile linked component
- Install the plugin

### Expected result
Successful installation of the plugin, with tables created in database. On uninstallation, uninstallation of the plugin and dropping corresponding tables.

### Actual result
Plugin does not install.
Installer gives warning:
"... xml:18: parser error : Opening and ending tag mismatch: sql line 17 ..."

Install and uninstall tags look like that (no sql closing tag!):
```
<install>
  <sql>
    <file driver="mysql" charset="utf8">sql/mysql/install.sql</file>
  <sql>
</install>
```

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 5.5.5-10.4.14
- Apache Version: 2.4.46
- PHP Version: 7.4.11
- Joomla Version: 3.9.23
- JCB Version: 2.11.7
- Browser: FF 83.0

### Additional comments

That'll be nice, if MySQL text areas would be supported by editor, chosen in JCB settings. Say, CodeMirror.
The same wish to other areas, where code is edited, for example fields scripts and some other places.

**Comment by Llewellynvdm** [comment]
Thanks, that is a typo on my part... will push the fix.
