### ISSUE TITLE
Bug: Error when try to load new Packages

### ISSUE THREAD

**Issue by ManfredHuebner** [vdm-io/Joomla-Component-Builder#631]
### Steps to reproduce the issue
Select Import packages in Component Builder

### Expected result
A dropdown with packages to load should be seen

### Actual result
Error
The url (https://api.github.com/repos/vdm-io/JCB-Packages/git/trees/master) set to retrieve the packages does not exist!
The url (https://api.github.com/repos/vdm-io/JCB-Community-Packages/git/trees/master) set to retrieve the packages does not exist!

### System information (as much as possible)
- OS Name & Version: Windows NT 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64 
- MySql Version:  5.7.32-log 
- Apache Version:  IIS 8.5
- PHP Version: 7.3.25
- Joomla Version: 3.9.23
- JCB Version: 2.12.3
- Browser:  Firefox

**Comment by Llewellynvdm** [comment]
care to explain?
