### ISSUE TITLE
Edit site view (coresponding to an admin view) "save" and "save&close" buttons inactive

### ISSUE THREAD

**Issue by fred-the-coder** [vdm-io/Joomla-Component-Builder#637]
### Steps to reproduce the issue
Add an admin wiew to a JCB component and select "Add+Menu" to the field "Edit/create Site View".

### Expected result
An edit site view is created in frontend (in components/_component name_/views/_admin edit view name_/tmpl/edit.php)

### Actual result
The edit site view is created, but it's "header" is "empty", leading to "save" and "save&close" buttons inactive.
The coresponding admin edit view "header" is:
```
JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
JHtml::_('formbehavior.chosen', 'select');
JHtml::_('behavior.keepalive');
$componentParams = $this->params; // will be removed just use $this->params instead
?>
<script type="text/javascript">
	// waiting spinner
	var outerDiv = jQuery('body');
	jQuery('<div id="loading"></div>')
		.css("background", "rgba(255, 255, 255, .8) url('components/com_mosoftbluemarine/assets/images/import.gif') 50% 15% no-repeat")
		.css("top", outerDiv.position().top - jQuery(window).scrollTop())
		.css("left", outerDiv.position().left - jQuery(window).scrollLeft())
		.css("width", outerDiv.width())
		.css("height", outerDiv.height())
		.css("position", "fixed")
		.css("opacity", "0.80")
		.css("-ms-filter", "progid:DXImageTransform.Microsoft.Alpha(Opacity = 80)")
		.css("filter", "alpha(opacity = 80)")
		.css("display", "none")
		.appendTo(outerDiv);
	jQuery('#loading').show();
	// when page is ready remove and show
	jQuery(window).load(function() {
		jQuery('#mosoftbluemarine_loader').fadeIn('fast');
		jQuery('#loading').hide();
	});
</script>
<div id="mosoftbluemarine_loader" style="display: none;">
```

The coresponding front-end edit view "header" is :
```
defined('_JEXEC') or die('Restricted access');
###SITE_ADMIN__VIEW_HEADER###
?>
<div class="mosoftbluemarine-registre">
<?php echo $this->toolbar->render(); ?>
```

### System information (as much as possible)
- OS Name & Version: Win10
- MySql Version:  	5.6.19 
- Apache Version: Apache/2.4.10 (Win32) 
- PHP Version: 7.1.22 
- Joomla Version: Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT 
- JCB Version: 2.12.3
- Browser: Firefox

### Additional comments
Seems like the pattern ###SITE_ADMIN__VIEW_HEADER### is not handled by the compiler...
Or should I add manually JHtml::_('behavior.formvalidation'); somewhere in JCB?

Thank you for your answer

**Comment by Llewellynvdm** [comment]
The placeholder `###SITE_ADMIN__VIEW_HEADER###` with the double underscore seems incorrect.

Please change the header in [this file](https://github.com/vdm-io/Joomla-Component-Builder/blob/v2.12.3/admin/compiler/joomla_3/edit_site.php) to say `###SITE_ADMIN_VIEW_HEADER###` instead.

I will push the fix out immediately. Seems like a typo on my part!

**Comment by fred-the-coder** [comment]
Great thanks
