### ISSUE TITLE
Adding new filters to the language translations view

### ISSUE THREAD

**Issue by vistamedia** [vdm-io/Joomla-Component-Builder#651]
**The problem :**
One of the nice features of JCB is the translation system. When we create custom extensions for our clients is very practical to export an excel file with the string to translate. They do the job, send us back the file then we import it back : end of the story. The problem is that the strings can be used in multiple extensions and it’s impossible to know, which strings belongs to a specific extension, what has been translated, in which language, which translation is missing…

**Our solution :** implement new filters in order to improve our translation worlkflow

**Filter strings by extension :**
With this filter we can easily select the strings that belong to a specific extension

![2021-01-17_14-14-38](https://user-images.githubusercontent.com/9335926/104844145-b77f1b80-58ce-11eb-9364-a15548e04dcd.jpeg)

**Filter string that have been translated**
With this filter we can select the strings that have already been translated either in every language or in a specific language

![2021-01-17_14-15-17](https://user-images.githubusercontent.com/9335926/104844160-d2519000-58ce-11eb-82e6-dac3e321c83d.jpeg)

**Filter string that have not been translated**
With this filter we can select the strings that have not been translated yet either in any language or in a specific language

![2021-01-17_14-15-34](https://user-images.githubusercontent.com/9335926/104844163-d8e00780-58ce-11eb-8ed4-f7ba247ee8ed.jpeg)

**You want to test it ?** Just download the attached language_translations.php.zip model file, unzip it and replace 
administrator/components/com_componentbuilder/models/language_translations.php
[language_translations.php.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/5826154/language_translations.php.zip)

**Warning : Make sure you are using the latest version of JCB before replacing the file**

Happy coding,
Agerix Team

**Comment by Llewellynvdm** [comment]
This is an excellent filter option, and indeed a great contribution.

I will add this to JCB, and make a tutorial so other can also understand how they can with this same approach be able to achieve the same.

**Comment by TLWebdesign** [comment]
Nice addition Thanks!
