### ISSUE TITLE
Media Libraries add additional Module Code

### ISSUE THREAD

**Issue by LordRazen** [vdm-io/Joomla-Component-Builder#660]
### Steps to reproduce the issue
- Create a new module, add a custom get so the default Module Code is added. 
- Add a Media Library (I used Bootstrap)

### Expected result
Normal default Code in the Code Module

### Actual result
Code snippets are repeated multiple times
```
// Include the data functions only once
JLoader::register('Mod[[[Module]]]Data', __DIR__ . '/data.php');

// Include the data functions only once
JLoader::register('Mod[[[Module]]]Data', __DIR__ . '/data.php');



[[[MOD_LIBRARIES]]]

// get the module class sfx (local)
$moduleclass_sfx = htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8');



// get the module class sfx (local)
$moduleclass_sfx = htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8');

// load the default Tmpl
require JModuleHelper::getLayoutPath('mod_[[[module]]]', $params->get('layout', 'default'));

// load the default Tmpl
require JModuleHelper::getLayoutPath('mod_[[[module]]]', $params->get('layout', 'default'));
```

### System information (as much as possible)
- OS Name & Version: Win 10
- MySql Version: mysql  Ver 15.1 Distrib 10.4.11-MariaDB, for Win64 (AMD64), 
- Apache Version: Apache/2.4.43 (Win64)
- PHP Version: PHP 7.4.6
- Joomla Version: Joomla! 3.9.24 Stable
- JCB Version: 2.12.4 
- Browser: Firefox

### Additional comments
- It seems like this is not the only variant how to trigger this multiple code addition, but it's the only one where I found a valid way to reproduce it right now.
- The code is also added again if you remove the media library

**Comment by Llewellynvdm** [comment]
This area is not yet fully dummy proof, if you see the code added double, please just remove what you know is not needed. We are trying to prevent this adding of already added code, but at times there can be a mix-up. We do not remove code that was added.

If you would like to improve this, [here is the code](https://github.com/vdm-io/Joomla-Component-Builder/blob/60f4e8af32aaa837da92bd4276f2c9ea7cf024be/admin/models/forms/joomla_module.js#L586) that adds the code into the editor/text area, with all the checks and stuff to avoid duplication. Contribution to improvements of this is welcome :+1:

**Comment by Llewellynvdm** [comment]
This area is not yet fully dummy proof, if you see the code added double, please just remove what you know is not needed. We are trying to prevent this adding of already added code, but at times there can be a mix-up.

If you would like to improve this, [here is the code](https://github.com/vdm-io/Joomla-Component-Builder/blob/60f4e8af32aaa837da92bd4276f2c9ea7cf024be/admin/models/forms/joomla_module.js#L586) that adds the code into the editor/text area, with all the checks and stuff to avoid duplication. Contribution to improvements of this is welcome :+1: 

We do at times try to remove code as your selection change, but not if you changed/adapted the code already. This [method is found here](https://github.com/vdm-io/Joomla-Component-Builder/blob/60f4e8af32aaa837da92bd4276f2c9ea7cf024be/admin/models/forms/joomla_module.js#L640), and improvements are also welcome.

**Comment by Llewellynvdm** [comment]
Yes the change of media library effect the code, since we are adding the library there if needed. So if it changes we need to also update the same area as needed.

Remember this is a helper function for those who are not that proficient in programming, and we are trying our best to make it work as expected.

So any help in this area is appreciated ;)

**Comment by LordRazen** [comment]
Thanks for the reply.

Even if I would like to help: I'm not a developer, I just know PHP and very little JS and due to JCB I finally learn more about the way Joomla works. I try to help with accurate reports in case I find something to further improve the project.
