### ISSUE TITLE
Sorting and Filtering on Checkbox doesnt work

### ISSUE THREAD

**Issue by LordRazen** [vdm-io/Joomla-Component-Builder#662]
### Steps to reproduce the issue
- Create a new checkbox field (Type: checkbox | Database:  Data Type: TINYINT, Data Length: 1, Data Default: 0, Indexes Type: None, Null Switch: Not Null, Field Modeling Method: Default)
- Add this field to an Admin View, Show it in All List Views and set "Sortable" active and "Filter" to "Yes (single)"

### Expected result
- Since the result is 0 or 1, I would expect the click on top of the column to sort the entries for those numbers. Same goes for the use of the dropdown "Sort Table by:" within the controls to the right.
- I would expect a dropdown to appear within the search tools of an admin view (like for Status or Access)

### Actual result
- Sorting dont work
- Dropdown dont appear

### System information (as much as possible)
- OS Name & Version: Win 10
- MySql Version: mysql Ver 15.1 Distrib 10.4.11-MariaDB, for Win64 (AMD64),
- Apache Version: Apache/2.4.43 (Win64)
- PHP Version: PHP 7.4.6
- Joomla Version: Joomla! 3.9.24 Stable
- JCB Version: 2.12.4
- Browser: Firefox

### Additional comments
**I recognized the cause for this is, that the column which should be sorted was not added inside the `$config['filter_fields'] = array()` inside the Constructor of the AdminView Model.**

**Comment by LordRazen** [comment]
I debugged the issue since I was curious why this didnt work and found the reason: 

The column which should be sorted and filtered (a checkbox) was not added inside the $config['filter_fields'] = array() inside the Constructor of the AdminView Model.

So I went looking for the cause inside component builder and found the reason:

Inside the com_componentbuilder\helpers\compiler\c_Fields.php file, line 5138 and 5191:
```
		// build the sort values
		if ($dbSwitch && (isset($field['sort']) && $field['sort'] == 1)
			&& ($listSwitch || $listJoin)
			&& (!$multiple && $typeName != 'checkbox'
				&& $typeName != 'checkboxes'
				&& $typeName != 'repeatable'
				&& $typeName != 'subform'))
		{
```
I can see that checkboxes are intentionally excluded from the sort and filter list. But why?

I remember a video where I got the info that Joomla does not deal with checkboxes correctly. But I wonder: I removed the
`&& $typeName != 'checkbox' && $typeName != 'checkboxes'`
in both spots and it worked perfectly, the sorting and the filtering. Sure the filter isnt pretty with the "0" and "1" as option, but I don't get why the feature is blocked when it works.

**Comment by Llewellynvdm** [comment]
Nice... you were able to trace the issue into the compiler. Yes I am blocking the checkbox/s from being used as sorting, and changing this could serve us with some challenges.

Little history, there has been a side-bar filter option and now the new top-bar filters in the list view. The previous option the side-bar filter could not work with checkbox/s and the fact that it worked in your case with the new top-bar filters is by accident and not design. Which does mean our decoupling is working and the area is stable.

But as you may have noticed it does not manage the dropdown well.

I would suggest using a radio button instead, as this works with the filters and is currently supported.

**Comment by Llewellynvdm** [comment]
The real issue with checkbox is the un-selected option does not have a text/name value. So the radio field solves that, and is therefore a better suited for filtering.

**Comment by LordRazen** [comment]
Uoh... indeed the radio button with the default bootstrap formating so it's a togglebutton is a very nice alternative for the checkbox! Thanks for the tip ^^
