### ISSUE TITLE
Problem with Label in new filter system

### ISSUE THREAD

**Issue by duetnet** [vdm-io/Joomla-Component-Builder#663]
### Steps to reproduce the issue
Implemented latest JCB update. 
Have existing field with type "list", name "list_country", label "Country".
This field appears in my admin view. 
This field is flagged in admin view as "filter = Yes (single)".

### Expected result
When viewing filters in admin view, the List field in filter form shows "label" as per field definition, i.e. : "- select Country -"

### Actual result
When viewing filters in admin view, List field in filter form shows "name" as per field definition, i.e. "- select list_country -"

### System information (as much as possible)
- OS Name & Version: Win 10 pro 64 2004
- MySql Version: 5.5.5-10.4.13-MariaDB 
- Apache Version: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.8 
- PHP Version: 7.4.8
- Joomla Version: 3.9.24
- JCB Version: 2.12.4
- Browser: Firefox/Chrome

### Additional comments
I notice that the XML file built for the filter_adminview.xml file generates a language string as follows:
- "com_component_view_fieldname_label". 
Therefore the label in the filter reflects the field "name" and not actual field "Label"
I have read through all comments on the filter, but do not find any reference to this issue. 
Is someone else also experiencing this problem?

**Comment by Llewellynvdm** [comment]
The text is build on [line 4732](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L4732) of the compiler fields class, by using the name value, unless it is a category field. So can you please var dump around this area, targeting that field and try and see what you get?

**Comment by Llewellynvdm** [comment]
See [here it gets added to the filter](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L5210) and then [into the array](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L5229) for later use when we build the filter.

**Comment by duetnet** [comment]
I have tried to trace based on info you provided to me above.
What I have established is that by the time the function setBuilders is called $langLabel is already set.
Things seem to go awry in the function setattributes (line 1599) is called from the function setdynamic field which updates the value of $langLabel.

My analysis shows that: 
1. Line 4361 get $xmlValue of the label
2. 4370 to 4387 checks for a translation and updates the placeholders. $xmlValue is update
3. I do not understand what happens in function setPlaceholders, because the label does not appears in the placeholders array, so it is not adding or updating this array
4.  4396 $langValue and 4403 $xmlValue is updated with the property 'name' 
5. Line 4455 $langLable is updated with  $xmlValue

**This issue does not just occur with LIST fields, but ANY field which I decide to use as a filter field in the admin view, EXCEPT  CUSTOM fields where I control the TEXT for the OPTION "select Country', etc.**

My field names have a 3 char prefix+underscore+cryptic name, as shown in example below. JCB uses the field name and replaces the underscore with a SPACE. The RED DOT filter is a CUSTOM field TYPE

![image](https://user-images.githubusercontent.com/47208167/106352922-7552d280-62ef-11eb-81fc-aa67fbab1bae.png)

This is a radio field example
![image](https://user-images.githubusercontent.com/47208167/106353138-0eceb400-62f1-11eb-8120-012b3067e1d0.png)



Below is the actual XML for the field "txt_bank"
![image](https://user-images.githubusercontent.com/47208167/106353043-5ef94680-62f0-11eb-81a2-df3f8909cc71.png)


And this is the acrual translation for the label "COM_DUETSOFT_BANK_TXT_BANK_LABEL"
![image](https://user-images.githubusercontent.com/47208167/106353060-84865000-62f0-11eb-9641-f15f534e34d5.png)


I hope this helps to pinpoint the problem as I am at a loss on determining EXACTLY where it goes wrong in the compiler.

Regards

**Comment by Llewellynvdm** [comment]
Try to replace all the code in side the else block from line [4727](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L4727) with the following:
```php
// if label was set use instead
if (ComponentbuilderHelper::checkString($langLabel))
{
	$listLangName = $langLabel;
	// set field name
	$listFieldName = $this->langContent[$this->lang][$langLabel];
}
else
{
	// set lang (just in case)
	$listLangName = $langView . '_'
		. ComponentbuilderHelper::safeFieldName($name, true);
	// set field name
	$listFieldName = ComponentbuilderHelper::safeString($name, 'W');
	// add to lang array
	$this->setLangContent(
		$this->lang, $listLangName, $listFieldName
	);
}
```

**Comment by duetnet** [comment]
Hi 

The new code has definitely appeared to fix the issue.

![image](https://user-images.githubusercontent.com/47208167/106359028-6cc2c200-6318-11eb-9d6a-155c385abb6e.png)

I will do further testing to see that nothing else is affected.

Thank you
