### ISSUE TITLE
Joomla 3.9.25 breaks JCB compiler page, don't upgrade just yet!!!!

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#678]
### Steps to reproduce the issue
When you upgrade to [Joomla 3.9.25](https://github.com/joomla/joomla-cms/releases/tag/3.9.25) there are a number of supersizes... one is that they strip all JavaScript from system messages. This means the compiler page buttons stop working, ans they are `onclick="install()"` buttons.

### Expected result
That they would not mess with system **"developer generated messages"**

### Actual result
They just added the following update to the message area.
https://github.com/joomla/joomla-cms/commit/aadf6979f8b99308c3621ea3af2ca98e678a477d#diff-cc812ef35110247c370f8a84f5ee62a1ed85bab5747ee4b0252bde2c6836b920R177

### Additional comments
We are working on a fix for this, and soon as its ready I will update this issue.

**Comment by Llewellynvdm** [comment]
This commit above should resolve this issue... we will make an urgent release.

**Comment by LordRazen** [comment]
Quite happy this got fixed. Thanks a lot!

I ust wonder: Whenever I compile (within Firefox), my qhole compiler page is marked and therefor turns blue. Like I selected the whole page with Strg + A. This is a cosmetic issue, everything works, that's why I didnt create an issue. If you would like to investigate, my settings can be found here: https://github.com/vdm-io/Joomla-Component-Builder/issues/686

**Comment by Llewellynvdm** [comment]
The screen going blue is new, I did that to prevent you from clicking on anything during compilation. I could add a switch to remove that behavior... 

Reality is that it does not effect the compiler at all. There is a whole new "graphic" being used and the page also has the notices on the side during compilation.

I will still push out a little tutorial about the update...

**Comment by Llewellynvdm** [comment]
Maybe I can make it green instead... :+1:

**Comment by LordRazen** [comment]
Oh, that might help indeed. The blue suggests Ctrl+A and it feels like a bug somehow. Any other colour would probably more feel like a feature ^^
