### ISSUE TITLE
SEF MOD joomla does not work site view item

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#68]
IN SEF mod joomla is on,  the demo component "looking" doesn't work.
Error message  
COM_DEMO_NOT_FOUND_OR_ACCESS_DENIED

"sss" - name of joomla menu item
"sdasd" - name of looking
"/sss/looking/sdasd.html"  - auto generated menu adress, which causes error
/index.php?option=com_demo&view=looking&id=1:sdasd&Itemid=300  - full adress in the same option -  ok

**Comment by Llewellynvdm** [comment]
Can you give some info surrounding the Joomla version and operating system.

**Comment by Llewellynvdm** [comment]
Okay I found this issue, will commit a fix soon. Thanks this is a bug.

**Comment by Llewellynvdm** [comment]
This is a on [line 4126](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L4126) of the Interpretation class. I have been looking at this issue for some time now. Trying to catch various kind of components, I have been making changes to this area. SO it use to work for the Demo... but not for other components. So I changed it, now it broke the demo lol... but okay I think a found a fix.

**Comment by ro-ot** [comment]
The other issue here is the permissions @canfine you will in the back-end of the demo component see a options button in the right corner. When you open the global options for the demo component, you will see there is a permissions tab. Search for **(Site) Access** you will see that you need to give access to the public or any group that you would like to have access to the front views. This is a stunning and easy control system of access control to the views. 

If you would like to compile the demo component without this permmision then you can in the component in JCB in the back-end. If you open the component "Demo" in JCB there is a tab [Settings] once you open that you will see a button called " Site Views" [Add] opening that you will see the front-end views are linked there. Change the **Add Access** to No next to the view that you don't want this access control and save the changes.

Go back to the compiler, and recompile and install the demo component, and now that permission control will not be there.

Hope this helps.

@Llewellynvdm the bug you found is still true, but I seemed that @canfine got stuck even before getting to that part.

**Comment by Llewellynvdm** [comment]
@canfine if you download the latest version and follow @ro-ot guidance on the permission this should resolve your issue. Let us know if you are still stuck.
