### ISSUE TITLE
Drag and drop ordering of Admin View fields doesnt save

### ISSUE THREAD

**Issue by multizone-uk** [vdm-io/Joomla-Component-Builder#694]
### Steps to reproduce the issue
Choose an Admin View, and press the 'edit' button
Drag a field record to a different position in the list by clicking and holding the blue ordering control
Save and Close
Notice that the ordering of the linked fields has not changed in the displayed table.

### Expected result
The ordering of the linked fields should have changed

### Actual result
It did not

### System information (as much as possible)
- OS Name & Version: Ubuntu 20.04
- MySql Version: Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu
- Apache Version:  2.4.41 
- PHP Version: PHP Version 7.4.3
- Joomla Version: 3.9.25
- JCB Version: 2.12.9
- Browser: Firefox 86.0 and Chromium 89.0.4389.82 same results

### Additional comments
Im quite experienced with Joomla, but I am a novice with this component and with development so I thought I would try to use it to develop a system.

**Comment by Llewellynvdm** [comment]
The ordering of the fields are not controlled by the subform ordering, but by the column called ordering. You can read about this change in some very old issues where this was implemented.

https://github.com/vdm-io/Joomla-Component-Builder/issues/43
https://github.com/vdm-io/Joomla-Component-Builder/issues/44

You will see that on save we order the fields based on the ordering column, which means you can add a new field, add it to a tab, and to a position, and give it an ordering number, without moving it into place, and when you save we move it to its correct place... that is the win... but if all your fields are set to `0` ordering then JCB false back to the subform ordering.

- [Here is the code that orders the form on save](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/admin_fields.php#L836)....
- [Here is the code in the compiler that falls back to subfrom ordering](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/c_Fields.php#L3923)...

I am closing this as the behavior is as expected in our design, but if you feel improvement can be made, your welcome to just continue communicating here with me, and we will re-evaluate our options.

**Comment by multizone-uk** [comment]
Thanks so much for the detailed response. Understood. Enjoying the depth of this component so far!
