### ISSUE TITLE
How does  Linked Views work?

### ISSUE THREAD

**Issue by canfine** [vdm-io/Joomla-Component-Builder#70]
As I understand, This featere uses for linking one table to another. How should it use? Which type of conection its realised "one to one", "one to many", "many to many" ? and how I can do such connections?

**Comment by Llewellynvdm** [comment]
I have made tutorials to how all this work, and at this time these tutorials are not for free. So if you want to get access to these tutorials I can give you 25% discount. Please read [this issue](https://github.com/vdm-io/Joomla-Component-Builder/issues/1).

**Comment by Llewellynvdm** [comment]
But yes there is ways to connect one to many and many to one. Infact this is done not only with linked views, but also custom fields. The custom fields are part of the tutorials.

**Comment by Llewellynvdm** [comment]
There are some videos open to the public check out this [play list](https://www.youtube.com/watch?v=9evJkBTnKxE&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE), the last and first view videos are open.
