### ISSUE TITLE
Feature request: calendar field type display one format, but store another

### ISSUE THREAD

**Issue by denovoit** [vdm-io/Joomla-Component-Builder#708]
When working with the calendar field type we normally need to store the value in the database as in this format 0000-00-00 00:00:00 (%Y-%m-%d %H:%I.%S). 

However, JCB allow us to translate the format, to what is native to the user, e.g. %d-%m-%Y %H:%I.%S. But if we use translate format, then the field will not save to the database, as it will try to save in the translated format and not the format set in the format property. 

In other words, I would like to be able to translate the format when displayed to the user, like e.g. 23-03-2021 22:32:37, but store it in the database as 2021-03-23 22:32:37.

I'm sure there is a way to do this, but it would be awesome if JCB could support this out of the box, when translate format was set to true.

**Comment by Llewellynvdm** [comment]
Please check out the discussion area, and use that area for these kind of issues as it is not core code related.

ps. This is where you can look https://github.com/vdm-io/Joomla-Component-Builder/discussions?discussions_q=date

**Comment by denovoit** [comment]
Moved the topic to discussions. For reference: https://github.com/vdm-io/Joomla-Component-Builder/discussions/709
