### ISSUE TITLE
Double slash after compilation 

### ISSUE THREAD

**Issue by infotecnica** [vdm-io/Joomla-Component-Builder#712]
### Steps to reproduce the issue
In the site view I have these lines of javascript code for datatable 
`var select = $('<select><option value=\"\">Show all</option></select>')`

`select.append( '<option value=\"'+d+'\">'+d+'</option>' )`
### Expected result
in file view.html.php
`var select = $('<select><option value=\"\">Show all</option></select>')`

`select.append( '<option value=\"'+d+'\">'+d+'</option>' )`

### Actual result
in file view.html.php
`var select = $('<select><option value=\\"\\">Show all</option></select>')`

`select.append( '<option value=\\"'+d+'\\">'+d+'</option>' )`
### System information (as much as possible)
- OS Name & Version: CentOS Linux 7.9.2009 (Core)
- MySql Version: 5.5.5-10.5.9-MariaDB
- Apache Version: 2.4.6-97.el7.centos
- PHP Version: 7.4.16
- Joomla: Version: 3.9.25
- JCB Version: 2.12.9
- Browser: Firefox

### Additional comments
and of course I get this error running the component:
syntax error, unexpected '\' (T_NS_SEPARATOR), expecting ')'

**Comment by Llewellynvdm** [comment]
Where are you adding this code?

**Comment by Llewellynvdm** [comment]
Yes I see you are having the code in the `view.html.php` file, but how does it get there... where in JCB are you adding this code.

**Comment by infotecnica** [comment]
This is the code that generates the datatable table:

```
			$(document).ready(function() {
			     $('<button>click to view archive  </button>')
			        .prependTo( '#above' )
			        .on( 'click', function () {
			        alert( 'Funzione in costruzione: ' );
			        } );
					
			    $('#register').DataTable( {

			        initComplete: function () {
						buttons: [
							'copy', 'excel', 'pdf'
						]
			            this.api().columns([4, 5, 6]).every( function () {
			                var column = this;
			                var select = $('<select><option value=\"\">Show all</option></select>')
			                    .appendTo( $(column.header()) )
			                    .on( 'change', function () {
			                        var val = $.fn.dataTable.util.escapeRegex(
			                            $(this).val()
			                        );
			                        column
			                            .search( val ? '^'+val+'$' : '', true, false )
			                            .draw();
			                    } );
			 
			                     column.data().unique().sort().each( function ( d, j ) {
			                    select.append( '<option value=\"'+d+'\">'+d+'</option>' )
			                } );
			            } );
						
			        }
			    } );
				
			} );
```
inserted in the Add JS (custom document script) tab * of the site view .

**Comment by Llewellynvdm** [comment]
Okay so this area does auto escape of all `"` characters as they are wrapped into a php string. If you don't need to use PHP values in this JS then move the code to the  `Add JavaScript (file) *` since this area does not have the auto escape of all `"` characters.

**Comment by infotecnica** [comment]
Ok i moved the code and everything works fine.

Thanks
