### ISSUE TITLE
Edit in site view override library calls

### ISSUE THREAD

**Issue by infotecnica** [vdm-io/Joomla-Component-Builder#723]
### Steps to reproduce the issue
I just add an edit button to the record list element 

### Expected result
The element can be edited by clicking on the edit button instead by clicking on an element in the list, I expect the related detail to open as set before adding the edit button 

### Actual result
The element is always editable by clicking on the edit button instead clicking on an element in the list skips the graphics and does not show me the detail fields.

### System information (as much as possible)
- OS Name & Version: Linux vmi309661.contaboserver.net 3.10.0-1062.el7.x86_64
- MySql Version: 5.5.5-10.5.9-MariaDB 
- Apache Version: 
- PHP Version: 7.4.16 
- Joomla Version: 3.9.25
- JCB Version: 2.12.9
- Browser: Mozilla Firefox

### Additional comments
It basically loads footable files instead of datatable files.

**Comment by infotecnica** [comment]
I add images before and after edit 
![before-edit](https://user-images.githubusercontent.com/21063487/113405594-61d4ee00-93aa-11eb-9f27-c7c0e37357bd.jpg)
![After-edit](https://user-images.githubusercontent.com/21063487/113405605-66010b80-93aa-11eb-9f48-ac1a9cc3edd4.jpg)

**Comment by Llewellynvdm** [comment]
I am not sure I understand what you are trying to do, and what really is the issue. Please explain more...

**Comment by Llewellynvdm** [comment]
Really sorry it took me so long to get to your issue...

Your adding another set of buttons, and it is not behaving as you would like.... is what I get from your posts.

You can override the form behavior in JCB, to move your buttons outside of the form, as this can have an effect. Next you can with a placeholder move the buttons anywhere you like on the page.

But before I give direction in these matters I need to understand more.

**Comment by infotecnica** [comment]
I thank you for your answer and I apologize if I was not clear enough.

But it's not the buttons that cause the problem but the fact that I don't see the records when I edit from the front-end, as well as messing up the graphics. I saw that it doesn't load datatable libraries for me. While if I don't apply the front-end editing everything is ok and datatable libraries are regularly loaded

**Comment by Llewellynvdm** [comment]
Check that the front-end view name is not the same as the admin-view name. So if the back-end has the  view name:
**car**, and **cars**.... you can't call the site-view **car**, but instead call it **car_display** or **motorcar**. Should these names be the same then those views will collide.

Let me know if you have any further questions on this issue,
