### ISSUE TITLE
Compilation error of JCB Component Builder using JCB 2.12.9

### ISSUE THREAD

**Issue by duetnet** [vdm-io/Joomla-Component-Builder#727]
### Steps to reproduce the issue

Upload package JCB Component Builder public (also same issue with package for pro v3)
Compile with JCB

### Expected result

Successfully compiled component

### Actual result
Error during compile (of both componenents

### System information (as much as possible)
See attached document for details.
[jcb2_12_9_compiler_error.docx](https://github.com/vdm-io/Joomla-Component-Builder/files/6284644/jcb2_12_9_compiler_error.docx)

### Additional comments
See attached document for details of steps taken to test and then to resolve based on Meeting with Llewellyn.

**Comment by Llewellynvdm** [comment]
Please try adding the following lines to the a_interpretation.php compiler file replacing the code block around line 5788 with the following:
```php
// just to check if the submission script is manually added
if (!isset($view['settings']->php_document)
	|| !ComponentbuilderHelper::checkArray(
		$view['settings']->php_document
	)
	|| (ComponentbuilderHelper::checkArray(
			$view['settings']->php_document
		)
		&& strpos(
			implode(' ', $view['settings']->php_document),
			'/submitbutton.js'
		) === false))
{
	// set the custom get form method  JAVASCRIPT_FOR_BUTTONS
	$this->fileContentDynamic[$view['settings']->code][$this->hhh
	. $TARGET . '_JAVASCRIPT_FOR_BUTTONS' . $this->hhh]
		= $this->setJavaScriptForButtons();
}
```

**Comment by duetnet** [comment]
Will do and test. Thanks

**Comment by duetnet** [comment]
Changes did resolve the issue, thank you
