### ISSUE TITLE
Typo in notice in compiler

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#735]
This line has typo "folder/s" instead of folders. 
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/b_Structure.php#L2102 

This line also had the "folder/s" typo and component is not spelled correctly towards the end of the sentence. 
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/b_Structure.php#L2107

typo "component"
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/views/compiler/view.html.php#L187
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/views/compiler/view.html.php#L189
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/site/helpers/componentbuilder.php#L1116
https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/c_Fields.php#L6138

**Comment by Llewellynvdm** [comment]
> This line has typo "folder/s" instead of folders.
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/b_Structure.php#L2102
> 
> This line also had the "folder/s" typo and component is not spelled correctly towards the end of the sentence.
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/b_Structure.php#L2107

The folder/s means one folder or many folders... since we are not counting them. So this one is not a typo.


> typo "component"
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/views/compiler/view.html.php#L187
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/views/compiler/view.html.php#L189
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/site/helpers/componentbuilder.php#L1116
> 
> https://github.com/vdm-io/Joomla-Component-Builder/blob/48d92659838a993ea98a9e6691b0209c0d381aeb/admin/helpers/compiler/c_Fields.php#L6138

These are typos, so if you like you can make a pull request for these componet typos... thanks.

**Comment by Llewellynvdm** [comment]
So all the places you found my `componet` typo you can correct, but please make sure to not change any other lines... as the once you identified here. so do not use auto code formatting.
