### ISSUE TITLE
Access Compiler from the Component Overview

### ISSUE THREAD

**Issue by LordRazen** [vdm-io/Joomla-Component-Builder#747]
Not a bug - it's a feature suggestion. 

I would think it'll be a very good idea to add a "Compile" button to the Joomla Components Admin View for every component. 

This way, you could save the "Go to Compiler -> Select -> Compile" Routine which has to be used quite often in my opinion. 

I know there're options for the compiler, but those could be set as default in the global component config or just assume the defaults anyways.

**Comment by TLWebdesign** [comment]
I don't see how this would speed up workflow much. it would mean you'd still have to keep another window open. I'm also constantly re-opening the compiler window so i understand where you are coming from. But the component admin view is one i don't have open much at all.
It would be nice if you could compile from any screen tho. like if i was in a layout or template or site view. i could click the compile button and it would automatically compile in a new window. the component the view is attached to. But that sounds very complicated.

**Comment by LordRazen** [comment]
Indeed having such a feature on every page would be even better, but in case there're multiple components in the JCB, there need to be a dropdown or something like this. 

Setting up some defaults in the JCB config might make it possible to do it with one click: Basically all the options from the compiler page go to the global settings and can be configured for the "compile" button on every page. So you kinda setup a default project for this button. 

Lets see where those ideas go ^^
Kinda curious what

**Comment by TLWebdesign** [comment]
Ok but then you have compiled. What is your next step? Mine is 99% of the time installing on the site i compiled it on. 

So i guess clicking compile would mean it has to open a new page that shows the compilation results and from there you could install. Or even a "compile", "compile and install" and "compile and download" option. 

But maybe we should stop day dreaming now haha. Seems like a huge ask for such a small gain.

**Comment by Llewellynvdm** [comment]
The closes we come to the ideal solution now is with the `Run Expansion` button, you can in the global options setup which component you would like to install and any other nice tweaks. Then where ever you click this button it will build and install all in one go that or those extensions. I have not been using this feature... but that is how it can be used.

So there you have your one button compile and install ;)

I will close this issue as I don't think we will add any more improvements on this front soon... really smart options already there. Let me know what you think...

**Comment by Llewellynvdm** [comment]
Checkout this tutorial: https://www.youtube.com/watch?v=ozp6m12Fj0o&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=77

**Comment by TLWebdesign** [comment]
Hmm i need to check that out as it seems almost what we described. Could save some time. BTW also like how the compiler page state saves after compilation. Idk how many times before i clicked away and had to recompile again ;)
