### ISSUE TITLE
Error when tags column visible in backend list view 

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#748]
### Steps to reproduce the issue
Create a field with field type "tag" and make it visible in all list views.

### Expected result

Have tag names show up in list view. 

### Actual result

Error:
<img width="1198" alt="Schermafbeelding 2021-05-18 om 09 52 48" src="https://user-images.githubusercontent.com/4402824/118644278-f15d2180-b7dd-11eb-9dbc-cfad46819619.png">

### System information (as much as possible)
- OS Name & Version: Macos
- MySql Version: mariadb 10.4.x
- Apache Version: 2.4.x
- PHP Version: 7.3.x
- Joomla Version: 3.9.26
- JCB Version: 2.12.9
- Browser: Safari 14.1

### Additional comments

It seems the compiler doesn't take into consideration that a tag field is a non database field. These values are not stored in the view table but in ucm map table. Would be nice if the backend view would automagically call the helper tag class and get the tag names comma separated instead of showing an error.

I actually made this happen with field relations by calling the helper class i created for this. and my code is:

public static function getTagsTitle($id, $view, $type = 'string') {
	$t = new JHelperTags;
	$contentType = "com_[[[component]]].".$view;
	$tagIds = $t->getTagIds($id, $contentType);
	$tagIdsArray = explode (",", $tagIds);
	$tagTitles = $t->getTagNames($tagIdsArray);
	if ($type == 'string') 
    {
		$tagTitles = implode(', ',$tagTitles);
    }
	return $tagTitles;
}

More documentation on tagsHelper class: https://api.joomla.org/cms-3/classes/Joomla.CMS.Helper.TagsHelper.html

**Comment by Llewellynvdm** [comment]
Okay so the tags implementation in list views has never been finished, as I never needed it before... lol

I can add this, but know that its filer is also not finished far as I know, and for this I don't have time right now.

**Comment by Llewellynvdm** [comment]
This is the code I will add the get item method of the list view:

```php
// get the needed tags
$item->tags = new JHelperTags;
$item->tags->getTagIds($item->id, 'com_[[[component]]].[[[view]]]');
if ($item->tags->tags)
{
	$tagTitles = $item->tags->getTagNames(explode(',', $item->tags->tags));
	$item->tags = implode(', ', $tagTitles);
}
else
{
	$item->tags = '';
}
```

**Comment by TLWebdesign** [comment]
Worked like a charm! :) Thanks
