### ISSUE TITLE
Dynamic Get on Joomla 3.7.0 issue

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#75]
I discovered when attempting to finalize some gets on my component that the Selection box on Join View Tables, and also on Join DB Tables, isn't populating with the fields from the selected DB. (This is on the repeatable fields)

I did some testing, and the select box (Text Area) would populate with Joomla! 3.6.5, running JCB 2.4.3, but after upgrade to JCB 2.4.4 and Joomla 3.7.0 they no longer populate.

Even after a fresh install of Joomla 3.7.0 and JCB 2.4.4 there was no change.

Now, I am seeing the following in webmaster tools console:

jquery-migrate.js?eb66ae6…:23 JQMIGRATE: Migrate is installed with logging active, version 1.4.1
jquery-migrate.js?eb66ae6…:45 JQMIGRATE: jQuery.fn.load() is deprecated
migrateWarn @ jquery-migrate.js?eb66ae6…:45
jquery-migrate.js?eb66ae6…:47 console.trace
migrateWarn @ jquery-migrate.js?eb66ae6…:47

Note: I tested this on my localhost, and on separate hosting server with the same issues.

**Comment by Llewellynvdm** [comment]
I will have a look at this, yet I did not have this issue as far as I know.

**Comment by ro-ot** [comment]
Yes I also found this, must be that Joomla changed some of their conventions in the field naming.
