### ISSUE TITLE
Please edit the language files!!!

### ISSUE THREAD

**Issue by rigin** [vdm-io/Joomla-Component-Builder#770]
### Steps to reproduce the issue
I am trying to make the localization of the component interface into Russian.

In the JCB_v2.12.10\admin\language\en-GB\en-GB.com_componentbuilder.sys.ini file, it is almost impossible to understand the meaning of most phrases. Especially DESCRIPTION!!

Please edit the interface text according to the rules of the English language. Or at least, place punctuation marks (.,).

You can't mock users like that! ))))

### Additional comments
I use machine translation from English, so the absence of commas and articles leads to a complete loss of meaning.

**Comment by Llewellynvdm** [comment]
I am sorry that my English do not meet your expectation, I am certainly not mocking anyone. Never helps to make your first post an attack on the person who is the reason this project exist for free.

I see you joined [Crowdin](https://crowdin.com/project/joomla-component-builder) and that is really the only place to communicate with other translators...

We need to import the new strings (as Crowdin is outdated) we also need to finish the bridge between crowdin and JCB.

My current focus is on moving JCB to Joomla 4 and so unless another person in the community has the time to fix these Language issues, I just can't do so right now, nor in the foreseeable future.

Thank you for your understanding.

**Comment by rigin** [comment]
Dear Llewellyn,

I am very sorry that you perceived my post as an attack on you personally.

It's not about your English. The problem is in my English. And also, it seems to me, in the English language of those who do not have English as their native language.
I compensate for my poor knowledge of English by translating the interfaces used into Russian using translation programs, for example, qTranslate.

Phrases like "Allows the users in this group to create create admins fields conditions" lead to a stupor of the translation program... )))

The result of the translation is a complete loss of the meaning of the phrase.

With respect,
Vadim Rigin.

**Comment by Llewellynvdm** [comment]
No offense taken, just the reality of time constraints, as explained.

The compiler generates those strings... we could improve this, I am just not able to look at this now.

**Comment by rigin** [comment]
Can I get the original language files in Afrikaans from you?
I will try to translate it directly into Russian.

**Comment by Llewellynvdm** [comment]
Like I said, those strings are being build by the compiler, and JCB is set to use English as its core language. There is no "original" Afrikaans language files.

I would say that part of translation is that you should understand English well enough... with this I can't help.

I am truly sorry that automatic generated strings are coming out so weird. I think we can fix that:
> I am just not able to look at this now.
