### ISSUE TITLE
Pagination on Custom Admin View Shows But does Not Work

### ISSUE THREAD

**Issue by philecom** [vdm-io/Joomla-Component-Builder#774]
### Steps to reproduce the issue

Create a dynamic Gets | enable pagination
Add it to a custom admin view
Add custom admin view to a component
Compile and Install Components
Open component 
Click on the pagination buttons at the bottom of the page.

Error can be seen in the browser console when you click on a button. 

### Expected result
It is supposed to select the next list of items but it just jumps to the top as if you're using an empty anchor tag.

### Actual result
This is what I see in the console when I click on any of the pagination buttons.
`Uncaught TypeError: document.adminForm.limitstart is undefined`

### System information (as much as possible)
- OS Name & Version: Linux business39.web-hosting.com 2.6.32-954.3.5.lve1.4.82.el6.x86_64
- MySql Version: 10.3.28-MariaDB-log-cll-lve 
- Apache Version: Apache
- PHP Version:  7.3.28 
- Joomla Version: Joomla! 3.9.28 Stable
- JCB Version: Version: 2.12.9
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

**Comment by Llewellynvdm** [comment]
This is indeed a issue, we never completed this feature in the admin view.

As JCB was and is still build as I need features for my own client projects... I just have not needed this yet. So everything you already see in JCB was all by client request and was indirectly funded.

Having said that, I am sure we could and should fix this issue. So I will add this issue to the todo feature requests.

**Comment by Llewellynvdm** [comment]
All todo feature request are in closed state until someone takes it up and does the work (code) then we open it again. So we close this issue... but it is in the list now.
