### ISSUE TITLE
Add subfolder in media folder

### ISSUE THREAD

**Issue by Polm90** [vdm-io/Joomla-Component-Builder#778]
Hi,
I was trying to add a custom file in a subfolder in the media folder.
I have specified as path "media/custom_folder" but when I install the component, the "custom_folder" is not created (and the custom file is not copied). I noticed that in the component xml file, in the media folder list, the "custom_folder" is not specified (however, the file is correctly included in the zip package).

Anyway, if I specify as path "media/images/custom_folder" it works :)

**Comment by Llewellynvdm** [comment]
The best way is not to move the file but the folder.

So in the custom folder, create a folder `jcb_admin_root/custom/custom_folder` and place your file in this folder, and then add the folder to JCB and the target `/media/custom_folder`

This should work, let me know.
