### ISSUE TITLE
Feature request - placeholder in target path field

### ISSUE THREAD

**Issue by TLWebdesign** [vdm-io/Joomla-Component-Builder#779]
### Steps to reproduce the issue
Being able to use placeholders in the "target path" field in the "Adding Custom Files & Folder" area.

### Expected result
When adding a path like this: libraries/[[[component]]]/mollie it saves an uses that for target path.

### Actual result
When i hit save i get redirected back to component settings and it shows this warning: Warning required field: Target Path

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: latest
- Browser: 

### Additional comments
It doesn't allow me to use the [[[component]]] placeholder in this field. Would be nice if we could make it work like this so it's variable.

**Comment by Llewellynvdm** [comment]
All todo feature request are in closed state until someone takes it up and does the work (code) then we open it again. So we close this issue... but it is in the list now.
