### ISSUE TITLE
Additional "issue", re: Issue #75

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#78]
In moving through a few more parts, since the upgrade to Joomla! 3.7.0, it looks like another multi-select box that "broke" is on the admin views -> conditions. The Match isn't loading with different options as it used to. I haven't checked anywhere else as yet to see if there are any other issues.

**Comment by Llewellynvdm** [comment]
Okay, thanks. Joomla made a change in the id structure of each field in a repeatable field. Painful when they do these things, but okay I fixed that and lets see if there is more before I push the update.

**Comment by mwweb** [comment]
Since joomla made a change like that, is there something that jcb users need to change in repeatable fields that they may use?

**Comment by Llewellynvdm** [comment]
Only if they attached JavaScript to the ids of each repeatable field. What changed?

`id="jform_fields_field_name-1"` became `id="1-jform_fields_field_name"`

So they moved the counter of the field.

Everything JCB builds still works, but if you added custom JavaScript to the repeatable fields you may also have this problem.

**Comment by ro-ot** [comment]
They made the change so you could move the fields around and so change the order of the fields. So it was needed and could not be avoided. Repeatable fields should be treated as beta as you all know I suppose and it still has many bugs, or so I think. So we should keep an eyes on this.
