### ISSUE TITLE
Cant select Base64 as a filter in ajax inputs 

### ISSUE THREAD

**Issue by antonbag** [vdm-io/Joomla-Component-Builder#784]
### Steps to reproduce the issue
In a Site View or Admin view-> PHP tab -> add PHP (AJAX) to yes, add an Ajax input, fill it with any data and in the field "select a Filter", select "base64". And Save.

### Expected result
The filter keeps the "base64" option.

### Actual result
The filter ignores the selection and shows "INT".

### System information (as much as possible)
- OS Name & Version: Ubuntu neon
- MySql Version: 
- Apache Version: 
- PHP Version: 7.4
- Joomla Version: 3.9.x
- JCB Version: 2.12.10
- Browser: chrome

**Comment by Llewellynvdm** [comment]
Not sure of the actual implementation you are trying to achieve. So please share code, screenshots and more details of what your trying to do. This does not sound like a bug, but a lack of knowing how the feature works... which is normal as this feature has many moving parts. Make sure to watch all tutorials on this topic... and share more details if needed here, so we can better understand your problem.

**Comment by TLWebdesign** [comment]
I just tested this and can confirm this bug.

**Comment by TLWebdesign** [comment]
**BEFORE SAVE**
<img width="1131" alt="Schermafbeelding 2021-08-16 om 10 17 21" src="https://user-images.githubusercontent.com/4402824/129533156-10ff930e-5a39-4603-a43e-430e261396a9.png">
**AFTER SAVE**
<img width="1134" alt="Schermafbeelding 2021-08-16 om 10 17 33" src="https://user-images.githubusercontent.com/4402824/129533220-ff4fbb7a-206a-4bd1-8115-a90fd72bfd9d.png">

**Comment by TLWebdesign** [comment]
Tested it on 2 different installs (two different servers) both on 2.12.10
