### ISSUE TITLE
What training videos to make next....

### ISSUE THREAD

**Issue by Llewellynvdm** [vdm-io/Joomla-Component-Builder#8]
## This is the videos already made

The [list of videos](https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE) that are already available are:
1. \- [Intro](https://youtu.be/9evJkBTnKxE?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE)
2. \- [Installation](https://youtu.be/t6Eux157428)
3. \- [General Planning](https://youtu.be/gEgwiVNj6N0)
4. \- [Field Types](https://youtu.be/OhLzvThDXls)
5. \- [Basic Fields](https://youtu.be/9NO2rKnC6Ug)
6. \- [Admin Views](https://youtu.be/CdSKSCTzmRA)
7. \- [Advanced Fields](https://youtu.be/VpzYbifqv0M)
8. \- [Adding Admin Views to a Component](https://youtu.be/39vY66X7GGU)
9. \- [Component Settings](https://youtu.be/V2WkTjNFjvo)
10. \- [Component Scripts](https://youtu.be/xY9TWQrF8AQ)
11. \- [Component FTP and more](https://youtu.be/hzbZlLl-xlA)
12. \- [dynamicGet](https://youtu.be/OPuCoxPW35s)
13. \- [Adding dynamicGet to a Site View](https://youtu.be/vEJZe6XqHJE)
14. \- [Adding Templates and Layouts to a Site View](https://youtu.be/6VBbi3Rl2eY)
15. \- [Template Setup](https://youtu.be/khxKeeubhiY)
16. \- [Layout Setup](https://youtu.be/52OLSZio0F8)
17. \- [Custom Admin Views](https://youtu.be/gtdQ1lwB9ds)
18. \- [Adding Site Views to a Component](https://youtu.be/zZ_HJeYL8ps)
19. \- [Adding Custom Admin Views to a Component](https://youtu.be/sPEkbuNXwds)
20. \- [Tweaking MySQL Demo Data](https://youtu.be/wkSLZUEN-RE)
21. \- [Global Settings of Component Builder](https://youtu.be/LA2WDi8G79E)
22. \- [Adding a custom time field](https://youtu.be/epA9zv4yWu0)
23. \- [How to use email helper in your components.](https://youtu.be/tp6mMUTOF2Y)
24. \- [How to setup a store message method along side the email helper class](https://youtu.be/peVNLsAncGY)
25. \- [How to ensure that a field is not escaped when added to list views.](https://youtu.be/bfl0l3AoLKU)
26. \- [How to change exported values and setup custom import options](https://youtu.be/fau5mZ6naLc)
27. \- [How to overwrite the custom fields](https://youtu.be/FHQfIhWHYyQ)
28. \- [How to filter a list field based on association with another field](https://youtu.be/Z8FLifQOjUk)
29. \- [Automatic import of custom code during compilation in JCB](https://youtu.be/DFMfIl-VkSk)
30. \- More coming....
### Here is a list of the training videos we are planning to make next:
- How to use email helper in your components. [[Done](https://youtu.be/tp6mMUTOF2Y)]
- How to ensure that a field is not escaped when added to list views. [[Done](https://youtu.be/bfl0l3AoLKU)]
- How to change exported values and setup custom import options [[Done](https://youtu.be/fau5mZ6naLc)]
- UIkit Implementation (automation explained)
- How to setup a store message method along side the email helper class[[Done](https://youtu.be/peVNLsAncGY)]
- How to overwrite the custom fields [[Done](https://youtu.be/FHQfIhWHYyQ)]
- How to set the limit box in site views to a custom location
## Please add your requests below:

_Please elaborate enough so we can understand the request without needing more explanation. Should the request be unclear it will be deleted and ignored._

**Comment by mwweb** [comment]
This is a tough choice. The email helper is your newest addition, so it might be good to know more about how it works. But on the other hand learning about escaped fields might be good too.

**Comment by paolavness** [comment]
Advanced ACL goodies :)

**Comment by mwweb** [comment]
A suggestion...

A tutorial on how to make/add frontend filters. For example, on Sermon Distributor if you had an "All Sermons" page, it would display a list of all sermons. But, at the top of the view, there would be filters, let's say Series and Preacher. If you selected a particular Preacher, it would dynamically filter the list to only show that Preacher's sermons.

Granted, you can create individual views, like you do now, but some may want a full list of everything, then be able to filter that main list.

**Comment by stutteringp0et** [comment]
I bought access several days ago, and I think there may be a problem with your site and automation.  I haven't received any emails, and the youtube playlist remains private to my youtube account. I administer my mail server, and in reviewing the logs - there have been no email attempts from any vdm.io MX.

I opened a ticket on the vdm.io site 3 days ago, but I have seen no response. "#235977 - tuturials"

Additionally, http://vdm.bz/component-builder-tutorials gives a URL Shortener database error.

> Fatal error
> 
> Incorrect DB config, or could not connect to DB
> 
> Powered by YOURLS v 1.7.1 – 1 query

**Comment by Llewellynvdm** [comment]
Tutorials are now free!!!!
https://www.youtube.com/playlist?list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE
