### ISSUE TITLE
Admin View Conditions

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#82]
I had conditions set in an admin view that would show or hide elements based on a radio. That was working fine, until recently. I hadn't tested the admin side in a while (since before 3.7 upgrade). Now, since the upgrade, the conditions don't seem to be working.

I've compared the code in edit.php to what I had previously, and it's identical. However, the /models/forms/ js file for the view has a lot of differences.

**Comment by Llewellynvdm** [comment]
Take a look at the admin view in JCB and check the conditions if they are all still setup correctly. I did notice Joomla has made some changes to the repeatable fields implementation. 

Really frustrating!!

I have many components using the conditions, and they still work. So if the above does not help to resolve the issue, you would need to add some code for me to help more.

**Comment by mwweb** [comment]
Sorry for bugging. It actually turns out to be a piece of javascript I added to the admin view that is the culprit. Process of elimination. Remove a piece of code, test, until it works. Now it's a matter of actually tracking down what in the code is causing it.
