### ISSUE TITLE
Installation xml is not created after compilation

### ISSUE THREAD

**Issue by nikkolaos** [vdm-io/Joomla-Component-Builder#822]
### Steps to reproduce the issue
Compile a project and then try to install it (please note that I try to install to another joomla instance, not the same as the one containing JCB).

### Expected result
After compilation, have a zip file that can be installed to any Joomla instance

### Actual result
During installation, I get the message "Error Unable to locate the installation XML"
The zip file that the compilation produces, does not contain the XML file, and the index.html file.
Also, the access.xml, config.xml, controller, .php and index.html files are missing from the admin directory.

### System information (as much as possible)
- OS Name & Version: debian 9
- MySql Version: Mariadb
- Apache Version: apache 2
- PHP Version: 7.3
- Joomla Version: 3.9.28
- JCB Version: 2.12.10 (recently upgraded)
- Browser: chrome

### Additional comments
- I noticed this after upgrading to the most recent .10 JCB from .9 version
- Also, after the compilation I get some warnings regarding "not being able to write/copy to folders", for example "Failed to copy .../.../public_html/images/Wooden-Folder-5515017801-plus.png to .../...public_html/administrator/components/com_componentbuilder/compiler/com_diaxeirisi_programmaton_v1_0_223__J3/admin/assets/images/icons/program_add.png"
- If I copy the missing files manually from an older compilation zip file, the installation seems to work properly. It doesn't seem to have affected other files.

**Comment by Llewellynvdm** [comment]
Please never use chrome, use Firefox, this will resolve your issue.

**Comment by nikkolaos** [comment]
> Please never use chrome, use Firefox, this will resolve your issue.

Thanks for the input.

I also used Opera, which perhaps shares things with Chrome, noticed the same problem there.

I will try Firefox tonight and let you know.

**Comment by nikkolaos** [comment]
For some reason it worked fine, both on Opera and Firefox. Can't explain why.

**Comment by Llewellynvdm** [comment]
Yes this is a chrome thing that mess with server side folder caching. Absolute madness if you ask me, since I saw this I never use chrome from anything except google stuff. Seems like massive over reach if you ask me....

Anyway building extensions with JCB in Firefox should work... the extensions themselves should be okay in all browsers... it seems like its just JCB itself as it deals much with file system creation, moving and screening far beyond your normal extensions would do.
