### ISSUE TITLE
Date Problem

### ISSUE THREAD

**Issue by JohnnyMcWeed** [vdm-io/Joomla-Component-Builder#84]
I think I found another problem if I'm not missing something... The date doesn't get stored as it should be.
Can be recreated like that:

- Make a new field (type _calendar_ and data type _date_) to store the date.
- Add the field to an admin view
- Install the component
- Save a new element / change the date of an element

Component Builder 2.4.6
Joomla 3.7.2
PHP 5.6.26

**Comment by ro-ot** [comment]
Check that you use the correct data type _DATETIME_ the date option does not work well with the Joomla date field, since it has time.

**Comment by JohnnyMcWeed** [comment]
If I change to data type DATETIME, this happens as well.
The strange thing is that I have two identical fields with that configuration but different field names. One is working, the other is not.

**Comment by Llewellynvdm** [comment]
If you added the second field after your first install of the component, you will need to uninstall the component or add the SQL update for the field in the **Editing the Joomla Component => Details =>  Version Updates** to insure the the new field is added to the database.

Something like:
```
ALTER TABLE `#__your_component_view` ADD `showon` VARCHAR( 255 ) NOT NULL AFTER `selectiontype` ;
```

**Comment by JohnnyMcWeed** [comment]
I did uninstall, compile/reinstall, but that doesn't change anything. So for both type datetime and date it doesn't work.

**Comment by Llewellynvdm** [comment]
Hmmm that does not happen on my side, so you will need to give us a screen shot of the JCB field view in question or the code in the sql install file of the table that this field belongs to.

**Comment by JohnnyMcWeed** [comment]
(Here images with date, but either date or datetime doesn't make any difference). The strange thing is that one field is working, but the other is not...
Endresult after saving:
![date3](https://cloud.githubusercontent.com/assets/9844452/26546437/422e4e9a-446a-11e7-836b-e595e03ee842.png)

Field 1:
![date](https://cloud.githubusercontent.com/assets/9844452/26546436/422de4f0-446a-11e7-8c23-17e786f687ec.png)

Field 2:
![date2](https://cloud.githubusercontent.com/assets/9844452/26546438/422e8ae0-446a-11e7-9542-e8cd2124e4c8.png)

**Comment by Llewellynvdm** [comment]
## This seems to work every time.
![screenshot from 2017-05-30 08-11-15](https://cloud.githubusercontent.com/assets/5607939/26570228/a6c3ede2-450f-11e7-9c66-880fa357cfae.png)

> You will see that it has a few differences but those worth noticing are
+ Data Type
+ Other Default
+ Null Switch

__Joomla Calender type always stores time even if the xml format does not show time__

**Comment by Llewellynvdm** [comment]
When using Joomla calendar aways use **DATETIME** and insure you have the Other default set to **0000-00-00 00:00:00** even if your xml format is _%d-%m-%Y_

The xml format is only for display, not for storing to database, the Calendar type always stores as **%Y-%m-%d %H:%M:%S**

**Comment by Llewellynvdm** [comment]
Joomla has date functions that are used to display the date, but I wrote a simple few functions that I use in my static helper class to deal with this:

```
	/**
	 *	Change to nice fancy date
	 */
	public static function fancyDate($date)
	{
		if (!self::isValidTimeStamp($date))
		{
			$date = strtotime($date);
		}
		return date('jS \o\f F Y',$date);
	}

	/**
	 *	Change to nice fancy day time and date
	 */
	public static function fancyDayTimeDate($time)
	{
		if (!self::isValidTimeStamp($time))
		{
			$time = strtotime($time);
		}
		return date('D ga jS \o\f F Y',$time);
	}

	/**
	 *	Change to nice fancy time and date
	 */
	public static function fancyDateTime($time)
	{
		if (!self::isValidTimeStamp($time))
		{
			$time = strtotime($time);
		}
		return date('(G:i) jS \o\f F Y',$time);
	}

	/**
	 *	Change to nice hour:minutes time
	 */
	public static function fancyTime($time)
	{
		if (!self::isValidTimeStamp($time))
		{
			$time = strtotime($time);
		}
		return date('G:i',$time);
	}

	/**
	 *	Check if string is a valid time stamp
	 */
	public static function isValidTimeStamp($timestamp)
	{
		return ((int) $timestamp === $timestamp)
		&& ($timestamp <= PHP_INT_MAX)
		&& ($timestamp >= ~PHP_INT_MAX);
	}
```
