### ISSUE TITLE
"IF NOT EXISTS" prevents installation

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#841]
### Steps to reproduce the issue
Upgrade to JCB 2.12.14
Add a new field to an existing admin view (thus having it add additional SQL to the component updates area).
JCB adds:
ALTER TABLE `#__kr_books_author_profile` ADD COLUMN IF NOT EXISTS `timezone` INT(11) NULL DEFAULT 0 AFTER `reviews_pending_count`;

### Expected result (i.e. code added)

field added and compile/install without a problem

### Actual result

On installing the component there is an error noted in the SQL near "IF NOT EXISTS"

Manually removing the "IF NOT EXISTS" allows the component compile/install process to work properly.

### System information (as much as possible)
- OS Name & Version:  WAMP
- MySql Version: 5.7.31
- Apache Version:  2.4.46
- PHP Version: 7.4.9
- Joomla Version: 3.10.3
- JCB Version: 2.12.14
- Browser: Firefox developer

### Additional comments

This didn't happen in previous versions of JCB. Appears that the "IF NOT EXITS" clause was added recently.

I'm guessing this is a MySQL version conflict.

Is there a way to tell JCB the minimum version of MySQL to support (and this avoid this type of code being added)? Or is there a minimum version of MySQL that is required now?

**Comment by Llewellynvdm** [comment]
Yes this was added, apology for the inconvenience. I did test this in a number if instances, but yes they are all running on MariaDB Version: 10.6.5

I will release a patch for your to choose which JCB should use. I liked the "IF NOT EXITS" as this avoids some of the errors we had when the same field gets removed and added again...

**Comment by cpaschen** [comment]
Well, I WISH that I could use the new "IF NOT EXISTS" I've just been cleaning up a bunch of sql updates that added a field to the table when it already existed.
Unfortunately, my live server can't be updated yet, so I have to live with this older version for a while.

NOTE: This is not critical for me. But it would be nice to be able to 'flip a switch' to disable the changes until I can upgrade (and then 'flip it back' to get that new functionality again. And in the mean time, I can manually check those db updates and adjust as needed.
Although for a new users this might be a bit frustrating/confusing. (Although hopefully I'm one of few using this old of a db :-( ).

**Comment by Llewellynvdm** [comment]
You can for now fix it in your install, until until I patch this... by going to the following line in the e_Interpretation.php [line 10358](https://git.vdm.dev/joomla/Component-Builder/src/branch/staging/admin/helpers/compiler/e_Interpretation.php#L10358p) and replace the whole block from line 10358-10363 with the following:

```php
$this->updateSQLBuilder["ALTERTABLE`#__" . $component
. "_" . $view . "`ADD`" . $field . "`"]
	= "ALTER TABLE `#__" . $component . "_" . $view
	. "` ADD `" . $field . "` " . $data['type']
	. $lenght . " " . $default . " AFTER `" . $last_name
	. "`;";
```
