### ISSUE TITLE
Component - Save

### ISSUE THREAD

**Issue by JohnnyMcWeed** [vdm-io/Joomla-Component-Builder#86]
A component can be saved without system name and is therefore no more accessible I think.
(Access through changing of id gives access permission problem)

**Comment by ro-ot** [comment]
If that happens, you can tick the checkbox next to the blank line and then click on edit in the toolbar.

If you have a permission problem, then access the component as admin and you will be able to edit the item.

**Comment by JohnnyMcWeed** [comment]
You're right, didn't think about this way anymore... xD
