### ISSUE TITLE
Wrong JCB code tags for custom code in html area

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#860]
### Steps to reproduce the issue
add custom code in site view html field

### Expected result
custom code added with  JCB comments
`<!--[INSERTED$$$$]--> and <!--[/INSERTED$$$$]-->`

### Actual result
comments added in php tags
`/***[INSERTED$$$$]***//**15**/ and /***[/INSERTED$$$$]***//**15**/`

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.10
- JCB Version: 2.12.15 master
- Browser: 

### Additional comments
I need a fast hardcode instruction as I have to deliver the package to the customer. Thanks.

**Comment by Llewellynvdm** [comment]
This is the notes on the subject:
https://github.com/vdm-io/Joomla-Component-Builder/wiki/TIPS:-Custom-Code

You should never ship any code with custom coding placeholders in a deliverable for production, as this is considered bad practice.

**Comment by Llewellynvdm** [comment]
You can not start with `INSERTED`....  you must alwasy start with `INSERT` and JCB will change that to `INSERTED`

So the custom code to start a replace or a insertion is:
`/***[INSERT<>$$$$]***/` and  `/***[/INSERT<>$$$$]***/`
`/***[REPLACE<>$$$$]***/` and  `/***[/REPLACE<>$$$$]***/`
Or for HTLM
`<!--[INSERT<>$$$$]-->` and `<!--[/INSERT<>$$$$]-->`
`<!--[REPLACE<>$$$$]-->` and `<!--[/REPLACE<>$$$$]-->`

**Comment by jcodewalker** [comment]
There is a missunderstanding...
I've just updated JCB and there is a BUG! The same component works perfectly on an old JCB version 2.11.2
Please, see the attached image.
![Schermata 2022-02-01 alle 14 51 46](https://user-images.githubusercontent.com/49115855/151981187-4dd32c18-1daf-4335-9051-2f83b2adbde5.png)

**Comment by Llewellynvdm** [comment]
Okay this is weird as I have many extensions with `CUSTOMCODE` and they still build with no error. What exactly is the problem?

**Comment by Llewellynvdm** [comment]
There is in the normal custom field no HTML area, so not sure where you are working... custom fields only have PHP area.
![image](https://user-images.githubusercontent.com/5607939/152029464-892b28f1-6149-49be-b1d2-a34e3230decb.png)

**Comment by jcodewalker** [comment]
I'm working in site view, html area (which will output the template/default.php file)
I place the code as shown in the image of previous post. It works fine in all old versions (I have other 5 installations of JCB, all older). Today I had to update this jjomla to the latest versione and JCB too as it did'nt work anymore (after compile buttons links broken).
Now I have this problem, JCB comments are shown in the html output.

**Comment by Llewellynvdm** [comment]
What version of PHP are you using?

**Comment by Llewellynvdm** [comment]
I can't reproduce your error so I can't debug it.

**Comment by jcodewalker** [comment]
All JCB installations are running on php v.7.3.8 but I think I've to investigate what's happened with the upgrade...

**Comment by jcodewalker** [comment]
ok, I think I can say you how to reproduce the error.
Create a new component, for admin side add **Demo's Look** admin view, for site side create a new view and just add the custom code as html output (a dummy dynamic get).
Compile and install.

**Comment by Llewellynvdm** [comment]
Okay I tried this and still no issue, let me ask the obvious question... is your custom code comment type set to HTML?
![image](https://user-images.githubusercontent.com/5607939/152517861-f4398bab-97a1-4451-b346-7f3620104200.png)
![image](https://user-images.githubusercontent.com/5607939/152517931-e1cafe71-f199-4287-8bfb-7bc59b3c5ac4.png)
![image](https://user-images.githubusercontent.com/5607939/152517974-a66e1880-447c-41aa-a734-210f3c5b3c7e.png)
![image](https://user-images.githubusercontent.com/5607939/152518190-c2547517-25a8-4e98-b83e-fff793368a05.png)
![image](https://user-images.githubusercontent.com/5607939/152518301-eddd56b7-5179-45ef-8f90-a7c63e33e7a4.png)

**Comment by jcodewalker** [comment]
Hi, thanks, yes to all.
Ok, I understand I have to investigate in own installation what is gone wrong when I've the time. By now I just manually clean up the compiled code. Luckly is not that much work. Thanks for your effort!
