### ISSUE TITLE
duplicated folder for Editing the Component Files & Folders/advance

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#866]
### Steps to reproduce the issue
in JCB component view, tab "Setting", click on "Edit component files folders for this joomla component" button.
Click on Tab "Advance" and add new "Folders (full path)"
I want to include the folder **data** which contains **folders** and files
Source folder path: my/full/source/folder/data
Destination path: my/full/destination/path/data

### Expected result
In destination:
my/full/destination/path/data/all-the-content-of-data-folder

### Actual result
my/full/destination/path/data/data/all-the-content-of-data-folder
Please, note the doubled **data/data** folder

If the folder data contains only files it works fine

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.10
- JCB Version: 2.12.15
- Browser:

**Comment by aradwan-mcg** [comment]
maybe try removing data folder from the source folder path
like this: Source folder path: my/full/source/folder/

**Comment by jcodewalker** [comment]
> maybe try removing data folder from the destination folder path like this: Destination path: my/full/destination/path/

Hello, thanks, that's right! BTW it worked without trailing slash: my/full/destination/path
Thank you for the hint!

**Comment by aradwan-mcg** [comment]
glad i could be of help
