### ISSUE TITLE
Feature Request: On the 'Component Admin Views' keep headers in place

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#876]
In the Component Admin Views list, if you have more than 10 or so admin views the headers scroll off the page at the top.

It would be helpful if those were still visible as you scroll down (maybe scroll the listing, not the entire page)?

Not sure if this is a huge task or not.

And this is NOT a high priority, but sure would be nice when dealing with complex components.

**Comment by Llewellynvdm** [comment]
There is an option to change the layout.... and I think that is the best we are going to do for now in J3

So in the JCB global options area, look under the global tab look for the `Sub-form Layouts`
![image](https://user-images.githubusercontent.com/5607939/157240071-4b359bac-ee21-4542-8437-6f8d44936d98.png)

Here you can select the area and the layout template for that area... the `uikit layout` option works best for large data sets. We could possibly in the future add more layout options... but that is it for now.

**Comment by cpaschen** [comment]
PERFECT! That solves the issue. (I forgot about that area ... just too many (good) things in JCB to remember them all :-)
Thanks!
