### ISSUE TITLE
Pagination does not work on custom admin views

### ISSUE THREAD

**Issue by vistamedia** [vdm-io/Joomla-Component-Builder#884]
The dynamic get pagination is working properly for site views but doesn't for custom admin views.
In order to fix this : 
`$this->pagination->getPagesLinks();`
has to be replaced by
`$this->pagination->getListFooter();`
for the custom admin views

**Comment by Llewellynvdm** [comment]
Thanks this is a bug, and we must fix this!

**Comment by Llewellynvdm** [comment]
I have added the code to the compiler:
![image](https://user-images.githubusercontent.com/5607939/167573884-d0738906-61c4-47f6-b233-49d15d2f12ee.png)
![image](https://user-images.githubusercontent.com/5607939/167573972-5ff32485-ddec-4a61-8ff6-ca24b8ba08df.png)

and will push it up to the staging branch later today...
