### ISSUE TITLE
Admin List View - order problem

### ISSUE THREAD

**Issue by JohnnyMcWeed** [vdm-io/Joomla-Component-Builder#89]
Reproduce
- Add fields to admin view
- Show some in _Admin List_
- Change _Order in list views_

This should handle the order on an overview ( list ) page, but is having problems at the moment and therefore not changing according to my settings.

**Comment by Llewellynvdm** [comment]
Can you provide us with a screen shot of the modal where you have this issue.

**Comment by JohnnyMcWeed** [comment]
![adminlist](https://cloud.githubusercontent.com/assets/9844452/26538136/a92554fc-4444-11e7-8952-3b309ebc8059.png)
![adminlist2](https://cloud.githubusercontent.com/assets/9844452/26538137/a92670a8-4444-11e7-9695-db93b7ad3062.png)

**Comment by Llewellynvdm** [comment]
What kind of field is Elephant Zoo, I would expect it to be a custom field, this means you will need the correct values set in the field to have it behave correctly. This means your error is in the custom field XML. So give me a screen shot of the Elephant Zoo field so we can check if it is actually setup correctly.

**Comment by Llewellynvdm** [comment]
O yes and at this time, JCB does not load images in the list view by default. You can with custom Ajax scripting get it done. But that is beyond the scope of JCB defaults.

**Comment by Llewellynvdm** [comment]
You can not use 0 as ordering number at this time when working with the list layout. We could improve the compiler to behave differently but just that you know it is best practice to always start with 1 as this first field in the list layout ordering.

**Comment by JohnnyMcWeed** [comment]
Solved through changing the starting number for it's order to 1, instead of 0.
Thanks for your help!
