### ISSUE TITLE
on zooming content in browser window the markup is shifted

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#894]
Only one page is tested, but I guess similar UI problems may be seen in other parts of UI too. Just zoom UI to 110-120% etc 
Please, check screenshot to understand what I mean.

![Screenshot from 2022-04-17 05-05-13](https://user-images.githubusercontent.com/4179340/163697439-e770d571-37b3-45e4-aa1e-ad6d924a262e.png)

**Comment by Llewellynvdm** [comment]
Unless your willing to contribute an improvement to this, I am not currently able to give time to this.

**Comment by kamilrafik** [comment]
I logged these bugs just in the process of exploring JCB; I do not expect to use JCB for any project now; so, my contribution now may be limited just with such accidental testing/review.

I see in your responses that some issues discovered by me were really bugs; so, it is very nice to hear that even such minor contribution was helpful for you.
