### ISSUE TITLE
UX problem: even if no changes were made in form an annoying warning explaining that unsaved work will be lost is displayed

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#895]
UX problem: even if no changes were made in form an annoying warning explaining that unsaved work will be lost is displayed.
Please, check screenshot to understand what I mean. It is expected that fact of changes in form should be checked before displaying the popup.

![Screenshot from 2022-04-17 05-19-44](https://user-images.githubusercontent.com/4179340/163697481-bf66aa6a-772b-4905-869c-3e48211f2d40.png)

**Comment by Llewellynvdm** [comment]
This warring is better than losing your work that you did without knowing, that is annoying. Unless your willing to contribute an improvement to this, I am not currently able to give time to this.
