### ISSUE TITLE
Compile Not Working

### ISSUE THREAD

**Issue by Colorado4Wheeler** [vdm-io/Joomla-Component-Builder#90]
I just installed CB and wanted to compile the demo component just to see how it worked and in your video it shows the animated GIF of it stamping out boxes but on my system it just goes to a blank screen that never refreshes.  In the end it never builds anything, there are no files in tmp.  

I am running Joomla 3.6.5 on PHP 5.6.30, fresh installation.  Is there a PHP module that your system relies on that perhaps I've not installed?

**Comment by Llewellynvdm** [comment]
Please upgrade to Joomla 3.7.2

If Joomla works then JCB should also work.

**Comment by Colorado4Wheeler** [comment]
Thank you, I updated to 3.7.2 and the same issue persists.

**Comment by Llewellynvdm** [comment]
Well this is clearly not a JCB problem, so to help you is very difficult. JCB is working on many dev systems. Best I can suggest is to check logs, uninstall JCB & reinstall.

Is this on a local developer environment?

If so you need to check that all the needed php modules are on. They usually get checked during Joomla install... lets see here is a list of those on my system:

**Comment by Colorado4Wheeler** [comment]
I'll check to see, but I haven't had any problems yet - not to say that something isn't missing though.  Your list wasn't pasted in your reply.

**Comment by Llewellynvdm** [comment]
Just reload the page

**Comment by Colorado4Wheeler** [comment]
Strange.  I have a number of them and some that I tried to install via pkg don't exist for php56, do you see a particular one missing from this list that you suspect might be the culprit?

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by Colorado4Wheeler** [comment]
Something I failed to mention about this process is that when I hit compile it just goes to a blank screen, but when I hit my back button I'll see the animated GIF file stamping out boxes but it still doesn't compile.  That's probably inconsequential but I thought I should mention it.

**Comment by Colorado4Wheeler** [comment]
Another update...  I loaded the component on three other J! sites that I have that are all 3.7.2 on different hosts (i.e., HostGator) with the same result.  I do completely understand this is running on many systems without an issue, I would love to find the common problem that is preventing both my hosted Joomla sites as well as my dedicated machine dev server to act this way.  Whatever I can do to assist in figuring this out I am at your disposal.  I'm excited to get this working before I subscribe.

**Comment by Llewellynvdm** [comment]
Hey that is great, I mean your willingness to get this resolved.

JCB does not work on PHP 7 as yet.

Would you be able to turn PHP error reporting on. I mean do you see any error messages anywhere in any log? To fix it we need to see it, so without any info it is very hard to debug... can I have access to any of these systems, and would I be able to see the error log?

**Comment by Colorado4Wheeler** [comment]
Email sent.

**Comment by Colorado4Wheeler** [comment]
So after some diagnostics from Llewellyn, everything ended up looking just fine until I tried it again.  Then it dawned on me that the one variable left was my browser.  This plugin will, apparently, NOT compile under Safari but when I used Chrome it worked perfectly.

So, there you go, don't use the plugin with Safari and everything works just fine!  

Thanks Llewellyn, I appreciate your assistance!

**Comment by ro-ot** [comment]
Testing JCB in Safari I also found this issue, console only gives the following info:

> Refused to execute a JavaScript script. Source code of script found within request.

Any ideas what may be the cause?

I have looked over the code and I can't see any JavaScript being returned, which is the common reason for this type of error. This should be a very simple and small issue, lets try to resolve this

**Comment by Llewellynvdm** [comment]
Any news on this front?
