### ISSUE TITLE
UX issue: textarea fields for entering PHP code can be customized easily via third-party libraries that turn them into fully functioning PHP code editor (with indentation, syntax highlighting etc).

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#901]
UX issue: textarea fields for entering PHP code can be customized easily via third-party libraries that turn them into fully functioning PHP code editor (with indentation, syntax highlighting etc).

The same note concerns textarea fields for entering SQL code. (Note: to find all these textareas manual check of all UI is needed because, as I see, in different pages labels of such textareas differ rather much.)

As I remember, https://codemirror.net/ is one of the best but other may be searched.

**Comment by Llewellynvdm** [comment]
This is already possible in most cases, we have had much conversation about this over the years... if you did a [search in the issues area for codemirror](https://github.com/vdm-io/Joomla-Component-Builder/issues?q=codemirror) you will find all the conversations. So we did add this potion... and you can activate it for you in the global options under the global tab:
![image](https://user-images.githubusercontent.com/5607939/164570313-f469b1bb-d893-4222-81c7-0bfea1731406.png)

But Joomla's implementation has at times not worked, and then it worked... and so I made it a selection, so developers can choose for themselves.
