### ISSUE TITLE
Incorrect links in "Linked to" section of view editor for trashed components

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#902]
Please, see screenshot. "qqq" and "Demo" components were trashed, but they are still visible in this section. After clicking on "pen/locker" links near them redirection happens to editing of existing "test 1" component.

![Screenshot from 2022-04-17 13-33-38](https://user-images.githubusercontent.com/4179340/163710854-d49d0b43-4d0a-46cf-83f4-ad48157f718e.png)

**Comment by Llewellynvdm** [comment]
Being trashed, does not mean its no longer linked. So we are not filtering state of these linked areas across the system by design, so you can always know about the full picture. This is how I preferred it to work.
