### ISSUE TITLE
UX minor issue: upon adding field to admin view it would be better to scroll down to the end of the list.

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#903]
UX minor issue: upon adding field to admin view it would be better to scroll down to the end of the list. It is supposed that similar scrolling logic may be added in other places where adding button is located at the top but added items are added at the end of very very long list.

As another solution, it may be useful to duplicate adding button at the end of the list.

![Screenshot from 2022-04-17 13-45-28](https://user-images.githubusercontent.com/4179340/163711147-d110f2d9-33e4-4b99-bc97-e89514c9c497.png)

**Comment by Llewellynvdm** [comment]
Yea that would be nice... but moving JCB to Joomla 4 at this point is our highest priority... so again. Unless your willing to contribute an improvement to this, I am not currently able to give time to this. (you are very welcome... but we would rather no focus on moving to J4)
