### ISSUE TITLE
UX minor issue: on scanning database for searching placeholders a loader icon or progress bar would be helpful.

### ISSUE THREAD

**Issue by kamilrafik** [vdm-io/Joomla-Component-Builder#904]
Please, check screenshot.
(At least, adding one more dot at the end of the string is really needed.)

![Screenshot from 2022-04-17 14-38-47](https://user-images.githubusercontent.com/4179340/163712814-2706d0e4-f31e-4edc-8ba2-88bf0a005526.png)

**Comment by Llewellynvdm** [comment]
Unless your willing to contribute an improvement to this, I am not currently able to give time to this. (you are very welcome... but we would rather now focus on moving to J4) I am smiling at this point.... :)
