### ISSUE TITLE
Install all above extensions  - Error

### ISSUE THREAD

**Issue by sshlord** [vdm-io/Joomla-Component-Builder#914]
### Steps to reproduce the issue
Compile component and modules

### Expected result
Install all of them at once

### Actual result
Error

Argument 2 passed to com_cinefandbInstallerScript::preflight() must be an instance of Joomla\CMS\Installer\Adapter\ComponentAdapter, instance of Joomla\CMS\Installer\Adapter\ModuleAdapter given, called in /home/cinefan/dev.cinefan.ro/public_html/libraries/src/Installer/InstallerAdapter.php on line 1026

### System information (as much as possible)
- OS Name & Version: Ubuntu 20.04
- MySql Version: MariaDB 10
- Apache Version: Open LiteSpeed  1.7.15
- PHP Version: 7.4
- Joomla Version: Latest - 3.10.9
- JCB Version: Latest - 2.12.16
- Browser: Firefox

### Additional comments

I have 2 servers, one with OpenLiteSpeed and another with LiteSpeed Ent. Results are the same.

**Comment by Llewellynvdm** [comment]
I think this is related to the same bug we [already have noted here](https://github.com/vdm-io/Joomla-Component-Builder/issues/868), with a current work around.

if the solution mention does not work, let me know here... and I will open it back up again.
