### ISSUE TITLE
sql error on fresh JCB install

### ISSUE THREAD

**Issue by KingWacke** [vdm-io/Joomla-Component-Builder#915]
### Steps to reproduce the issue
fresh install JCB into Joomla 4.1.3

### Expected result
no errors on fresh install

### Actual result
Incorrect integer value: '' for column 'add_license' at row 1

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 	8.0.28-0ubuntu0.20.04.3
- Apache Version:  n/a
- PHP Version: 8.1.0
- Joomla Version: 4.1.3
- JCB Version: Component Builder (v.2.12.17)
- Browser: Brave

**Comment by Llewellynvdm** [comment]
JCB is not yet ready to run on Joomla 4... sorry we are working hard to get it there :+1:
