### ISSUE TITLE
Class 'JTableObserverContenthistory' not found -- when click on any "NEW" button

### ISSUE THREAD

**Issue by morphinestyle** [vdm-io/Joomla-Component-Builder#916]
Click on NEW button on any JCB menu to get error.

My Joomla! version: 4.1.2
MariaDB 10.3.32
PHP 7.4.27
OpenLitespeed

**Comment by Llewellynvdm** [comment]
JCB is not yet ready to run on Joomla 4... sorry we are working hard to get it there :+1:

**Comment by morphinestyle** [comment]
Excuse me to open this issue: after opening it i read much about JCB and only later i understand it's not ready for J4, so i installed J3 and i discovered an AWESOME plugin! Great work!
I'm not a developer so i can't help you on programming, but i'm an a italian designer from "Photoshop to CSS", i have not much free time, but let me know how i can help you, if you need.
