### ISSUE TITLE
Dynamic Values on Layouts

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#93]
I noticed, today, when working on finishing a couple of views that there is a "reference" issue on layouts when it's displaying the dynamic values. You can see this on, as an example "Preachers Panel". The main get shows the foreach correctly: <?php foreach ($displayData as $item): ?>, using $displayData instead of $this->item.

However, on the additional get, idPreacherSermonB, it references $item, instead of $displayData: <?php foreach ($item->idPreacherSermonB as $idPreacherSermonB): ?>. As written, it would throw errors. However, if it was  <?php foreach ($displayData->idPreacherSermonB as $idPreacherSermonB): ?>, it would work fine.

If someone is relying, copying from those references, they may get frustrated when idPreacherSermonB is throwing errors.

**Comment by ro-ot** [comment]
Yes those code snippets do need some attention, would you like to make improvement to it?

**Comment by Llewellynvdm** [comment]
Okay this could be an issue if you don't know PHP, but this is clearly a requirement :)

Would be great to improve this, the algorithm is very crazy... you can have a [look at it here](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/ajax.php#L322). It is just that the variation is huge, and to correctly set those values across various places is where the improvements are needed.
