### ISSUE TITLE
Setting Site View Permission

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#97]
Llewellyn,

How are the site view permissions automatically set? Upon install of a component, all of the view (including the site views) default to "Not Allowed".

I know there has to be a way to set those to allowed, as most components available default with the frontend site views "preset".

**Comment by Llewellynvdm** [comment]
Yes there is a way. Let me make a video :)

**Comment by mwweb** [comment]
Thank you. That would be great. I know that those who end up using my component, as soon as it is released to the community, would "gripe and complain" about having to set permissions for all the views. Last count, there were 19 or 20 different site views.

**Comment by Llewellynvdm** [comment]
Well hope this will help. [Watch Tutorial.](https://youtu.be/gWjQjdhYqXI)
